### ISSUE TITLE
Random crash on Archlinux

### ISSUE THREAD

**Issue by danielbadawi** [gnunn1/tilix#1002]
Sometimes Tilix simply crash:
Follow the core dump:

`
jul 06 01:43:01 myuser kernel: tilix[32577]: segfault at 1108 ip 0000000000432ff8 sp 00007ffea60fb120 error 4 in tilix[400000+937000]
jul 06 01:43:01 myuser systemd[1]: Started Process Core Dump (PID 14738/UID 0).
jul 06 01:43:01 myuser systemd-coredump[14739]: Process 32577 (tilix) of user 1000 dumped core.
                                                
                                                Stack trace of thread 32577:
                                                #0  0x0000000000432ff8 n/a (tilix)
                                                #1  0x00007f522d4c4333 n/a (libglib-2.0.so.0)
                                                #2  0x00007f522d4c38b5 g_main_context_dispatch (libglib-2.0.so.0)
                                                #3  0x00007f522d4c3c78 n/a (libglib-2.0.so.0)
                                                #4  0x00007f522d4c3d0c g_main_context_iteration (libglib-2.0.so.0)
                                                #5  0x00007f522c59760d g_application_run (libgio-2.0.so.0)
                                                #6  0x000000000059c61d n/a (tilix)
                                                #7  0x00000000005094b6 n/a (tilix)
                                                #8  0x0000000000aac7bf n/a (tilix)
                                                #9  0x0000000000aac704 n/a (tilix)
                                                #10 0x0000000000aac630 n/a (tilix)
                                                #11 0x000000000056c4a5 n/a (tilix)
                                                #12 0x00007f522dddf43a __libc_start_main (libc.so.6)
                                                #13 0x0000000000405f3a n/a (tilix)
                                                
                                                Stack trace of thread 32578:
                                                #0  0x00007f522dea224d poll (libc.so.6)
                                                #1  0x00007f522d4c3bf9 n/a (libglib-2.0.so.0)
                                                #2  0x00007f522d4c3d0c g_main_context_iteration (libglib-2.0.so.0)
                                                #3  0x00007f522d4c3d51 n/a (libglib-2.0.so.0)
                                                #4  0x00007f522d4eaac5 n/a (libglib-2.0.so.0)
                                                #5  0x00007f522e694297 start_thread (libpthread.so.0)
                                                #6  0x00007f522deac1ef __clone (libc.so.6)
                                                
                                                Stack trace of thread 32579:
                                                #0  0x00007f522dea224d poll (libc.so.6)
                                                #1  0x00007f522d4c3bf9 n/a (libglib-2.0.so.0)
                                                #2  0x00007f522d4c3f92 g_main_loop_run (libglib-2.0.so.0)
                                                #3  0x00007f522c5c3426 n/a (libgio-2.0.so.0)
                                                #4  0x00007f522d4eaac5 n/a (libglib-2.0.so.0)
                                                #5  0x00007f522e694297 start_thread (libpthread.so.0)
                                                #6  0x00007f522deac1ef __clone (libc.so.6)
                                                
                                                Stack trace of thread 32580:
                                                #0  0x00007f522dea224d poll (libc.so.6)
                                                #1  0x00007f522d4c3bf9 n/a (libglib-2.0.so.0)
                                                #2  0x00007f522d4c3d0c g_main_context_iteration (libglib-2.0.so.0)
                                                #3  0x00007f521b7f355d n/a (libdconfsettings.so)
                                                #4  0x00007f522d4eaac5 n/a (libglib-2.0.so.0)
                                                #5  0x00007f522e694297 start_thread (libpthread.so.0)
                                                #6  0x00007f522deac1ef __clone (libc.so.6)

`

**Comment by gnunn1** [comment]
Unfortunately that core dump doesn't tell me much. Is the crash repeatable or does it just happen out of the blue. If it's repeatable, building tilix from source and running it in ```gdb``` would allow you to get a backtrace which I could then use to see where the problem is.

Also, what desktop environment are you using, gnome?

**Comment by danielbadawi** [comment]
Tilix crashes about 3 or 4 times per day since last week I think. Completely out of the blue. Sometimes even without user interaction, like showing log with "tail -f".
I'll try running with `gdb` from source.

My environment:
Arch Linux
Kernel x86_64 4.11.7-1-ARCH
GNOME 3.24.2

**Comment by gnunn1** [comment]
I'm running in the same environment with no issue, wonder if there is something specific causing the issue. Are you using Wayland or X11?

**Comment by danielbadawi** [comment]
X11
Version 1.19.3-2

**Comment by gnunn1** [comment]
@danielbadawi Have you had a chance to get a backtrace? Also, I released 1.6.4 so feel free to try that and see if it fixes the issue.

**Comment by danielbadawi** [comment]
Hi @gnunn1 
I have use (same version) from source since then, but had no issue.
Since 1.6.4 I back to the binary version from AUR and still no crashes.
I think the cause of the problem was that I did not restart my system nor the Tilix for several days even after various updates such gtk, mesa, etc.
After rebooting, no more crashes :)

**Comment by gnunn1** [comment]
Thanks for the update and glad it is working well for you now.
