### ISSUE TITLE
Feature request: Keyboard shortcuts for input synchronisation

### ISSUE THREAD

**Issue by soumya92** [gnunn1/tilix#1003]
iTerm on macOS has a shortcut, and it is very useful. A shortcut that behaves the same as clicking on the menu and then the "Synchronise Input" checkbox would be great :)

A separate shortcut for toggling input synchronisation for the active terminal would also be helpful, which would behave the same as clicking on the keyboard icon in the active terminal's title bar.

**Comment by gnunn1** [comment]
Tilix already had the ability to set a shortcut for the global input synchronization, I've added the ability to set the shortcut for the terminal override as well.
