### ISSUE TITLE
Feature request: Keyboard shortcut to move tiled terminals around

### ISSUE THREAD

**Issue by ajyotirmay** [gnunn1/tilix#1004]
It will be nice if there's an option to move the tiled windows around the terminal, because it gets impossible to move them around when the "Terminal Title Style" is set to "none".

**Comment by gnunn1** [comment]
Maybe a key that can be held down with the mouse to move a terminal. Super+Hold Mouse button moves a gnome window anywhere, maybe Alt+Hold Mouse Button for the terminal?

**Comment by dsboger** [comment]
Why not both :). A totally mouse-free way to move terminals could be interesting.

It could work in a similar way as the Alt+<arrow>, but instead of focusing the neighbor terminal, it would switch places.

**Comment by gnunn1** [comment]
A mouse free way would be challenging, it would require a special mode to navigate around to identify the target terminal and zone. Doing it with the mouse uses the same implementation that already exists and is much easier.

Having said, I'm happy to take a PR for a mouse free if someone wants to invest the time into it, but it won't be me :)

**Comment by gnunn1** [comment]
I've checked in a change that allows you to drag the terminal directly if you hold the ALT key down with the mouse button. Let me know if it causes any unexpected issues.

**Comment by ajyotirmay** [comment]
You fixed it quickly! That's cool... right now I'm using the PPA from webupd8 (the same was mentioned on your website for Ubuntu). So I guess it will take some time for the latest code to be there. But it's great to have this feature. Thanks for the commit :)
