### ISSUE TITLE
Force Terminal Color Scheme

### ISSUE THREAD

**Issue by Clyybber** [gnunn1/tilix#1005]
It would be nice to have an option that when enabled forces cli-apps to use the original color scheme.
This already works(unintentionally, I suppose) when opening tilix and running ncmpcpp for example.
Tilix then uses the terminal color-scheme until the window is resized, then the color-scheme of the app will be used.
We could use that bug as a feature, which would allow us to have a global color-scheme and skip configuring each apps config.

**Comment by gnunn1** [comment]
I don't think I can do this, I have no control over how CLI applications manage their own color schemes if they decide to do something different then leverage the terminal color scheme provided. For example, if an ncurses app decides to define and use it's own RGB scheme I don't think there's much I can do about it.

If I'm misunderstanding what you are asking for feel free to elaborate.
