### ISSUE TITLE
harden compilation flags

### ISSUE THREAD

**Issue by deathtrip** [gnunn1/tilix#1006]
Since some distros use the prebuilt binaries (like Arch's AUR), it makes sense to enable all hardening flags to raise the security level. As you do many sensitive operations in the terminal.
Current checksec output:
Partial RELRO   No canary found   NX enabled    No PIE          No RPATH   No RUNPATH   No	Fortify
Ideally we'd enable them all.

**Comment by gnunn1** [comment]
I'm not sure how applicable that tool is to a D language program, I don't think LDC2 has options for stack canary or fortify. For now I'm satisfied with how the binary is generated, if you have suggestions for specific improvements by adding additional flags feel free to open a PR and I'd be happy to look at them.
