### ISSUE TITLE
Invisible shortcut

### ISSUE THREAD

**Issue by woprandi** [gnunn1/tilix#1008]
Hi,
I just installed Tilix 1.6.1 on Fedora 26. I was checked available shortcuts and some of them are "hidden" : 
EDIT : I understood, there are disabled. But It's not clear, it miss maybe a label to indicate that

![capture du 2017-07-11 22-22-34](https://user-images.githubusercontent.com/1449422/28088965-ae92f150-6687-11e7-96f5-b43ed52c5bfd.png)
![capture du 2017-07-11 22-23-52](https://user-images.githubusercontent.com/1449422/28088966-ae9ba46c-6687-11e7-9970-2c26b3bf0ee8.png)

**Comment by gnunn1** [comment]
Those are shortcuts that don't have a key assigned, unfortunately the GTK shortcut widget doesn't provide a way to show "Disabled" as far as I know.
