### ISSUE TITLE
Would be great if we can add shortcuts for reordering sessions

### ISSUE THREAD

**Issue by y-usuzumi** [gnunn1/tilix#1009]
Hi! I have been in love with Tilix so far! One thing I noticed that was missing in the old Terminix days is that I can re-order sessions by dragging them around, which is great!

I want to enjoy full keyboard experience, and session re-ordering is the only thing that drags me behind.

Maybe we can add some operations like "Move session up/down" and assign shortcuts to them?

Cheers! :+1:

**Comment by gnunn1** [comment]
You can reorder sessions in the session bar by either dragging or dropping them or using <ctrl><up or <ctrl><down>. No plans to do any more then that.

**Comment by y-usuzumi** [comment]
@gnunn1 Sorry, what do you mean by "<up or ."?

**Comment by andjo** [comment]
Just happened to find that you can do this byt hitting F12, and then using Ctrl+Up/Down.
(Using Tilix 1.6.4)
