### ISSUE TITLE
Add "Copy & Paste" context menu item

### ISSUE THREAD

**Issue by martin-g** [gnunn1/tilix#1010]
Hi,

I am a happy user of http://roxterm.sourceforge.net/ but it is not maintained lately.
I'd like to switch to Tilix but I miss one functionality that I use very often: copy some text and immediately paste it.

Is it possible to add it ?

**Comment by martin-g** [comment]
I'm trying to upload a small video of the feature in Roxterm but GitHub doesn't accept .mp4 it seems.

**Comment by martin-g** [comment]
https://drive.google.com/file/d/0B-m73kEtvHyoYV9BX21CbjV1TGs/view?usp=sharing
Here is the video

**Comment by phw** [comment]
Nice. But I usually use the middle mouse button for it, works even faster: Select text, one middle click, done. Not sure whether this will work on Wayland, tough, does selection pasting exist there?

![peek 2017-07-12 17-03](https://user-images.githubusercontent.com/29852/28124482-13b3856c-6724-11e7-8256-465cacc8dff8.gif)

**Comment by martin-g** [comment]
Interesting!

I do not use mouse, so I don't have middle button.
Let me google how to emulate it with the touchpad!

**Comment by phw** [comment]
For me it is three finger tapping on the touchpad, which actually is kinda awkward to use :(

**Comment by f2404** [comment]
@phw You can also press left and right touchpad buttons simultaneously, but this does not always work as expected.

**Comment by martin-g** [comment]
According to https://help.ubuntu.com/stable/ubuntu-help/mouse-touchpad-click.html it should by tapping once in the top-right corner but it doesn't work.

> press left and right touchpad buttons simultaneously

This works!
I'll try to get used to it!

Thank you!

**Comment by gnunn1** [comment]
There's a configurable shortcut as well for ```Paste Selection``` in Tilix that defaults to <Shift><Insert>.

**Comment by martin-g** [comment]
Defaults to what ?

**Comment by gnunn1** [comment]
Ctrl-insert, GitHub hid because I used &lt;
