### ISSUE TITLE
No icon on 16.04 Ubuntu

### ISSUE THREAD

**Issue by tenleftfingers** [gnunn1/tilix#1013]
I installed following these directions http://www.omgubuntu.co.uk/2017/07/tilix-terminix-terminal-emulator-ubuntu

But the icon is 'blank' (default for Unity).

![image](https://user-images.githubusercontent.com/1757768/28231184-10ced396-68e2-11e7-8d7d-b78e5b742e51.png)

**Comment by gnunn1** [comment]
Did you install from a package or manually using install.sh? The install script should rebuild the icon cache but if not try logging out and in again to see if it helps.

Note there is also the webupd8 PPA for tilix as well.

**Comment by tenleftfingers** [comment]
I've checked again, the icon now shows. I didn't need to log out, but some hours passed. 

FYI, I used the command: sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
after extracting using the /d option, as per the linked article.

Thanks very much!
