### ISSUE TITLE
Extend Tilix with plugins ?

### ISSUE THREAD

**Issue by lheido** [gnunn1/tilix#1014]
There are any plans to extend Tilix via plugins (Written in Python or other scripting languages) ?
I found nothing about it (sorry if I missed an issue).

**Comment by bil-elmoussaoui** [comment]
gtkd has libpeas bindings which can be used in this case

**Comment by gnunn1** [comment]
I'd like too, it would probably be done using LUA as descibed in #88 which covers this feature.

No plans to use libpeas for this as it requires GObject bindings which are somewhat painful to create in D.
