### ISSUE TITLE
Starting Tilix from .desktop file does not respect -s or --session= parameter

### ISSUE THREAD

**Issue by Taijian** [gnunn1/tilix#1016]
I use tilix on Arch Linux /GNOME (installed from AUR/tilix).

I have made a copy of the com.gexperts.Tilix.desktop in ~/.local/share/applications and edited to contain the following Exec line:

Exec=tilix --session=Default.json

However, this only gives me the 'normal' tilix window, without the specified session file loaded. Executing the same command from a terminal behaves as expected, i.e. tilix opens in the pre-configured state that I want. 

Is this a bug or am I doing it wrong?

**Comment by gnunn1** [comment]
I tested with the following in Exec in my desktop file and it worked fine for me:

```
tilix --session ~/test.json
```

I think you need to specify the full path for Default.json, otherwise how does Tilix know where it is unless it is in your home path?

**Comment by Taijian** [comment]
Well, I have tried both `tilix --session ~/default.json` and `tilix --session=~/default.json` and neither of them work on my system. Maybe there is a way to debug this?

**Comment by Hagith** [comment]
I have the same problem, I was trying both relative and absolute paths to json file.
Anyone has an idea how to make it work?
I'm on latest Fedora 30 with Gnome 3.32.2

**Comment by Hagith** [comment]
After some trial & error I was able to make it work.
First I added `-s ~/tilix.json` to all `Exec` entries in desktop file. 
Second important thing is to comment out or remove `DBusActivatable=true` line.
After logging-in again to gnome Tilix session is loaded.

Hope it will help someone.

Thanks Tilix Team for your great work!
