### ISSUE TITLE
1px bottom margin when maximised

### ISSUE THREAD

**Issue by kubrickfr** [gnunn1/tilix#1017]
In Fullscreen mode (wayland, gnome 3.24.2, HiDPI), there is a distracting 1px margin at the bottom of the screen through which the content of the window under it can be seen.

![screenshot from 2017-07-16 16-33-25](https://user-images.githubusercontent.com/2634188/28248923-d1e14452-6a44-11e7-922a-dc47b9bc3300.png)

**Comment by gnunn1** [comment]
I cannot reproduce, are you using Adwaita as a theme?

**Comment by kubrickfr** [comment]
I usually use arc theme, but I've now tried with Adwaita and the issue is still present.

**Comment by gnunn1** [comment]
Do any other applications have the same issue, for example gedit?

**Comment by kubrickfr** [comment]
No, I'm only having this issue with Tilix

**Comment by kubrickfr** [comment]
Sorry, maybe it's a semantic issue, I meant "with the window maximised" not full screen (F11). The issue is not present in full screen.

**Comment by gnunn1** [comment]
Thanks, however I still cannot reproduce this. Is anyone else having this issue?

**Comment by kubrickfr** [comment]
Wait! Sorry, *I am* having the issue with other apps like gedit! it's just that it was more obvious with tilix because it's got a dark background. I guess it must be a gtk/gnome bug then.
