### ISSUE TITLE
Cannot introduce any changes [Question]

### ISSUE THREAD

**Issue by Mike-Now** [gnunn1/tilix#1019]
How would I go about adding some features to tilix? After compiling
with dub, the UI looks the same no matter what I change in the source code.
I even went so far as compiling in docker container and the ui still looks the same.
If I try to compile with tilix not installed from the official repo I get errors [#1018] .
Thanks for any help in that matter.

**Comment by gnunn1** [comment]
I answered the question about #1018 so hopefully that gets you going.

As to changes, just to edit the source code, build it with dub and then run the local version ```./tilix``` works fine for me. I use Visual Studio Code with the code-d plugin which makes it even simpler, just press the run button (assuming all resources are installed via ```sudo ./install.sh``` as per your #1018 question).

**Comment by Mike-Now** [comment]
After removing system-wide tilix installation and applying steps specified in #1018, I can run tilix with my changes.

**Comment by Mike-Now** [comment]
To run locally compiled tilix, even though system version is present and running, add the --new-process flag:

`./tilix --new-process`
