### ISSUE TITLE
Configuration Issue Detected link not valid

### ISSUE THREAD

**Issue by benjohnston24** [gnunn1/tilix#1022]
I recently install terminix version 1.4.2-3 from the Ubuntu universe using apt-get.  Upon launching I received a configuration issue detected window.
![untitled window_051](https://user-images.githubusercontent.com/6936084/28254983-59bcb824-6af5-11e7-88b5-f8d91fadaeda.png)

The cited [github pages link](https://gnunn1.github.io/terminix-web/manual/vteconfig) is not valid

**Comment by arcticicestudio** [comment]
You're running an outdated version of Tilix, it was named *Terminix* at this time. The latest version is [1.6.1](https://github.com/gnunn1/tilix/releases/tag/1.6.1) which is available through the [WebUpd8 PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/terminix) for Ubuntu.
Information about the VTE configuration can now be found in the [documentation](https://gnunn1.github.io/tilix-web/manual/vteconfig).

**Comment by benjohnston24** [comment]
Ah ok, thanks! I grabbed it from the Ubuntu repo, I'll update now

**Comment by benjohnston24** [comment]
Ah ok, thanks! I grabbed it from the Ubuntu repo, I'll update now
