### ISSUE TITLE
having trouble using automatic profile switching by directory only

### ISSUE THREAD

**Issue by bakedbean** [gnunn1/tilix#1023]
I'm trying to setup automatic profile switching using just the directory.  Thus far I have not been successful in getting it to work, and am wondering if I'm "doing it wrong"?

What exactly needs to be defined for the directory?  If I am in my home folder, and I cd into `some/dir`, my assumption would be that the profile switch expects `:some/dir` or `:/home/user/some/dir` or `:~some/dir`, but none of these combinations has the desired effect.  The desired effect is that when I change into the directory, the profile is activated, I assume that's what is supposed to happen if this is setup properly?

I'm on Fedora 25, tilix 1.6.4, VTE 0.46, GTK 3.22.16.

Any feedback is appreciated!

**Comment by gnunn1** [comment]
I don't think it's you, I just tested it myself and it looks like I broke something. I'll have a look.

**Comment by gnunn1** [comment]
Actually I didn't break anything, I mis-configured a trigger which was causing my issue.

If you open tilix, cd to a different directory and then split the terminal does the new terminal stay in the previous directory or does it revert to your starting directory. Just confirming that VTE is reporting directory changes correctly.

**Comment by bakedbean** [comment]
the new split reverts to my starting (home) directory.  So, VTE issue on my end then?

**Comment by gnunn1** [comment]
That would be my guess, have a look here for more information on the issue:

https://gnunn1.github.io/tilix-web/manual/vteconfig/

**Comment by bakedbean** [comment]
will do, and thanks for taking the time to respond.

**Comment by bakedbean** [comment]
just in case anyone else has a similar issue, I traced it to a custom prompt decorator that I use "liquidprompt".  Disabling that got everything working as expected.
