### ISSUE TITLE
New strings to be translated for 1.6.4 not found in Weblate

### ISSUE THREAD

**Issue by sogalboogalsky** [gnunn1/tilix#1025]
Hi,
I contribute to Tilix's French translation, as so I regularly check the Weblate dedicated page (https://hosted.weblate.org/projects/tilix/translations/fr/).
In 1.6.4 release, I was surprised to see that new strings appeared but those are not available in Weblate so I cannot translate them.
Am I missing something ?

Regards.

**Comment by gnunn1** [comment]
There's a conflict in weblate that I need to look into, I got an email about it on Tuesday.

**Comment by gnunn1** [comment]
Fixed conflict.

**Comment by sogalboogalsky** [comment]
Thanks, I am going to update translation.
