### ISSUE TITLE
Gnome Shell crash with Tilix -quake

### ISSUE THREAD

**Issue by Mancooo** [gnunn1/tilix#1029]
Hi,

I have Tilix quake mode assigned to the tilde key. 

I accidentally noticed that pressing and holding of the tilde key and thereby repeated appearing and disappearing of Tilix causes gnome shell to crash and restart. I use Xorg (on Fedora 26) and I assume that under Wayland whole of Gnome crashes and sends you back to GDM (because of the fact you can't restart the shell under Wayland).

It is a small bug that you really have to 'want' to trigger (yeah I know who would willingly want to do that), under normal circumstances the crash does not happen.

**Comment by Mancooo** [comment]
journalctl shows the following output:

jul 22 10:48:01 elif org.gnome.Shell.desktop[5986]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:01 elif org.gnome.Shell.desktop[5986]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:01 elif org.gnome.Shell.desktop[5986]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:01 elif audit[5986]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=7 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c102
jul 22 10:48:01 elif kernel: gnome-shell[5986]: segfault at 38 ip 00007fa1da17dff6 sp 00007ffdea774e30 error 6 in libgnome-shell.so[7fa1
jul 22 10:48:01 elif kernel: audit: type=1701 audit(1500713281.476:1405): auid=1000 uid=1000 gid=1000 ses=7 subj=unconfined_u:unconfined
jul 22 10:48:01 elif systemd[1]: Started Process Core Dump (PID 6823/UID 0).
jul 22 10:48:01 elif audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=syste
jul 22 10:48:01 elif kernel: audit: type=1130 audit(1500713281.497:1406): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:syste
jul 22 10:48:01 elif systemd-coredump[6824]: Resource limits disable core dumping for process 5986 (gnome-shell).
jul 22 10:48:01 elif systemd-coredump[6824]: Process 5986 (gnome-shell) of user 1000 dumped core.
jul 22 10:48:01 elif audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=system
jul 22 10:48:01 elif kernel: audit: type=1131 audit(1500713281.523:1407): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:syste
jul 22 10:48:01 elif polkitd[682]: Unregistered Authentication Agent for unix-session:7 (system bus name :1.728, object path /org/freede
jul 22 10:48:01 elif gnome-session[5913]: gnome-session-binary[5913]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
jul 22 10:48:01 elif gnome-session-binary[5913]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 317]: reference to undefined property global
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 217]: reference to undefined property glob
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 899]: reference to undefined property this
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined pro
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/panel.js 1107]: reference to undefined property indi
jul 22 10:48:02 elif gnome-shell[6832]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or dir
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 34]: reference to undefined property St.Ge
jul 22 10:48:02 elif polkitd[682]: Registered Authentication Agent for unix-session:7 (system bus name :1.755 [/usr/bin/gnome-shell], ob
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined p
jul 22 10:48:02 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/search.js 436]: reference to undefined property prov
jul 22 10:48:02 elif gnome-shell[6832]: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.E
jul 22 10:48:02 elif gnome-shell[6832]: Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org
jul 22 10:48:02 elif gnome-shell[6832]: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.GeoClue2 was not
jul 22 10:48:03 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1617]: reference to undefined prope
jul 22 10:48:03 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/status/network.js 1897]: reference to undefined prop
jul 22 10:48:03 elif gnome-shell[6832]: GNOME Shell started at Sat Jul 22 2017 10:48:02 GMT+0200 (CEST)
jul 22 10:48:03 elif org.gnome.Shell.desktop[6832]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:03 elif org.gnome.Shell.desktop[6832]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:03 elif org.gnome.Shell.desktop[6832]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timest
jul 22 10:48:22 elif gnome-shell[6832]: JS WARNING: [resource:///org/gnome/shell/ui/dash.js 760]: reference to undefined property oldApp
lines 19267-19302/19302 (END)

**Comment by gnunn1** [comment]
That's a nasty one, off the top of my head I'm not sure how to fix it. I'll have to give it some thought.

**Comment by gnunn1** [comment]
I've optimized the code and removed some the things that were happening twice when the window was being shown and this seems to have fixed it, at least on my laptop. If you can, please try the version from git and sees if it works for you.

**Comment by Mancooo** [comment]
Thank you, my internet connection is bad atm, in about 3 weeks from now I
have the opportunity to test, I will let you know

Op 29 jul. 2017 17:08 schreef "Gerald Nunn" <notifications@github.com>:
