### ISSUE TITLE
Where does Tilix save the profiles ?

### ISSUE THREAD

**Issue by martin-g** [gnunn1/tilix#1033]
I've tried to use my tilix-all.sh (https://github.com/gnunn1/tilix/issues/99#issuecomment-318327720) as a default command that should be executed when Tilix starts.
Unfortunately this leads to some recursive call and my CPU goes wild and Tilix cannot start anymore.

Where does Tilix save the profiles so I can remove the custom command or even the whole profile ?

**Comment by gnunn1** [comment]
It's in donf under com/gexperts/Tilix

**Comment by martin-g** [comment]
For anyone having a similar problem in the future:

`dconf reset /com/gexperts/Tilix/profiles/default`

Thank you!

**Comment by gnunn1** [comment]
You can also access the Preferences dialog directly by running:

```tilix --preferences``` 

in a different terminal.
