### ISSUE TITLE
Segementation fault when deselect encoding

### ISSUE THREAD

**Issue by sdicke** [gnunn1/tilix#1034]
Steps to reproduce: deselect encoding. When select another encoding, the application works fine. The behavior is reproducible.

Operating System: Linux 4.11.0
Distribution: Debian Testing
Platform: Intel 64

~"\nThread "
>~"1 \"tilix\" received signal SIGSEGV, Segmentation fault.\n"
>~"0x00007f2c3278739e in glib.Str.Str.toStringzArray(immutable(char)[][]) () from /usr/lib/x86_64-linux-gnu/libgtkd-3.so.0\n"
>*stopped,reason="signal-received",signal-name="SIGSEGV",signal-meaning="Segmentation fault",frame={addr="0x00007f2c3278739e",func="glib.Str.Str.toStringzArray(immutable(char)[][])",args=[],from="/usr/lib/x86_64-linux-gnu/libgtkd-3.so.0"},thread-id="1",stopped-threads="all",core="2"
dNOTE: INFERIOR SPONTANEOUS STOP
sAngehalten.
dState changed from InferiorRunOk(11) to InferiorStopOk(14) [master]
dHANDLING SIGNAL SIGSEGV
sAngehalten: Segmentation fault (Signal SIGSEGV).

>&"p 0\n"
>~"$2 = 0"
>~"\n"
>^done

<25-thread-info
>25^done,threads=[{id="1",target-id="Thread 0x7f2c3316b980 (LWP 26808)",name="tilix",frame={level="0",addr="0x00007f2c3278739e",func="glib.Str.Str.toStringzArray(immutable(char)[][])",args=[],from="/usr/lib/x86_64-linux-gnu/libgtkd-3.so.0"},state="stopped",core="2"},{id="2",target-id="Thread 0x7f2c22618700 (LWP 26809)",name="gmain",frame={level="0",addr="0x00007f2c300ed63d",func="poll",args=[],file="../sysdeps/unix/syscall-template.S",fullname="/build/glibc-DY4NiR/glibc-2.24/io/../sysdeps/unix/syscall-template.S",line="84"},state="stopped",core="2"},{id="3",target-id="Thread 0x7f2c21e17700 (LWP 26810)",name="gdbus",frame={level="0",addr="0x00007f2c300ed63d",func="poll",args=[],file="../sysdeps/unix/syscall-template.S",fullname="/build/glibc-DY4NiR/glibc-2.24/io/../sysdeps/unix/syscall-template.S",line="84"},state="stopped",core="2"},{id="4",target-id="Thread 0x7f2c20f86700 (LWP 26811)",name="dconf worker",frame={level="0",addr="0x00007f2c300ed63d",func="poll",args=[],file="../sysdeps/unix/syscall-template.S",fullname="/build/glibc-DY4NiR/glibc-2.24/io/../sysdeps/unix/syscall-template.S",line="84"},state="stopped",core="1"},{id="8",target-id="Thread 0x7f2c116c3700 (LWP 26838)",name="pool",frame={level="0",addr="0x00007f2c300f21e9",func="syscall",args=[],file="../sysdeps/unix/sysv/linux/x86_64/syscall.S",fullname="/build/glibc-DY4NiR/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/syscall.S",line="38"},state="stopped",core="2"}],current-thread-id="1"
<26python theDumper.fetchStack({"limit":20,"nativemixed":0,"token":26})

>&"python theDumper.fetchStack({\"limit\":20,\"nativemixed\":0,\"token\":26})\n"
>~"result={token=\"0\",stack={frames=[frame={level=\"0\",address=\"0x7f2c3278739e\",function=\"glib.Str.Str.toStringzArray(immutable(char)[][])\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"1\",address=\"0x7f2c32565935\",function=\"gio.Settings.Settings.setStrv(immutable(char)[], immutable(char)[][])\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"2\",address=\"0x559d108045d5\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"3\",address=\"0x7f2c2e9929e4\",function=\"g_cclosure_marshal_VOID__STRINGv\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"4\",address=\"0x7f2c2e9901a4\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"5\",address=\"0x7f2c2e9aa8cd\",function=\"g_signal_emit_valist\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"6\",address=\"0x7f2c2e9aafbf\",function=\"g_signal_emit\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"7\",address=\"0x7f2c2862dae1\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"8\",address=\"0x7f2c2861a502\",function=\"gtk_cell_area_activate_cell\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"9\",address=\"0x7f2c2861a8fe\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"10\",address=\"0x7f2c2884a545\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"11\",address=\"0x7f2c2dba9038\",function=\"ffi_call_unix64\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"12\",address=\"0x7f2c2dba8a9a\",function=\"ffi_call\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"13\",address=\"0x7f2c2e990c8a\",function=\"g_cclosure_marshal_generic_va\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"14\",address=\"0x7f2c2e9901a4\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"15\",address=\"0x7f2c2e9aa8cd\",function=\"g_signal_emit_valist\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"16\",address=\"0x7f2c2e9aafbf\",function=\"g_signal_emit\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"17\",address=\"0x7f2c286c706b\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"18\",address=\"0x7f2c2e992d27\",function=\"g_cclosure_marshal_VOID__BOXEDv\",file=\"\",line=\"0\",module=\"\",language=\"c\"}frame={level=\"19\",address=\"0x7f2c2e9901a4\",function=\"??\",file=\"\",line=\"0\",module=\"\",language=\"c\"}].report}}\n"
>26^done

**Comment by gnunn1** [comment]
Thanks for reporting this, it has been fixed.
