### ISSUE TITLE
Saving history using session identifiers

### ISSUE THREAD

**Issue by rickhall** [gnunn1/tilix#1035]
Tilix seems pretty cool. On the Mac I use iTerm and with it I was able to save my command histories for each of my shell instances using a special environment variable from iTerm called $ITERM_SESSION_ID. I couldn't find any specific documentation on this, but it looks something like:
```
$ echo $ITERM_SESSION_ID
w0t8p0:2B55E6E0-AEFC-4CF0-9FC7-BCB1EB7D9B57
```
The first part encodes a unique identifier for the shell instance which is in [w]indow 0, [t]ab 8, and [p]anel 0. With such an environment variable, I was able to add the following to my ~/.profile for bash to get a unique history file for each shell instance:
```
sessionid=${ITERM_SESSION_ID%:*}
export HISTFILE=~/.bash-history-${sessionid}
```
Would it be possible to come up with a similar type of session identifier environment variable to make it possible for people to do similar tricks with Tilix?

**Comment by gnunn1** [comment]
Adding an environment variable for a session identifier is trivial and I'm happy to do that. However I'm curious, does iterm somehow reassociate the same session id between invocations or are you always creating new history files with this technique? If iterm does do this, do you know how it works?

**Comment by gnunn1** [comment]
Oh and just to be clear, tilix already has a ```TILIX_ID``` environment variable that represents a specific terminal. When you say session, I'm assuming you are referring to what Tilix calls a session: a single page with multiple split terminals.

**Comment by rickhall** [comment]
Yeah, I tried not to use the term "session" to avoid confusion. :-)

The iTerm approach isn't infallible. I believe its session identifier is based on the order the windows are opened (i.e., Tilix sessions). So, if you open your windows in the wrong order, then you get your saved command histories associated with the wrong terminals. So, as long as you take care to open the windows (i.e., sessions) in the same order, the same session identifier is associated with the same terminals in the window.

Perhaps there is a way to improve upon this by using named sessions or something and then using the session name in the identifier, so that way the order of opening sessions wouldn't matter.

**Comment by gnunn1** [comment]
Tilix allows you to save and restore the layout of the session in a JSON file (see Save/Open in hamburger menu). I think an easy way to do this is to simply save and restore the TILIX_ID when saving and loading the sessions. This way when you reload the session you will be using the same IDs and attached to the same history files.

Would this do the trick for you?

**Comment by rickhall** [comment]
As long as the TILIX_ID is globally unique for a given terminal, I think that would work fine. Perhaps even better than the iTerm solution. Not only would it be order independent, but it would also survive changing your layout.

**Comment by gnunn1** [comment]
OK I've modified the session to save/load the UUIDs so hopefully this will do the trick.

**Comment by rickhall** [comment]
Is there a place where I can get a nightly build to give it a test drive?

**Comment by gnunn1** [comment]
There is not but I built a new binary for you that you can download at the link below and try out.

gexperts.com/files/tilix.zip

**Comment by rickhall** [comment]
Ok, thanks, I'll give it a whirl tomorrow.

**Comment by rickhall** [comment]
I tested this out and it appears to work fine, now I can save my history for each terminal. On the Mac I was putting the HISTFILE environment variable in .profile, but on Fedora I had to add it to .bashrc. Regardless, this works great. Thanks!

**Comment by rickhall** [comment]
Ok, it's been a while, but a quick question to follow up on this. Is it possible to determine if a given terminal has been reloaded as part of a session? I'd like to differentiate between history files from temporary terminals and ones that are part of a saved session.

My approach for saving the history using the TILIX_ID works fine, but it does create unique history files for every terminal instance, which ultimately requires some garbage collection on my part for any temporary terminals I've opened/closed.

If I could determine if the terminal was from a saved session, then I could set a unique TILIX_ID-based history in that case and just use the default ~/.bash_history in the temporary case.

Thanks.

**Comment by gnunn1** [comment]
By reloaded, do you mean when it is initially loaded from a session file. If so, I don't know of an obvious way to know that as tilix doesn't keep track of the fact the session was loaded from the file. It's not impossible to do in terms of having tilix set an environment variable or something but it's not something I plan on doing myself. Not averse to accepting a PR for it though.

**Comment by rickhall** [comment]
Yeah, simply setting an environment variable for terminals created when loading a saved session would be sufficient, whereas terminals created randomly by the use would not have this flag set.

Technically, this would mean that when you first created a session, these terminals would not have the environment variable set, so any history up until you save the session and reload it would not be saved.

I can live with that, since I can't think of another way right off the top of my head.

I'm not averse to looking into making a pull request, but perhaps you could point me in the direction of where I should start my investigation?
