### ISSUE TITLE
Padding around terminal

### ISSUE THREAD

**Issue by pawandubey** [gnunn1/tilix#1036]
Is there a way to add padding around the text in the terminal? I basically want there to be a gap of a few pixels between the edges of the text and the actual edge of the window. Most terminal emulators support this via some kind of configuration option but I haven't found anything for tilix yet :cry:

**Comment by gnunn1** [comment]
There is no configuration option for this and I have no plans to add one. However, you can do it by adding some CSS to ```~/.config/gtk-3.0/gtk.css``` as follows:

```
vte-terminal {
    padding: 10px;
}
```
Depending on what version of GTK you are using, the selector may need to be adjusted. This works for me on GTK 3.22. Also note this will effect all VTE based terminals including gnome-terminal.
