### ISSUE TITLE
GTK Inspector doesn't work

### ISSUE THREAD

**Issue by happylynx** [gnunn1/tilix#1039]
`tilix --help-gtk` suggests that it accepts parameter `--gtk-debug`. However `tilix --gtk-debug=interactive` just starts tilix without GTK Inspector. `--gtk-debug=interactive` parameter invokes GTK Inspector for standard gnome apps like `gnome-calc` or `gnome-calendar`.

```
$ tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.17

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
You can use the inspector by specifying an environment variable for now:

```
GTK_DEBUG=interactive tilix
```

**Comment by gnunn1** [comment]
Also, ```tilix --gtk-debug=interactive``` works fine for me here on GTK 3.22. Are you using the Gnome Desktop Environment?

**Comment by egmontkob** [comment]
Works here too (Ubuntu Zesty).

**Comment by gnunn1** [comment]
I do not believe this is a Tilix issue, closing.

Thanks for the second data point @egmontkob.
