### ISSUE TITLE
Fedora 26 VTE Configuration Warning with Tmux

### ISSUE THREAD

**Issue by jravetch** [gnunn1/tilix#1043]
I followed the docs here:

https://gnunn1.github.io/tilix-web/manual/vteconfig/

I tried both methods, I'm using Zsh, either explicitly sourcing vte.sh in zshrc or using "run as login".  Neither work, as I still get the pop that VTE is not configured correctly.

**Comment by gnunn1** [comment]
If you switch to a different directory and then split the terminal, does the new terminal stay in the same directory or return to root? Just trying to determine if the warning is valid or not.

**Comment by jravetch** [comment]
I should also mention that I use tmux with byobu and create multiple tmux sessions in the same window.  When switching to a different directory and splitting, I stat in the stay directory in the first tmux session that I opened. The second window is actually duplicating everything I type in the first window.  I had already silenced the pop up, so not sure if it's working or not.

**Comment by gnunn1** [comment]
Can you try without tmux and byobu and see if you still get the warning and the directory works as expected.

**Comment by jravetch** [comment]
With tmux and byobu disabled I can create new sessions with different directories.  How can I test that VTE is working properly?  I disabled the pop up.

**Comment by gnunn1** [comment]
You can re-enable the warning in dconf under com/gexperts/tilix under the key warn-vte-config-issue.

**Comment by jravetch** [comment]
Thanks, re-enabled the warning in dconf.  Opened tilix with tmux and byobu disabled and no warnings appear.  I guess this issue should be changed to VTE configuration issue with tmux?

**Comment by gnunn1** [comment]
The detection of this issue is inherently flaky as it relies on the timing of a couple of asynchronous events. I'm working on improving this for #982 and I've made a change already which may fix this issue. However, I suspect it's unlikely I will get this perfect. 

Since this is related to a specific program and the warning can be disabled I'm not planning on pursuing it further at this time.
