### ISSUE TITLE
Add support for fractional parameters (for columns and rows)  in --geometry

### ISSUE THREAD

**Issue by arigit** [gnunn1/tilix#1046]
Use case: using various desktop shortcuts to open Terminal windows in predetermined places in the screen, at fixed sizes.

With urxvt, I can use for example:

--geometry 141x**38.4**+1283+737

... which  fills a 1/4th tile in my 27" screen.

Tilix accepts the same input but ignores (trims out) the fractional part, and the tiling does not look good (tilix interprets 141x38)

I understand that cols/rows map to pixels based on the font size. Hence the workaround to obtain a desired height & width used by urxvt is to accept fractional input there.

An alternative way to support the same use case could be something like:

--geometry-in-pixels WIDTHxHEIGHT+X+Y

instead of COLSxROWS+X+Y  -  but this departs a bit from the X11 tradition that urxvt maintains.

**Comment by gnunn1** [comment]
Right now tilix relies on the VTE to set the size based on the columns and rows, I have no plans to bring that calculation into tilix as keeping it consistent with the VTE's implementation is a fools game IMHO.

The ```--geometry-in-pixels``` option could be done though.

**Comment by gnunn1** [comment]
I'm cleaning up issues and closing this issue. At the moment I'm trying to keep the number of new options introduced to a minimum and I don't have any plans to implement a ```geometry-in-pixels``` option.

**Comment by arigit** [comment]
No worries and thanks for all the work on Tilix, it's great. 
The driver for this request was the absence (at that time) of good window-tiling options when using gnome shell + Wayland, most were broken. 
Nowadays, the "gtile" gnome shell extension works nicely and it has been fully revamped - it fits my use case and replaces the needed of fixed geometry, in my use-case.
