### ISSUE TITLE
Add optional support for tabs

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#1047]
Add optional support for tabs for people who prefer this style. The sidebar would remain the default but allow enabling tabs as an alternative. The option would require a window restart.

**Comment by gnunn1** [comment]
The basics are there now and seem to be working OK. I need to add support for detaching and re-attaching tabs plus some options about the tabs themselves.

**Comment by gnunn1** [comment]
Hmm, that went faster then I expected. Have at it and let me know what I screwed up.

**Comment by alexwhitman** [comment]
I notice there's only a single option for tab positioning - it would be good to have a different position between "regular" windows and Quake mode.  I'd most likely have tabs at the top of regular windows and tabs at the bottom on Quake windows.

**Comment by gnunn1** [comment]
Good point @alexwhitman, I'll add that option to the Quake page as well.
