### ISSUE TITLE
tilix does not expand text

### ISSUE THREAD

**Issue by mozartilize** [gnunn1/tilix#1049]
![screenshot from 2017-08-07 14-27-47](https://user-images.githubusercontent.com/26346270/29016515-eedf0618-7b7c-11e7-9be5-7b58177e8809.png)

tilix version 1.6.4 - compares to gnome terminal, Ubuntu gnome 17.04

**Comment by gnunn1** [comment]
In the Tilix profile that is being used, is the option "Rewrap on resize" under Text Appearance enabled?

**Comment by mozartilize** [comment]
@gnunn1 thanks, it was uncheck :)
