### ISSUE TITLE
Quake mode blocks Gnome shell in Fedora 26

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1050]
Starting `tilix --quake` renders my system unusable. I then need to Ctrl+Alt+F3 and `killall tilix`.

In detail, Ctrl+Alt+F3 doesn’t work at first and nothing happens – I need to unplug my external monitor for my system to respond and to give me a CLI prompt. But I assume this to be a shell bug (and I don’t report it, due to the new monitor abstraction system being introduced at the moment).

**Comment by gnunn1** [comment]
I assume this is under Wayland, any difference in X11? Also if you run tilix from a terminal in quake mode (with all other tilix instances closed) are any warnings or errors shown on the command line.

I'll download Fedora 26 and test it in a VM as well.

**Comment by fbruetting** [comment]
• With X11, Quake-Tilix opens from the bottom upwards on my second HD screen (my Laptop-internal screen is UHD, maybe because of this or some X11 weirdness).
• If I start the Tilix application via Gnome-Terminal, I don’t receive any output when the system hangs.

**Comment by gnunn1** [comment]
I just tried in a Fedora 26 VM and it is working fine for me here unfortunately. If you disable one of the screens does it make any difference, just wondering if it is related to the layout somehow.

**Comment by fbruetting** [comment]
Ok, now it get’s weird. If I disconnect my external screen, I get it to work properly. I connected my screen again, ran `tilix --quake` in Gnome Terminal and it worked with two screens, too. But then I tried a second time and Gnome shell was blocked again.

Plus, now my keyboard shortcut Ctrl+T opens tilix (normal mode) with about 20 seconds delay. If I start Tilix right out of the applications overview, it works fine.

**Comment by gnunn1** [comment]
I'm not sure if there is much I can do to resolve this, I just a my multi-monitor setup on my Arch install with a 4k laptop screen and normal dpi external monitor and it worked fine under both Wayland and X11 other then a positioning issue I need to address. No crash of gnome shell though.

Debugging gnome-shell itself looks to be a bit of a monster.

Anyone else on fedora 26 having this issue?

**Comment by fbruetting** [comment]
So it seems to be an issue of Wayland or something like that. We can wait and check this behaviour at a later point in time?

**Comment by OriginalFannibal** [comment]
> Anyone else on fedora 26 having this issue?  

Not at all.

**Comment by mariuszs** [comment]
I have fedora 26 with wayland and have no issue with quake mode.

**Comment by fbruetting** [comment]
Multi-monitor, too?

**Comment by mariuszs** [comment]
Yes, laptop w 4k display + external monitor 4k

**Comment by fbruetting** [comment]
So I just checked this behaviour again. Following you see starting Quake by Tilix / Gnome-Terminal / Alt+F2:

![bildschirmfoto von 2017-09-09 15-35-13](https://user-images.githubusercontent.com/10520767/30240662-e9ed1e1c-9574-11e7-9b40-80a9fdc13c20.png)
![bildschirmfoto von 2017-09-09 15-35-39](https://user-images.githubusercontent.com/10520767/30240663-ed21521a-9574-11e7-9977-56f178c72559.png)
![bildschirmfoto von 2017-09-09 15-36-06](https://user-images.githubusercontent.com/10520767/30240665-efc4423e-9574-11e7-921b-1c5e950de4e7.png)

So I assume this to be a bug in gnome-shell, but I don’t know the circumstances. Can anyone forward this to gnome-shell with a good description about what’s not working right?

**Comment by gnunn1** [comment]
As this doesn't appear to be a tilix bug and the issue itself has gotten stale I'm going to go ahead and close it as part of cleaning up issues. Feel free to re-open if you disagree.

**Comment by fbruetting** [comment]
I now get a message that Quake mode isn’t supported under Wayland… ;)
