### ISSUE TITLE
Inactive tabs are transparent

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/tilix#1051]
On Ubuntu 16.04, inactive tabs are transparent and the desktop can be seen:
![selection_001](https://user-images.githubusercontent.com/422013/29022484-68774ccc-7b61-11e7-86d2-9a87281679e5.png)

Also, the top and bottom of the tabs have more padding than is necessary in my opinion (but this may be by design).

**Comment by gnunn1** [comment]
Interestingly the tab size in Ubuntu is inconsistent, compare the tabs in Nautilus versus gedit for example. I've opted to emulate gedit since more people will see that but just a point of interest.
