### ISSUE TITLE
Add a way to quickly select bookmarks using keyboard

### ISSUE THREAD

**Issue by Naatan** [gnunn1/tilix#1053]
At the moment there's no simple way of accessing bookmarks with just your keyboard (that I can find), it would be nice if there was one.

**Comment by gnunn1** [comment]
Use the shortcut for the book mark dialog (ctrl-shift-b or whatever you assigned to it), type a few letters of the bookmark you want, hit enter.

**Comment by Naatan** [comment]
Bah, I must be going blind cause I went through the shortcut list twice -.- Thanks!
