### ISSUE TITLE
Remember last path for open/save sessions

### ISSUE THREAD

**Issue by Naatan** [gnunn1/tilix#1054]
I have to navigate to the folder with my session files each time I invoke these as it always defaults to my home folder.

**Comment by maidenone** [comment]
I just built tilix 1.7.1 and my loaded session starts at home instead of the dir that was present when i saved the session. i also see no paths is set in the session file that i saved. (save with ctr + shift + s) and see that the session.json file is updated, but paths is always " "

**Comment by iaeiou** [comment]
> I have to navigate to the folder with my session files each time I invoke these as it always defaults to my home folder.

See https://github.com/gnunn1/tilix/issues/632#issuecomment-521092538
