### ISSUE TITLE
Allow associating sessions with profiles

### ISSUE THREAD

**Issue by Naatan** [gnunn1/tilix#1055]
It would be nice if I could associate sessions with a profile, so that when a profile is selected it automatically launches these sessions. 

My primary use case would be to have Tilix automatically load my default sessions and splits whenever I start it.

**Comment by gnunn1** [comment]
No plans for that, profiles are associated with terminals and not sessions and it would be too complicated to try to this for little benefit IMHO. You can have Tilix automatically load sessions on startup by using the ```--session``` command line option.
