### ISSUE TITLE
Save session doesn't save path for split if a command is running 

### ISSUE THREAD

**Issue by Naatan** [gnunn1/tilix#1056]
* Created a bookmark with command `cd PATH && tail FILE`
* Opened a new session, split the session and ran the bookmark in the second split
* Saved the session
* Opened the session

Both splits are on the same (default) path

**Comment by gnunn1** [comment]
Is the VTE configured correctly (https://gnunn1.github.io/tilix-web/manual/vteconfig/), did you get the warning dialog when you started tilix?

If you open Tilix, cd to a directory and then split the terminal is the new terminal using the same directory as the previous terminal or home? If it's using home your VTE isn't configured correctly, see the link above.

**Comment by Naatan** [comment]
It's using the same directory as the other when I open a split.

It seems bookmarks are unrelated, I can reproduce the issue just by typing `cd PATH && tail -f FILE`, which is an important detail I seem to have left out before; the `-f` switch.

**Comment by gnunn1** [comment]
I understand now, unfortunately it's not something that can be fixed because the command needs to end in order for the directory to be reported to tilix. This is because the VTE uses the PROMPT_COMMAND to pass it up to the terminal so it requires the prompt to appear after the directory change.

**Comment by Naatan** [comment]
Alright, thanks for explaining.
