### ISSUE TITLE
tabs size is too big

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1057]
can it be reduced?
![tabs-size](https://user-images.githubusercontent.com/11244308/29049454-b0c0d8ea-7bde-11e7-8152-fdc1813a65bc.png)

on image is compared with Nautilus and Adapta Nokto Eta, but i can reproduce with Adwaita too

**Comment by gnunn1** [comment]
It already was for Ubuntu so hopefully it should work on other themes, see #1051. Try updating the source and rebuilding to see if it helps, note it depends on CSS in the resource file so you can't just compile the binary, you need to install the resource file as well.

**Comment by alex285** [comment]
what you mean install the resource file? it is installed
should i do something with the css files?

**Comment by gnunn1** [comment]
Just run ```sudo ./install.sh```

**Comment by alex285** [comment]
how i could run Tilix without sudo ./install.sh? :)

**Comment by alex285** [comment]
did you try with Adapta?
when i said i can reproduce with Adwaita, it was my bad. the difference is like 2-3 pixels really

**Comment by alex285** [comment]
@gnunn1  basically i think it is Adapta issue. keep trying with other themes seems okay

**Comment by alex285** [comment]
basically Adapta needs something like that 
```
tab {
  padding:0px;
}
```
can we have specific styles for themes like: `tilix.Adapta.css`? i can PR if you want me, since i use both Adapta and Tilix from source

**Comment by gnunn1** [comment]
There's already css for specific themes, see data/resources/css

**Comment by alex285** [comment]
@gnunn1 it only needs to add Adapta on `tilix.gresource.xml` and `css/tilix.Adapta.css` ?

**Comment by gnunn1** [comment]
That should be it, the code loads the case with the same name as the theme.

**Comment by alex285** [comment]
@gnunn1 cool! i will try that

**Comment by alex285** [comment]
@gnunn1 that seems to work 
https://github.com/gnunn1/tilix/pull/1058

however i found more broken things, like the notifications on tabs

**Comment by alex285** [comment]
it is fixed upstream on Adapta!

**Comment by dfbadawi** [comment]
looks like the tab size "grew up" again.
It is something in Tilix or Adapta?

tks

**Comment by trialism** [comment]
I have this issue too with 1.9.1 on manjaro.

**Comment by siavashs** [comment]
An update from Fedora 29 to 30 cause tab width on left/right to be too wide!
```
Installed Packages
Name         : tilix
Version      : 1.9.0
Release      : 2.fc30
Architecture : x86_64
Size         : 4.0 M
Source       : tilix-1.9.0-2.fc30.src.rpm
Repository   : @System
From repo    : fedora
```
![image](https://user-images.githubusercontent.com/113189/57089541-f3420e00-6d04-11e9-96c1-caee59d2174c.png)
