### ISSUE TITLE
Context menu is clipped and only shows within the application.

### ISSUE THREAD

**Issue by cj-sv** [gnunn1/tilix#1059]
Ubuntu GNOME 17.04

![image](https://user-images.githubusercontent.com/11567756/29059285-67bf1792-7c47-11e7-82a0-bd34ee288a19.png)

![image](https://user-images.githubusercontent.com/11567756/29059319-8e84bf8a-7c47-11e7-88cf-ce973d3e8c28.png)

**Comment by gnunn1** [comment]
That's a limitation of popovers under X11 and there's nothing I can do about that. However I should look at moving a few more items in sub-menus to reduce the size particularly when running without  terminal titlebars where this is more likely to occur.

**Comment by gnunn1** [comment]
I'm thinking move ```Show File Browser...``` into ```Other``` and create a new submenu called ```Assistants``` where the Password and Bookmark stuff would be moved into.
