### ISSUE TITLE
Debian Sid terminal size not right

### ISSUE THREAD

**Issue by russel** [gnunn1/tilix#1061]
I have set the terminal size to 80x24, but it is coming up at 87x27.

**Comment by gnunn1** [comment]
Are you using Tilix from the debian package or building from master? There were some issues in the past with this but they have been sorted out the last few versions as far as I am aware. On my system 80x24 works fine.

Also, are you running Gnome or some other window manager?

**Comment by russel** [comment]
Debian Sid currently has Tilix 1.6.4 which is the version I am using from the package. Yes Gnome 3.

**Comment by gnunn1** [comment]
Can you post the output of ```tilix --version```, might be a VTE issue since it does the actual sizing.

Also, if you go bigger, like 90 x 30, does that work accurately? Just wondering if it's hitting a size constraint for some reason.

**Comment by russel** [comment]
```
|> tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.46
	GTK Version: 3.22.17

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by russel** [comment]
I tried setting 90x30 and got 95x33.

**Comment by gnunn1** [comment]
Thanks, that sounds like a problem with VTE but yours is pretty recent and should be fine. I'm on 0.48 myself.

I'll do some thinking and check some of my VMs to see if there is a similar problem in any of them.

**Comment by gnunn1** [comment]
Ubuntu 16.04 works fine, however Fedora 26 has the same issue. Interestingly it is using the exact same stack I am in Arch except I have ```GTK Version: 3.22.18``` and in Fedora it is ```GTK Version: 3.22.17```.

**Comment by gnunn1** [comment]
So I tried terminator and xfce4-terminal as well on Fedora 26 and they have the same issue as Tilix, looks like something is broken in VTE or GTK for that version. The reason gnome-terminal works is because they switched to calculating the sizing themselves instead of relying on VTE to do it as a convoluted way to fix geometry handling versus the simpler way Tilix does it.

Can you try xfce4-terminal or terminator and confirm you see the same issue. if so I'll close this and I'd recommend you file a bug with Debian.

**Comment by f2404** [comment]
Are Fedora 26 and Debian Sid systems running wayland or X?

**Comment by gnunn1** [comment]
@f2404 Good point, I'm so used to Debian/Ubuntu not using Wayland that I didn't even think of it. Fedora 26 is on Wayland, as soon as I switch to X11 it works fine. @russel can you confirm on your side?

**Comment by f2404** [comment]
@gnunn1 If something that should be working doesn't work, I first think wayland :)

**Comment by russel** [comment]
I generally use Wayland on Fedora Rawhide and Xorg on Debian Sid. However Debian Sid just switched to defaulting to Wayland so I am using Wayland – hence the need for Tilix since Debian Gnome Terminal doesn't have transparency unlike Fedora Gnome Terminal.

I will be using Xorg for presentations though as a crucial bit of software doesn't work on Wayland.

I'll check tomorrow to see if I can show this to be a Wayland problem.

**Comment by gnunn1** [comment]
It's always fun when you go to file a bug report you find you've already done it, apparently my memory is shit:

https://bugzilla.gnome.org/show_bug.cgi?id=779572

Closing this issue since it is in upstreams hands to fix.
