### ISSUE TITLE
Color-coded special characters

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1063]
I just had an issue with a CLI program, which – I first thought – is showing misbehaviour. Then I found out, that an ampersand inside an argument (an URL in this case) led to the shell altering the argument, before it was passed to the program. Is it therefore possible to color-code all special characters in the prompt? Like dyeing them red or anything like that. Or has this to be done by the shell itself?

**Comment by gnunn1** [comment]
Unfortunately this would need to be done by the shell or the program itself.
