### ISSUE TITLE
Window state restoring

### ISSUE THREAD

**Issue by hgaiser** [gnunn1/tilix#1065]
I was about to make an issue that since the latest update of Tilix, my window state is not restored, but then I saw the changelog and noticed an option was added to either save the window state or not. (* Added option to disable saving/restoring window state between invocations)

I decided to make an issue anyway :p but it is more of a suggestion to make the default behaviour of this option reflect the old situation (ie. save window state). Right now the default behaviour changed, which struck me as odd.

**Comment by gnunn1** [comment]
It was actually a very recent feature that was generating quite a few complaints, hence why I elected to leave it off by default. I think it's one of those cases where 50% of people are not going to like the default regardless of what I pick.

**Comment by hgaiser** [comment]
> I think it's one of those cases where 50% of people are not going to like the default regardless of what I pick.

Very true :) I didn't know it was a new feature, thats why I suggested to keep the old functionality. If it generated a lot of complaints then I leave it up to you on what the default should be. I am one of those persons who likes this feature (on) at least ;p
