### ISSUE TITLE
Feature request, support send text command line action

### ISSUE THREAD

**Issue by randy3k** [gnunn1/tilix#1068]
Something like `tilix -a send_text "echo hello world"` would send the echo statement to the active pane. It would be useful for other GUI programs to interact with tilix.

**Comment by f2404** [comment]
You know you can `echo "hello world" > /dev/pts/x` where x is the terminal number?

**Comment by gnunn1** [comment]
@f2404 I learned something new today, thanks!

@randy3k This would be covered by the existing open issues for a scripting capability and d-bus support, I don't plan on making it available via a command line option.

**Comment by f2404** [comment]
@gnunn1 You're welcome, I learned it recently myself :)

**Comment by randy3k** [comment]
But it requires capture the device number of the active pane at the first place. May be tilix can return some related info of the active pane?

**Comment by gnunn1** [comment]
@randy3k I'm not saying that is the way to go, just that it's a neat thing I didn't know about. As mentioned in my comment a scripting capability and/or a d-bus api would be the way to implement this.
