### ISSUE TITLE
Off topic what is the bash-prompt being used in the example screenshots?

### ISSUE THREAD

**Issue by harshavardhana** [gnunn1/tilix#1069]
Can you paste your .bashrc PS1, PROMPT_COMMAND somewhere?  :smile:  - looks pretty cool i must say!!

**Comment by gnunn1** [comment]
It's powerline.

https://powerline.readthedocs.io/en/latest/

**Comment by harshavardhana** [comment]
> It's powerline.
> 
> https://powerline.readthedocs.io/en/latest/

Cool figured it out anyways.. Thanks
