### ISSUE TITLE
Unable to install on Ubuntu 14

### ISSUE THREAD

**Issue by ArthurZ** [gnunn1/tilix#1070]
I am getting error
W:Failed to fetch http://ppa.launchpad.net/webupd8team/terminix/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
so unable to install

**Comment by gnunn1** [comment]
That version of Ubuntu is too old, the webupd8 PPA only supports 17.10, 17.04, and 16.04 as per the package description here:

https://launchpad.net/~webupd8team/+archive/ubuntu/terminix

Note I do not do the packaging, if you want to follow up on this please open an issue against the package in launchpad directly.

**Comment by ArthurZ** [comment]
OK, thanks, I think I should since I cannot upgrade the OS, now I wanted to install it on another machine which is Centos 7. 
The package notes says:

> Instructions not filled in by author. Author knows what to do. Everybody else should avoid this repo. 

Author who?

**Comment by gnunn1** [comment]
No idea, like I said I don't do the packaging. I would suggest opening an issue with the package. Having said that though installing tilix should be the same as any other COPR.

**Comment by bil-elmoussaoui** [comment]
@ArthurZ the gtk version shipped with Ubuntu 14 is too old(3.10 or 3.12, can't remember). The application uses gtk.headerbar which is a widget introduced on gtk 3.14.
