### ISSUE TITLE
Cannot unbind keyboard shortcuts

### ISSUE THREAD

**Issue by brndd** [gnunn1/tilix#1074]
I'd like to remove some, but not all, of the existing keyboard shortcuts, but there does not seem to be any way to do this in the settings dialog.

A workaround I found was binding each undesired action to the same key, clicking "Ok" on the prompt to unbind the existing action every time, then finally rebinding some desired action to the same key to get rid of the final undesired action, and then resetting the binding of the desired action.

**Comment by gnunn1** [comment]
In Preferences | Shortcuts click on the shortcut you want to remove and hit the backspace key, the shortcut should now show ```disabled```.

**Comment by frannylac** [comment]
> In Preferences | Shortcuts click on the shortcut you want to remove and hit the backspace key, the shortcut should now show `disabled`.

I would to clarify this for those people who didn't understood like me.
"**Click on the shortcut as if you would to assign it**", then when the text "New accelerator..." is shown, hit the backspace key for disable shortcut. Now the text "disable" is shown, the shortcut is clean.

**Comment by clockworkpc** [comment]
> ###
> **[frannylac](/frannylac) ** commented [May 3, 2024](#issuecomment-2093875689) •

THANK YOU
