### ISSUE TITLE
Dark theme doesn't seem to work.

### ISSUE THREAD

**Issue by samr28** [gnunn1/tilix#1075]
So I opened the preferences and clicked on Appearance on the side bar. I then switched Theme to Dark and restarted the app. I tried restarting with the quit button in the top menu, quitting by right clicking on the taskbar, and the quit button in the corner. Each time when I repoen, it still has the light theme. Please let me know any logs or other info that I can provide to help diagnose this issue.

Debian 9 with KDE

**Comment by gnunn1** [comment]
Your GTK theme needs to support the dark variant, if you switch the theme to Adwaita does it work?

**Comment by gnunn1** [comment]
No response from OP, closing issue.

**Comment by samr28** [comment]
For theme, the only options that I have are Light or Dark. I don't have an Adwaita option. From what I read online, GTK is for Gnome and I'm using KDE. Not sure if there's something that I'm missing but my KDE is currently themed with the dark theme.

**Comment by samr28** [comment]
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/3688992/29488454-2222f068-84d1-11e7-9a99-632c60a86eeb.png)

As you can see, I have the dark theme selected as well as a background image which both don't show up. I did quit and restart but that didn't seem to work.

**Comment by phw** [comment]
@samr28 As written in the original answer whether the dark theme is available or not depends on the GTK theme you use. The GTK theme is not something that is set in Tilix settings, but globally. AFAIK KDE Plasma provides options for setting the GTK theme, too.

**Comment by samr28** [comment]
Sorry for the delayed response. I checked in KDE and my theme has been set to "Breeze Dark" the whole time. Maybe I'm looking in the wrong place or something.

**Comment by samr28** [comment]
I also can't get the background image to work.
![image](https://user-images.githubusercontent.com/3688992/29743322-43d2319a-8a55-11e7-92bf-9c415ac21707.png)

**Comment by phw** [comment]
Is this the Qt (KDE) theme or GTK? The KDE Plasma settings should look something like https://blog.monotok.org/wp-content/uploads/2014/08/snapshot2.png

I know there is a GTK Variant of the breeze theme, don't know if it supports a dark variant, though. Try setting a GTK theme that supports dark theming.

**Comment by samr28** [comment]
oooo. Found it :) I switched from breeze to breeze to breeze dark for my GTK theme. Still not sure about the background image though. Should I make a different issue report for that?

**Comment by gnunn1** [comment]
@samr28 The background picture requires transparency to work, go into the profile and make use the transparency slider and the image should appear.

**Comment by samr28** [comment]
Awesome!! Thanks for your help :+1:

**Comment by tsoernes** [comment]
I'm having the same problem. Two computers both running Fedora 27 KDE with same settings for GTK application style. Dark theme works for tilix on one computer but not the other.

Have tried Adwaita and Adwaita-Dark for GTK2, and Default and Emacs (the only options) for GTK3, with and without 'Prefer Dark GTK3 themes' for Tilix.

It's strange 'cause dark theme has been working for a year on both computers.

**Comment by danjac** [comment]
I'm seeing a similar issue with Tilix 1.9.3 (on Gnome 3.34/Fedora 31). Even using Adwaita Dark, and with appearance set to Default or Dark, Tilix still uses Light theme for title/menus. Resetting settings, reinstalling etc has no affect. No other applications have this issue.

**Comment by abuGit** [comment]
I have the same problem. Tried everything:

 * changed dark theme preferences
 * disabled my blur script
 * set different env
 * set several kvantum themes, forced title bar color theme, ...

Tilix looks like 

![tilix](https://user-images.githubusercontent.com/26663544/119737787-0e4dc080-be80-11eb-94ec-196a6c97dc8c.png)

Other programs like evolution can be application specific set to a dark theme like e.g. evince

![evince](https://user-images.githubusercontent.com/26663544/119738059-5a990080-be80-11eb-9c26-03f05269c52b.png)


 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.4.0-73-generic
 Shell: bash 5.0.17
 DE: KDE 5.68.0 / Plasma 5.18.5
 WM: KWin
 GTK Theme: WhiteSur-light [GTK2/3]
 Icon Theme: WhiteSur

Versions
	Tilix version: 1.9.4
	VTE version: 0.60
	GTK Version: 3.24.20

**Comment by GeorgeSapkin** [comment]
As of Fedora 40, Dark theme starts to work in Tilix after installing `gnome-themes-extra`.
