### ISSUE TITLE
Long delay when opening in quake mode

### ISSUE THREAD

**Issue by step21** [gnunn1/tilix#1076]
Since a recent update (probably) tilix takes forever to show up from quake mode, to the point of being unusable. I didn't measure super accurately but it is approximately almost 30 seconds. As a result, I basically had to stop using quake mode.
This is on Tilix 1.6.4 installed on Ubuntu 16.04.2 running under Unity with Gtk 3.18.9

**Comment by gnunn1** [comment]
When you say recent update, do you mean an update to Tilix or a recent update in Ubuntu? Off hand I'm not sure what the problem is, I'll try it out on a local 16.04 VM.

**Comment by step21** [comment]
It could be either, really. I cannot pinpoint a specific update, as i didn't react at first, thinking it was maybe just some other apps slowing down the Desktop Environment/Window Manager. But then as it persisted, I thought it might have been an update, though really no idea which one. For Ubuntu, if anything it could only have been a security update or similar, as they do not really do version upgrade on LTS.

**Comment by gnunn1** [comment]
So I tried install Tilix 1.6.4 from the webupd8 PPA in Ubuntu 16.04 VM and it worked fine for me, no issue at all. If you run tilix from gnome-terminal, i.e. ```tilix --quake```, without any other instances of tilix's running do you still see a delay? Is anything logged to stdout?

**Comment by step21** [comment]
Mmmh. When I run it just like this it doesn't have a delay. I have it set as a 'start program' in Ubuntu's settings. However maybe it is mentioned somewhere else, as I also noticed that when I kill all of its processes, and then hit the key combination, tilix still starts (after a delay) - which shouldn't happen, right?

**Comment by gnunn1** [comment]
What happens if you setup another program like gedit to start with a hot key, is there any delay.

I also wonder if it's related to DBus activation. In the tilix desktop file, try changing DBusActivatable to false from true, reboot and see if it makes any difference.

**Comment by step21** [comment]
Yeah there is also a delay for gedit. I could not test the dbus thing yet.

**Comment by gnunn1** [comment]
If you get the same problem with gedit then it sounds more like an Ubuntu issue rather then a tilix issue.

**Comment by step21** [comment]
Yeah, maybe. But there were not really any big updates . :-/ Though no idea to figure out why. Just re-tried guake, with their built-in key combination functionality (not set in unity/gnome settings) the delay doesn't happen. So maybe I'll just use that again.

**Comment by gnunn1** [comment]
The difference is that Guake manages the hot key itself whereas tilix (and others like xfce4-terminal) relies on the desktop manager. The benefit of the latter approach is that it works under Wayland.

**Comment by step21** [comment]
Sure. But like I said, really no idea how to figure out why this started happening.

**Comment by gnunn1** [comment]
That's why you should open a bug with Ubuntu, they know better then I do what's changed recently. Post a link to the bug report here and I'll keep an eye on it.

**Comment by step21** [comment]
Ok. Report is here https://answers.launchpad.net/ubuntu/+question/656599

**Comment by daniel-wtd** [comment]
Same issue can be seen in F26 with Gnome (wayland and xorg) session.

The only index I can see during hitting the shortcut is:
`Aug 27 12:05:16 nb01 org.gnome.Shell.desktop[27446]: Window manager warning: last_user_time (44627450) is greater than comparison timestamp (44627449).  This most likely represents a buggy client sending inaccurat
Aug 27 12:05:16 nb01 org.gnome.Shell.desktop[27446]: Window manager warning: 0x3400010 (Tilix Quak) appears to be one of the offending windows with a timestamp of 44627450.  Working around...
Aug 27 12:05:16 nb01 org.gnome.Shell.desktop[27446]: Window manager warning: last_user_time (44627783) is greater than comparison timestamp (44627782).  This most likely represents a buggy client sending inaccurat
Aug 27 12:05:16 nb01 org.gnome.Shell.desktop[27446]: Window manager warning: 0x3400010 (Tilix Quak) appears to be one of the offending windows with a timestamp of 44627783.  Working around...
`

**Comment by step21** [comment]
Thanks, @daniel-wtd - I do not remember seeing this error message with unity - where did you see it? (I am asking because normally when launching tilix from terminal, it does not write output to the originating shell or itself) (And it will prob look a bit different anyway under Unity)

**Comment by daniel-wtd** [comment]
just had a look at "journalctl -x"

**Comment by gnunn1** [comment]
That error message should be fixed now, if it resolves this that would be great.

**Comment by PombaM** [comment]
I don't see any lags on my device running Ubuntu 16.04.3, if it helps I set my keyboard shortcuts using `CCSM` (CompizConfig Settings Manager)

**Comment by step21** [comment]
@gnunn1 where should it be fixed? Only in source or also in ppa?

**Comment by gnunn1** [comment]
Only on the master in github, ie source.

**Comment by step21** [comment]
ah, thanks.

**Comment by step21** [comment]
Ok, so this still happens, even with the version compiled from source. Also, pretty sure soon I will have all the toolchains on one machine. ^^
FWIW, I also checked the logs with both versions. The only thing I could find that seems possibly related is ```Sep 08 18:20:41 <hostname> gnome-keyring-daemon[9575]: The Secret Service was already initialized
Sep 08 18:20:41 <hostname> org.freedesktop.secrets[9697]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh```

**Comment by step21** [comment]
Ok, I might have it figured out. Though it doesn not entirely add up. Some time ago, I disabled at least gnome-keyring daemons handling of ssh sessions or disabled it from starting entirely. (see also previous comment) This was because of the way it tries credentials/handles keys I was unable to use ssh alone or with git on the terminal in a normal way.
Most apps did not care. The only app that I found cared was Nylas Mail, which relies on it for storing account information. Other apps, even gnome native ones such as Geary apparently do not. Now, it seems that when starting it manually, tilix starts fine again. Or it was some other update? I will monitor this some more and report if anything changes.

**Comment by gnunn1** [comment]
I use the gnome-keyring to store passwords however it should only be used when you activate the password dialog. I'll double check that though.

**Comment by macandchief** [comment]
As for the quake mode: I have Tilix version: 1.6.4 and it's been working great! I really like it, no delay when opening. Two short questions though: - It's more like hide/unhide and not that quake-opening (roll down) with animation. Any chance implementing something like that?
- It's not possible to resize the window after opening it via quake mode (I mean making the window bigger via right down corner). Am I missing something or is it not implemented yet?
Cheers

**Comment by step21** [comment]
@macandchief I'll let gnunn1 talk about animation/their plans - afaik it should be possible, but not sure about plans. It might depend a bit on desktop environment - you might be able to set window animation to slide in or something.
Resizing should be possible. At least I can drag the window further down at the bottom border, not sure about changing width.

**Comment by gnunn1** [comment]
@macandchief There is no way to animate the window in Wayland so no plans to invest effort in it. You can resize the window in the preferences dialog, since the quake window is borderless it can't be resized.

**Comment by macandchief** [comment]
I see, thank you for the explanation. So Height percent in Preferences/Quake is the way to go.

@step21 On which DE? As gnunn1 mentioned, after opening the window in quake mode I cannot resize it on openbox.

**Comment by step21** [comment]
This is on Unity.

**Comment by macandchief** [comment]
I see, thx. Good to know, resizing sometimes works, depending on the DE.

**Comment by gnunn1** [comment]
@step21 Is this delay still happening or did it sort itself out?

**Comment by step21** [comment]
@gnunn1 It is gone for now, when I remember to start gnome-keyring-daemon - sorry for not closing it.
