### ISSUE TITLE
I've found the terminal of my dreams!

### ISSUE THREAD

**Issue by mlcdf** [gnunn1/tilix#1077]
Hello,

I've been using Tilix for a month of so, and I'm completely in love with this terminal emulator.

 Thank you. :heart: 

![screenshot from 2017-08-15 12-20-37](https://user-images.githubusercontent.com/9364931/29312064-30e9fcd8-81b4-11e7-9ca9-afe0fa3a85e0.png)

**Comment by gnunn1** [comment]
Thanks, I appreciate the kind words.
