### ISSUE TITLE
Cursor gets invisible outside of context menu

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1078]
not sure what i updated and that started to happen
https://www.youtube.com/watch?v=_E13G6M8Vyc&feature=youtu.be

**Comment by egmontkob** [comment]
Interesting, it also happens if you have "Autohide the mouse pointer when typing" disabled. Could you please check that Tilix is not toggling the API setting back and forth by any chance when opening the menu?

I'm wondering if I could have broken this with https://git.gnome.org/browse/vte/commit/?id=776823d...

**Comment by alex285** [comment]
@egmontkob i cant check right now, but good call! i was using tilix-vte from AUR, but that was breaking GNOME Terminal, so i used upstream VTE! that was my change!

**Comment by gnunn1** [comment]
I cannot reproduce this on Arch. The mouse auto hide is only called when the preference is changed, it's not being toggled or used otherwise.

**Comment by bil-elmoussaoui** [comment]
I can't confirm this on Arch Linux. Using Gnome Testing & the testing repos too. You can see that if you split the terminal horizontally or vertically, then right click to open the menu move your mouse into any position on the VTE widget and the mouse will be hidden. if you move the mouse to the sub-terminal header it will be shown again.

**Comment by alex285** [comment]
@gnunn1 @bil-elmoussaoui  did you test with VTE 0.49.1

**Comment by alex285** [comment]
also it happens with anything it steals the focus from VTE, not just the context menu. for example the About Dialog, or the three lines menu

**Comment by bil-elmoussaoui** [comment]
I'm using `vte3 0.49.1-1` too

**Comment by egmontkob** [comment]
@bil-elmoussaoui Could you please clarify your comment? You say "I can't confirm" and later on "and the mouse will be hidden" which sounds to me that you _can_ confirm. Or what am I misunderstanding?

**Comment by alex285** [comment]
@bil-elmoussaoui i tried on a blank Shell session, same issue. do you use Wayland? im using Xorg

**Comment by egmontkob** [comment]
Upstreamed at https://bugzilla.gnome.org/show_bug.cgi?id=786441.

My suspicion was correct, I broke it in the aforementioned VTE change.

(I could test with a kinda randomly chosen older Tilix (namely 3974f2a) - newer ones have problems with the hyperlink feature not yet existing in VTE, and even if I revert that commit, there's some mysterious GTK+ problem.)

Does anyone feel like digging into VTE and do some debugging? Unfortunately I hardly have any time nowadays.

**Comment by gnunn1** [comment]
Unfortunately I am also short on time these days plus my C-foo sucks, sorry @egmontkob.

**Comment by bil-elmoussaoui** [comment]
@egmontkob sorry it was a typo. I meant that I can confirm this too. And sadly i don't have much time to track this down neither :(

**Comment by egmontkob** [comment]
Sep 4 is the deadline for the next stable series of VTE. I'll try to find some time for it (I don't particularly care about the development series being broken) – please ping me when this date approaches :)

**Comment by egmontkob** [comment]
I can hardly sleep until I fix whatever I broke... Could you guys please test the patch that I attached to the upstream bug (with both settings of "Autohide the mouse pointer when typing" and all aspects of the cursor, not just this menu bug)?

**Comment by gnunn1** [comment]
Sure, I'll have a look at it over the weekend.

**Comment by bil-elmoussaoui** [comment]
@egmontkob Works perfectly fine here with your latest patch. Thanks :+1:

**Comment by gnunn1** [comment]
Works for me as well.

**Comment by egmontkob** [comment]
Okay, committed.

Just for the record: GNOME Terminal uses the standard right-click menu widget (whatever it's called) which has its own X window (might stick out from the terminal window) and grabs the X cursor, overriding its appearance for the entire display.

Tilix uses a popover widget which isn't a standalone X window, just Gtk+ drawing stuff in the main window, and does not grab the cursor and does not override its look outside of the popover.

That's why this bug went unnoticed with GNOME Terminal.

**Comment by egmontkob** [comment]
FYI:

There's another pretty similar bug, [see here](https://bugzilla.gnome.org/show_bug.cgi?id=789390). The steps to reproduce work with Tilix too with the "view session sidebar" and "hamburger" buttons.

It'll be fixed in vte-0.50.2.
