### ISSUE TITLE
New tab, not new session

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1079]
when we use Tab system, the menu on appMenu should say "New Tab" instead of "New Session" 

![tilix-session](https://user-images.githubusercontent.com/11244308/29364540-7bef16d0-829c-11e7-8b9a-477984c0824e.png)

and actually it makes more sense this option to be totally removed. There is a "Plus" icon to open a new Session or a New Tab on headebars

**Comment by gnunn1** [comment]
The Session terminology is all over the place (preferences, documentation, etc). For consistency I'm leaving the session terminology in ace.
