### ISSUE TITLE
Cannot set shortcuts with Tab key in config window

### ISSUE THREAD

**Issue by kronos29296** [gnunn1/tilix#1082]
I tried to set Ctrl Tab and Shift Ctrl Tab to change sessions in the config window but it did not work.
The keys were not captured at all. I had to use dconf to set the shortcuts.

I have installed Tilix version 1.6.4 in Manjaro Linux from AUR.

**Comment by gnunn1** [comment]
Duplicate of #890, unfortunately the GTK shortcut widget doesn't support setting tab.
