### ISSUE TITLE
unsafe paste alert seems broken in 1.6.4

### ISSUE THREAD

**Issue by sogalboogalsky** [gnunn1/tilix#1084]
Hi,
I have Tilix 1.6.4 installed in Fedora 26 (gtk 3.22.17)(using bash) + openSUSE Tumbleweed (using zsh), both with GNOME 3.24, as well as Tilix 1.6.4 compiled from master.
In each of them I can't obtain a warning when pasting something like:
`sudo ./install.sh`
Of course the appropriate option is active and correctly shown in dconf (_unsafe-paste-alert == true_).
Am I missing something or expecting something wrong from this option ?
Thank you.

**Comment by gnunn1** [comment]
The paste needs to be terminated by a linefeed in order for the dialog to display, the warning is meant for cases where you paste something that will be executed immediately. Lines that are just pasted but don't execute give you the opportunity to review them first before pressing the enter key.

**Comment by sogalboogalsky** [comment]
Oh... shame on me ! I was writing a tutorial about Tilix' advanced features and tried a lot of things to get it working.  Seems that I missed coffee this morning !
Anyway, thanks a lot !
