### ISSUE TITLE
Assistants

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#1085]
I'm looking at adding a new feature like iterm2's toolbelt, you can see a video of it here (https://www.youtube.com/watch?v=ZwlcnhsNgaE). The idea is to have a variety of tools/assistants always available when working with terminals. I'd be looking at incorporating the following assistants:

a. Paste History
b. Command History (only if Fedora notification patch is being used)
c. Manage Processes (i.e. view processes started from terminal, send signals to them, etc)
d. Bookmark selector (replace bookmark dialog)
e. Password selector (replace password dialog)

While the iterm2 toolbelt slides from under the window, I'd plan on having an embedded pane in tilix to host these assistants. Below is a fairly quick and dirty mockup of the pane but no assistants at this time.

![screenshot from 2017-08-20 14-49-32](https://user-images.githubusercontent.com/9358238/29497531-743dc1f2-85b7-11e7-8b44-64a4686a6443.png)

I'm interested in feedback with regards to whether people would actually use this feature or if it's simply overkill.

**Comment by sogalboogalsky** [comment]
I use **a lot** bookmarks and passwords dialogs as they are, opening them through keyboard shortcuts. Shortcuts are a very handy way to manage and use them fast, so unless you plan to keep the keyboard shortcuts available to access them in the embedded pane, it is not something I would use myself.
Paste history can be nice as a complement of a desktop clipboard manager (like GPaste).
Having the pane showing a list of processes launched in Tilix would be great and is definitely something that I will use at work (to manage background or long processes).

Do you plan to have this pane fixed, like in the mockup, or mobile, like the current sidebar ?

**Comment by daniel-wtd** [comment]
Can be helpful, as long as it is "out of the way" when unneeded. ❤️

**Comment by guillefar** [comment]
Can also custom commands being added to that? 
Terminator has this very useful plugin that allow you to add custom commands that you can insert using the right click menu. Very handy for commands you use a lot, or are hard to remember its syntax.

**Comment by gnunn1** [comment]
@guillefar You can already do custom commands with bookmarks, if it's missing something let me know and I'm happy to have a look.

**Comment by sogalboogalsky** [comment]
Le mardi 29 août 2017 à 11:49:53, guillefar a écrit :
> Can also custom commands being added to that?
> Terminator has this very useful plugin that allow you to add custom commands
> that you can insert using the right click menu. Very handy for commands you use
> a lot, or are hard to remember its syntax.

You can already use the bookmarks for that purpose (they work for local or
remote path as well as commands).

**Comment by lucascosti** [comment]
I'm not sure I would remember to use this. The only one I would possibly use is the process manager. They'd be nice to have extras, but nothing I would miss too much.

**Comment by heikkiket** [comment]
I think bookmarks are currently a little bit cumbersome to use. To edit a bookmark, you need to open Preference panel. Also adding and using bookmarks could be in the same UI. Now they are separate menu items. So maybe this kind of sidebar would make bookmarks more useful and easier to access? I could have sidebar open and launch a series of commands that way, clicking them one after another.

**Comment by gnunn1** [comment]
Thanks for the comments everyone, after thinking about this further I don't think I'm willing to invest the effort on it. While it appears simple, keeping these panels updated with the current state of the terminal is a fair amount of effort and I'm not sure the benefit is there.
