### ISSUE TITLE
Dynamic tab title for SSH sessions

### ISSUE THREAD

**Issue by mhalano** [gnunn1/tilix#1087]
Konsole has a nice feature (which I couldn't find in any other terminal emulator) which shows the SSH IP address on tab title, so I always know what server I'm working on. On Tilix (and GNOME Terminal) title is just the local user and local machine name, which isn't useful when working on a remote machine.

**Comment by f2404** [comment]
https://unix.stackexchange.com/questions/14113/is-it-possible-to-set-gnome-terminals-title-to-userhost-for-whatever-host-i

**Comment by mhalano** [comment]
Nice, but doesn't work. The workaround on GNOME Terminal using "echo -ne "\033]0;${1}\007"..." works, but just on GNOME Terminal.

**Comment by phw** [comment]
If trigger support is available you can set the username and hostname variables with them according to https://github.com/gnunn1/tilix/wiki/Triggers

But actually I never got this working for me here :(

**Comment by gnunn1** [comment]
Tilix supports this already via the ${hostname} variable used in titles. However for this to work for remote systems, the VTE script has to be sourced in the remote system. 

Alternatively you can use a trigger for this if you are using a tilix patched version of the VTE. This is what I do, I have a trigger that parses the hostname out of the prompt.

**Comment by gnunn1** [comment]
The documentation has an example of how to this with triggers.

https://gnunn1.github.io/tilix-web/manual/triggers/

**Comment by gnunn1** [comment]
@phw Are you using the regex from the documentation page or something else?

**Comment by phw** [comment]
@gnunn1 The regex on that example is messed up :( I tried this myself by having a set state trigger with the regex `^(.*?)@([-a-zA-Z0-9]*)` and action `username=$1;hostname=$2`, but username and hostname never get set.

On my host systems I have prompts like `user@myserver:~$`, but no luck :(
