### ISSUE TITLE
Is it possible to set ubuntu default terminal style sessions layout?

### ISSUE THREAD

**Issue by kiddick** [gnunn1/tilix#1088]
![image](https://user-images.githubusercontent.com/9250239/29568130-0c924fb2-8758-11e7-8572-6b75f8b9e521.png)

Something like that..

**Comment by gnunn1** [comment]
Sorry there is no way to have a menubar in tilix.

**Comment by gnunn1** [comment]
Oh just had a thought, if you are asking for tabs it's been added in Master and I'll push out a new release in a few weeks.

**Comment by kiddick** [comment]
Yeah about tabs of sessions within same window.

**Comment by gnunn1** [comment]
You can see a video showing the tabs in action here:

https://www.youtube.com/watch?v=CqCnfIPIFkg

**Comment by kiddick** [comment]
Sweet!! Exactly what I need!
