### ISSUE TITLE
Can I set a title(Application Title) when Tilix runs?

### ISSUE THREAD

**Issue by nemonein** [gnunn1/tilix#1089]
Hello.
I'm using Tilix from the PPA(Webupd8) on Kubuntu 17.04.

I would like to set the Application title on my own, like 'Tilix: Ubuntu Server', or 'Tilix: Archi', etc.
I have read #929, and #930, but I'm not sure it's implemented already.

What I want is, something like this. (I know there's no option like --windowtitle.)

```$ tilix --windowtitle 'Ubuntu Server'```

Then, Tilix's application title will be 'Tilix: Ubuntu Server'.

Is is possible?

**Comment by gnunn1** [comment]
If you run the helo command:

```tilix --help```

It shows the following as one of the command line switches:

```
  -t, --title=TITLE                     Set the title of the new terminal
```

**Comment by gnunn1** [comment]
Also, it's not possible to set the application title, just the terminal.
