### ISSUE TITLE
Support commands after '--' argument

### ISSUE THREAD

**Issue by KSXGitHub** [gnunn1/tilix#1090]
Similar to gnome-terminal support of `--`, the following command should open Tilix and execute `bash -c 'echo hello; read'`

```sh
tilix -- bash -c 'echo hello; read'
```

Tilix does support `-e`/`--command` but it is not as convenient, it is also deprecated by gnome-terminal.

**Comment by gnunn1** [comment]
I think gnome-terminal was a bit hasty in deprecating ```-e```:

https://bugzilla.gnome.org/show_bug.cgi?id=784925

I do not have any plans to support the ```---``` syntax.

**Comment by KSXGitHub** [comment]
@gnunn1 

> I do not have any plans to support the `---` syntax

When I make this request, I indeed must assume you didn't plan to. If you meant you don't want to, why wouldn't you? Specifying command after `--` is just more convenient, especially when command has quotation marks in it.

> I think gnome-terminal was a bit hasty in deprecating `-e`

I don't ask to deprecate `-e` anyway
