### ISSUE TITLE
Read-only mode shortcuts, scrolling mode

### ISSUE THREAD

**Issue by doubleloop** [gnunn1/tilix#1091]
After you turn on read-only, it would be cool to allow pager-like shortcuts for example (some subset took from less pager):

| key    |  action            |
| ------ | ------------------ |
| j/k    |  scrolling up/down |
| space  |  scroll down |
| u/d    |  scroll half of the screen (up/down) |
| gg     |  scroll to the top |
| G      | scroll to the bottom |
| /      |  search |

in addition, I believe this could, for some people, become the preferred way to scroll terminal. To make it more user friendly, a separate scrolling-mode can be introduced. It would be identical to read-only mode with one exception: after ESC/q is pressed, the mode is disabled and terminal scrolls down. Then, a user can bind `enter scrolling mode` as a convenient shortcut and enjoy less-like navigation shortcuts. Separating read-only from scrolling-mode makes sense as read-only is something you do not want to exit by accident, while scrolling is something you want to exit easily.

**Comment by gnunn1** [comment]
It's an interesting idea, but I think it would be confusing to users and not intuitive. So sorry, no plans to support this.

**Comment by jberryman** [comment]
Something like this would be quite intuitive to vim users (and other terminals implement half-assed vim emulation already). I would rather have a shortcut to open the entire scrollback buffer in my program of choice (e.g. less or vim). (in fact that's what I'm here looking for)
