### ISSUE TITLE
Tilix is in the Antergos repository but isn't listed on the site.

### ISSUE THREAD

**Issue by hobbledehoy899** [gnunn1/tilix#1094]
![screenshot](https://user-images.githubusercontent.com/29778895/29737533-ef227a72-89d4-11e7-9814-4d0fe6309c2f.png)
![screenshot](https://user-images.githubusercontent.com/29778895/29737527-ccff7f58-89d4-11e7-88a9-b0801a67ebc8.png)

**Comment by gnunn1** [comment]
What's the link to tilix in the Antergos repository?

Note also you can update this yourself via a PR in the tilix-web repository.

https://github.com/gnunn1/tilix-web/

**Comment by hobbledehoy899** [comment]
Here's the link.
http://build.antergos.com/package/tilix

**Comment by hobbledehoy899** [comment]
Would the antergos repository count as Antergos' default repository?

**Comment by gnunn1** [comment]
Merged PR
