### ISSUE TITLE
Tilix Quake renders mid screen

### ISSUE THREAD

**Issue by daniel-wtd** [gnunn1/tilix#1095]
Hey I'm having the following setup:

Fedora 26
Tilix-Version:  1.6.4
VTE-Version: 0.48
GTK-Version: 3.22.19
Wayland 1.13

The probkem is, taht "tilix --quake" renders in the mid of the screen. Full width, but with with a huge offset on top and bottom. The Window is kind of vertically centered.

Regards,
Daniel

**Comment by gnunn1** [comment]
Are you using a single monitor or multi-monitor? If it's a single monitor then there's likely nothing I can do about it since Wayland doesn't allow windows to be explicitly positioned. You can try forcing Tilix to use the X11 back-end by doing something like:
```
export GDK_BACKEND=x11 tilix --quake
```
If it's happening in a multi-monitor setup it might be a bug and I can have a look at it.

**Comment by daniel-wtd** [comment]
Thanks a  lot for your fast response.

It is a single monitor (most time).

Have tested the forcing via "GDK_BACKEND=x11 tilix --quake", which is leading to the same result. Will try in the xorg-gnome-session and report back.

**Comment by daniel-wtd** [comment]
Hmm, in the xorg session it renders correctly top. 
As you stated, this behaviour seems to be related to wayland.

**Comment by gnunn1** [comment]
Do you have a HiDPI monitor, just wondering if that could be a factor as well.

**Comment by daniel-wtd** [comment]
Dunno if you can call it HiDPI. Its an 13" 1920x1080.

**Comment by gnunn1** [comment]
Sorry, is it using window scaling from the gnome tweak tool or is the scaling using 1:1? Wayland auto-detects HiDPI and sets the scaling factor automatically, just wondering if that could be causing an issue.

**Comment by daniel-wtd** [comment]
The windows Scaling and font scaling is set to 1.

**Comment by gnunn1** [comment]
Thanks, unfortunately I don't think there is anything I can do about this.

**Comment by daniel-wtd** [comment]
Not a problem. Even the most awesome terminal emulator for Linux can have some flaws. And maybe we will see improvements going along with wayland upgrades.
