### ISSUE TITLE
Color schema switching

### ISSUE THREAD

**Issue by wzrdtales** [gnunn1/tilix#1096]
Hey searching for a way to switch the color schema quickly. Is there any possibility yet? 

Could not find any hotkey binding for this, but I would like to enter in a different color schema when I enter into vim (I combine the vim colorschema with the console one here though and switching over from solarized dark to a more darker one with opacity).

If there is anything that would work already, please let me know :)

**Comment by gnunn1** [comment]
The way this works is to create a separate profile with a different color scheme and then switch between the two as needed. You can then switch between profiles in the terminal title menu using the Profiles menu section.

**Comment by wzrdtales** [comment]
Mh, so the answer is no :(. That I can click around stuff I knew already and I have two profiles, but I want to switch with them without wasting time clicking through interfaces. I.e. hotkey binding, but still thanks, it does not seem to work then.
