### ISSUE TITLE
How to load terminal layout configuration on startup?

### ISSUE THREAD

**Issue by Venemo** [gnunn1/tilix#1097]
I'm new to tilix and I love it so far. (I switched to it from guake.)

I've figured it out how to save and load the current terminal layout, but I couldn't figure out how to load a specific layout config on startup. Also, how to run specific commands in the various sub-terminals? For example in one of them I'd like to have a root shell, on the other one an `octave-cli`, etc. Can I do this with tilix?

**Comment by gnunn1** [comment]
You can use the command line switch ```---sessions````, i.e.:

```
tilix --sessions myfile.json
```
You can specify the command you want to run for each terminal in the session by using the layout options menu item in the terminal title menu.

**Comment by Venemo** [comment]
@gnunn1 Awesome, thank you! This is even more convenient to set up than guake! :) I love tilix!

**Comment by hypr2771** [comment]
> I'm new to tilix and I love it so far. (I switched to it from guake.)
> 
> I've figured it out how to save and load the current terminal layout, but I couldn't figure out how to load a specific layout config on startup. Also, how to run specific commands in the various sub-terminals? For example in one of them I'd like to have a root shell, on the other one an `octave-cli`, etc. Can I do this with tilix?

Hi Venemo !
Can you please tell me how did you figured it out ? I have been looking for a few keywords over the issues and search engines, aswell as in the documentation, but I cannot find anything explaining how to save current layout (as a `json` file ?) or load it on startup...

I know it sounds so dumb and I am sincerely sorry if it is a repost or something...

**Comment by Venemo** [comment]
> I cannot find anything explaining how to save current layout (as a json file ?) or load it on startup...

Click on the downwards pointing arrow that is right to the terminal title, click "Other", and then "Layout Options". Then you will see a dialog that will allow you to set the command. After setting the command, save the current layout as a json file and then load that json file.

> I know it sounds so dumb and I am sincerely sorry if it is a repost or something...

No problem, don't worry about it.

**Comment by hypr2771** [comment]
Thanks for your answer @Venemo.
What blocked me was that I did not think about going in "Preferences > Shortcuts > Session" to notice that you could actually "Save the current session".
So basically doing this saves the state of your layout as a `json` file as expected.

**Comment by zerkz** [comment]
for those who are just seeing this issue, it appears that `--sessions` is not a valid switch anymore, it has been renamed to `--session`
