### ISSUE TITLE
"Scroll on output" off, but indicate there is new output

### ISSUE THREAD

**Issue by pnomolos** [gnunn1/tilix#1098]
Would it be possible to have an indicator (perhaps some character after the title) to indicate that more output has been produced if you have "scroll on output" off and have scrolled back in the history?

**Comment by gnunn1** [comment]
I could put something in the terminal title bar like the visual bell. It would be cleared when you scroll to the bottom.

**Comment by pnomolos** [comment]
@gnunn1 That's pretty much exactly what I'm thinking of :) I believe that's how iTerm does it.

**Comment by xelite** [comment]
+1

**Comment by gnunn1** [comment]
Does someone have a symbolic icon that would work well to indicate this? My artistic skills never progressed past stick figures unfortunately...
