### ISSUE TITLE
X errors caused by tilix

### ISSUE THREAD

**Issue by Venemo** [gnunn1/tilix#1100]
My `journalctl` log has several of these:

```
aug 30 03:15:46 Timur-Zenbook org.gnome.Shell.desktop[1580]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c00007 (Tilix: Def)
```
Since it says `Tilix: Def` I assume this is somehow caused by Tilix.

**Comment by gnunn1** [comment]
Note this should only be happening in Wayland. I'll have a look over the weekend.

**Comment by gnunn1** [comment]
This was actually a bug with the way I was calling XSendEvent, should be fixed now hopefully.

**Comment by gnunn1** [comment]
BTW thanks @f2404, I saw where I was going wrong by looking at the xfce4-terminal code.

**Comment by f2404** [comment]
@gnunn1 You're very welcome :)
