### ISSUE TITLE
[New Feature] add variable ${sessionNumberTotal}

### ISSUE THREAD

**Issue by ugoviti** [gnunn1/tilix#1101]
Hi, 

I found very useful the ${sessionNumber} variable to know what session I running, but for my usage, would be great to have a total session counter also, like ${sessionNumberTotal}, so I can use a Title like this:

${sessionNumber}/${sessionNumberTotal} ${title} ${activeTerminalTitle}

So I can know how may sessions are running inside a single window.

With kind regards

**Comment by bil-elmoussaoui** [comment]
Already added in master
see https://github.com/gnunn1/tilix/pull/1072
