### ISSUE TITLE
New session does not relaunch ssh connection

### ISSUE THREAD

**Issue by mrshpaks** [gnunn1/tilix#1103]
Hi,

I created new session with function added in bashrc, this function opens new **ssh connection** to some host in **new session**. Tilix profile config is set to **hold terminal open** is case command exits, so expected behaviour in case ssh session been disconnected, is to click on button **relaunch** and **restore ssh connection**. But clicking relaunch button just opens my **local home dir**.

**Function in bashrc:** `function new-tab-ssh() { tilix -p SSH -e "ssh $@" ;}`

**OS:** Ubuntu 16.04
**Tilix version:** 1.6.4 
**VTE version:** 0.44
**GTK Version:** 3.20.8

Please let me know if any additional information needed.

Thanks!

**Comment by gnunn1** [comment]
Thanks for the report, this has been fixed in master previously.
