### ISSUE TITLE
Themes affects applications

### ISSUE THREAD

**Issue by a-komarev** [gnunn1/tilix#1108]
Is there is a way to not apply theme settings to `mc`?

Here is how `Monokai Dark` themed `mc` looks like:
![screenshot from 2017-09-05 01-54-34](https://user-images.githubusercontent.com/1849174/30039685-4fa00b02-91dd-11e7-953f-e97398f1436d.png)

And here is classical one:
![screenshot from 2017-09-05 01-57-39](https://user-images.githubusercontent.com/1849174/30039724-a7752dd0-91dd-11e7-9ec7-ad8aa4b084ea.png)

My eyes are bleeding >_<

**Comment by gnunn1** [comment]
There is not, sorry.
