### ISSUE TITLE
cannot see window borders

### ISSUE THREAD

**Issue by rsperl** [gnunn1/tilix#1111]
In appearance, I have window style set to normal, but I still do not have any window borders. If tilix is on top of another application that a black foreground, then tilix blends in with that application.

Am I missing something on how to show a thin border around the entire window?

**Comment by gnunn1** [comment]
What version of GTK are you using, on 3.14 you need to disable transparency in Preferences | Appearance due to a bug in that version.

If you are on a later version, what theme are you using and do you have the same issue with Adwaita?

**Comment by rsperl** [comment]
I'm on gnome 3.24.2 using Adwaita, and I didn't see a transparency setting in Preferences | Appearance. In general, though, I keep everything opaque.

**Comment by gnunn1** [comment]
Screenshot?

**Comment by gnunn1** [comment]
Also note that Adwaita uses a black border around windows, so if it is in front of an application that has a black background it will of course blend it. This is perfectly normal. Do you something different with Tilix versus gedit or gnome videos?

**Comment by rsperl** [comment]
That was it. Actually, if I switch to Adwaita-dark as a theme, it puts a thin white border around the window. Thanks!
