### ISSUE TITLE
Archlinux's package manager fails to run "hooks" when used on tilix

### ISSUE THREAD

**Issue by StuntsPT** [gnunn1/tilix#1112]
This is a **very** strange issue.
If I try to update my system using tilix, the `pacman` hook for the "linux" package will fail.
It works if run on another terminal emulator...
I know this sounds absurd, but I have made a screencast video showing the issue, which is attached below (sorry, github will only allow me to attach a compressed video).
How can I help debug this?
Also, this only occurs in one of my systems. In another machine (both x86_64) everything works on tilix.

[tilix bug video](https://github.com/gnunn1/tilix/files/1279004/tilix_bug.mkv.zip)

**Comment by gnunn1** [comment]
Unfortunately I don't manage the packaging, please open a bug report against the Arch package you are using to install Tilix. If the package needs new to help with the issue I am more then happy to do so.

**Comment by StuntsPT** [comment]
This doesn't look like a packaging problem to me.
From what I could tell, it was either something in the code of tilix, or some misconfiguration on my part.
Or the fact I am running tilix under Mate Desktop Environment.
I'll report back here if I ever get to the bottom of it.
