### ISSUE TITLE
Add option to maximize window on start and disable titlebar (like in terminator)

### ISSUE THREAD

**Issue by mariuszs** [gnunn1/tilix#1113]
Can we put title information into gnome top bar? There is plenty of place here.

**Comment by phw** [comment]
tilix --maximize --window-style=disable-csd-hide-toolbar

Does this do what you want?

**Comment by mariuszs** [comment]
Yes, it is! Thanks! Is possible to set this from Settings menu or somehow in configuratio file?

**Comment by mariuszs** [comment]
Hmm, no exactly this is what I want.... Titlebar is ok and useful, but window title is not. I'm thinking about window **without** title.

**Comment by gnunn1** [comment]
You can set the window style to borderless instead:

```
tilix --maximize --window-style=borderless
```

**Comment by mariuszs** [comment]
Thanks, this is what I was looking for!

**Comment by lokesh-krishna** [comment]
Where does one pass this command in order for Tilix launched from the launcher to have these properties? I tried adding them to `com.gexperts.Tilix.desktop` but that doesn't seem to do it.

**Comment by odimko** [comment]
@lokesh-krishna have you found a solution? I have the same issue. 

@gnunn1 @phw: guys, could you please explain how to make a desktop shortcut launching Tilix maximized? As now adding the suggested parameters in the configuration file has no effect.

Thanks in advance!

**Comment by FFY00** [comment]
@odimko, just copy the .desktop file and add that to the exec command.

https://wiki.archlinux.org/index.php/desktop_entries

**Comment by odimko** [comment]
@FFY00 thanks a lot for a fast reply! it does launch fullscreen now, when run from the Applications menu, however, running from the launchpad has no effect - the window appears small. any ideas? :)

**Comment by tronorama** [comment]
> @odimko, just copy the .desktop file and add that to the exec command.

For whatever reason, for me `tilix --maximize` works in a terminal, but in Manjaro GNOME 40 Wayland, it does _not_ work in my desktop entry (my US name is picked up, and the file validates):

```
[Desktop Entry]
Version=1.4

#       updated 01 August 2021
# desktop-file-validate com.gexperts.Tilix.desktop
# desktop-file-install --dir=$HOME/.local/share/applications com.gexperts.Tilix.desktop
# update-desktop-database ~/.local/share/applications

Name[en_US]=Tilix max
Name=Tilix
Comment=A tiling terminal for Gnome
Keywords=shell;prompt;command;commandline;cmd;

Exec=tilix --maximize

Terminal=false
Type=Application
StartupNotify=true
Categories=System;TerminalEmulator;X-GNOME-Utilities;
Icon=com.gexperts.Tilix
DBusActivatable=true

Actions=new-window;new-session;preferences;

[Desktop Action new-window]
Name=New Window
Exec=tilix --action=app-new-window

[Desktop Action new-session]
Name=New Session
Exec=tilix --action=app-new-session

[Desktop Action preferences]
Name=Preferences
Exec=tilix --preferences
```

Thus it would still be nice to have this **maximize** switch in the dconf settings (even better: a `~/.config/tilix.toml` file or similar, anything but JSON or a custom syntax) rather than rely on desktop entries. I mean this seems like a more obvious option than some of the options already present directly in the Tilix "Preferences" GUI menu itself.

**Comment by unlimitD** [comment]
> > @odimko, just copy the .desktop file and add that to the exec command.
> 
> For whatever reason, for me `tilix --**maximize**` works in a terminal, but in Manjaro GNOME 40 Wayland, it does _not_ work in my desktop entry (my US name is picked up, and the file validates). Similarly, a convoluted hack to try to use a **session** in the desktop entry fails (`tilix --session=/path/to/tilix-default-maximized-session.json`), but works in Terminator:
> 
> ```
> [Desktop Entry]
> Version=1.4
> 
> #       updated 01 August 2021
> # desktop-file-validate com.gexperts.Tilix.desktop
> # desktop-file-install --dir=$HOME/.local/share/applications com.gexperts.Tilix.desktop
> # update-desktop-database ~/.local/share/applications
> 
> Name[en_US]=Tilix max
> Name=Tilix
> Comment=A tiling terminal for Gnome
> Keywords=shell;prompt;command;commandline;cmd;
> 
> Exec=tilix --maximize
> 
> Terminal=false
> Type=Application
> StartupNotify=true
> Categories=System;TerminalEmulator;X-GNOME-Utilities;
> Icon=com.gexperts.Tilix
> DBusActivatable=true
> 
> Actions=new-window;new-session;preferences;
> 
> [Desktop Action new-window]
> Name=New Window
> Exec=tilix --action=app-new-window
> 
> [Desktop Action new-session]
> Name=New Session
> Exec=tilix --action=app-new-session
> 
> [Desktop Action preferences]
> Name=Preferences
> Exec=tilix --preferences
> ```
> 
> Thus, rather than rely on desktop entries, and in spite of [past resistance to make this a preference](https://github.com/gnunn1/tilix/issues/935#issuecomment-302936792), it would still be nice to have this **maximize** switch in the dconf settings (even better: in an editable, versionable `~/.config/tilix.toml` file or similar ... anything but data interchange formats never intended for use as config files (and disallowing comments), e.g., `JSON`, nor a custom syntaxes, e.g., `.gitconfig`). I mean this seems like a more obvious option than some of the options already present directly in the Tilix "Preferences" GUI menu itself.
> 
> You can change it in the settings file for, e.g., Terminator ... [see here for an example](https://github.com/tronorama/dotfiles-public/blob/main/src/terminator/terminator_folder_in_dot_config/config#L38).

hi i was facing the same problem i think i found a "solution" ...just click in preferences/Global and check "Save and restore windows state" ..and then click en maximize button or just put tilix --maximize and then exit and reopen, and thats it!

**Comment by tronorama** [comment]
> hi i was facing the same problem i think i found a "solution" ...just click in preferences/Global and check "Save and restore windows state" ..and then click en maximize button or just put tilix --maximize and then exit and reopen, and thats it!

I've always had `Save and restore windows state` selected, and it doesn't work for me, under Wayland or X11, no matter how many hackish ways I try to trick TIlix into being obedient like Terminator.

**Comment by morfyum** [comment]
same issue. I cant start in maximized... Tilix the best, and this is a really evil bug :( 
I try to modify .desktop file, and check restore session in Global settings, but nothing,

**Comment by jvalleroy** [comment]
> same issue. I cant start in maximized... Tilix the best, and this is a really evil bug :( I try to modify .desktop file, and check restore session in Global settings, but nothing,

Here is a solution that worked for me: After copying and modifying the .desktop file, I also had to rename it (I renamed it to `tilix.desktop`).
