### ISSUE TITLE
D-Bus causes desktop file not to work as expected

### ISSUE THREAD

**Issue by PhydeauxLeChien** [gnunn1/tilix#1117]
Firstly, thanks for developing a great terminal emulator! It has replaced terminator for me.

I am having an issue trying to set a default session (default layout of panes etc). By the way, I would love for this to be a setting in the app.

I have copied `com.gexperts.Tilix.desktop` to `~/.local/share/applications` and changed the Exec field to `tilix -s ~/.tilix/Default.json`. When I reload the desktop file, nothing changes about the behaviour and Tilix opens with only one pane. If I run the same command from the terminal, Tilix opens with my session file as expected.

However, when I comment out the line `DBusActivatable=true` further down (as suggested [here](https://bbs.archlinux.org/viewtopic.php?id=224347)) the desktop file works as expected. This suggests that opening with D-Bus activation is broken somehow.

**Comment by PhydeauxLeChien** [comment]
I am running Ubuntu 17.04, Gnome 3.24.2

**Comment by bil-elmoussaoui** [comment]
the `~` symbol is interpreted by your SHELL(bash/zsh/fish...) and not the Desktop File; that's why it doesn't work. You should replace it with the absolute real path to your file. In your case it must be something like /home/myusername/.tilix/default.json

**Comment by PhydeauxLeChien** [comment]
Thanks for your reply, but I do not think that this explains the issue - the desktop file works perfectly **iff** I comment out `DBusActivatable=true`. This is with `~` in the exec field.

And indeed, if I change the command to `/home/chris/...` and **do not** comment out the D-Bus line, the desktop file does not work.

**Comment by phw** [comment]
AFAIK this is expected behavior. When DBusActivatable is true the exec command is not used, instead the DBus service gets activated, and the command for the service is defined in the service file. The exec is just a fallback for environments not supporting DBusActivatable.

This is not a bug. Since you have to use a custom .desktop file anyway just set DBusActivatable to false.

**Comment by gnunn1** [comment]
I think @bil-elmoussaoui  and @phw covered this sufficiently, it's not a bug IMHO.
