### ISSUE TITLE
Disable quake mode in Wayland

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#1118]
I'm thinking of disabling quake mode in Wayland as there are just too many problems with it. The basic problem is that in Wayland there is no way to control the window placement, right now quake mode relies on a hack to put the window in the right spot. This is brittle though and breaks in all sorts of different situations.

**Comment by lucascosti** [comment]
:'( I'm not using wayland yet, but this is one of my favorite features at the moment.

**Comment by Atem18** [comment]
I am using Wayland and yeah there is some flaws. @gnunn1 Can't you ask upstream about your problem. I would be very sad to say goodbye to tilling in Wayland. :(

**Comment by gnunn1** [comment]
I've asked about it several times, it's just the way Wayland works.

**Comment by Atem18** [comment]
@gnunn1 My flaw (quake window was placed a bit on the second screen) disappeared after updating to gnome 3.26 and to your latest version. Could you consider it to keep quake mode in Wayland because it is one if not the main reason I'm using and loving Tilix.

Thanks in advance.

**Comment by klingtnet** [comment]
I am running gnome-shell `3.26.2-11` on Arch Linux `4.14.1-1-ck` and tilix `1.7.1` seems to run fine in quake mode now.

**Comment by Atem18** [comment]
@klingtnet On X.org or Wayland ?

**Comment by wollistik** [comment]
I am using tilix quake mode on two machines, both Arch Linux with latest gnome-shell running on Wayland. On one machine there is no issues at all, but on the other I have enabled screen scaling due to HiDPI Laptop screen. On this machine, Tilix has only half the width/height as it should and is placed not poperly.
Please do not disable quake mode, since I really appreciate your work!

**Comment by klingtnet** [comment]
@wollistik I can confirm your observation, placement and size of tilix in quake mode is off when output in a Wayland session is scaled.

**Comment by gnunn1** [comment]
I'll close this and leave things be for now.

**Comment by klingtnet** [comment]
A workaround for me is to activate fullscreen mode in tilix's quake mode (`F11`).
