### ISSUE TITLE
Tilix system tray icon

### ISSUE THREAD

**Issue by darkLord19** [gnunn1/tilix#1123]
It would be good to have system tray icon when Tilix is opened in quake mode.

**Comment by bil-elmoussaoui** [comment]
Noooooon :( you can setup a keyboard shortcut to do the same. A tray icon is not really needed here and as Tilix follows GNOME's HIG and they just removed tray icon support on their latest version

**Comment by f2404** [comment]
I really like the tray icon idea, though, as you said, the removed systray from Gnome, and they also declared  [GtkStatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html) deprecated long time ago without providing any good alternative.

**Comment by darkLord19** [comment]
@bil-elmoussaoui @f2404  Yes I know we can set up keyboard shortcut but that's not what I meant. I meant when we open tilix in quake mode then only it should show system icon. If tilix is not opened then tray icon won't be there. (Attaching Screenshots so you can know what I'm referring to)(1st screenshot with another terminal open in quake mode which supports sys tray icon)(2nd screenshot with that terminal closed)
And yes Gnome recently removed syatray but xfce, lxde, kde and some other DEs still supports system tray.
And yes if it feels to current contributors that it'd be unnecessary then it's fine. I understand team's decision to be with the flow but i like that small utility and i think many people do so if you don't mind can you guys point me out in a direction to implement this. I've some programming background. Although It'll be my first time with something like this but I'm ready to learn new things.
![screenshot_2017-09-14_19-37-33](https://user-images.githubusercontent.com/16662014/30434249-64683448-9984-11e7-8788-af29b16a8969.png)
![screenshot_2017-09-14_19-37-52](https://user-images.githubusercontent.com/16662014/30434251-647516ea-9984-11e7-9f69-b0d33505b47e.png)

**Comment by f2404** [comment]
@darkLord19 I understand what you are talking about because I'm the current developer of that "another terminal" you're showing :) And I actually support you saying that the status icon works great for me.

**Comment by gnunn1** [comment]
I can understand the ask amd I have no interest in adding the capability myself. If someone wants to do it as a PR I'm happy to take it as long as it's optional. I'm not familiar with what it takes to implement it since I've never done it, GtkD does implement a StatusIcon which is probably what you are looking for.

**Comment by phw** [comment]
What's the point of that tray icon? I mean when it is only shown when Tilix is opened in quake mode there is a quake mode window anyway. What additional utility would it provide?

**Comment by gnunn1** [comment]
I took it that it shows the icon when in quake mode for when the window isn't being shown.

**Comment by f2404** [comment]
@phw Quake mode window may not be always visible. Taking "another terminal" as an example, its status icon allows to show or hide the window, and also provides a right-click menu that allows to e.g. open Preferences.

**Comment by darkLord19** [comment]
@gnunn1 It will show tray icon even when terminal is not running in background. It acts exactly as @f2404 stated. And you can take "another terminal's" name if you are a developer of it.;) I thought it'd sound rude and like I'm asking something just because it is in that "another terminal". For others who haven't figured out what that terminal is, it's "xfce4-terminal"

**Comment by gnunn1** [comment]
I'm cleaning up issues and closing this, I don't have any plans to implement this myself. If someone else wants to tackle it I'm not averse to accepting a PR but I don't believe that is likely to happen.
