### ISSUE TITLE
Initial profile selection different when starting a new session than adding a new terminal

### ISSUE THREAD

**Issue by robmv** [gnunn1/tilix#1129]
When a terminal is on an automatically switched profile, adding a new terminal start that terminal with the default profile, but when a new session is opened the new session inherits the profile of the parent terminal.

Steps to reproduce:

1. Create a new profile named remote for a known host, for example host.example.com.
2. Open a ssh connection to the host.example.com, the profile switch to the remote profile.
3. From that first terminal add a new terminal to the same session. The new terminal is on the default profile.
4. Close the newly added terminal
5. You are again on the first terminal on the remote session and remote profile.
6. Open a new session. The terminal on the new session inherits the remote profile. It should be on the default profile like step 3.

**Comment by gnunn1** [comment]
I think I fixed this in #1109, does this look the same to you?

**Comment by robmv** [comment]
@gnunn1 Yes, look like it.
