### ISSUE TITLE
Triggers correct syntax for regex

### ISSUE THREAD

**Issue by JuanCAlpizar** [gnunn1/tilix#1130]
Hi, today I was learning from trigges using tilix and I noticed there was a way to grab the username and put it in the title of either each tab or the window title, which I found awesome because I use to have at least two different users across multiple tabs and sometimes it gets confusing. I'm using Arch Linux with all of the tilix package dependencies installed, running tilix -v outputs this:

    [jc@jc-pc ~]$ tilix -v
    Versions
	    Tilix version: 1.6.4
	    VTE version: 0.48
	    GTK Version: 3.22.21

    Tilix Special Features
	    Notifications enabled=1
	    Triggers enabled=1
	    Badges enabled=1

Since it outputs triggers are enabled and that I can see the Advanced -> Triggers option I'm assuming I have the right setup to begin with. My problem comes after following the guides on https://gnunn1.github.io/tilix-web/manual/triggers/ about triggers, in there it states `^[(?P<user>.)@(?P<host>[-a-zA-Z0-9])` should work as a sample to catch the username, hostname and set it in the global variables to use. However when I copy and paste such line in the Regex field, it outputs this error:

![image](https://user-images.githubusercontent.com/2028118/30743752-453196d6-9f5c-11e7-8e38-d8b9a54073e7.png)

If I add an extra parenthesis set it outputs the same error, and if I escape the brackets using a backslash it stops showing the error but when I click on apply nothing happens, even after setting the `${username}` var inside the title under Appearance settings, it just displays an empty space where the username should be.

What's the proper syntax to apply on the regex field? Am I missing any dependency or setting to activate?

Thanks so much

**Comment by gnunn1** [comment]
It was a case of characters on that page not being properly escaped, I've formatted it as code so it works.
