### ISSUE TITLE
Full width bottom pane

### ISSUE THREAD

**Issue by steelstring94** [gnunn1/tilix#1131]
Create two vertical panes.  Then create a bottom pane on the left.  If you resize that bottom pane to the right, the top one comes with it.  It would be a very nice feature to be able to resize the right pane upwards and extend the bottom pane to fill the full width of the lower half of the window.

**Comment by gnunn1** [comment]
Unfortunately It's not feasible due to the way the gtk splitter works. You can achieve the same thing by adding the bottom to the left terminal and then dragging and dropping the right terminal to the right side of the left panel.

**Comment by EmTee70** [comment]
Ok, I got it. Thank you!
