### ISSUE TITLE
Tilix doesn't terminate running process

### ISSUE THREAD

**Issue by doppioandante** [gnunn1/tilix#1133]
I'm using Kakoune inside tilix, when I close the pane with the [X] the process isn't terminated properly.
At https://github.com/mawww/kakoune/issues/1594#issuecomment-332479317 there is a comparision of what `strace` reports, with the other terminal being qterminal.

**Comment by gnunn1** [comment]
Unfortunately I cannot reproduce this on Arch, when I close a terminal with ```kak``` running the process get's terminated as expected. Note that tilix only sends processes a SIGHUP to terminate. If you run another process like htop or nano, does that get terminated by tilix as expected?

I did find one issue where kak where terminating kak was triggering a segfault in tilix (not the fault of kak though) and I've cleaned that up in master.

**Comment by doppioandante** [comment]
I realize only now that the rep steps are actually tricky.
This is what is needed

* Open two different terminal windows
* In one window, do a split and start a program in one pane (e.g. `htop`)
* strace that process from the OTHER window
* close the pane containing the running process

Now, I can see htop still going with strace.
Closing the first window doesn't change this fact.
BUT, opening a NEW tilix window sends the SIGHUP to it.

**Comment by f2404** [comment]
@doppioandante I cannot reproduce this with tilix 1.6.4 on my system.

**Comment by gnunn1** [comment]
I cannot reproduce this with master, when I strace htop with and then  close the pane it stops as expected:

```
...
write(1, "3\33[8;75H", 8)               = 8
write(1, "\33[36m41\33[H", 10)          = 10
write(1, "\33[39m\33(B\33[m", 11)       = 11
rt_sigaction(SIGTSTP, {sa_handler=0x7f13bca4d310, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f13bc355920}, NULL, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 1500)  = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=21157, si_uid=1000} ---
+++ killed by SIGHUP +++
```

**Comment by doppioandante** [comment]
Okay, I will try again with master :-(

**Comment by doppioandante** [comment]
I don't think this is a problem with tilix, probably it's the shell's fault, closing.
