### ISSUE TITLE
Tilix does not remove nautilus entry on uninstall

### ISSUE THREAD

**Issue by czardoz** [gnunn1/tilix#1136]
It ideally should remove the "Open in Terminix" entry.

**Comment by gnunn1** [comment]
How are you uninstalling it?

**Comment by czardoz** [comment]
I'd installed through the WebUpd8 PPA, and uninstalled using `apt-get`.

```
sudo apt-get purge tilix
```

**Comment by czardoz** [comment]
Hmm, it seems that Tilix is not exactly packaged by you for the PPA. Feel free to close this issue, if the fix lies elsewhere :smile:

**Comment by gnunn1** [comment]
That's correct, you should open an issue on launch pad against that PPA.
