### ISSUE TITLE
Switch to tab mode

### ISSUE THREAD

**Issue by Scaum** [gnunn1/tilix#1137]
Hi,
I'd like to start by thanking you for Tilix. I've been using it for a few month and I really do enjoy it a lot !

I realized today that the option to switch to tab mode was added in the beginning of August. However, I cannot find the way to make this switch. 

My tilix is up-to-date on Fedora 26:
`rpm -q tilix`
`tilix-1.6.4-1.fc26.x86_64`

In the Appearance tab of preferences, I only have 4 available checkboxes, last one being "Use overlay scrollbars", but I can't find the "Use tabs instead of sidebar" checkbox I've seen on Youtube videos when trying to find the solution.

I realize this might not be the best place for such a question, really sorry for that, didn't really know where to ask.

**Comment by phw** [comment]
There hasn't been a stable release with this feature yet, but @gnunn1 recently talked about wanting to do a new release soon.

**Comment by gnunn1** [comment]
As @phw noted there hasn't been a stable release with tabs support up to now, I've been holding off trying to close a few issues. Hopefully next week I can push something out, I just want to fix how the notifications are displayed on the tabs.

**Comment by Scaum** [comment]
Ok, my bad then, saw tabs in the commit, thought it was released. Can't wait for it !
Thanks for reconsidering the tab issue @gnunn1
