### ISSUE TITLE
organize bookmarks with trees or tags

### ISSUE THREAD

**Issue by freeseacher** [gnunn1/tilix#1138]
Hi! 
tnx for great app! 
I have lots of hosts to administer and previously work with gcm. currently i am working with several project with different ssh ports and policies to connect to.
it has tree style organizer for host list. it was not perfect but good enough. Now site is down and author did not reply's to emails for about 6 years 

I aw wondering if you can add some kind of bookmark organizer.I am dreaming about some kind of tags and filters for them. and a thinking about such process to do it. hitting some hotkey for example ctrl+n i got a window with host list and search bar. Search bar looks for tags, description and addresses. then i have to click on host to connect to it or select several hosts to connect to them all and open them in session or window.

**Comment by gnunn1** [comment]
Tilix already supports bookmarks that does much of what you want. You can organize your bookmarks into trees with folders and using drag and drop. The bookmark window can be shown via a hotkey and enables you to quickly search based on the name of the bookmark.

I think the only thing I'm missing is support for tags and searching tags as well as titles?

**Comment by freeseacher** [comment]
yep. ctrl+shift+b that one i miss. switching language  to english makes sense.

But still it pastes ssh command in current shell. so it is big difference where i launch that hotkey. not idempotent. 
Can i select whether to open new session or paste command there. ?

**Comment by gnunn1** [comment]
No you cannot ask it to launch the bookmark in a new session and I don't have any plans to add that feature as it gets complicated fast. i.e. Launch in session, Launch in split tab right, Launch in split tab down, etc...

**Comment by freeseacher** [comment]
ok. thx any way for doing open source. 
can you advice any good ssh connection managers ?

**Comment by gnunn1** [comment]
Unfortunately I'm a developer and not a system administrator so the number of systems I SSH to is quite small and thus I haven't had a need for something like that.

**Comment by freeseacher** [comment]
thre were couple of them. pac and gcm. both projects looks dead for now. 
any plans to do connection managers and not only terminal ?
