### ISSUE TITLE
Add bastion like connections

### ISSUE THREAD

**Issue by freeseacher** [gnunn1/tilix#1140]
It will be perfect if i can connect to host via another host. 
Such settings can be done via 
`./.ssh/config` but is not manageable 
i am talking about such type of connections 
https://unix.stackexchange.com/questions/25055/ssh-via-multiple-hosts 

From ui point of view i'm expecting that can be chained via interface with specifying another bookmark.

tnx

**Comment by gnunn1** [comment]
This is something that should be managed by SSH and not in the terminal emulator itself IMHO, no plans to work on this. ProxyCommand in your SSH config is the way to go I would think.
