### ISSUE TITLE
After using Neovim in Tilix, the i-bar cursor turns into a block cursor--and will not change back

### ISSUE THREAD

**Issue by 00krishna** [gnunn1/tilix#1141]
So this is an odd issue. Tilix works just fine when I load it up. I have the cursor set to I-bar which I prefer. 

Once I invoke `neovim`, using the `nvim` command, I can go into neovim and do my normal things. However, once I exit `neovim` the cursor stays as a block--and will not return to I-bar. 

This might have something to do with the fact that in `neovim` the block cursor is used for normal mode and the I-bar is used for insert mode. But whatever the case is, the cursor does not reset back to the original terminal setting when it exits `neovim`. 

Just wanted to make you aware of this issue. Thanks for the great Tilix tool.

**Comment by gnunn1** [comment]
Does the same thing happen in gnome-terminal as tilix shares the same VTE widget for the terminal emulation?

**Comment by f2404** [comment]
I can confirm the same happens in g-t and other terminal (c)
I guess 'neovim' could be using some hacks for changing cursor shape that prevent terminal widget from handling it.

**Comment by gnunn1** [comment]
Thanks @f2404.

@00krishna I would suggest opening an issue with the neovim folks about this and see what they say. As this doesn't appear to be a Tilix issue I'm closing this issue.

**Comment by f2404** [comment]
In fact, Egmont has already captured the issue: https://github.com/neovim/neovim/issues/4396

**Comment by 00krishna** [comment]
Oh interesting. Okay thanks for the quick and interesting response. I will follow up with the neovim project.

Thanks again.
