### ISSUE TITLE
Confirm terminating the running process

### ISSUE THREAD

**Issue by slgobinath** [gnunn1/tilix#1143]
First of all, thank you very much for such an awesome terminal.

I have one enhancement request:
Could you please add an optional feature to confirm the `Ctrl + C` and `Ctrl + D` shortcuts similar to what you have for pasting commands.

I experienced this problem today by accidentally pressing `Ctrl + D` from Python console where I had few lines of code and I lost them completely. I know Python console is not for writing hundreds of line but it may be useful for other applications as well.

Thanks

**Comment by f2404** [comment]
https://unix.stackexchange.com/questions/27588/how-can-i-keep-controld-from-disconnecting-my-session

**Comment by slgobinath** [comment]
Hi @f2404,

Thanks for `IGNOREEOF` which I didn't know earlier. However, I think it works with Bash only.
Still, I am able to terminate Python console using single `Ctrl + D`.

**Comment by f2404** [comment]
Hi @slgobinath,

This could mean that the Python console is handling Ctrl+D by itself, not relying on the shell.

**Comment by gnunn1** [comment]
Thanks for the suggestion but I don't have any plans to add an option for this. I have too many options already in Tilix and I don't see this one as being much used.
