### ISSUE TITLE
select by word characters

### ISSUE THREAD

**Issue by iax7** [gnunn1/tilix#1148]
There is a feature in terminator that is very handy:
![image](https://user-images.githubusercontent.com/6983510/31361467-21acf8f2-ad19-11e7-82c9-70ef0ae8f248.png)
this basically is used as a separator character when double-clicking in a long word, it selects only the part that is divided by this char list:
![image](https://user-images.githubusercontent.com/6983510/31361521-58cfcc1a-ad19-11e7-894c-bc81a53acd6b.png)
double click in `slaveId=892b5dd8-ad27-426f-aff6-5a977198320e-S11` only selects one part, in the previous example, the second part, instead of the whole word.

can it be added to tilix?

**Comment by gnunn1** [comment]
Sure, the VTE has a method for this so supporting it is easy.

https://developer.gnome.org/vte/0.40/VteTerminal.html#vte-terminal-set-word-char-exceptions
