### ISSUE TITLE
Ability to donate/sponsor Tilix?

### ISSUE THREAD

**Issue by wezm** [gnunn1/tilix#1149]
I'm trying to make an effort to support tools like Tilix that are a core part of my computer use. Do you have any means to accept donations/[Patreon](https://www.patreon.com/)/[Liberapay](https://liberapay.com/) etc? I use Tilix for hours each day as part of my job and on personal machines and would like to support its development.

**Comment by gnunn1** [comment]
While I appreciate the sentiment I have no plans to accept donations.
