### ISSUE TITLE
Tilix 1.7.0 Scrollbar Always Visible

### ISSUE THREAD

**Issue by ErikWallstrom** [gnunn1/tilix#1150]
The scrollbar of Tilix is always visible after the update. 
I believe it's a bug, since the scrollbar goes away if you don't move your mouse in all other GTK3 applications.

**Comment by gnunn1** [comment]
Do you have the environment variable GTK_OVERLAY_SCROLLING=0 per chance? Some DEs, notably MATE, set this variable to disable overlay scrolling, tilix now respects it since it causes issues otherwise.

Otherwise what DE do you use and can you supply a screenshot?

**Comment by ErikWallstrom** [comment]
I am using GNOME 3.26. 

Here is Tilix:
![screenshot from 2017-10-14 23-01-35](https://user-images.githubusercontent.com/15019604/31579296-b7fdec44-b133-11e7-9ddd-7c75bd4525c7.png)

Here is Natuilus with "small scrollbar":
![screenshot from 2017-10-14 23-01-53](https://user-images.githubusercontent.com/15019604/31579298-bf8e7f00-b133-11e7-9257-a5ad0b55dca5.png)

Here is Natuilus with the same scrollbar as tilix:
![screenshot from 2017-10-14 23-03-25](https://user-images.githubusercontent.com/15019604/31579305-f90f0222-b133-11e7-9ab1-364c978c46bc.png)

As you can see, the new version of Tilix always shows the scrollbar like the last screenshot, even though it should show as the second last since I haven't selected the scrollbar

**Comment by gnunn1** [comment]
Check the preferences, is the overlay scrollbar default setting in Appearances turned on. I may have missed setting that back to true when working on that bug

**Comment by ErikWallstrom** [comment]
Oh, my bad. The issue is fixed by enabling that option. I didn't realise that was an option since it was enabled by default before. Thanks!

**Comment by gnunn1** [comment]
I'm re-opening this as it should be on by default.
