### ISSUE TITLE
[Run Error] tilix: undefined symbol on Ubuntu 17.10

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1151]
this happens on Ubuntu 17.10 on `1.6.4-1ubuntu1` package and apparently isn't reproduce-able to all Ubuntu installations

```
Starting program: /usr/bin/tilix 
/usr/bin/tilix: symbol lookup error: /usr/bin/tilix: undefined symbol: _D3gio9DBusProxy9DBusProxy9__mixin3622getAsyncInitableStructMFbZPS4gtkc8giotypes14GAsyncInitable
[Inferior 1 (process 24485) exited with code 0177]
```

**Comment by jbicha** [comment]
I don't think this is an upstream tilix bug. I think this is because alex285 was using artful-proposed packages.

**Comment by alex285** [comment]
@jbicha was correct. 
i did `apt-cache showpkg tilix` and i downgrade the dependencies. what was breaking Tilix was `libgtkd-3-0`

downgrade it from ` 3.6.6-1ubuntu1` to `3.6.5-2ubuntu1` fixed the issue

**Comment by alex285** [comment]
btw Tilix requires dGTK 3.6.6
