### ISSUE TITLE
Problem running Tilix 1.7.1 and 1.7.0

### ISSUE THREAD

**Issue by simoniz0r** [gnunn1/tilix#1153]
I am running Xubuntu 16.04, and I have Tilix 1.6.4 installed through the PPA.  I downloaded the latest release from the releases page here, and when I try to run it without my installed version of Tilix running first, I get the following error:

```
(tilix:23699): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Tilix.Settings' does not contain a key named 'use-tabs'
Trace/breakpoint trap (core dumped)
```

If I have my current installed version of Tilix running before attempting to launch the new version, it seems to launch fine, but I'm thinking it might just be launching the installed version instead of trying to execute the version I just downloaded. 

Version 1.7.0 also gives the same error.  Using the zip release of 1.6.4 from here (the same as I have installed) works fine.

Any help would be appreciated, thanks.

**Comment by gnunn1** [comment]
Did you run ```install.sh``` as per the instructions and what was the output?

**Comment by simoniz0r** [comment]
The download contains no install.sh?

**Comment by gnunn1** [comment]
Me bad, I'm so used to running it from source I forgot about that. Did you run this command:

```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```
And where there any issues? The reason it is complaining about the key is because it is using the old schema. Compiling the schema should correct the issue.

Sorry for the confusion.

**Comment by simoniz0r** [comment]
Thanks, that worked!

**Comment by simoniz0r** [comment]
I'm going to go ahead and close this; that error doesn't seem to be hurting anything as far as I can tell.  I'll open up a new issue if I notice some weird behavior being caused by this.
