### ISSUE TITLE
Save session does not get active directory, dir is empty in save file

### ISSUE THREAD

**Issue by maidenone** [gnunn1/tilix#1156]
I just built tilix 1.7.1 and my loaded session starts at home instead of the dir that was present when i saved the session. i also see no paths is set in the session file that i saved. (save with ctr + shift + s) and see that the session.json file is updated, but paths is always " "

Also "new terminal inherits directory and profile from active terminal" does not work either, maybe related? all new terminals will be started in the home directory.

**Comment by gnunn1** [comment]
You probably need to source vte.sh in bash, see the following for information on how to rectify it:

https://gnunn1.github.io/tilix-web/manual/vteconfig/

**Comment by gnunn1** [comment]
Any luck with this?

**Comment by maidenone** [comment]
Yes. Setting the source in bashrc and restart the application in a new
terminal did it.
