### ISSUE TITLE
Strange paste and history behavior

### ISSUE THREAD

**Issue by tlinsley** [gnunn1/tilix#1160]
Issue: When I paste into terminal (same result via shift+insert or shift+ctrl+v) AND the data wraps to more than one line, Tilix repeats the first line many times before finally showing the remainder. Note it does not actually execute the repetitious lines, just kinda echoes them. Once the entire paste is there, everything works a normal. But if I up arrow through history to that command, the same strange behavior happens. Let me know if further information is required. Thanks.

Running on Fedora 26.
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.21

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0

**Comment by gnunn1** [comment]
Does it happen in gnome-terminal as well or just tilix?

**Comment by tlinsley** [comment]
Wolf! Wolf! Wolf!

My apologies fro crying wolf. The issue has cleared itself. Since I had done a "dnf update" an hour or so before the issue started happening, I suspect that caused the temporary issue. I later noticed some vte components had updated. After restarting my system, all was happy again.

Thanks for the wonderful terminal and sorry again for the false report.

**Comment by egmontkob** [comment]
Maybe it was a rarely occurring bug that you won't ever see or we won't be able to trace down. However, VTE didn't receive any change recently that could be relevant; plus a "dnf update" running in the background, or VTE itself just being upgraded is not a valid reason for such a bug to occur.
