### ISSUE TITLE
Window doesn't come to front and prompt doesn't appear immediately

### ISSUE THREAD

**Issue by gnuvince** [gnunn1/tilix#1161]
I have Tilix 1.7.1 (downloaded the .zip from Github) installed on a Debian Unstable machine running the Openbox window manager.  I've noticed two issues:

1. If no other tilix instance is opened, the PS1 prompt doesn't appear.  Pressing Enter (or any other key really) makes the prompt appear; opening a new tab (`Ctrl+Shift+T`) makes the prompt appear in both tabs; opening a new instance of tilix makes the prompt appear in the new window, but not the old one.
2. Sometimes the window doesn't appear to the front, it's hidden behind other windows.

I have a Debian Stable (9.1 or 9.2) with Openbox at work where these issues don't seem to come up.

**Comment by gnunn1** [comment]
Nothing comes to mind for these issues, does gnome-terminal work?

Unfortunately I do not support Openbox, just Gnome and Unity. I only have so many hours in the day and have to limit the scope of what I can support effectively. I will not be investigating further, sorry.
