### ISSUE TITLE
Can't drag tiles with long titles (paths)

### ISSUE THREAD

**Issue by jotaf98** [gnunn1/tilix#1163]
Hi, first of all, thanks for developing Tilix, it is awesome!

One snag I run into frequently:

A tile's title bar seems to have two components; the bar's background, which is draggable, and the title text which is not draggable (it is a drop-down menu).

This is a problem, because if a tile's title text is long enough (which happens in directories with long paths), it covers the whole title bar. Effectively this locks the tile in place, because it is not draggable and I can't move the tile anymore.

**Comment by gnunn1** [comment]
It's a good point, I'm wondering if I should add some margin somewhere to always ensure there is whitespace. Alternatively an always visible grab handle could be used but that's a bit ugly. I'll think about the options, ideas always welcome.

**Comment by dsboger** [comment]
@gnunn1 Is it possible to make the button itself a drag source behaving the same as its container?

**Comment by gnunn1** [comment]
@dsboger Maybe, I'll have a look at what is involved.

**Comment by jotaf98** [comment]
I guess an invisible spacer element (that is draggable) to the right of the text should do the trick.

Making the dropdown menu draggable would be even better. However it might not be worth it if it clashes with the clicking/drop-down behavior, and turns out to be flimsy or hard to implement.

**Comment by gnunn1** [comment]
I have added ten pixels of margin to the right of the button so there will always be place to click and drag.

**Comment by jotaf98** [comment]
Thanks, that's great! BTW how often are these changes usually reflected on the Webupd8 PPA? (Just to know the time scale of when to expect it)

**Comment by gnunn1** [comment]
It generally gets updated whenever I do a release which isn't that often these days. However it looks like they haven't done an update to 1.70 or 1.7.1 yet so they may be running behind. You would be better off asking the package maintainer.
