### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by wezm** [gnunn1/tilix#1168]
I guess this is a combination of bug report and documentation. I'll start of with saying I managed to build Tilix 1.7.1 on FreeBSD 11.1. Unfortunately it crashes right after showing the initial window ([screenshot of window](https://mastodon.social/media/v8N4rSVkaneDyBWJqWE)):

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000014a3f90 in gdk_x11_get_server_time ()
```

The steps to build were:

1. Install dmd from the [dlang](https://dlang.org/download.html) download page
2. Install `dub` from FreeBSD packages
2. Install dependencies listed in README + `gcc` (for libstd++).
3. `source ~/dlang/dmd-2.076.1/activate`
4. `dub build --build=release -v`
  * This works, right up until the linking step, which fails with `/usr/bin/ld: cannot find -ldl` (libdl is a Linux/glibc thing)
  * Removing `-L-ldl` from the liking invocation results in `source/x11/Xlib.d:(.text._D2gx3gtk3x1117activateX11WindowFC3gtk6Window6WindowZv+0xfa): undefined reference to 'XSendEvent'`
5. Ultimately removing the reference to `libdl` and adding one to `libX11` gets it to link: `dmd -of.dub/build/default-release-posix.freebsd-x86_64-dmd_2076-7B2EDFB9396303A2BF2679165D6BB30E/tilix .dub/build/default-release-posix.freebsd-x86_64-dmd_2076-7B2EDFB9396303A2BF2679165D6BB30E/tilix.o ../../../../../home/wmoore/.dub/packages/gtk-d-3.6.6/gtk-d/.dub/build/library-release-posix.freebsd-x86_64-dmd_2076-8020FBA15D9CB282743C46398A5CCB1B/libvted-3.a ../../../../../home/wmoore/.dub/packages/gtk-d-3.6.6/gtk-d/.dub/build/library-release-posix.freebsd-x86_64-dmd_2076-538A4AEA96E4D4D5881193FF1C479054/libgtkd-3.a -L-L/usr/local/lib -L-lX11`
6. The install script had a slight incompatibility with BSD `find`, which I fixed in #1167.
7. After installation, running `tilix` shows the window briefly, then it crashes as mentioned above.

My next planned steps are to do a debug build and see what's causing it to crash. My guess is the `window` argument to [gdk_x11_get_server_time](https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#gdk-x11-get-server-time) is NULL for some reason.

I've never written any D before so I guess my main reason for opening this issue is to document what I did and to see if you had any guidance for dealing with the linking issues. I.e. how can I influence the linking arguments.

**Comment by wezm** [comment]
Interestingly it's crashing in the same function in https://github.com/gnunn1/tilix/issues/1157

**Comment by wezm** [comment]
Ahh I got a working build with LDC (which I know the README says is unsupported) but still had to diddle with the linking args.

**Comment by gnunn1** [comment]
LDC is supported, it says not supported somewhere then that should be corrected. It's GDC that's not supported.

**Comment by gnunn1** [comment]
I'm cleaning up older issues and closing this, if you have a new question and want to re-open it feel free.

**Comment by JasMich** [comment]
> Ahh I got a working build with LDC (which I know the README says is unsupported) but still had to diddle with the linking args.

How did you? `ldc` is not supported on FreeBSD:
```
���  ~ curl -fsS https://dlang.org/install.sh | bash -s ldc
no ldc binaries available for freebsd
```

**Comment by wezm** [comment]
I just used the package: https://www.freshports.org/lang/ldc/

**Comment by JasMich** [comment]
I see. Could you share the exact commands you were using to build on FreeBSD? I'm totally new to `ldc`.

**Comment by wezm** [comment]
These are the notes I took. I haven't done this for more than a year though so they might not work.

# Tilix Build on FreeBSD

## Installing D

* Install ldc and dub via pkg: `sudo pkg install ldc dub`
* Install gcc and pkgconf

## Building & Installing Tilix

    dub build --build=release -v

The build will fail in the linking step so you have to manually link it. Take the linker command and remove `-ldl` and replace it with `-lX11`:

    /usr/local/bin/ldc2 -disable-linker-strip-dead ... -L=-ldl -vcolumns

into:

    /usr/local/bin/ldc2 -disable-linker-strip-dead ... -L=-lX11 -vcolumns

Re-run `dub build --build=release -v`, which will ensure the final binary is copied into the right place in the source directory for installing.

Install with the install script:

    sudo ./install.sh /usr/local/stow/tilix-1.8.5
    sudo rm tilix-1.8.5/share/glib-2.0/schemas/gschemas.compiled
    sudo xstow tilix-1.8.5
    sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas/
