### ISSUE TITLE
Can't change cursor color (Debian 9.2/MATE 1.16.2/Tilix 1.6.4)

### ISSUE THREAD

**Issue by koalization** [gnunn1/tilix#1171]
Just installed Tilix 1.6.4 from [stretch-backports](https://packages.debian.org/stretch-backports/tilix) in Debian 9.2. In Preferences->Default->Color->Advanced I change my cursor background to red (or any other color), which makes my cursor temporarily change color to red, then I close the window and the cursor turns back to white (or any other color previously set). I tried with both the Dark and Light theme variant and with "Use theme colors for foreground/background" box checked and unchecked. The behavior is always the same, the color cannot be changed.

**Comment by gnunn1** [comment]
I just tried it in 1.7.0 and it worked fine for me. There was an issue back in April that caused this but 1.6.4 was released after that. Can you try the latest version and see if it is corrected there.

**Comment by koalization** [comment]
I've built Tilix with DUB and DMD from the master branch (installed DMD's .deb from the official website) and it crashed when clicking on Preferences. I also haven't managed to build it with DUB and GDC that come with Debian by default, I got lots of errors (most of related to GTKD 3.7.0 by the way). However, since Debian gave me other major annoyances I wiped out the partition and I couldn't help you debugging it. I'll stick with CentOS.

**Comment by gnunn1** [comment]
Sorry about that, unfortunately there's a bug with DMD and GTK 3.7.0, please use LDC to compile tilix for the moment.

**Comment by koalization** [comment]
I will. Thanks for your great work, Tilix is really appreciated and a joy to use. Unfortunately I'm having issues with Debian overall, I'm going to submit a couple bug reports to them, not related to Tilix. Sorry if I can't be of more help with this particular issue.
