### ISSUE TITLE
New Terminal via Ctrl+Alt+T creates Split to Quake Console

### ISSUE THREAD

**Issue by ktomk** [gnunn1/tilix#1172]
I have Ubuntu 16.04 LTS and Tilix installed. I'm using the quake console as well.

When pressing Ctrl+Alt+T keyboard accelerator keys to open the terminal and only the Quake-Tilix was loaded so far, a new split is created inside the quake-console.

I would consider this as a flaw as my expectation is that a Tilix main terminal window is opened instead of splitting the quake terminal.

**Comment by gnunn1** [comment]
I don't believe Tilix configures a shortcut by default for ctrl-alt-T, did you mean ctrl-shift-T? If so, the behavior that occurs when opening a new Tilix window is controlled by the preference ```On New Instance``` in the Global section of preferences. Do you have it configured to split a window?

**Comment by ktomk** [comment]
Ctrl+Alt+T is just the default shortcut on my desktop for the default terminal which is Tilix for me.

The global preference is indeed set that way.

Having that as a global preference looks counter-productive to me as I use two different styles of Tillix, the standard one and the quake one.

The quake one should not split down on new instance as the quake one should have only one instance and instead just open a new window with the default profile (or a configurable one).

**Comment by gnunn1** [comment]
I understand where you are coming from, I'm not sure there's a clean solution to this though without adding more options which at this point I'm loathe to do as I have too many of them already. Folks that primarily use Tilix out of quake mode likely want to keep things the way they are so there has to be a balance between the two.

I'll let it percolate in my brain a bit, but thoughts about this from others is always appreciated.

**Comment by f2404** [comment]
@ktomk What command is assigned to your shortcut, is it just `tilix`?

**Comment by ktomk** [comment]
@gnunn1: Thanks for the feedback, really appreciated. So far just take it as a report, I'm less a fan to jump to conclusions quickly and code something in, most often not very useful "features" come out of that. I should always have the option to install guake again, I was using Terminator + Guake previously and I'm currently evaluating replacing both with Tilix, but I can imagine to replace Terminator with Tilix (Terminator did crash often recently) only.

@f2404: I think it is `x-terminal-emulator`, which according to ` update-alternatives` is `/usr/bin/tilix`. With these two commands I can reproduce the reported behavior.

However, when I use the Super+1 hotkey in Ubuntu (first program in Launcher, which is Tilix), a new larger window is opened (no split in quake Tilix). The launcher uses the desktop file

- `/usr/share/applications/com.gexperts.Tilix.desktop`

which has the following command: `tilix --action=app-new-window`

So this looks it's already the solution. I'll try to bring it into the alternatives. Thanks for all your feedback so far!

**Comment by ktomk** [comment]
No luck with this for me so far, the Ubunut launcher keeps track if the application has been started already or not. Therefore it works well.  Need to keep track as well then for that one... .

**Comment by ktomk** [comment]
I made a little progress by creating a small shell-script and update the alternatives:

~~~
#!/bin/bash
#
# tilix-once.sh - start tilix (new window), but only once
#
# sudo update-alternatives --install /etc/alternatives/x-terminal-emulator tilix-once /home/${USER}/bin/tilix-once.sh 100
#
set -euo pipefail
IFS=$'\n\t'

set +e
win="$(xdotool search --onlyvisible --class tilix | head -n 1)"
found=$?
set -e

if [[ ${found} -eq 0 ]]; then
  xdotool windowactivate "${win}"
else
  /usr/bin/tilix --profile=Default --action=app-new-window &
fi
~~~

The only problem left is that setting the profile (here: Default) on launch does not work. This is perhaps related to the app-new-window action.

It would be nice if a default profile can be specified for quake mode and when quake mode is closed it would not set the overall default window next from last.
