### ISSUE TITLE
[Feature Request] Blur like Opacity in Tilix / VTE

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1176]
is that doable?

**Comment by gnunn1** [comment]
No it is not, Cairo has no blur operator AFAIK.

**Comment by alex285** [comment]
tata! with elementary's Gala Blur experimental API
https://github.com/elementary/gala/commits/optimized-blur-vala

![screenshot from 2018-03-04 21-21-06](https://user-images.githubusercontent.com/11244308/36949513-2f9719ba-1ff2-11e8-93d5-bb08a611494f.png)

**Comment by gnunn1** [comment]
Cool, did you have to change code in Tilix to do it?

**Comment by alex285** [comment]
@gnunn1 nop! i only activated with DBus! it is Gala feature, that you can enable for each app! if they push it that in their master, i will open an issue to add an Blur switch next to opacity, of someone runs Tilix on elementary!

**Comment by gnunn1** [comment]
While it's cool please don't bother opening an issue, i don't have any plans to support gala or elementary.

**Comment by alex285** [comment]
@gnunn1 thats absolutely fine! if they use it on Juno, i can PR it anyway! it is pretty simple! plus it can work with KWin too!

**Comment by GNOME-IS-LIFE** [comment]
@alex285 wow! does it cause any major slowdowns? <3 big fan

**Comment by alex285** [comment]
@GNOME-IS-LIFE it shouldn't, Deepin has already same implementation as the one elementary uses, but we should wait elementary Juno final release first

**Comment by GNOME-IS-LIFE** [comment]
@alex285 really? so KDE Plasma just used the same "new" technique Deepin had been doing for years?

**Comment by ryu-ketsueki** [comment]
@alex285 How do I enable the blur background in Tilix with KWin?

**Comment by belozer** [comment]
Blur working in KDE Neon 5.13.2 and tilix 1.8.1!!!

![image](https://user-images.githubusercontent.com/1655916/42410246-53011e5a-81ef-11e8-864d-b34317807b8f.png)

**Comment by belozer** [comment]
@alex285 please try ;)

**Comment by ryu-ketsueki** [comment]
@belozer how did you do it? I'm running Manjaro with KDE Plasma 5.13.2 and Tilix 1.8.1 here.

**Comment by alex285** [comment]
@belozer i dont want to spam Tilix Github, [but for one time i will](https://twitter.com/BabyWogue/status/1015924915227291648) :p

**Comment by belozer** [comment]
@ryu-ketsueki 

1. Set opacity in Tilix
![image](https://user-images.githubusercontent.com/1655916/42422154-c24150be-82e9-11e8-8d29-432f431c4698.png)

2. Set Blur in effects
![image](https://user-images.githubusercontent.com/1655916/42422168-fc0b8d6e-82e9-11e8-9d93-e9d950593c1c.png)

**Comment by ryu-ketsueki** [comment]
Just did that and KDE still refuses to blur Tilix's background

**Comment by ryu-ketsueki** [comment]
@belozer Just did that and KDE still refuses to blur Tilix's background.Perhaps it's something with my GTK theme? I'm using Gnome OSC

**Comment by belozer** [comment]
@ryu-ketsueki @alex285 Oops. I forgot I have one code in my `.zshrc`.

```
if [[ $(ps --no-header -p $PPID -o comm) ]]; then
    for wid in $(xdotool search --pid $PPID); do
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
```

Please try.

I mistakenly believed that this is due to the Plasma 5.13.2..........

**Comment by ryu-ketsueki** [comment]
@belozer I'm using fish as my default shell. Is there a code that works for it?

**Comment by belozer** [comment]
@ryu-ketsueki  I don't use fish. But you can try to adapt the code https://axionl.me/2018/01/27/blur-for-terminal/

**Comment by belozer** [comment]
@ryu-ketsueki 

Try in your fish config
```
set -l ppid (cat /proc/(echo %self)/status | grep PPid | cut -f2)
if string match -r 'tilix' (ps --no-headers -p $ppid -o comm) 1> /dev/null
    for wid in (xdotool search --pid $ppid)
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid
    end
end
```

**Comment by FFY00** [comment]
```
if test (ps --no-header -p $PPID -o comm) =~ tilix
    for wid in (xdotool search --pid $PPID)
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id wid
    end
end
```

should work

**Comment by ryu-ketsueki** [comment]
@FFY00 @belozer Alright. I tested both and none worked. Here's what might be causing it:
1 - _ps --no-header -p $PPID -o comm_ is not equal to "tilix", but to "fish" in my end.
2 - _xdotool search --pid $PPID_ is not giving an output, not even when I type the command manually with my PID. (Just installed xdotool from Manjaro Repositories). Because of this, the xprop command won't work, not even manually.
Now I'm trying to use the fish code for blur that appeared for Konsole and Yakuake here as base to work for Tilix. I'll tell you guys if I do any progress;

The code for Konsole and Yakuake is:
`if test $DISPLAY
    for ID in (qdbus | grep -E "konsole" | cut -f 2 -d\ )
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id (qdbus $ID /konsole/MainWindow_1 winId)
    end
    for ID in (qdbus | grep org.kde.yakuake)
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id (xwininfo -name Yakuake | grep "Yakuake" | sed 's/xwininfo: Window id: //g' | sed 's/"Yakuake"//g')
    end
end`

**Comment by dougmaitelli** [comment]
The code from @belozer works perfectly for me on fish! Thanks

**Comment by belozer** [comment]
@alex285 yes :tada: thanks! ;)

**Comment by webispy** [comment]
I recommend using the [devilspie](https://github.com/GNOME/devilspie) tool instead of modifying the .zshrc script.

Following is my `~/.devilspie/tilix.ds` configuration.
```
( if
( is ( application_name ) "tilix" )
( begin
( spawn_async (str "xprop -id " (window_xid) " -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 ") )
)
)
```

And register the devilspie tool to autorun.

**Comment by alexschomb** [comment]
If the ``.config/fish/config.fish`` of @belozer above doesn't work for you, try adding a short pause to the script. That did the trick for me:
```
set -l ppid (cat /proc/(echo %self)/status | grep PPid | cut -f2)
if string match -r 'tilix' (ps --no-headers -p $ppid -o comm) 1> /dev/null
    sleep 0.01
    for wid in (xdotool search --pid $ppid)
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid
    end
end
```

**Comment by danielwangksu** [comment]
Are those settings only work for KDE?

**Comment by AkgunFatih** [comment]
> @ryu-ketsueki @alex285 Oops. I forgot I have one code in my `.zshrc`.
> 
> ```
> if [[ $(ps --no-header -p $PPID -o comm) =~ tilix ]]; then
>     for wid in $(xdotool search --pid $PPID); do
>         xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
> fi
> ```
> 
> Please try.
> 
> I mistakenly believed that this is due to the Plasma 5.13.2  ..........

i tried this in deepin but it doesnt work
they use fork of kwin

> @ryu-ketsueki @alex285 Oops. I forgot I have one code in my `.zshrc`.
> 
> ```
> if [[ $(ps --no-header -p $PPID -o comm) =~ tilix ]]; then
>     for wid in $(xdotool search --pid $PPID); do
>         xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
> fi
> ```
> 
> Please try.
> 
> I mistakenly believed that this is due to the Plasma 5.13.2  ..........

Thank, it works in deepin
![DeepinScreenshot_20200212143322](https://user-images.githubusercontent.com/39423167/74339650-ca2acf80-4da4-11ea-8e8d-158f8c913b08.png)

**Comment by Paralusion** [comment]
the solution provided by belozer is great, but wasn't quite functioning how i liked; it'd only blur if you opened it twice.
i fixed this by adding a simple sleep function, here's the updated code for if anyone has the same problem

`
sleep 0.2
if [[ $(ps --no-header -p $PPID -o comm) =~ tilix ]]; then
    for wid in $(xdotool search --pid $PPID); do
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
`

**Comment by mykahveli** [comment]
@ryu-ketsueki, I have a particular issue. The blur effect goes beyond the window:

![image](https://user-images.githubusercontent.com/19893245/86252019-cce26180-bb99-11ea-8bc1-81089e3a5ea3.png)

Would you mind give me some tips?

**Comment by abuGit** [comment]
To have the blur effect already on the first opening include a sleep and  source it as a parallel process:

file: ~/.tilix_blur
:
```
#!/usr/bin/bash
# filename: .tilix_blur

# for gnu sleep time can be non-integer
sleep 0.1 
# Tilix Blur effect
if [[ $(ps --no-header -p $PPID -o comm) =~ tilix ]]; then
    for wid in $(xdotool search --pid $PPID); do
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
```

and put the following line at the end of your .bashrc` or `.zshrc`

```
( source ~/.tilix_blur&  )
```

**Comment by d4rkb4sh8** [comment]
this feature can be achieved in Gnome on wayland using the "blur my shell" extension - 2024 - Debian
