### ISSUE TITLE
[RFE] double size of window when creating new terminal when there is place

### ISSUE THREAD

**Issue by ericzolf** [gnunn1/tilix#1177]
Instead of cutting the window in two when pressing Ctrl+Alt+D or Ctrl+Alt+R, I would like the new terminal to appear next to the existing one, doubling hence the size of the window. This should probably only happen if there is enough space on the screen to the right or bottom of the window, but as I always increase the size of the window after I've added a terminal, this would save me quite a lot of mouse movement.

**Comment by gnunn1** [comment]
Thanks for the suggestion however I don't think this is something I'm interested in adding. At this point I have too many features and I'm reluctant to add things that I feel have a limited audience.

Also technically you would potentially need to move the window to keep it all on screen when it doubles it's size which isn't feasible under Wayland.

**Comment by ericzolf** [comment]
You're the developer but allow me to argument:

1. you can still leave the enhancement request open and see how many people subscribe to it. Feeling is not knowing.
2. regarding moving the window: I wouldn't want either a window jumping around, that's why I suggested to have the "double size" behaviour only if there is enough space to the bottom or to the right.
