### ISSUE TITLE
error: com.canonical.Unity, when first run after git install

### ISSUE THREAD

**Issue by japhir** [gnunn1/tilix#1181]
Hi! Upon running tilix for the first time after installing the AUR pacakage tilix-git, I get the following error:

`(tilix:24401): GLib-GIO-ERROR **: Settings schema 'com.canonical.Unity' is not installed`

Is this an issue with the [AUR package](https://aur.archlinux.org/packages/tilix-git/), missing recently added dependencies, or is there something else going on here?

**Comment by gnunn1** [comment]
Please open an issue on AUR as I don't deal with packaging issues. However it sounds like the settings schema didn't compiled by the package for some reason. You can compile it using:

sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
