### ISSUE TITLE
Tilix 1.7 package for Fedora

### ISSUE THREAD

**Issue by lokesh-krishna** [gnunn1/tilix#1187]
I am currently on the Fedora 27 Beta and the latest available version of Tilix available, as checked by using `rpm -q tilix` after installing Tilix is tilix-1.6.4-5.fc27.x86_64

Is it normal for the latest package to not be available yet?

**Comment by gnunn1** [comment]
I don't handle the packaging and neither do I follow it particularly closely so I'm not sure how long it takes Fedora to package. I would suggest asking the Fedora folks by opening an issue with them.
