### ISSUE TITLE
Add Terminal Auto Size

### ISSUE THREAD

**Issue by iax7** [gnunn1/tilix#1189]
When you're adding terminal, the current screen gets split by half, but if you keep splitting inside of a split terminal you end with a minimal size.

Initial Split:
![image](https://user-images.githubusercontent.com/6983510/32810819-550d53ee-c962-11e7-9053-32c4b1d34fbe.png)

If you keep splitting:
![image](https://user-images.githubusercontent.com/6983510/32810834-686c9954-c962-11e7-920c-769e20725953.png)

A button and/or a shortcut to make all windows the same size would be handy.

**Comment by gnunn1** [comment]
If you double click one of the separators between terminals, I.e. the one you grab to resize, and double click it and all of the terminals should equalize in size.

**Comment by iax7** [comment]
Excellent, for me, is ok the way it is. Perhaps for some users could use a more discoverable way of doing this.

**Comment by gnunn1** [comment]
I don't see an obvious way of making it more discoverable, but if someone has an idea feel free to re-open the issue.

**Comment by edubxb** [comment]
Any chance to do this through command line? I use [actions](https://github.com/gnunn1/tilix/wiki/Command-Line-Actions) to split the current session, and the need to rely on the mouse to rearrange the splits is not the best option to me :(
