### ISSUE TITLE
Update tab title with split views

### ISSUE THREAD

**Issue by aleho** [gnunn1/tilix#1193]
Updating the tab-title with session set to `${title}` works perfectly fine. So if I change directories or SSH into a server the tab title updates as well. This also works with split views (current tile sets tab title), but only as soon as the title changes.

Could the session name be updated when active tile is changed?
This would help with identifying which tile is currently active in a tab.

**Comment by gnunn1** [comment]
You can change the session title in Preferences | Appearance. Any terminal variables you use here, including terminal title, reference the active terminal. So as active terminal changes so will the session title.

**Comment by aleho** [comment]
Obviously I couldn't explain it right.

Here's a screencast: https://derhofbauer.at/files/titles.webm

I've got two sessions within a tab. If I switch sessions, the tab name is not updated, only if the title changes (e.g. by cd-ing). The tab name keeps the title of the last pane that changed its title.

**Comment by gnunn1** [comment]
What do you have set for the option below:

![screenshot from 2017-11-19 15-40-13](https://user-images.githubusercontent.com/9358238/32995271-28645b58-cd40-11e7-8691-8dcf1bbf57a3.png)

**Comment by aleho** [comment]
It's set to `${title}`.

**Comment by gnunn1** [comment]
I understand now thanks, I'll have a look at it. Sorry for the delay.
