### ISSUE TITLE
quake section of wiki needs updating

### ISSUE THREAD

**Issue by alexeastaugh** [gnunn1/tilix#1196]
Since the name change to tilix the screenshot is incorrect and will no work. This needs to change to tilix --quake like you have stated in the guide above the screenshot.

Needs to be this:
![custom-shortcut](https://user-images.githubusercontent.com/9928886/33064238-ecab53a6-ce9c-11e7-96d2-e7b3ba89f1bd.png)

**Comment by bil-elmoussaoui** [comment]
Can you please create a PR to the tilix-web repository?

**Comment by alexeastaugh** [comment]
Yep no problem. Ill close this one down and focus on the tilix-web repo.
