### ISSUE TITLE
Blur transparent background ?

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#1199]
A slight blur on the transparent background can improve readability when the terminal is over another terminal and text of the same colour is in the same place.

One use for transparency is to be able to see the text on a window behind, so transparency users may not want too much, making background text illegible.

**Comment by alex285** [comment]
Duplicated of https://github.com/gnunn1/tilix/issues/1176

**Comment by stuaxo** [comment]
Doh, hadn't thought that the background goes through Cairo, but makes sense.

Maybe this will be doable when Gtk4 happens.
