### ISSUE TITLE
Argument to open tilix in a new tab in an existing window?

### ISSUE THREAD

**Issue by sliddjur** [gnunn1/tilix#1200]
Is it possible to call tilix to open a new tab in an existing window, rather than just opening a new Window?

I use GNS3 and tilix, every time I click a device, tilix will open a new window. I would like it to open just a new tab in one of my existing windows.

My OS: Ubuntu Budgie 17.10.

**Comment by gnunn1** [comment]
There is a preference for it in the Global Page called "On new instance". set it to 'New Session' and that should give you the behavior you want.

**Comment by jairusan** [comment]
@gnunn1 ,
Worked perfectly!
Thank you very much!

**Comment by 108806** [comment]
I use Tilix as my main terminal, and also as my compilation viewer in Sublime-Text and this solution above is not quite good for me, what would work for me is something like the 'On new instance' setting but for a specified profile.
