### ISSUE TITLE
Quake mode shouldn't honor /org/gnome/mutter/center-new-windows

### ISSUE THREAD

**Issue by dag** [gnunn1/tilix#1201]
With `dconf write /org/gnome/mutter/center-new-windows true`, Mutter positions all newly opened windows perfectly in the center of the screen. This causes `tilix --quake` to open vertically centered, horizontally maximized. I don't know if this is something you can work around, but for example Firefox doesn't open its first window centered, so it does seem you can position windows in spite of this, although it seems to "jump" so maybe it's simply positioning itself *after* mutter centers it. That's probably Firefox being slow to load its stored window position; I bet you can set the position at some event the instant the window is created and it would be fast enough that you don't notice the jump.

Apologies if this is a dup of #1095; it doesn't mention this configuration option and reported different results in Wayland and X11—this option should behave the same in both and in deed with it set to the default `false`, quake mode opens correctly at the top for me in Wayland. If you can't do anything about this, I perfectly understand. It's an obscure option hidden away inside dconf, although Ubuntu paches GNOME Tweak to expose it last I checked.

**Comment by phw** [comment]
AFAIK Firefox does not run natively on Wayland but runs via XWayland, hence it can position itself.

**Comment by dag** [comment]
Still, quake mode works under Wayland for me if I don't set this Mutter option.

**Comment by gnunn1** [comment]
Unfortunately I have no control on how Wayland places the quake window on the screen, it's one of the reasons why I'm considering dropping support for it. I just don't see an easy way to manage this, sorry.

**Comment by dag** [comment]
I think this is independent of Wayland, but fair enough.

**Comment by phw** [comment]
> I think this is independent of Wayland, but fair enough.

This doesn't happen for me on X11 when setting `/org/gnome/mutter/center-new-windows true`, the quake window gets positioned at the top no matter what.
