### ISSUE TITLE
screen messed up after :make command on vim, and start crash.

### ISSUE THREAD

**Issue by cacheflood** [gnunn1/tilix#1204]
Screen gets messed up after make command from vim. Dunno is this due tilix or vim?
![tilix](https://user-images.githubusercontent.com/5121781/33395878-89d8f88c-d54f-11e7-8c24-8ff51fcfeeb3.png). Screen get fixed after the mess if I move cursor etc.

ver: 1.6.4
Fedora 27: Linux xxxxxxxxx 4.13.15-300.fc27.x86_64 #1 SMP Tue Nov 21 21:10:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Also crashed sometimes when starting (when crashing,every second time starts ok, every second crashed imho)

**Comment by egmontkob** [comment]
How reproducible is it?

Could you please try the same steps in `xterm` (in approximately the same window size, measured in characters)? Is it reproducible there?

**Comment by cacheflood** [comment]
Hi!, it's reproducible, xterm work.

Just tested, at least after resizing the split it happens more often. I
think it also happened when i just opened vim, but not sure.
Could it be something I have special chars on editor to show tabs (on
screenshot)? I mean I'm using UTF-8 and it's variable length... and drawing
structure reads just middle of some char code... just guessing...
If you need more information / test please do not hesitate to ask!

Cheers, Jani


[image: Tekstiin lisättävä kuva 1]

2017-11-29 22:56 GMT+02:00 egmontkob <notifications@github.com>:

**Comment by cacheflood** [comment]
Just opened tilix, started vim to show you surrounging code, and this
happened, so no split screen affects this.
Attached the main.cpp so you can see the order or messed texts on previous
email if it helps.

-Jani


[image: Tekstiin lisättävä kuva 1]





2017-11-30 0:13 GMT+02:00 Olvin Janoisin <cacheflood@gmail.com>:

**Comment by cacheflood** [comment]
xterm works. This is reproducible. I'm using UTF-8 so it's variable length and I have special chars to show tabs. could the problem be that some routine assumes chars to be aligned by 2?

**Comment by cacheflood** [comment]
This also happens when just starting vim with filename... and is annoying, happens all the time...
Removed the special tab char from vim settings, no help. But... tried also nano/less/highlight and some others, no mess... so... could this really be issue on... vim o_O ?(!)

**Comment by egmontkob** [comment]
Could you please test if disabling overlay scrollbar (Preferences -> Appearance; then restart Tilix) fixes this issue?

If not then could you test the behavior in gnome-terminal?

**Comment by cacheflood** [comment]
Disabling overlay scrollbar seems to help!!!! Tried on different window sizes and repeated many times.

I'm curious... is it thread issue or just old school 'bug'? (thinking thread issue just because random appearance even start condition is same...)

**Comment by egmontkob** [comment]
Okay it's yet another phenomenon caused by #1122 then.

**Comment by egmontkob** [comment]
See also https://github.com/vim/vim/issues/424.

**Comment by cacheflood** [comment]
Ok, so... kind of "thread" problem... ty 👍

**Comment by gnunn1** [comment]
@egmontkob Is there a VTE bug already on the overlay scrollbar, should I open an issue summarizing the different issues with it?

**Comment by egmontkob** [comment]
The picture is not clear to me. There's a bug I guess about GtkScrolledWindow, and overlay scrollbar is probably related to that, but not clear to me how exactly (if at all). I can't recall a bug about overlay scrollbar in particular.

As for overlay scrollbar, the only issue seems to me that it causes VTE to frequently change its size back and forth. The rest (top, vim etc. misbehavior) are just symptoms of this. It's unclear to me why an overlay scrollbar would change the widget's width, rather than, well, overlay.

If you think VTE does anything incorrectly (rather than this being a generic bug/misdesign in Gtk+ and overlay scrollbar) then yup I think filing a bugreport is a good idea. At least we might get precious feedback from the project's main developer who's more knowledgeable in this area.

**Comment by gnunn1** [comment]
#1367 related issue to overlay scrollbars.

**Comment by gnunn1** [comment]
I have updated the GAQ with a note about the overlay scrollbars.

https://gnunn1.github.io/tilix-web/faq
