### ISSUE TITLE
Support emoji drag'n'drop into the terminal

### ISSUE THREAD

**Issue by bestouff** [gnunn1/tilix#1205]
In GNOME Terminal I can drag&drop Emojis from the character table, and they are displayed correctly (e.g. "😛") whereas in Tilix I get a Unicode code instead (i.e. "`\U0001f61b`"), in bash and in vim.

**Comment by f2404** [comment]
This shouldn't be the case since both tilix and gnome-terminal are using vte library as backend.
Are you using the same font in tilix and gnome-terminal?

**Comment by bestouff** [comment]
It's the same (default 'Monospaced') for both.

**Comment by f2404** [comment]
What about copying and pasting a symbol?

**Comment by egmontkob** [comment]
I'm afraid drag'n'drop is way more problematic than copy'n'paste, and it's not handled by VTE but the container app. I'm not familiar with the details, but see the mess with MOZ_URL and NETSCAPE_URL and other stuff in [gnome-terminal's terminal_screen_drag_data_received()](https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-screen.c?h=3.26.2#n1757) as well as a former [terminator bug](https://bugs.launchpad.net/terminator/+bug/1518705).

**Comment by bestouff** [comment]
Effectively copy/paste works, but DnD doesn't (not for emojis, not for other Unicode symbols), @egmontkob you're probably right.
FWIW I'm using 1.6.4 under Debian (I'm reluctant to close all my terminals to test the update).

**Comment by gnunn1** [comment]
I'm not seeing what I'm doing differently then gnome-terminal. Testing other terminal emulators I can see that Terminator behaves the same as Tilix whereas xfce4-terminal behaves the same as gnome-terminal. Could be something in the way python/D handles string conversion from C maybe but not sure. I'll have to investigate more.

**Comment by gnunn1** [comment]
Adding the ```UTF8_STRING``` to the drop targets fixes the issue as per the way xfce4-terminal does it.

**Comment by bestouff** [comment]
I confirm, thanks !
