### ISSUE TITLE
Highlight all find results

### ISSUE THREAD

**Issue by elw00d** [gnunn1/tilix#1206]
Hello !

I have tried this terminal emulator and it is very good !

But unfortunately it seems there is not possible to highlight all search results at once.

Would you like to add this feature in next releases ?

**Comment by f2404** [comment]
Unfortunately, the base library (vte) doesn't support this functionality.
There's a similar bug in their bugtracker: https://bugzilla.gnome.org/show_bug.cgi?id=627886

**Comment by gnunn1** [comment]
Tilix uses the VTE widget for terminal emulation so they would need to support this feature. There is already an issue open for this in the gnome bug tracker.
