### ISSUE TITLE
Can't make new terminal tiling window (or entirely new window) to inherit profile / directory

### ISSUE THREAD

**Issue by Nikki1993** [gnunn1/tilix#1208]
Hello,

Got problem with Tilix not inheriting current directory and environment. Got the option under Settings -> Global checked "New window inherits directory and profile from active terminal" but opening a new tiling window or entirely new separate still puts me back at home directory and stuff like nvm reverts to the default configuration. (if I switched to different node version in the previous terminal)

I also checked run the command as login shell as per issue under tilix but nothing.

Running Solus with zsh.

**Comment by gnunn1** [comment]
Does Solus source the vte.sh script? Do you have the same issue with bash?

**Comment by Nikki1993** [comment]
Huh, that's interesting. I just switched to bash (by simply typing bash in the terminal) cd'ed into the directory and it opened zsh session with the **correct** directory. However, opening new session from zsh results in home path. 

@gnunn1 I actually have no idea about vte.sh, at least based on your wiki issue, it's nowhere to be found in /etc/profile.d even profile.d itself doesn't exist.

**Comment by gnunn1** [comment]
In gnome-terminal, does it open a new tab in the same directory as the previous tab rather than the home directory? If no, then that's indicative of an issue where vte.sh isn't sourced.

Unfortunately I done use Solus so I'm not sure where it installs it.

**Comment by Nikki1993** [comment]
@gnunn1 with gnome terminal it's the same as Tilix. Bash works fine and inherits stuff properly. Zsh inherits from bash but then on tilix any new zsh session results in home while in gnome terminal it results in the "last bash -> zsh opened window" if that makes sense. So if I use bash, open new session under /git/projects then zsh session will inherit that path, but if I cd directory up and end up under /git and open new zsh -> zsh window then it will revert back to /git/projects under gnome-terminal BUT under home in Tilix. 

So should I bug Solus devs about vte then?

**Comment by gnunn1** [comment]
I think so I suspect Solus doesn't have zsh setup to source vte.sh properly.

If you find vte.sh on your system, you call always source it manually in an appropriate spot for zsh.

**Comment by Nikki1993** [comment]
I will try to contact upstream and see, meanwhile I ran `find ~/ -type f -name "vte.sh"` and it didn't return anything o_O I recon that can't be the case or what would be the better command to run the search and see if / where vte.sh is?

**Comment by Nikki1993** [comment]
Abort, found it under `/usr/share/defaults/etc/profile.d/vte.sh`

**Comment by Nikki1993** [comment]
Alright, got it fixed by sourcing the path above :) thanks a lot @gnunn1

**Comment by Nikki1993** [comment]
Actually, one last thing @gnunn1 if you don't mind, should this sourcing also inherit stuff like nvm? So if I set nvm to use node 6 in one terminal window, should it inherit?

**Comment by gnunn1** [comment]
Nothing is inherited, all tilix is doing is setting the CWD to be the same as the previous tab. It has no impact on nvm or other programs.
