### ISSUE TITLE
toggle window visibility

### ISSUE THREAD

**Issue by iruindegi** [gnunn1/tilix#1209]
Hello,

I'm comming from Terminator emulator and there is a shorckut witch I used a lot is call:
hide_window => toggle window visibility witch I assigned to Ctrl + º

With this shorcut, if I'm for example browsing the internet with chrome for example, and I hit Ctrl + º the terminal appears, and if I hit again it dissapears. I can do this all around my system.

Is there any way to tho this with tilix? I didn't see this functionality on preferences...

**Comment by gnunn1** [comment]
You can use quake mode for this, see https://gnunn1.github.io/tilix-web/manual/quake/
