### ISSUE TITLE
In Quake mode, Add a option to set whether it is always top

### ISSUE THREAD

**Issue by NanerLee** [gnunn1/tilix#1211]
Although most people like the terminal is always top, I thinks it should give people more choices.

So I think it should add a option to let people select what they like

**Comment by gnunn1** [comment]
I don't think I'm going to implement this, the whole point of a quake window, at least to me, is to be a top-level window. I already have too many options in tilix and I just don't this as one as being important enough to add, sorry.

**Comment by ionyx0** [comment]
I'd like to second this as an option anyway.  Most other quake-style CLIs allow this.  If the option is developed and pull requested, would you be open to peer review and approving?

**Comment by trialism** [comment]
The lack of this breaks terminal workflows which are not focus-oriented and utilize external GUI popups.

**Comment by heyakyra** [comment]
Tilix could replace devilspie2, guake, and yakuake with this feature. :pray: It feels incomplete #1301 #1421 if there's no way to have Tilix stay open behind the current workspace behind all other windows. 

Is there some other way to use tilix terminal as background for the gnome desktop? :crossed_fingers:
