### ISSUE TITLE
Force use of source build?

### ISSUE THREAD

**Issue by pat-s** [gnunn1/tilix#1213]
Hey there,

I just built 1.7.1 from source on 16.04 and while `tilix --version` shows
```

tilix --version
Versions
	Tilix version: 1.7.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

looking at the "About" menu in the application still says 1.6.4.
Furthermore, the tab option is missing so I assume that I still have the settings of 1.6.4

I uninstalled 1.6.4 using my package manager and now I am bit confused where the problem might be.

I did

```
dub build --build=release
./install.sh
```
using `dmd` as the compiler.

**Comment by egmontkob** [comment]
Maybe the old one is still running, and hence the "tilix" command asks that to open a new window?

**Comment by pat-s** [comment]
Rebooting solved the problem :+1:
