### ISSUE TITLE
Crash on deleting the only profile

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/tilix#1214]
Open Preferences, select the only profile that's defined, click on the "-" symbol down there to delete it. Tilix segfaults.

Expected: probably the "-" symbol should be inactive if there's only one profile defined (but this still raises the question which profile should be the default if you delete the default, so instead, maybe the button should be inactive in the default profile is selected).

Sorry if it's already been fixed, I'm on 1.6.4 (because I cannot compile newer ones on Artful)

**Comment by gnunn1** [comment]
It's already been fixed
