### ISSUE TITLE
feature suggestion: warn on pasting many lines

### ISSUE THREAD

**Issue by robclark** [gnunn1/tilix#1215]
similar to the way tilix warns if you paste things that include "sudo"..  user usually doesn't want to paste 800 lines into terminal so that is probably an accident (ie. ctrl-c'd in other terminal instead of ctrl-shift-c so you still have old clipboard)..

might be a good idea to have a way to warn if user is trying to paste more than N lines into terminal (perhaps configurable, but reasonable default would be ~4)

**Comment by gnunn1** [comment]
Thanks for the suggestion but I think I'll have to disagree. If I'm using an editor like vi or nano in the terminal it's not unusual to want to paste in a lot of lines. I think this would be an unnecessary limitation for limited safety benefits.

**Comment by robclark** [comment]
hmm, I thought you somehow differentiated between shell / cmdprompt and app?  If that is possible somehow it would be reasonable to have size checks (and things like sudo checks) only for shell prompt..

**Comment by f2404** [comment]
@robclark No, it isn't possible for a terminal app to reliably detect whether it has a shell or a client app running.

**Comment by robclark** [comment]
oh, that is unfortunate..  well, it would have been a nice idea to prevent unintended pastes of random/unintended stuff into shell prompt, but oh well
