### ISSUE TITLE
feature suggestion: color copy

### ISSUE THREAD

**Issue by robclark** [gnunn1/tilix#1216]
sometimes it would be nice to cut/paste terminal contents that have ansii escape sequences for color into other editor to annotate w/ comments..  it would be nice to do that without loosing the color.

Maybe there is a way to ctrl-c but translate the escape sequences into rtf so it could be paste into an rtf aware editor??

**Comment by robclark** [comment]
(as an aside, I'm super-happy with tilex.. it is everything that gnome-terminal *should* have been.. this and last issue where just random ideas I had to make it even more awesome..)

**Comment by egmontkob** [comment]
VTE 0.50 added the possibility to copy in HTML rather than plain text (and by the way, correspondingly gnome-terminal 3.26 also added an Edit -> Copy in HTML menu entry).

**Comment by gnunn1** [comment]
Thanks @egmontkob, I had not realized that html copy had been added. I'll add support for it in tilix.
