### ISSUE TITLE
Perprofile window appearance

### ISSUE THREAD

**Issue by arashm** [gnunn1/tilix#1218]
I like the Quake mode to be borderless but the regular windows to have it's own preference. Right now if I change options in Quake window to be borderless, it will affect all windows.

It could be great that if the "Appearance" options were part of the profile, so we could set them with `-p` or we had a `--broderless` cli option.

**Comment by gnunn1** [comment]
It can't be in the profile since profiles are per terminal and not per window. There is already a command line option, ```--window-style=WINDOW_STYLE```, that supports this so hopefully that is sufficient for your needs.
