### ISSUE TITLE
Options menu doesn't scroll when windows are resized to "small"

### ISSUE THREAD

**Issue by PombaM** [gnunn1/tilix#1220]
# Normal window
![normal_window](https://user-images.githubusercontent.com/11157420/33815616-dd9c559a-de5a-11e7-9af4-f8f3de258b14.png)

# Resized window
![resized_window](https://user-images.githubusercontent.com/11157420/33815618-e353d8c8-de5a-11e7-9084-31920e1cd450.png)

As you can see in the given screenshots when you right click mouse, the menu pops up and stays inside the window which is how it should work but it also prevents user from using other options.

My suggestions is to make the "options menu" always scrollable or whenever it detects itself as resized. But I think the former would be easier to implement. 

Thanks anyways!

**Comment by gnunn1** [comment]
Yes, it is an issue with popovers and X11 where the popover cannot extend past the edge of the window. I do not have any plans to fix it by reverting to popup menus instead of popovers.
