### ISSUE TITLE
Add keyboard shortcut to open terminal menu

### ISSUE THREAD

**Issue by sogalboogalsky** [gnunn1/tilix#1221]
This is just an enhancement request.
I use keyboard shortcuts a lot in Tilix and I think that it would be very handy to have a shortcut that opens the terminal menu (the one that contains Find, Read only, Helpers, Profiles, Other).
With such a shortcut it would be possible to navigate in subsections with arrow keys so that one does not have to use the mouse to access these functionalities.
Thanks.

**Comment by gnunn1** [comment]
All of those items can be accessed through individual shortcuts, I do not plan on adding one for the menu itself.
