### ISSUE TITLE
Open saved session in current window

### ISSUE THREAD

**Issue by fsateler** [gnunn1/tilix#1222]
Hi,

First of all, thanks for this awesome terminal emulator.

I think this is a feature request. I want to open a saved session as a new session in the current window, via the command line. Unfortunately that does not seem to be possible. `tilix -s $session` opens up a new window, and `tilix -a app-new-session -s $session` ignores the given session and starts a new one. It would be great if the last rune could open the given session in the current window.

Thanks

**Comment by gnunn1** [comment]
You can achieve this by changing the "On New Instance" option in the Preferences | Global page to Session rather than Window. Hopefully this does what you are looking for.

**Comment by fsateler** [comment]
Thanks, that worked.
