### ISSUE TITLE
Text does not wrap to the correct line when entering a command.

### ISSUE THREAD

**Issue by Nolan-O** [gnunn1/tilix#1223]
I compiled tilix from the master branch a few days ago, using xfce4 on arch linux. When I'm typing a command and it runs into the side of the terminal, text wraps around to the current line instead of the next one. However, additional wraps later in the command do wrap to the next line. ![Like so](https://user-images.githubusercontent.com/10750189/34060841-86fda91c-e1b3-11e7-8034-7b39f0ec099c.png)

**Comment by gnunn1** [comment]
In Appearances if you disable the overlay scrollbar option and restart tilix does it fix this issue?

**Comment by Nolan-O** [comment]
Nope =\

**Comment by gnunn1** [comment]
Does it happen on xfce4-terminal or gnome-terminal?

**Comment by Nolan-O** [comment]
Oh, it does. I didn't notice that before.

**Comment by gnunn1** [comment]
That means it's a bug with the VTE widget which provides the terminal emulation for all three terminals. I'll have a look in the morning to see if there is an existing bug report for this in the gnome bugzilla.

**Comment by egmontkob** [comment]
The bash prompt `PS1` needs to enclose nonprintable characters (e.g. color-changing ANSI escape sequences) between `\[` and `\]`. What you describe is a typical symptom of omitting these characters.

**Comment by Nolan-O** [comment]
Yep, that was it. Thank you!

**Comment by gnunn1** [comment]
Thanks @egmontkob
