### ISSUE TITLE
fork each window in a new process

### ISSUE THREAD

**Issue by mosajjal** [gnunn1/tilix#1224]
Is there an option for having a new PID with each window tilix opens? I work with large files and sometimes copying a huge text may crash the terminal. I'd like to have my other terminals open when it happens. 

thanks

**Comment by gnunn1** [comment]
Leveraging the GtkApplication single instance model requires a single process, I do not have any plans to start supporting the forking of processes as it would be a major architectural change involving loads of work.

There is a switch, ```--new-process```, that does so this however it is only intended for debugging purposes and many features like dragging terminals between windows, new instance options, etc, will not work with this switch. I will not accept bug reports relating to the usage of this switch either.
