### ISSUE TITLE
open in tilix not working

### ISSUE THREAD

**Issue by rudrab** [gnunn1/tilix#1231]
It was working fine, but suddenly i found then in nautilus, open in tilix is not appearing.
I am in f27.
$rpm -qa|\grep tilix
tilix-1.7.3-1.fc27.x86_64
tilix-nautilus-1.7.3-1.fc27.x86_64
$rpm -q nautilus
nautilus-3.26.2-1.fc27.x86_64

**Comment by bil-elmoussaoui** [comment]
Can you close nautilus using `nautilus -q` and then reopen it in the terminal and click on open in tilix; and copy/paste the output you got on the terminal please?

**Comment by rudrab** [comment]
nautilus
Initializing nautilus-dropbox 2015.10.28
ImportError: could not import gobject (error was: 'No module named gi._gobject')

(nautilus:3592): Nautilus-Python-WARNING **: pygobject initialization failed

(nautilus:3592): Nautilus-Python-WARNING **: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/home/rudra/.local/share/nautilus-python/extensions/nautilus-send-mconnect.py", line 11, in <module>
ImportError: No module named gi

**Comment by rudrab** [comment]
in a more cleaner system, with mconnect removed, I got this:
```
 nautilus
Initializing nautilus-dropbox 2015.10.28
ImportError: could not import gobject (error was: 'No module named gi._gobject')

(nautilus:2522): Nautilus-Python-WARNING **: pygobject initialization failed

(nautilus:2522): Nautilus-Python-WARNING **: nautilus_python_init_python failed
```

**Comment by bil-elmoussaoui** [comment]
You need to install python-gobject. Otherwise python extensions won't work for Nautilus. 

@gnunn1 This should be added to the list of the dependencies otherwise it won't work. Normally it should be added to `nautilus-python` dependencies list........

**Comment by rudrab** [comment]
Actually I have solved it, and it is what you said. 
For the rpm, the `python2-nautilus` should be added as dep.

**Comment by bil-elmoussaoui** [comment]
Well, @gnunn1 doesn't manage any packaging at all. You should contact the fedora packager of Tilix. This can be closed

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui
