### ISSUE TITLE
Scrolling with touchscreen too fast

### ISSUE THREAD

**Issue by flipflop97** [gnunn1/tilix#1232]
When scrolling through the terminal output using my touchscreen the content scrolls way faster than my finger moves. Moving about one pixel scrolls one whole line in the terminal output. Happens with both Xorg and Wayland.

Tilix 1.7.3
Gnome 3.26.2
Arch Linux

**Comment by egmontkob** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=769696. (Neither of the two active VTE maintainers have touchscreen device so we'd need someone to contribute a fix.)

**Comment by gnunn1** [comment]
As @egmontkob notes this is an issue with VTE and not Tilix specific.
