### ISSUE TITLE
FYI: New APIs in VTE 0.52

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/tilix#1233]
FYI: VTE 0.52 (to be released in March 2018) adds 3 new functionalities and their corresponding APIs (already present in git). It's up to you whether you want to hook up and make config options for them.

Hopefully Ubuntu Bionic 18.04 LTS is going to ship VTE 0.52. If you care about this distro and would like your app to offer these features in this long term support release, you should probably release a new version of your app in time which (conditionally to this VTE version) enables these features.

- `vte_terminal_{get,set}_cell_{height,width}_scale`: Increased line spacing and character spacing mostly for accessibility for people with imperfect sight.

- `vte_terminal_{get,set}_bold_is_bright`: Whether escape sequences such as `\e[1;35m` switch to bright colors in addition to bold (legacy behavior) or switch to bold and leave the color intact (new behavior, required for solarized, base16 and similar modern color schemes). (And while at it, we've removed "Allow bold text" from `gnome-terminal`'s UI, and will probably start deprecating its API in about a year. I see no sane reason for this option to exist.)

- `vte_terminal_{get,set}_text_blink_mode`: VTE now implements blinking text (`\e[5m`) and enables it by default, this option lets you disable it or make it conditional to the terminal being (un)focused.

Please refer to VTE's source tree for details, e.g. compile with `--enable-gtk-doc` and check the generated docs under `doc/reference/html/index.html`.

**Comment by gnunn1** [comment]
Thanks, I'll look into it.

**Comment by gnunn1** [comment]
Done but note these will not be available until GtkD updates for VTE 0.52. Right now changes are protected behind a static if flag in constants.d.

**Comment by egmontkob** [comment]
Bummer. (Does GtkD really need to update something, like, err, "manually"? By the developers, or how? Isn't it automatic once it's built against a new VTE? Sounds weird to me.)

**Comment by gnunn1** [comment]
GtkD as a wrapper is generated using gir files, so until 0.52 gets released with the updated gir files it won't get updated unless the GtkD maintainer decides to re-build against the pre-release versions. In order for him to do that and test things, he would need to be running a pre-release version of Gnome which probably isn't straight forward for him.

Frankly I'm not too concerned about meeting Ubuntu's release windows as it's impossible for me to track all of the distro schedules. I prefer to leave that to the packagers and just concentrate on the code which is what I enjoy doing.

**Comment by egmontkob** [comment]
> GtkD as a wrapper is generated using gir files

I thought it was automatically generated during package build. That is, if a distribution (e.g. Ubuntu) recompiled their GtkD package against a newer VTE, it would automatically pick up all the new APIs (without GtkD's maintainer having to perform some magic and release a new version).

> Frankly I'm not too concerned about meeting Ubuntu's release windows

Okay then :)

**Comment by egmontkob** [comment]
FYI: vte-0.56 / gnome-terminal 3.32 (March 2019) will flip the default of "bold is bright" to false.

It's of course entirely up to you whether you follow us or not.
