### ISSUE TITLE
Don't core dump if a settings schema key is not found.

### ISSUE THREAD

**Issue by ghuls** [gnunn1/tilix#1234]
After updating tilix from 1.7.1 to 1.7.3, I get this error when I try to start tilix:

```
(tilix:13214): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Tilix.Keybindings' does not contain a key named 'terminal-copy-as-html'
Trace/breakpoint trap (core dumped)
```

I think I had a similar error in the past after another update of tilix (core dump when a certain settings key didn't exist). It would be nice if tilix would try to create missing keys, instead of crashing.

**Comment by phw** [comment]
There is nothing to "re-create" here, errors like this usually imply that the gsettings schema was not installed properly. So this is an installation / packaging error.

A typical cause for this is that the schema was installed, but not compiled after installation. Try running:

    glib-compile-schemas /usr/share/glib-2.0/schemas/

If you installed to `/usr/local` use `/usr/local/share/glib-2.0/schemas/` instead.

How did you install Tilix? If you use distribution packages the package management should usually take care of this, if not report it as a packaging issue. If you install from source the `install.sh` should take care of this.

**Comment by gnunn1** [comment]
What @phw stated is accurate, you need to have the matching schema file for the application as there is a 1:1 correspondence between the two. As he noted, typically this is automatically taken care of by either the packagers or the ```install.sh``` script when installing manually.

**Comment by ghuls** [comment]
@phw 
Thanks for the compile schema command. I am able to start Tilix now.

I used tilix.zip from the release page.
It would be nice to add "installation" instructions when using this zip file.

**Comment by bil-elmoussaoui** [comment]
@ghuls It's already mentionned on the website
https://gnunn1.github.io/tilix-web/#packages
See the Manual Installation tab
