### ISSUE TITLE
Feature request: Add an option for synchronized input password/bookmarks

### ISSUE THREAD

**Issue by gileshuang** [gnunn1/tilix#1236]
When synchronized input mode enabled, the old version of tilix, password and bookmarks in "Assistants" will send to all of synchronized terminal. This is useful when I have the same password or have the same command to run in different ssh session.

But in the new version, "password" and "bookmarks" will only send to the current terminal. I known that there are some reason for the change, so I will not call for rollback to the old behavior.

What I want to say is that, could there be a switch for choose what behavior to do: send password / bookmarks to all synchronized terminal, or just send to current terminal?

**Comment by gnunn1** [comment]
Yeah that should work, I'll have a look at it.

**Comment by gileshuang** [comment]
Thanks for your work.
