### ISSUE TITLE
Quake window width

### ISSUE THREAD

**Issue by gersonjferreira** [gnunn1/tilix#1238]
Previously it was possible to adjust the window width and height in quake mode, but not my Tilix Preferences shows only the height option. Why is that? Please put back the width control.

![image](https://user-images.githubusercontent.com/5455489/34610257-72eb7df0-f207-11e7-8f71-0f9c49cd2186.png)

I'm using Manjaro Linux with Gnome + Wayland, dual monitor.

**Comment by gnunn1** [comment]
It's because it doesn't work under Wayland and there is no way AFAIK to make it work. If you use it in X11 you'll see the option is available.
