### ISSUE TITLE
Ubuntu PPA is behind

### ISSUE THREAD

**Issue by qazip** [gnunn1/tilix#1239]
Hello,

According to your site (https://gnunn1.github.io/tilix-web/), there's a ppa (by web8pd) but it seems like the most recent version available from there is 1.6.4, which is severely behind.

Do you know why that is? I'd like to install tilix via PPA and I need the 1.7.x because I want tabs..

**Comment by gnunn1** [comment]
Unfortunately I do not manage packaging so you would need to inquire with the web8pd folks in terms of status.

**Comment by qazip** [comment]
Yes, I'm aware of that. I thought that perhaps you had a way to contact them. Guess not. Thanks anyway.

**Comment by qazip** [comment]
@hotice
