### ISSUE TITLE
Profile not working on quake mode

### ISSUE THREAD

**Issue by dattn** [gnunn1/tilix#1242]
When starting tilix in quake mode the "--profile" argument gets ignored.

`tilix -q --profile="Quake"`

Is there an other way to start tilix in quake mode with a specific profile ?

**Comment by gnunn1** [comment]
It's working fine for me on master, what version of tilix are you using?

**Comment by dattn** [comment]
I use the following version on an Ubuntu 17.10
```
tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.25

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

Without the "-q" modifier the correct profile gets loaded.

**Comment by gnunn1** [comment]
There was a big in previous versions with regards to this but it has been fixed for awhile now, please update to a current version and try it there.

**Comment by dattn** [comment]
Ok, I will then wait until the tilix package gets updated in the Repo.
`https://launchpad.net/~webupd8team/+archive/ubuntu/terminix`

I don't like building tilix myself.

**Comment by eramm** [comment]
Was this issue fixed ? I am experiencing the same thing on Linux Mint 19

> Versions
> 	Tilix version: 1.7.7
> 	VTE version: 0.52
> 	GTK Version: 3.22.30
> 
> Tilix Special Features
> 	Notifications enabled=0
> 	Triggers enabled=0
> 	Badges enabled=0
