### ISSUE TITLE
Doesn't compile on Ubuntu: /usr/bin/ld: final link failed: Nonrepresentable section on output

### ISSUE THREAD

**Issue by snitko** [gnunn1/tilix#1245]
```
### (similar kind of errors above, lots of them)
/usr/bin/ld: /home/roman/dlang/dmd-2.071.1/linux/bin64/../lib64/libphobos2.a(conv_320_6ae.o): relocation R_X86_64_32 against symbol `__dmd_personality_v0' can not be used when making a shared object; recompile with -fPIC

collect2: error: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.

```
Ubuntu version: 17.04
DUB version 1.0.0, built on Jun 20 2016
Tilix version: latest master, 1.7.3 I assume.

**Comment by gnunn1** [comment]
This seems related to -fPIC, You can try updating ```etc/dmd.conf``` to include the ```-fPIC``` switch. If that doesn't work, try updating to a new version of DMD.

**Comment by snitko** [comment]
Updating dmd from v2.0.71 to v2.078.0 worked. Thank you.
