### ISSUE TITLE
kbd navigation: easy to delete profile

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/tilix#1246]
1.6.4, sorry if it's no longer relevant.

Open Preferences, and press TAB a couple of times, until the triangle of a (deletable) profile is focused.

Press Enter. The popover menu opens.

Press Enter again. The default action, which is the topmost menu entry, namely "Delete" is activated.

A destructive operation without confirmation shouldn't be the popover's default widget.

**Comment by gnunn1** [comment]
Thanks, I'll have a look.

**Comment by egmontkob** [comment]
FYI: I'm using Ubuntu's default theme Ambiance where this problem is [even worse](https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1742269).

**Comment by gnunn1** [comment]
Everything is worse in Ambiance in my experience :)
