### ISSUE TITLE
As user of ubuntu 16.04.

### ISSUE THREAD

**Issue by EmTee70** [gnunn1/tilix#1248]
The update via https://gnunn1.github.io/tilix-web/
>  Tilix is available for Ubuntu thanks to the WebUpd8 team and their PPA: WebUpd8
is relatively outdated, see below
Which alternative installation do you recommend?

```
> ls -l $(which tilix)
-rwxr-xr-x 1 root root 2866400 Aug  2 11:56 /usr/bin/tilix 
> tilix --version
Versionen
	Tilix-Version:  1.6.4
	VTE-Version: 0.42
	GTK-Version: 3.18.9

```

**Comment by gnunn1** [comment]
I'm not aware of other PPA's, however if someone is maintaining a more up to date one then I am happy to update the docs to reflect that. As mentioned previously though I don't do packaging and I have no desire to take that on.

**Comment by qazip** [comment]
I had already created a similar issue: https://github.com/gnunn1/tilix/issues/1239

I even tag the guy from WebUpd8 there, but he has not answered yet. A friend of mine also sent him an email (weeks ago?) but he did not answer either. I suggest you remove the PPA from the site @gnunn1

**Comment by EmTee70** [comment]
> I suggest you remove the PPA from the site @gnunn1

Seems to be the right thing todo!

**Comment by gnunn1** [comment]
I've updated the web page.

**Comment by meddario** [comment]
The WebUpd8 PPA seems updated now, I just got Tilix 1.7.5
