### ISSUE TITLE
open Tilix here 2 times

### ISSUE THREAD

**Issue by tgorzka** [gnunn1/tilix#1250]
morning,

in nautilus is "open Tilix here" is double

![b1](https://user-images.githubusercontent.com/28889569/34759982-305a74f2-f5de-11e7-997b-585691106990.png)

I use Arch Linux Nautilus 3.26

**Comment by phw** [comment]
I can reproduce this, looks like the extension is loaded twice. It worked a short time ago.

As a quick test I copied the extension also to `$HOME/.local/share/nautilus-python/extensions/`, and then the menu entry appears thrice. So it seems the extension itself is doing the right thing (adding a single entry) but for some reason it is loaded twice. But I could not locate it anywhere except in `/usr/share/nautilus-python/extensions/`

 Check `/usr/share/nautilus-python/extensions/`, `/usr/local/share/nautilus-python/extensions/` and `$HOME/.local/share/nautilus-python/extensions/` whether there is the file `open-tilix.py`. It should only be in once place.

**Comment by gnunn1** [comment]
Not sure what is going on with this, but can confirm has well. However I don't think it's a tilix issue, the insync nautilus plugin I use as the same issue.

**Comment by bil-elmoussaoui** [comment]
If you add a `print(items)` here https://github.com/gnunn1/tilix/blob/master/data/nautilus/open-tilix.py#L137
You will see that the function is called twice. It must be somehow an upstream issue as I didn't have this before :(

**Comment by brittyazel** [comment]
Yes I can confirm on Archlinux that I see it twice as well. Also, this plugin doesn't seem to work with python-nautilus, but still the older python2-nautilus, and they are in conflict. Not a big deal

**Comment by bil-elmoussaoui** [comment]
@brittyazel I have already fixed the python-nautilus issue. Should work perfectly with the next version

**Comment by bil-elmoussaoui** [comment]
This patch fixed the issue on Archlinux. https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/nautilus-python&id=f33eabbbda9a4e7528d42a02993c5fa755ff6e80
This can be closed

**Comment by phw** [comment]
Yes, I can confirm this works again. No Tilix issue anyway.

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui
