### ISSUE TITLE
Tilix crash since upgrade to Fedora 27

### ISSUE THREAD

**Issue by sguizard** [gnunn1/tilix#1251]
Hi, 

First i would like to say that tilix is the best terminal that I ever used, so thank you ! 

Yesterday I upgraded my Fedora to 27 (25 -> 26 -> 27) and now I'm experiencing crashes of tilix. 
The crash randomly happen, sometimes after few minutes, sometimes after few hours. 
It always happen with several terminals opened (~ 5) and (I believe) when the input synchronization is activated. 

When the crash occur, I can notice a graphical bug on some terminal. 
![tilix_bug](https://user-images.githubusercontent.com/4322805/34762750-2e1a28ee-f5e9-11e7-8208-1f7e6f672362.png)

When I start tilix from konsole I can grab the next Error message : 
`**
Gtk:ERROR:gtkwidget.c:15926:gtk_widget_unregister_window: assertion failed: (user_data == widget)
fish: Tâche 1284617360, 'tilix' terminée par le signal SIGABRT (Abandon)
`

I'm running KDE (plasma 5.11.4). 

Do you have any idea to fix this bug ? 

Thank in advance !

**Comment by gnunn1** [comment]
It's been fixed in #1228, just haven't had a chance to roll out a new version.

**Comment by sguizard** [comment]
Sorry for the duplicate ! 
Thanks !
