### ISSUE TITLE
Not working with Python3 in Arch

### ISSUE THREAD

**Issue by zgwerby** [gnunn1/tilix#1252]
Using python-nautilus (pointing to python3 and not python2-nautilus, it's different packages) the menu item does not appear.

Running python open-tilix.py from /usr/share/nautilus-python/extensions/ I get the message

`
Traceback (most recent call last):
  File "open-tilix.py", line 8, in <module>
    from urllib import unquote
ImportError: cannot import name 'unquote'
`

**Comment by gnunn1** [comment]
At the moment it's not written for Python 3, please use ```python2-nautilus``` as per the dependencies for Arch Linux.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 I can update the code to work with both python versions it shouldn't be that complicated

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui, I've re-opened the issue.

**Comment by gnunn1** [comment]
@zgwerby Please try the updated version and let me know if it works for you

**Comment by zgwerby** [comment]
@gnunn1 Yes, I've been paste new script - working fine. But I have new problem, like in #1250 issue. And I think it global bug - extensions like nautilus-admin (after fixing by me on my machine, like near pull request), that use python-nautilus bindings have duplicate menu entry too. Sorry for my poor language.
