### ISSUE TITLE
Impossible to select first char on right split

### ISSUE THREAD

**Issue by marcoben73** [gnunn1/tilix#1254]
Hi,
I just started to use Tilix and I find it amazing. Thanks for this great software.

But I found a really annoying problem: on the right split it's impossible to mouse select the first character because the pointer change in "move the split" mode...

![selection first](https://user-images.githubusercontent.com/14200187/34784497-b2ef5ed2-f62e-11e7-8314-6ef3780c0d11.png)

Marco

**Comment by gnunn1** [comment]
It's known issue with the GTK sidebar when you use the thin style, gedit has the same issue when you use the sidepane in it. If it really annoys you, you can turn on the "Use a wide handle for splitter" option in Preferences | Appearance.
