### ISSUE TITLE
Suggestion: avoid accidents when syncronizing inputs with maximized terminal

### ISSUE THREAD

**Issue by diogocalgaro** [gnunn1/tilix#1255]
Just a suggestion to avoid a problem a I just had today. I had a window with 4 open terminals, I maximized one of then and started to remove some files from my home area. A few minutes later, I realized that I pressed unintentionally the shortcut to enable the input syncronize of the terminals. I ran some rm commands on different machines (and different folders). Luckily, I just removed a README file, but the accident could be really bigger. I know it was my fault but it would be really helpful to have some mechanism to prevent this. I don't know, it could be preventing the sync to start from a maximized terminal, or a visual hint that the sync is on, something like that.

**Comment by bil-elmoussaoui** [comment]
A Gtk.InfoBar could be shown when the terminal is maximized ;)

**Comment by gnunn1** [comment]
It shows the keyboard icon in the terminal titlebar when input synchronization is active, that's the hint that something is happening.

I'll think about other options for a few days, one might be to automatically disable input sync when you maximize a terminal with a message. @bil-elmoussaoui suggestion about an infobar showing when input sync is on and the terminal is maximized is another possibility.

**Comment by diogocalgaro** [comment]
I'm using KDE, I didn't noticed any keyboard icon :(

**Comment by gnunn1** [comment]
![screenshot from 2018-01-10 18-57-22](https://user-images.githubusercontent.com/9358238/34801748-4da525c0-f638-11e7-8cce-61412be20135.png)

**Comment by diogocalgaro** [comment]
Here is how it looks like in Fedora 27 with Plasma 5.11 with input syncronized:
![screenshot_20180111_081855](https://user-images.githubusercontent.com/8246699/34820631-3d8c4e32-f6a8-11e7-9857-0789909ec80a.png)

**Comment by diogocalgaro** [comment]
Oh, now I see. I changed the appearance of the terminal's title style to "nothing". In this case it doesn't show the icon. I think I will change it back :-P

**Comment by AsharLohmar** [comment]
I had a similar event, and even thou in my case I have the "little tittlebar" visible and the keyboard icon present that didn't meant that I've also looked at it /acknowledged it in any way :D.
So, how about "feature request" ?
An option that could help us, the more "absent-minded" users, a checkbox in the preferences to disable input synchronization when one of terminals gets maximized. You could even signal it by drawing the keyboard icon with a "red crossed out circle".

**Comment by bilbonotry** [comment]
Hello. 
My 2 cents : input synchronization _should_ be paused when maximizing a pane. 
Why ? Because the purpose of input synchronization is to work on multiple similar servers, but you maximize a pane when you want to do something on one specific server.
Moreover this the behaviour of concurrent screen and tmux.
Regards.

**Comment by gnunn1** [comment]
There is a new status variable you can add to the title to tell you if input synchronization is on but you've hidden the titlebar. I think that's about as far as I want to go with this.
