### ISSUE TITLE
bring window to background with middle mouse click

### ISSUE THREAD

**Issue by mabod** [gnunn1/tilix#1258]
Hi,

I tried out tilix. I wanted to use it in favor of terminator. But the tilix title bar is not behaving as most other apps. I am using cinnamon desktop. With that I can click the title bar of an app with the middle mouse button and the app goes to the background. This is an important use case for me. And it is not working with tilix. Why is that?

**Comment by gnunn1** [comment]
If I had to guess, I'd say it because Cinnamon applications do not use a headerbar. I would suggest configuring Tilix to do the same, in Preferences|Appearance set the ```Window Style``` to ```Disable CSD``` and re-start it. Does that fix the issue?

**Comment by mabod** [comment]
The solution is setting `gtk-titlebar-middle-click=lower` in `$HOME/.config/gtk-3.0/settings.ini`

https://forum.manjaro.org/t/pamac-titlebar-behaviour-ignoring-middle-click/38459

**Comment by gnunn1** [comment]
Thanks for the update, closing issue.
