### ISSUE TITLE
Allow settings to come from config file

### ISSUE THREAD

**Issue by rightaway** [gnunn1/tilix#1260]
Rather than needing to import and export settings, it would be good to have a settings file that tilix will read on startup. This is useful for provisioning systems so tilix looks and behaves the same way based on a config file. So someone installing tilix could restore the config file, install tilix, and everything would be running exactly as expected.

**Comment by gnunn1** [comment]
Sorry but no plans to do this, maintaining two different ways of managing settings is too much work. You can achieve the same effect by importing/exporting from dconf, I just don't see enough value to warrant the effort.

**Comment by rightaway** [comment]
I've tried exporting the theme file but can't seem to import it. I've changed the settings in the json file but how can I get them to reflect in tilix?

**Comment by phw** [comment]
@rightaway You mean color schemes? You just place them in `$HOME/.config/tilis/schemes` and they will be available in Tilix's settings (color scheme in profiles)
