### ISSUE TITLE
New pane gets directory from active pane

### ISSUE THREAD

**Issue by rightaway** [gnunn1/tilix#1261]
There's a setting that a new window inherits directory from active terminal, it would be nice to have a setting where a new pane gets the directory from the active pane. So if I'm in a directory and split the terminal into a vertical pane, the new pane's shell should have an initial working directory of that same directory.

**Comment by gnunn1** [comment]
It does this by default, if it's not for you then you likely do not have ```vte.sh``` configured correctly. See the documentation here:

https://gnunn1.github.io/tilix-web/manual/vteconfig/

**Comment by rightaway** [comment]
Thanks!
