### ISSUE TITLE
Customize WM_NAME from command line

### ISSUE THREAD

**Issue by rightaway** [gnunn1/tilix#1262]
For use with window managers I'd like to be able to customize the `_NET_WM_NAME` or `WM_NAME` for the window so that I can match that string and have the window treated in a certain way, like being moved to a particular workspace or changed to a certain size automatically. In many programs you can do this with a command line flag like `tilix --name "custom"`.

**Comment by gnunn1** [comment]
Try using --class or --name as per below:

```
tilix --help-gtk
Usage:
  tilix [OPTION…]

GTK+ Options
  --class=CLASS                         Program class as used by the window manager
  --name=NAME                           Program name as used by the window manager
  --display=DISPLAY                     X display to use
  --gdk-debug=FLAGS                     GDK debugging flags to set
  --gdk-no-debug=FLAGS                  GDK debugging flags to unset
  --gtk-module=MODULES                  Load additional GTK+ modules
  --g-fatal-warnings                    Make all warnings fatal
  --gtk-debug=FLAGS                     GTK+ debugging flags to set
  --gtk-no-debug=FLAGS                  GTK+ debugging flags to unset
```

**Comment by rightaway** [comment]
Actually does it work for you? If I do `tilix --name=test` and then use `xprop` to see the WM_NAME and _NET_WM_NAME, they aren't set to `test` but instead the application title as configured in settings.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 Maybe it worth adding a page to the documentation on the website about the command line arguments of tilix?

**Comment by phw** [comment]
@rightaway AFAIK not really a bug. WM_NAME is the window name the window manager will use for the window (e.g. for the window decorations, if CSD is disabled). And Tilix sets and changes the title dynamically. So whatever you set here, it will be overridden later.

But why don't you use WM_CLASS? That's actually more what you want to have in your use case: You want certain windows to behave differently, and WM_CLASS is perfectly fine for this.

**Comment by phw** [comment]
@rightaway Another way would be to specify a separate profile in Tilix with the title you want, and then you configure the application title to be `${activeTerminalTitle}`. That way the profile controls the window title.

**Comment by rightaway** [comment]
@phw You're right I should be using WM_CLASS instead. However when I try doing `tilix --class=test` I still get `WM_CLASS(STRING) = "tilix", "Tilix"`, the `test` doesn't appear in the class. That's not expected right?

**Comment by phw** [comment]
@rightaway Works for me. But for this to work Tilix must not be running already, as it will just open a new window window in the current process. You can force to open a new instance by passing the ` --new-process`  parameter, but that's mainly meant for development. You can use it, but must be aware that some things might not work as expected (e.g. you can't drag and drop terminals between different instances).

Not sure whether it should actually apply the WM_CLASS to the new window in case the running instance is reused, and if it should whether GTK or Tilix would be responsible. @gnunn1 Your thoughts?

**Comment by rightaway** [comment]
Shouldn't `WM_CLASS` be settable per window rather than per process, since it's a property of the window itself? Because otherwise it won't be possible to match the various windows in the window manager with different positioning and layouts.

**Comment by gnunn1** [comment]
@phw in gtk when using GtkApplication and it's single process model, it takes care that the cli parameters are sent from the new process to the existing one. So in theory the -class could work.

Having said that, I tend to look at how other applications behave like gedit or Nautilus to determine whether it's possible.

Unfortunately I'm away for work this week with a full schedule so I won't be able to look at this until the weekend.

**Comment by phw** [comment]
There is [`gtk-window-set-wmclassv`](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass). It's documentation says:

```
Don’t use this function. It sets the X Window System “class” and “name” hints for a window. According to the ICCCM, you should always set these to the same value for all windows in an application, [...]
```

And nautilus behaves the same as tilix, when initially starting it the `--class` is used, but not for new windows opened.

@rightaway Did you try my second suggestion about using profiles to set the `WM_NAME`?

**Comment by gnunn1** [comment]
Considering this is a GTK feature and that Nautilus works the same way I'm fine concluding this isn't a bug with tilix.

**Comment by untoreh** [comment]
I believe per window settings without new process is offered by `WM_ROLE` which gnome-terminal provides and works while it is not provided by tilix
