### ISSUE TITLE
Broken VTE version check

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/tilix#1264]
VTE version check will be broken whenever vte-1.0 is released.

```
bool checkVTEVersionNumber(uint major, uint minor) {
    return (major > vteMajorVersion || (major == vteMajorVersion && minor <= vteMinorVersion));
                 ^^^ should be <                                         ^^^^ ok
}
```

**Comment by egmontkob** [comment]
(oops, sorry, clicked accidentally)

**Comment by jbicha** [comment]
Are there any plans of a vte 1.0 any time soon?

**Comment by egmontkob** [comment]
Not before you'll upgrade to a fixed Tilix :)

I'm hoping to sync up with gnome-terminal so that vte-1.0 corresponds to gnome-terminal-4.0 whenever that is due. The current version offset is just driving me crazy.

**Comment by egmontkob** [comment]
Nitpicking:

My (and apparently many others') coding style is that I prefer to write comparisons so that the more variable thing goes on the left, and the more fixed thing goes on the right. This feels to more naturally follow human languages and hence the human brain's thinking.

A bit counterintuitively at first, here `vteMajorVersion` feels to be the more variable thing to me, as it differs from user to user, whereas `major` is the more fixed thing, as it's a fixed number at every possible place you call this method from.

So here it's "fixed" vs. "variable"  from user to user that matters to me, rather than from one invocation of this method to another invocation within a Tilix process. At least this is how I feel about it, it's not exact science.

I'm wondering if this might have confused you, too.

So I'd probably write the condition (and rename the function's parameters) like:

    vteMajor > requiredMajor || (vteMajor == requiredMajor && vteMinor >= requiredMinor)

**Comment by gnunn1** [comment]
Thanks, looks right to me. However now I'm wondering why I'm not seeing a bunch of bug reports with regards to issues using older VTE versions? I need to look into this a bit more to be sure before checking in a fix.

**Comment by egmontkob** [comment]
Because you check the minor version correctly, only the major one is swapped, and so far the major version is always 0.
