### ISSUE TITLE
Session switcher removed?

### ISSUE THREAD

**Issue by fboender** [gnunn1/tilix#1267]
Hi Gerald!

First of all, thank you for the amazing tool. Tilix is my favorite terminal emulator by far.

I just upgraded from Tilix 1.6.4 to v1.7.5, and I noticed the Session switcher has been removed? I used to assign a keybinding to it (`win-view-session-switcher`), but that keybinding is now gone. I loved that feature, as it let me switch between sessions very quickly, even with a few dozen sessions open at the same time.

Is there are chance that this feature will be reinstated? Perhaps as a type-to-find search option when the Session sidebar is open? Would you alternatively accept pull requests implementing a similar feature? (I don't know any D, but it doesn't look too complicated).

PS, do you accept donations? Tilix is fantastic, and I wouldn't mind throwing a few bucks your way to thank you for your work.

With kind regards,

Ferry

**Comment by phw** [comment]
I don't know much about this feature and what it did, since I never used it :) But yes, got removed in https://github.com/gnunn1/tilix/issues/1048

**Comment by gnunn1** [comment]
Yes it was removed when tabs were added, it was just getting too complicated with the sidebar, switcher and tabs that something had to give. I didn't feel anyone was using it and even the original author of it hadn't been using it as it was not as useful as he thought it would be.

I do not have any plans to bring it back and I doubt I would accept a PR request to bring it back as it was.

Finally thanks for the kind offer but I do not accept donations.

**Comment by fboender** [comment]
Okay, thanks for the clarification Gerald!

**Comment by y-usuzumi** [comment]
Hell. I'm a heavy user of this feature. After an update I thought I messed my shortcuts up and kept looking for the keybinding option of session switcher for half an hour. Sorry for having to quit Tilix for something else.

**Comment by fboender** [comment]
I've simply downgraded to v1.6.4, which I will stay at. It took a bit of fiddling because the gconf / dconf schema's weren't working anymore after downgrading. To fix this, I did the following:

    cd /home/fboender/Download/
    wget -O tilix-1.6.4.zip https://github.com/gnunn1/tilix/releases/download/1.6.4/tilix.zip
    cd /
    sudo unzip /home/fboender/Download/tilix-1.6.4.zip
    sudo glib-compile-schemas /usr/share/glib-2.0/schemas

After this, Tilix v1.6.4 is usable again.
