### ISSUE TITLE
FR: Make session tabs smaller

### ISSUE THREAD

**Issue by f2404** [gnunn1/tilix#1269]
Similarly to terminal tabs.

**Comment by gnunn1** [comment]
They are the exact same size for me on Adwaita, are you running some custom CSS to reduce the height of terminal tabs in gnome-terminal?

![screenshot from 2018-01-26 00-05-57](https://user-images.githubusercontent.com/9358238/35425925-f3c30d8c-022c-11e8-958a-7995f44f4482.png)

**Comment by f2404** [comment]
This is how it looks for me using Adwaita and "small tabs" style:
![tabs](https://user-images.githubusercontent.com/14939413/35441425-7660c204-0271-11e8-92b9-c2c8ca46121e.png)

**Comment by f2404** [comment]
Same look on a VM running Fedora 27 with Gnome, Adwaita, and tilix 1.7.3.

**Comment by gnunn1** [comment]
@f2404 I'm confused (not unusual!), what are you referring to exactly by "small tabs" style? Is this a setting somewhere?

**Comment by f2404** [comment]
@gnunn1 Oh, I'm sorry. I meant that I have "Terminal title style" set to "small" under Appearance.
There seems to be no configuration for session tabs.

**Comment by gnunn1** [comment]
My misunderstanding, didn't catch on what FR meant. I don't have any plans to implement this, if someone wants smaller tabs they should be able to do it with a custom gtk css file.

**Comment by m-kru** [comment]
@gnunn1 If someone makes PR with making session tabs height configurable (similar to terminal title style) would you accept it?

**Comment by gnunn1** [comment]
No

**Comment by saveriomiroddi** [comment]
If anybody happened to look for the same solution, there's a ready one [here](https://gist.github.com/gregorycollins/f8705521889e65bf4a34d28e4fc5131c#file-00-hacking-tilix-smaller-chrome-md), although it's a bit extreme (I personally replaces `8px` with `12px`, and also increase the padding).

Direct command:

```sh
cat >> ~/.config/gtk-3.0/gtk.css << 'CSS'
decoration.ssd headerbar.titlebar {
    padding-top: 1px;
    padding-bottom: 1px;
    min-height: 0;
}

decoration.ssd headerbar.titlebar button.titlebutton {
    padding-top: 1px;
    padding-bottom: 1px;
    min-height: 0;
}

window.ssd headerbar.titlebar {
    padding-top: 1px;
    padding-bottom: 1px;
    min-height: 0;
}

window.ssd headerbar.titlebar button.titlebutton {
    padding-top: 1px;
    padding-bottom: 1px;
    min-height: 0;
}

.terminal-titlebar {
    min-height: 0;
    margin: 0; padding: 0;
    font-size: 4px;
    line-height: 8px;
}

.terminal-titlebar box {
    margin: 0; padding: 0; border: 0;
    min-height: 0;
}

.terminal-titlebar > button {
    height: 8px !important;
    min-height: 0 !important;
    transform: scale(0.5, 0.5);
    padding: 0; margin: 0; line-height: 0; min-height: 4px;
}

.terminal-titlebar > button image {
    padding: 0; margin: 0;
    -gtk-icon-transform: scale(0.5, 0.5);
}

label.tilix-terminal-title {
    min-height: 0 !important;
    font-size: 8px;
}
label.tilix-terminal-title > * {
    font-size: 8px;
}

notebook.tilix-background header {
    font-size: 8px;
    padding: 0; margin: 0; line-height: 0; min-height: 4px;
    height: 8px;
}
notebook.tilix-background * {
    font-size: 8px;
    padding: 0; margin: 0; line-height: 0; min-height: 4px;
}
CSS
```
