### ISSUE TITLE
Allow synchronized input when toolbar/CSD is hidden

### ISSUE THREAD

**Issue by ukch** [gnunn1/tilix#1271]
I normally run my Tilix with the setting 'Disable CSD/hide toolbar', as I have a small screen and this gives me the maximum amount of usable space. Unfortunately, I can find no way of enabling the 'Synchronize input' option (or any of the other options from the toolbar) in this mode.

What I would expect to see:

* All commands have keyboard shortcuts that are exposed to the user (through the 'shortcuts' screen and possibly also from help-text in the menus)
* There is a way of accessing this menu in this mode (either by right clicking on the title bar, or from the GNOME menu)

**Comment by phw** [comment]
By default there is no keyboard shortcut for synchronize input, but you can easily assign one through the settings.

**Comment by gnunn1** [comment]
As @phw noted, you can assign a shortcut for this in the shortcuts section of Preferences. Specifically it is the ```Session | Synchronize the input```. 

Note to self, remove "the", sounds kind of odd.
