### ISSUE TITLE
Tilix can switch from tabs to sidebar mode by itself

### ISSUE THREAD

**Issue by f2404** [gnunn1/tilix#1272]
Steps to reproduce:
1. Open tilix with "Use tabs instead of sidebar" configuration, add terminal right
2. Click "Find" button
3. Drag the free space on the left of the search input field and drop it outside of the window
4. A new window opens which now has sidebar instead of session tabs.
```
$ tilix -v
Versions
	Tilix version: 1.7.5
	VTE version: 0.44
	GTK Version: 3.20.8

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by alexwhitman** [comment]
I'm able to replicate.
```
$ tilix -v
Versions
	Tilix version: 1.7.6-0.0.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```
