### ISSUE TITLE
Quake mode activates on unset shortcut key.

### ISSUE THREAD

**Issue by alex-vivo** [gnunn1/tilix#1273]
I'm using Gnome on Fedora 27, latest stable version of tilix.

The issue I'm encountering is that after setting the DE's custom shortcut to run 'tilix -q' upon the press of the '`' (grave) key the quake mode gets toggled even by keys that have the grave character at other levels. For example, I have this configuration for one of my keys set in xkb:

``    key <AB06>  { [         k,          K,        grave,    ampersand ] }; 
``

The behavior I used to have in the past on a different version of gnome with the same keyboard layout exactly, was that quake would only get toggled if I pressed the grave key directly (the one to the left of 1 and above Tab) and not if any key that had grave defined at any other level. Thus I was able to utilize the quick accessibility of the grave key, yet not lose the ability to type the character in any other context. At the moment, I'm unable to even simple press the key that is supposed to simply type the letter k, without it also launching Quake mode. I have had to disable the feature for now.

I'm not sure if the behavior started with a new gnome version or tilix, since I just came back to this application again after a break. Please see if the old behavior can be restored. Thank you for this beautiful piece of programming regardless.

**Comment by gnunn1** [comment]
I'm not seeing how this is a tilix issue since as you noted tilix isn't handling the hotkey itself, the DE is. If there is a conflict between the DE and xbd then I would suggest opening a bug for that against the DE. Does that make sense?

**Comment by alex-vivo** [comment]
Yes that does make sense, thank you. I will try to file the bug with Gnome in that case. The issue you referenced above also might be related to whatever change that was made with how Gnome now handles shortcuts which led to the problem I described in this issue.
