### ISSUE TITLE
Webupd8 have an up-to-date uUuntu PPA

### ISSUE THREAD

**Issue by hailwood** [gnunn1/tilix#1274]
Hey @gnunn1,

Love Tilix, Just thought I'd let you know that Ubuntu users can use the Webupd8 PPA which is up to date to install Tilix.

https://launchpad.net/~webupd8team/+archive/ubuntu/terminix

**Comment by gnunn1** [comment]
Bugs and PRs for the web-site should be done against against tilix-web

https://github.com/gnunn1/tilix-web
