### ISSUE TITLE
App icons do not load anywhere (Linux Mint 18 / Kubuntu 16.04.3 LTS)

### ISSUE THREAD

**Issue by kyle-rader** [gnunn1/tilix#1277]
# Description

On Linux Mint 18 (and Kubuntu 16.04.3 LTS) after installing Tilix using the manual unzip method the App icons do not appear in any menu, the task panel, the app switcher, the app itself, ... no where.

Currently I'm in Linux Mint 18.

# Updates

After 
```
sudo apt install shutter
```

The icons show up! I'm guessing there is some common dependency between Tilix and Shutter. 
It would be great to know what that is and have it installed/ more explicitly required by Tilix.

**Comment by kyle-rader** [comment]
Ironically - I installed shutter to take a screenshot of the missing icons.

**Comment by gnunn1** [comment]
The ```install.sh``` script updates the icons on the last line which works fine on Gnome:

```
gtk-update-icon-cache -f ${PREFIX}/share/icons/hicolor/
```

I do not know if Mint requires something different, unfortunately I only support Gnome so will not be spending time investigating this. If someone else wants to look into it and submit a PR I'm happy to accept it.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 As far as I can tell from the issue it must be the launcher who doesn't even show up. 
Can you try reinstalling the application (you should remove the desktop file too $prefix/share/applications/)  Once it's done, reinstall the application and try running `update-desktop-database $prefix/share/applications/` You might need root permissions
