### ISSUE TITLE
tilix-nautilus doesn’t work anymore in Fedora 27

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1278]
Pretty strange… In my older system is works fine since F26, but in two freshly installed F27 VMs, I got no Tilix context menu (whereas gnome-terminal-nautilus works fine when (un)installing).

**Comment by gnunn1** [comment]
At a command line, if you run ```nautilus -q``` to close it and then run ```nautilus``` again, what is the output that is shown?

**Comment by fbruetting** [comment]
Hi Gerald, here’s the output (there’s absolutely no output with this package not installed):
```
$ nautilus
ImportError: could not import gobject (error was: 'No module named gi._gobject')

(nautilus:28062): Nautilus-Python-WARNING **: pygobject initialization failed

(nautilus:28062): Nautilus-Python-WARNING **: nautilus_python_init_python failed
```

**Comment by storm119** [comment]
Tilix depend on python2-nautilus for open "context menu" to works correctly on Nautilus [correct me if I'm wrong]...but prior installing the python2-nautilus, one need to uninstall the python-nautilus (current version conflicting with python2-nautilus atleast it's happen on my box running Manjaro Arch) 

@gnunn1 any chances Tilix will use/integrating with python-nautilus instead of python2-nautilus or make it to work with nautilus-python3 ?

TIA

**Comment by phw** [comment]
> any chances Tilix will use/integrating with python-nautilus instead of python2-nautilus or make it to work with nautilus-python3 ?

Actually it should already work with python3, see https://github.com/gnunn1/tilix/issues/1252 . Which version of Tilix is this?

**Comment by storm119** [comment]
> Actually it should already work with python3, see #1252 . Which version of Tilix is this?

Alrite....my mistake ditched python2-nautilus and rebuild/reinstall Tilix solved my issue...version 1.7.5 btw

**Comment by gnunn1** [comment]
So is this an issue with the waytilix is packaged in COPR or did you install tilix manually?

**Comment by fbruetting** [comment]
I installed it right out of the dnf repo (v1.7.5-1).

**Comment by gnunn1** [comment]
@fbruetting I think you should open a bug report against that then since this sounds like a package issue to me. If that makes sense to you then please link this issue to that when you do so.

**Comment by ykgmfq** [comment]
Works fine for me, cannot reproduce.

```
$ dnf list installed|grep tilix
tilix.x86_64                         1.7.5-1.fc27               @updates        
tilix-nautilus.x86_64                1.7.5-1.fc27               @updates
```

**Comment by cra0zy** [comment]
I was able to reproduce it, but looking at the error it seems like the dependency was not getting installed, to fix it run: `sudo dnf install pygobject3 python3-gobject`

**Comment by gnunn1** [comment]
I'm closing this as it is not a tilix issue but rather a packaging issue.

**Comment by ykgmfq** [comment]
[downstream bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1539039)

**Comment by fbruetting** [comment]
Thanks! Just right now, I was searching for the packager… ^^

**Comment by fbruetting** [comment]
@gnunn1 Will it be possible to ship Tilix via flatpak? I know the sandbox thing won’t work, but still it would be more convenient.

**Comment by gnunn1** [comment]
Yes it is and I think the work is done with respect to fixing the sandbox, it's just a matter of time. If someone wants to volunteer to maintain the flatpak so I don't have to then that would be great.

**Comment by gombosg** [comment]
Still not fixed in Fedora. :(

**Comment by cra0zy** [comment]
`sudo dnf install pygobject3 python3-gobject`

**Comment by gombosg** [comment]
Yes, thanks, I saw it above and fixed for myself already. I mean, the package dependency is not fixed. :)

**Comment by bilelmoussaoui** [comment]
@gombosg  It was reported to Fedora packagers see https://bugzilla.redhat.com/show_bug.cgi?id=1539039
