### ISSUE TITLE
RFE: Hotkey for detaching a terminal in borderless mode?

### ISSUE THREAD

**Issue by larsks** [gnunn1/tilix#1279]
I like to run Tilix in borderless mode, but this means that I am not able to detach a terminal to it's own window (since there's nothing to grab for drag-and-drop).  A simple solution would be a hotkey that would pop the current terminal into a new window.

Does that seem like a reasonable idea?

**Comment by gnunn1** [comment]
Hold the Alt key down and then you can drag the terminal directly, no need for a new hotkey IMHO.

**Comment by Zeioth** [comment]
I use tilix in I3WM where you are supossed to use only your keyboard for everything. I'd also like to have a shortcut to detach a session/terminal.  Thank you.
