### ISSUE TITLE
Low resolution cursor on HiDPI display

### ISSUE THREAD

**Issue by flipflop97** [gnunn1/tilix#1280]
The normal pointer cursor in Tilix on a HiDPI screen is a lower resolution than in other apps, the ibeam/text cursor is fine however. I tried to record a video of it. While this shows the problem there's also an additional cursor lagging behind for some reason (this only appears in the recording).

[![video](https://thumbs.gfycat.com/HastyElasticGrison-size_restricted.gif)](https://gfycat.com/HastyElasticGrison)  
*(click for higher quality)*

```
Versions
	Tilix version: 1.7.5
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
What desktop environment are you using? Do you see the same behavior with something like gedit?

**Comment by flipflop97** [comment]
I'm using Gnome (3.26). And no, I've never seen this behaviour before in any other app, only with Tilix.

**Comment by gnunn1** [comment]
If you use Adwaita as the theme do you see the same behavior?

**Comment by flipflop97** [comment]
Just tested it and yes, it has the exact same behavior when all theme options are set to default.

**Comment by flipflop97** [comment]
The issue seems to only occur on the Gnome Wayland session. I just tested it on the Xorg session and it seems to work perfectly fine there.

**Comment by gnunn1** [comment]
Thanks for the bug report however I don't think this is a tilix issue and I'm not planning on spending any time investigating it further at this point. As a result I am closing the issue has part of cleaning up older issues, feel free to re-open if you disagree and we can discuss.
