### ISSUE TITLE
Add support for sessionName and sessionNumber in Terminal Title

### ISSUE THREAD

**Issue by ramilehti** [gnunn1/tilix#1281]
Some windowmanagers do not show window title except while switching between windows (Alt-Tab). In this case there is no easy way to see which session is active in tilix. 

So please add support for sessionName  and sessionNumber in Terminal Titles. This seems an arbitrary restriction to have.

**Comment by gnunn1** [comment]
Unfortunately for various architecture reasons the terminal knows nothing about the session and I have no plans to change that. An option for you would be to switch to using tabs as you will see the session title in each tab.
