### ISSUE TITLE
Background image folder

### ISSUE THREAD

**Issue by vauvenal5** [gnunn1/tilix#1282]
Hi,
is it somehow possible to provide a background image folder to switch automatically through those images?

**Comment by gnunn1** [comment]
You could write a script that periodically updates the setting in dconf, tilix should recreate automatically and change the image. Tilix stores it's settings in com/gexperts/Tilix and you can see dconf editor to explore the settings. The background image path is stored in ```background-image```.

**Comment by vauvenal5** [comment]
Thx. Leaving this here if someone else is interested in a simple cron script for the job: [tilix-background-image-switcher](https://github.com/vauvenal5/tilix-background-image-switcher)
