### ISSUE TITLE
New Instance Settings Ignored in Budgie

### ISSUE THREAD

**Issue by remlap** [gnunn1/tilix#1283]
Hi on Ubuntu Budgie 17.10 New Instance setting are Ignored and a new window is open.

**Comment by phw** [comment]
To what have you set this value? How do you open a new instance?

**Comment by remlap** [comment]
I have tried every value except new window, I have used ctrl+a+t and launching from budgie menu.

**Comment by remlap** [comment]
I have found one way that is conforming, the open in terminal here within Nautilus

**Comment by gnunn1** [comment]
What version of ```tilix``` are you using? If you run ```tilix``` from gnome-terminal in a command line multiple times does it work as expected?

You could try disabling DbusActivatable in the desktop file to see if that helps as well.

Finally note that I only support the Gnome desktop environment, I don't actively test with other DEs nor will I go out of my way to fix DE specific issues on them. I am of course always happy to accept pull requests from others that may fix those issues.

**Comment by gnunn1** [comment]
No reply from OP and since I don't support other DE I'm closing this issue.
