### ISSUE TITLE
Quake mode takes size from wrong monitor

### ISSUE THREAD

**Issue by ggalmazor** [gnunn1/tilix#1285]
Hi!

I'm on a Debian Buster using Gnome. I have a two monitor setup configured as shown in this picture:

![screen_settings](https://user-images.githubusercontent.com/205913/35724280-705878a2-07fd-11e8-8f66-7ddf549ba250.png)

When I launch Tilix on quake mode, It seems like Tilix is taking size measurements from the first monitor, instead of using the monitor on which it's appearing, like so:

![desktop](https://user-images.githubusercontent.com/205913/35724331-9ecedd3e-07fd-11e8-8976-148896eaae1b.png)

I would expect Tilix to take the size of the monitor where it's being launched on.

**Comment by gnunn1** [comment]
I am not able to reproduce, is this under X11 or Wayland? If Wayland, can you check if it works correctly under X11 as Wayland can be problematic for quake mode.

Also, what are the resolutions of your two monitors?

**Comment by ggalmazor** [comment]
Hi! Just checked that I'm running on Wayland. I'll switch to X11 and try again.

Resolutions are:
- Screen 1 (right): FullHD 1980x1080
- Screen 2 (left): QHD 2560x1440

**Comment by ggalmazor** [comment]
:| I might need some time to get you some feedback on X11... My Debian stalls if I choose to run Gnome on xorg in GDM

**Comment by gnunn1** [comment]
Quake mode is no longer supported in Wayland, see #1314
