### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by simontong** [gnunn1/tilix#1288]
After the most recent update (1.7.5) I'm unable to alter the transparency on the window (see attached image). 

It remains 100% transparent. 

```
Versions
	Tilix version: 1.7.5
	VTE version: 0.51
	GTK Version: 3.22.26
```
![image](https://user-images.githubusercontent.com/1494859/35793840-2a0d1812-0a4b-11e8-8e90-a61726b152f5.png)

**Comment by phw** [comment]
Please see https://github.com/gnunn1/tilix/issues/1257
