### ISSUE TITLE
[ Minor enhancement request ] - Quake mode should actually be a drop-down

### ISSUE THREAD

**Issue by quasipedia** [gnunn1/tilix#1289]
This is a very minor aesthetic/semantics enhancement request.

Instead of having the quake terminal "appear from thin air" it would be neat to have it actually rolling down from the top of the monitor.  As it is, the quake mode really isn't a drop-down but rather a way of toggling the visibility of a window stuck in the upper part of the screen.  Not a big deal, but having just switched from another drop-down terminal, the difference is noticeable and somehow annoying! :)

**Comment by gnunn1** [comment]
It's been asked for before, unfortunately it's not possible on Wayland given you can't control window position. As a result I have no plans for this as I'm trying to minimize working on things that only work on X11.
