### ISSUE TITLE
Quake mode under Wayland: Tilix appears on leftmost, not primary monitor

### ISSUE THREAD

**Issue by dlukes** [gnunn1/tilix#1290]
The [wiki entry concerning Quake mode under Wayland](https://github.com/gnunn1/tilix/wiki/Quake-Mode#wayland) implies that Tilix always appears on the primary monitor under Wayland. However, in my case (Arch Linux, Gnome 3.26.2), it appears on whichever monitor is the **leftmost** in the geometry, irrespective of which one is the primary.

I realize this may be a problem with Wayland which cannot be fixed in Tilix (I've seen #1118, so I have a vague idea that handling multihead is complicated under Wayland), but in that case, I think it might still be a good idea to change the wording in the wiki so that it's clear what behavior to expect :)

**Comment by dlukes** [comment]
Tilix calls `gdk.Screen.getPrimaryMonitor()` to get the monitor number, so the problem is upstream. It looks like in general, GDK is (was?) getting confused about which display is which under Wayland, see <https://bugzilla.redhat.com/show_bug.cgi?id=1386948#c6>.

The actual behavior that I'm seeing after playing with it for a bit is even weirder than indicated in the OP:

- opening Quake mode Tilix for the first time with a Gnome shortcut does what I said above (= Tilix opens on the leftmost monitor, whether it's primary or not); toggling its visibility via the shortcut keeps it on the same monitor
- opening Tilix for the first time via terminal, with the terminal being on the leftmost monitor, results in the same behavior
- opening Tilix for the first time via terminal, with the terminal being **on the other monitor**, results in Tilix appearing **on that monitor**, and when subsequently toggling its visibility via the shortcut, it appears **on whichever monitor has the currently focused window**

**Comment by dlukes** [comment]
In addition to the third point above: the startup animation (Tilix growing out of the center of the monitor) actually still plays out on the leftmost monitor, but after it's done, Tilix switches to the other one.

**Comment by dlukes** [comment]
I've added some logging to `getQuakePosition()` and `screen.getPrimaryMonitor()` always reports 0, irrespective of which monitor I open Tilix from. Also, it's called only on first startup, not when toggling visibility. I guess that explains why the opening animation always plays out on the leftmost screen. So that's one thing, GDK being confused about which monitor is primary under Wayland.

The other thing is that the code which makes Tilix visible when hidden is somehow sensitive to how Tilix was opened and either consistently shows Tilix on the leftmost monitor, or makes it track the monitor with the focused window. I haven't figured out yet what code that is, but it does not run `Screen.getPrimaryMonitor()` (as per grep) and probably also runs on first startup, putting Tilix on the other screen after the opening animation has played on the leftmost one.

**Comment by dlukes** [comment]
I've added some logging to `getQuakePosition()` and `screen.getPrimaryMonitor()` always reports 0, both under X11 and Wayland.

**Comment by dlukes** [comment]
Some more details: the above (Tilix always showing on the leftmost monitor) holds only if Tilix is **started** with `tilix --quake --full-screen` (case 1). If it's started with `tilix --quake` (case 2), then it appears on the monitor where the currently focused window is.

When subsequently toggling visbility of a running Tilix instance, in case 1, it always stays on the leftmost monitor. In case 2, it keeps following the focused window, irrespective of whether it's toggled using just `tilix --quake` or `tilix --quake --full-screen`.

**Comment by gnunn1** [comment]
Under Wayland everything is a crapshoot for quake mode because you can't control window positioning. Right now tilix relies on certain behaviors to get it working but no guarantee that it will continue. As a result I've long considered disabling quake mode in Wayland.

**Comment by dlukes** [comment]
Yeah, I saw #1118 :) I just thought that instead of "Under Wayland, Tilix is hardwired to show up on the primary monitor", the behavior was s/primary/leftmost/. Which I think would have been helpful to amend in the wiki.

But it turns out it's not that simple, the actual behavior is messy and depends on a combination of options ("Under Wayland, if you start Tilix as `tilix --quake --full-screen`, it will keep showing up on the leftmost monitor. But if you start it as `tilix --quake`, etc."). Feel free to close if you don't want to keep this around as a reminder for some reason.

**Comment by luispabon** [comment]
This is not my experience at all, under wayland or X tilix appears on whichever screen has the mouse pointer:

```
~ tilix --version                             747ms  Thu 15 Feb 2018 15:19:55 GMT
Versions
	Tilix version: 1.7.5
	VTE version: 0.48
	GTK Version: 3.22.25

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by dlukes** [comment]
@luispabon I added details in [this comment](https://github.com/gnunn1/tilix/issues/1290#issuecomment-363118173), the issue seems to be more complicated, there's an interaction with `--full-screen` as well.

To reiterate, under X, I see the behavior you're describing if:

1. *Display terminal on active monitor* is ticked under *Quake* preferences.
2. Tilix is opened using `tilix --quake`.

If I open Tilix with `tilix --quake --full-screen`, it will keep showing on the same monitor (it may be either one, probably depending on where Tilix appeared last). I hadn't noticed this before, but it seems like there's a window placement bug on X as well then...?

Under Wayland, the *Display terminal on active monitor* preference doesn't exist (and I assume it's ignored, i.e. it doesn't matter whether you ticked it or not when using the same account from both X and Wayland). Again, if I call Tilix simply as `tilix --quake`, I get the behavior you described; calling it with `tilix --quake --full-screen` results in the leftmost monitor behavior described initially.

Also, when testing a different command line invocation, I made sure to completely exit Tilix so that the first call launches it anew.

**Comment by dlukes** [comment]
Another observation, under X:

1. Setup: Tilix Gnome-assigned shortcut runs just `tilix --quake`, *Display terminal on active monitor* is ticked under *Quake* preferences.
2. First run: Tilix starts, appears on active monitor.
3. Now I can set it to full-screen manually using `F11`.
4. When hidden and reopened, Tilix remains in full-screen mode and indeed appears on the active monitor.

So this works as expected. Contrast this with using the `--full-screen` option in the shortcut instead of going to full-screen manually the first time around, which results in Tilix always appearing on the same monitor, as described above.

**Comment by gnunn1** [comment]
Quake mode is no longer supported in Wayland, see #1314

**Comment by avastmick** [comment]
Damned, this is a shame. I was a heavy user of `tilix --quake`, only just grabbed the update and saw the notification. I understand why you've done this, but, for me it was working well enough for my workflow - fullscreen `vim` with `F10` to drop down a terminal for complex file handling or complex `git` work.

Great terminal emulator though, hope the `wayland` support can be re-introduced at a later date once the technology is more widely used.

**Comment by dzikismigol** [comment]
@avastmick 	if you run `GDK_BACKEND=x11 tilix --quake` it works just fine in some cases, I have this in `/usr/local/tilix-quake` as setting an env var didn't work with plain gnome keybinding
