### ISSUE TITLE
background transparence

### ISSUE THREAD

**Issue by ktrls** [gnunn1/tilix#1291]
Hi, I'm on Manjaro and after the last update my terminal is always transparent, so I can't read anything until I open some application with opposite colours of the font color.

I tried to change percent transparence but it doesn't work.

Any tip?

**Comment by phw** [comment]
Yes, Manjaro messed up their packaging of vte, see https://github.com/gnunn1/tilix/issues/1257

Quick fix is to use tilix-git from AUR.
