### ISSUE TITLE
Tilix opening thousands of file streams

### ISSUE THREAD

**Issue by ukch** [gnunn1/tilix#1295]
I just had this weird error today: I normally run two instances of tilix, one of which is in Quake mode and the other of which is a regular window, often divided up into frames. Today for some reason the Quake-mode terminal suddenly wouldn't go away using the hotkey, and I soon discovered that I was unable to open any Xorg app (I was receiving the error: `cannot open display: :0.0 Maximum number of clients reached`).

In order to try and figure out what was going on, I ran `lsof -U` and saw thousands of entries for `tilix`. I have pasted some of the entries below:
```
$ lsof -U | grep tilix | head -n 15
tilix     10541 ukch    1u  unix 0xffff956084b55c00      0t0  31634 type=STREAM
tilix     10541 ukch    2u  unix 0xffff95607f5dbc00      0t0  31635 type=STREAM
tilix     10541 ukch    3u  unix 0xffff955f2f721c00      0t0 196876 type=STREAM
tilix     10541 ukch    5u  unix 0xffff955f19646000      0t0 196878 type=STREAM
tilix     10541 ukch    8u  unix 0xffff955f0a605c00      0t0 194102 type=STREAM
tilix     10541 ukch   10u  unix 0xffff95607de3fc00      0t0 196880 type=DGRAM
tilix     11116 ukch    1u  unix 0xffff956084b55c00      0t0  31634 type=STREAM
tilix     11116 ukch    2u  unix 0xffff95607f5dbc00      0t0  31635 type=STREAM
tilix     11116 ukch    3u  unix 0xffff955f54d6c000      0t0 194453 type=STREAM
tilix     11116 ukch    5u  unix 0xffff955f60721800      0t0 197410 type=STREAM
tilix     11116 ukch    8u  unix 0xffff955ee0692000      0t0 197412 type=STREAM
tilix     11116 ukch   10u  unix 0xffff955f511dc800      0t0 197413 type=DGRAM
tilix     11446 ukch    1u  unix 0xffff956084b55c00      0t0  31634 type=STREAM
tilix     11446 ukch    2u  unix 0xffff95607f5dbc00      0t0  31635 type=STREAM
tilix     11446 ukch    3u  unix 0xffff95603c619000      0t0 209414 type=STREAM
$ lsof -U | grep tilix | wc -l
1273
```

Upon running `killall tilix` and restarting, my system returned to normal.

If you need more info to debug this issue, please let me know what you need and I will try and provide it if this happens again.

**Comment by ukch** [comment]
```
$ tilix --version
Versions
	Tilix version: 1.7.5
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
Nothing comes to mind as causing this issue. VTE opens a couple of streams per instance to off-load the buffer to disk. There was a memory issue in past instances of tilix around freeing VTE but that should be resolved in 1.7.5. Additionally you shouldn't see thousands unless you've been constantly opening and closing terminals.

If you can reproduce it let me know and I'll think of some things to try.

**Comment by egmontkob** [comment]
The ones that VTE opens don't show up for me in this `lsof` command. Looks like it's more about network streams, like Tilix trying to re-establish connection to the X server, or something similar. Probably not something that Tilix does directly, but done by the X libraries underneath??...

**Comment by ukch** [comment]
Since reporting this, I have noticed it happening quite often (4-5 times per workday). I guess it must have started after I did a system upgrade on Friday.

**Comment by ukch** [comment]
OK, I've looked into this a bit deeper, and it seems that whenever I close and reopen the Quake window (by running `tilix --quake`), the process does not close but remains open and using system resources.

Based on this section of the manpage, ...
```
       -q --quake
              Open a window in quake mode or toggle existing quake mode window visibility.
```
...my assumption about what running `tilix --quake` should do is as follows:

* Is a Quake process already running?
  * No?
    * Open one.
    * Process continues running until closed.
  * Yes?
    * Is the window visible?
      * No?
        * Show it.
      * Yes?
        * Hide it.
    * Current process exits.

The current behaviour of keeping each Quake process open indefinitely seems wrong to me.

**Comment by phw** [comment]
@ukch You said something about you are running two processes. Are you starting the quake window with ` --new-process`? Because doing so results in a similar (and not surprising) result for me.

**Comment by ukch** [comment]
I am starting both instances through keyboard shortcuts. The first shortcut is configured to run `tilix`, which I press only once. The second is configured to run `tilix --quake` and I press it all the time (I am constantly wanting to show and hide the quake-mode window). I tend to use the quake-mode window for whatever I am doing at the present, and the other window for any long-running processes.

As far as I am aware, Tilix is never being invoked using the `--new-process` flag.

**Comment by gnunn1** [comment]
Keeping the process running in quake mode and showing/hiding the window is how it is supposed to work. If it exited the process any long running processes in the terminal would be killed and your scrollback buffer would be gone.

A few questions for you as follows:

What desktop environment are you running this in?

If you show/hide the quake window a few times and then run ```ps -ef | grep tilix``` do you only see one tilix process running? This is the expected result since tilix runs as a single process similar to gedit and Nautilus.

**Comment by ukch** [comment]
@gnunn1 The problem is that every time I show/hide the quake window, it starts another process which never terminates. Sorry if I didn't make that clear in my above post.

In answer to your above questions, I am running Gnome 3.22 on Debian Sid (unstable). Running `ps -ef | grep tilix` returns me over 200 results. Showing and hiding the quake window consistently increases this amount by 2.

**Comment by gnunn1** [comment]
I suspect your issue is the same as #1275, what version of GtkD are you using?

**Comment by ukch** [comment]
3.7.1-1. I will try upgrading and see if that fixes the problem.

**Comment by ukch** [comment]
I can confirm that this issue no longer occurs after upgrade to GtkD 3.7.3.
