### ISSUE TITLE
"Open Tilix Here" in Quake tab

### ISSUE THREAD

**Issue by kwill** [gnunn1/tilix#1297]
**User story:** I use Tilix primarily in Quake mode (aka dropdown mode). When I select "Open Tilix Here" in Nautilus, I want the new terminal to appear as a new tab in the dropdown window (not a new desktop window), so that all my terminal views are in the same place.

**Suggested solution:**

Given dropdown tabs already exist
And dropdown window is hidden
When user selects "Open Tilix Here"
Or hits <kbd>Shift</kbd> + <kbd>Ctrl</kbd> + <kbd>T</kbd>
Then reveal the dropdown window
And create new tab at Nautilus location

(Similarly if dropdown window doesn't exist yet.)

**Comment by gnunn1** [comment]
In Preferences in the General section there is an entry called "On new instance", change the setting to be New Session instead of New Window and it should do what you want.
