### ISSUE TITLE
Binary is available from Solus repos too

### ISSUE THREAD

**Issue by survivor303** [gnunn1/tilix#1299]
Just an update request to website:
Solus OS (https://solus-project.com/) has tilix on its own and official repositories too.
So it is great if website maintainer can add this information under the "Getting Tilix" section.

Tilix can be installed from terminal: eopkg install tilix
or from the gui based software center.

**Comment by gnunn1** [comment]
PR for adding this is welcome at https://github.com/gnunn1/tilix-web

**Comment by gnunn1** [comment]
Added to website.
