### ISSUE TITLE
Tilix background transparent can't be change!

### ISSUE THREAD

**Issue by federicoleandroc** [gnunn1/tilix#1303]
Hello guys, I have a problem with Tilix transparent function, at version 1.7.5, and its can't be change just modify on preferent view, is this a bug or a bad settings?, I have reinstalled but is still doing the same.

**Comment by gnunn1** [comment]
You are probably running vte 0.51, please see #1257. If that's not the issue feel free to re-open.

**Comment by wfpaisa** [comment]
I have the same problem
![screenshot from 2018-02-15 19-41-51](https://user-images.githubusercontent.com/1735752/36288375-56bfed18-1288-11e8-965c-ecef169c9757.png)

**Comment by federicoleandroc** [comment]
I'm checking @gnunn1...

**Comment by federicoleandroc** [comment]
@gnunn1 I have installed tilix-git from AUR and the problem is solved. Thankyou!

**Comment by wfpaisa** [comment]
Versions
	Tilix version: 1.7.5
	VTE version: 0.51
	GTK Version: 3.22.26

works with vte3-tilixy vte-tilix-common
