### ISSUE TITLE
Feature sugestion : selection mode

### ISSUE THREAD

**Issue by Faelian** [gnunn1/tilix#1305]
Hey, thanks for building Tilix. I use it daily at work and I love it !

Nowadays I can do most of my work in terminal with keyboard shortcuts, by still need to grab my mouse to copy a part of an command output.

Wouldn't it be cool, if with a keyboard shortcut, you could move freely the cursor on the terminal to copy text into the clipboard ?

**Comment by gnunn1** [comment]
It would require patching the VTE to support this. Termite, another terminal emulator, supports this by having a custom patch to vte called vte-ng. Unfortunately they and the VTE maintainer do not agree on how to provide this functionality so it will never get into VTE. Until it or another approach gets into VTE I do not have any plans to support this feature.

**Comment by abitrolly** [comment]
Another approach - https://bugzilla.gnome.org/show_bug.cgi?id=78291
