### ISSUE TITLE
Nautilus "open in Tilix" shortcut conflicts with Nautilus' "undo close tab" ("restore tab") shortcut

### ISSUE THREAD

**Issue by smithfred** [gnunn1/tilix#1307]
Self-explanatory really ;)

Edit: result is both things happen if a Nautilus tab was closed in the active Nautilus window.

**Comment by gnunn1** [comment]
Note you can customize it in Tilix in Preferences | Appearance.

**Comment by smithfred** [comment]
Yep but the default shouldn't conflict with an existing Nautilus shortcut.

**Comment by gnunn1** [comment]
Changed to Ctrl-Alt-T

**Comment by smithfred** [comment]
Thanks :)
