### ISSUE TITLE
Nautilus "Open In Tilix" opens SSH (remote) session when in SFTP location

### ISSUE THREAD

**Issue by smithfred** [gnunn1/tilix#1309]
I.e. is does the same as "Open Remote Tilix".

Presumably it should actually open a local terminal to the FUSE mount point of the SFTP location (i.e. something like /var/run/user/1000/gvfs/sftp:host=somehost,user=someuser/some/remote/path)

**Comment by gnunn1** [comment]
Duplicate of #957
