### ISSUE TITLE
Support Arabic text (rtl)

### ISSUE THREAD

**Issue by pupyc** [gnunn1/tilix#1310]
I have noticed this recently while creating folders and switching to them, the Arabic text is not rendered correctly
![screenshot](https://user-images.githubusercontent.com/31791780/36357481-737a1882-14f6-11e8-849d-b19af0a38c86.png)

Here is how it looks like in LibreOffice):
![screenshot1](https://user-images.githubusercontent.com/31791780/36357497-b98648a0-14f6-11e8-8ebf-330159f176ca.png)

I think the solution to this is adding two libraries [`bicon`](https://github.com/behdad/bicon/) and [`FriBiDi`](https://github.com/fribidi/fribidi/)

also I want to point out that most upstream terminal emulators doesn't support this, but it will be nice to have that in tilix!

**Comment by gnunn1** [comment]
The terminal emulation in Tilix is handled by the VTE widget just like in gnome-terminal. It does not support rtl languages though there is a bug report open for it. As a result I'm closing this as an upstream issue.

**Comment by egmontkob** [comment]
VTE 0.57.3 implements BiDi support (according to [this proposal](https://terminal-wg.pages.freedesktop.org/bidi/)).
