### ISSUE TITLE
HSL color selector

### ISSUE THREAD

**Issue by develop7** [gnunn1/tilix#1311]
Subj please. Would make color tuning experience orders of magnitude better.

Thank you in advance.

**Comment by gnunn1** [comment]
AFAIK the GTKColorChooser does not support HSL out of the box, do you know of a GTK application that does this?

**Comment by develop7** [comment]
Not sure it qualifies, GIMP maybe?

**Comment by gnunn1** [comment]
GIMP is specialized for this area. I don't have any plans to add this unless the standard GTK ColorChooser supports it. If you have an example of a GTK app supporting this feel free to post the link to it and re-open the issue.
