### ISSUE TITLE
Wrong Size Quake Terminal with Wayland Scaling

### ISSUE THREAD

**Issue by PoLoMoTo** [gnunn1/tilix#1312]
Using any display scaling setting under Wayland except 100% causes the terminal window opened to not be the correct height or width. On 125%, 150%, and 175% it is also not in the correct location.

![screenshot from 2018-02-20 19-37-09](https://user-images.githubusercontent.com/5509894/36456964-a9a31adc-1675-11e8-8728-be1b30831f48.png)

![screenshot from 2018-02-20 19-37-21](https://user-images.githubusercontent.com/5509894/36456968-b036a454-1675-11e8-8a45-fa26a07fb7fc.png)

![screenshot from 2018-02-20 19-37-38](https://user-images.githubusercontent.com/5509894/36456971-b26ab13e-1675-11e8-8ed4-625729a537c1.png)

**Comment by gnunn1** [comment]
Quake mode is no longer supported in Wayland, see #1314.
