### ISSUE TITLE
"Open Tilix Here" in quake mode

### ISSUE THREAD

**Issue by jkosecki** [gnunn1/tilix#1315]
Currently, when the nautilus action "Open Tilix Here" is used, Tilix is always opened as a standalone application. 
For some users, who uses Tilix mainly in quake mode and expect the window to appear from the top, it might be a bit frustrating. 
I was thinking, that maybe an additional option in Preferences/Quake could be added to enforce opening tilix in quake mode, when "Open Tilix Here" is used.

**Comment by gnunn1** [comment]
You can already do this in Preferences | General, change the "On new instance" setting to "New Session" from "New Window"
