### ISSUE TITLE
How to use variable in triggers/custom links actions 

### ISSUE THREAD

**Issue by matclab** [gnunn1/tilix#1316]
I tried to launch a specific command (`pass show -c user@hostname`) upon certain text occurrence, but I would need to access hostname and username state variables, which doesn't seem to work.

I also tried with a notification, but the notification displays `title=${hostname}` and does neither expand the variable nor set the `title` variable… 

So, I'm a bit lost about what is possible and what is not possible here. Could you possibly give us some indication about which state variable may be used and how and when ?

**Comment by gnunn1** [comment]
Right now it doesn't replace the environment variable style tokens that you can use in titles. I think that is a good idea though if that is what you are asking for in terms of a feature enhancement.

**Comment by matclab** [comment]
Yes, it would be a nice feature enhancement !

Also an example on how to set title for Notification triggers in https://github.com/gnunn1/tilix/wiki/Triggers would be appreciated.

**Comment by matclab** [comment]
Thanks a lot.
 I'll test it soon.
