### ISSUE TITLE
Tilix unable to start with gtkd 3.7.5

### ISSUE THREAD

**Issue by lxdlam** [gnunn1/tilix#1319]
I'm using Manjaro and done an upgrade yesterday. Then I open tilix and received following error:
```bash
tilix: symbol lookup error: tilix: undefined symbol: _D3gtk6WidgetQh10__mixin74820getImplementorStructMFbZPS3atk1c5types14AtkImplementor
```
I checked the current version of gtkd:
```bash
$ pacman -Qs gtkd
```
It's `gtkd-3.7.5`.
Then I downgrade to gtkd to 3.7.3, everything works fine.
It's anything wrong with newer gtkd?

**Comment by gnunn1** [comment]
I suspect Manjaro needs to recompile tilix for the new version of GtkD. Please open a bug with them as I do not believe this is a code issue and I do not handle packaging.

**Comment by plguo15** [comment]
Just an update on this issue, it is not an exact solution, but this issue shows up in google when you search for the exact error.  If the one shipped in your distro does not work and you had no luck compile from source, try download the compiled binary from the [release page](https://github.com/gnunn1/tilix/releases) and it may just work out of box

````bash
# scripts for lazy people (like me), use at your own risk
# remember to change the version
wget https://github.com/gnunn1/tilix/releases/download/1.9.3/tilix.zip
sudo unzip tilix.zip -d /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
tilix
````

**Comment by FFY00** [comment]
@lxdlam open a bug report on manjaro. They must have screwed up, I pushed both packages at the same time to the arch repos. For some reason manjaro decided to only move the new gtkd version to their repos, and ignoring tilix.
