### ISSUE TITLE
Quake-mode for wayland (gnome-shell-extension)

### ISSUE THREAD

**Issue by repsac-by** [gnunn1/tilix#1322]
Hi guys.
I developed my first extension for gnome-shell. I really wanted to use quake-mode in wayland, but time went on and nothing changed. I did it and now you can use it, but don't count on powerful support, it's better to send pull-requests.

https://github.com/repsac-by/gnome-shell-extension-quake-mode

Thank you @gnunn1 for a great terminal emulator.

**Comment by noirbizarre** [comment]
Thanks for this extension. :+1: 
I just installed it, it's working after a restart.

**Comment by gnunn1** [comment]
Thanks for doing this.

**Comment by Nexmean** [comment]
@gnunn1 really? You removed wayland support for quake mode in minor version? I used `tilix` only in quake mode and it worked fine. And now I can not even roll back to the previous version. Nice semver.

**Comment by gnunn1** [comment]
I'll update the quake mode documentation with this as a potential way to get tilix working in quake mode in Wayland.

**Comment by EdiDD** [comment]
Why wayland support was dropped ? I haven't had any single issue with tilix (tilix quake mode) on wayland.

**Comment by gnunn1** [comment]
@EdiDD  It relied on various hacks to work (such as forcing the width to be 100%) and couldn't support the same features that work under X11. Also lot's of other people had issues with it and I got tired of supporting something that could never be perfect to the limitations of Wayland.

**Comment by gnunn1** [comment]
The documentation page has been updated:

https://gnunn1.github.io/tilix-web/manual/quake/

**Comment by SergiyKolesnikov** [comment]
A slightly modified version of the command worked for me:
```
env GDK_BACKEND=x11 tilix --quake
```
It is suggested in [Tilix wiki](https://github.com/gnunn1/tilix/wiki/Quake-Mode#wayland), but not mentioned in the [documentation](https://gnunn1.github.io/tilix-web/manual/quake/)

**Comment by vgonisanz** [comment]
For those who don't want to use X11 as a backend, I've made a small workaround script that works if you want a Wayland-based alternative. The script works in Hyprland window manager, but would be adaptable to sway and other similar window managers: https://unix.stackexchange.com/a/765588/19676
