### ISSUE TITLE
Archlinux packages disappeared from AUR

### ISSUE THREAD

**Issue by trustin** [gnunn1/tilix#1323]
`tilix` and `gtkd` have disappeared from aur.archlinux.org:

- https://aur.archlinux.org/packages/tilix
- https://aur.archlinux.org/packages/gtkd

May I know what's going on?

**Comment by gnunn1** [comment]
There is ```tilix-bin``` which fits with the Arch Linux naming convention, not sure what happened to tilix as I am not involved with packaging. I would suggest asking on the tilix-bin package.

**Comment by Vild** [comment]
Hi, I'm the maintainer of LDC package for arch, and today when I updated LDC I also took over the maintenance of the tilix and gtkd packages. So they are now in the official repository (the community repo).
I talked to dsboger earlier today about this.

**Comment by trustin** [comment]
Thanks a lot for a quick update.
