### ISSUE TITLE
Shortcuts for session sidebar view

### ISSUE THREAD

**Issue by jkosecki** [gnunn1/tilix#1325]
Currently, when sidebar view is open, UP and DOWN arrows are used to choose desired session and ENTER  to confirm it. 
Would it be possible to add another group of shortcuts in the Preferences to change shortcuts for active sidebar view.
I like trying to keep my hands as close to home row as possible so I've changed changed my shortcuts for "Switch to next/previous session" to "Ctrl + Shift + J/K". However, if overriding sidebar shortcuts would be possible, I could use then just "J/K".
Also, when sidebar is open it's not possible to have a cyclic iteration, ie. UP arrow when on first session jumps to last one and DOWN arrow when on last session jumps to first. 
On the other hand, changing session with "Switch to next/previous session" shortcuts has such a behavior.

**Comment by gnunn1** [comment]
I don't have any plans to offer alternative shortcuts for the arrow keys in the sidebar.

With respect to the cycling in the sidebar from bottom to top or vice versa, I took a shot at it awhile ago but it was really flaky. I don't have any plans to revisit it.
