### ISSUE TITLE
Cursor disappears

### ISSUE THREAD

**Issue by MikeBergmann** [gnunn1/tilix#1326]
Sometimes my cursor disappears, and I have to open a new session or terminal.
(See screenshot, the first terminal without the cursor, second with one)

Has anyone seen this before? 

Is there something I can do to debug this behavior or to get my cursor back?

It's Tilix 1.7.5

Thanks

Mike

![screenshot_2018-03-08_14-36-30](https://user-images.githubusercontent.com/7700206/37153789-25d9fd2c-22de-11e8-9de0-f839d129bf55.png)

**Comment by egmontkob** [comment]
There is a legal way for applications to hide the cursor, you can replicate it manually by running

    echo -ne '\e[?25l'

The next time it happens, could you please execute

    echo -ne '\e[?25h'
 
(or the `reset` command for a more complete reset of the terminal state), does it restore the cursor? If so, probably a misbehaving (or crashing) application accidentally leaves it hidden.

**Comment by MikeBergmann** [comment]
Yes, `echo -ne '\e[?25h'` let the cursor reappear. Thanks a lot.
