### ISSUE TITLE
Middle mouse clicking to close tabs

### ISSUE THREAD

**Issue by rafaelmardojai** [gnunn1/tilix#1327]
I know is possible middle-click on the terminal title bar to close it (#455). 
IMO, would be nice to have the same behavior on tabs.

Regards, and thanks for the great work.

**Comment by gnunn1** [comment]
The middle-click close is a feature of gnome where you can configure what to do on a middle-click with the gnome tweak tool. I do not have any plans to add middle-click close for tabs since it wouldn't be consistent with the rest of the gnome environment.

**Comment by rafaelmardojai** [comment]
GNOME Files & Web 3.28 now allows this behavior, any plans to reconsider?
