### ISSUE TITLE
Shortcut to select text

### ISSUE THREAD

**Issue by Nurza** [gnunn1/tilix#1329]
Hello, I am trying to learn to use Tilix. It's a great terminal emulator ! But it would be nice if you could use your keyboard to select and copy text instead of your mouse.

What do you think about it ?

**Comment by gnunn1** [comment]
VTE which is the terminal widget tilix uses along with gnome-terminal, terminator, etc would need to support this. There is a fork of VTE that termite, another terminal emulator, uses that supports this so feel free to check out that emulator and see if it meets your needs.

I do not have any plans to add this unless VTE officially starts supporting it.
