### ISSUE TITLE
Tilix widget

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1332]
Hi Gerald, I asked Christian Hergert, [if he could make Tilix runnable inside Builder](https://gitlab.gnome.org/GNOME/gnome-builder/issues/427#note_79565) – but that sadly seems to be not that easy. Is there maybe a possibility of creating some sort of Tilix widget, for wrapping it inside other programs? Would be damn cool!

**Comment by gnunn1** [comment]
There is not, tilix is written in D and uses a GC which means it would be challenging to integrate with a C program. I also have no time :(

**Comment by f2404** [comment]
Tilix itself, as many other terminal apps, is built upon vte widget. Is that what you are looking for?

**Comment by fbruetting** [comment]
Not quite sure what your question is…? :/ For me it would be cool, if I could have Tilix everywhere, like in Gnome Builder. :)

**Comment by f2404** [comment]
If you are looking for a terminal emulator widget, you can use vte. For example, Geany (a text editor) uses vte widget as a built-in command prompt.
