### ISSUE TITLE
Enable notifications

### ISSUE THREAD

**Issue by Bamban** [gnunn1/tilix#1334]
Hi,
My question may be dumb but I'm currently stuck ... I enable VTE support (with bashrc + symlink method). Here is what I get with tilix --version
```bash
$ tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.46
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```
It seems that VTE is correctly set, but I don't see how I can now enable the special features.
I installed tilix from debian stretch-backports.
Thanks !
And congrats for this nice software :+1:

**Comment by gnunn1** [comment]
You need to have a VTE that has the Fedora patch to support notifications, I do not know if it's available in Debian like it is in Arch.
