### ISSUE TITLE
Word-Wise Select Characters are not working 

### ISSUE THREAD

**Issue by syedah314** [gnunn1/tilix#1336]
Configured following characters under Profile/Word-Wise Characters -,./?%&#:_\
Issue is reproduced by typing out the following string in terminal:
 abc-def,geh.ijk/lmn?opq%rst&uvw#xyz:123_456/789 and double-clicking on the string.
Expected behaviour is that individual words separated by those characters are selected but the entire string gets selected indicating that none of the Word-Wise select characters are working.

> tilix --version
> Versions
> 	Tilix version: 1.7.5
> 	VTE version: 0.50
> 	GTK Version: 3.22.26
> 
> Tilix Special Features
> 	Notifications enabled=1
> 	Triggers enabled=0
> 	Badges enabled=0

**Comment by phw** [comment]
It is working as expected: You told Tilix that all those characters are part of a word. Normally they are not (except _ probably). So if you remove all the characters from the config you will see that only parts of your text string get selected.

**Comment by syedah314** [comment]
Ok - Thank you for explaining this, I understand the behaviour now.
