### ISSUE TITLE
Progress bar when pasting large texts

### ISSUE THREAD

**Issue by kramer65** [gnunn1/tilix#1337]
When I'm ssh'd into a remote server and I paste a very large text into nano nothing seems to happen for some time. At first I thought it freezed or I simply didn't click ctrl-v correctly. So I pasted again, and again. After about 20 seconds it finally showed the pasted text (three times by then).

In iTerm2 on OSX you get to see a kind of progress bar in situations like this. It would be awesome if tilix would support a similar thing.

**Comment by gnunn1** [comment]
The terminal widget, VTE, that tilix and other emulators like gnome-terminal use would need to support this. At the moment pasting is a synchronous call so there is nothing on my side I can do to support it. I would suggest opening a request in the gnome bug tracker for VTE if this is of interest to you.

**Comment by kramer65** [comment]
Thanks for the info. Now that I know this it's not actually a biggie. When I paste something I now simply wait until it shows the result. 

Thanks for creating tilix. You make my day. Every single day! :-)
