### ISSUE TITLE
Quake mode titlebar option also affects regular windows.

### ISSUE THREAD

**Issue by M4he** [gnunn1/tilix#1338]
It seems like Tilix is treating the "Hide titlebar" option of the Quake mode globally (including regular windows) if CSD is disabled.

## Setup

- within **Preferences** > **Appearance** set "**Window Style**" to "**Disable CSD**"
- within **Preferences** > **Quake** check "**[x] Hide titlebar of the window**"

## Expected behavior

- Tilix should still display the non-CSD titlebar/toolbar for regular windows

## Actual behavior

- Tilix does not the display the titlebar/toolbar for regular windows

## Environment

Output of `tilix -v`:

```
Versions
	Tilix version: 1.7.5
	VTE version: 0.46
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```
System is a **Debian 9.4 x64**. I'm using **awesome WM** standalone with xsettingsd.

**Comment by gnunn1** [comment]
That's a case of bad naming on my part, it only hides the headerbar so when you disable CSD the headerbar becomes the toolbar which gets hidden in quake mode. I'll need to look at this to either change the phrasing to be accurate and get it working properly where it hides the titlebar regardless of whether CSD is disabled.

**Comment by M4he** [comment]
> it only hides the headerbar so when you disable CSD the headerbar becomes the toolbar which gets hidden in quake mode ... get it working properly where it hides the titlebar regardless of whether CSD is disabled.

Maybe I'm misunderstanding something here but I think the actual issue is that an option categorized within "Quake" is affecting non-Quake style windows as well. The option also hides the toolbar in regular windows, which I doubt it is supposed to do unless I'm missing something here.
