### ISSUE TITLE
Nothing works while shortcuts window is open.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [gnunn1/tilix#1339]
Nothing works while shortcuts window is open!

**Comment by gnunn1** [comment]
This is the standard Gnome behavior, gedit works exactly the same way.

**Comment by c-e-p-x-u-o** [comment]
I knot, but it's excuse, and not the reason to work bad.
I't totally unusable, I open hotkeys cheatsheet to try them, but need to remember, close window and open it each time again and again.

**Comment by c-e-p-x-u-o** [comment]
Please reopen.

**Comment by gnunn1** [comment]
Sorry but I will not, this conforms to the Gnome HIG and is the way it is supposed to work.

**Comment by c-e-p-x-u-o** [comment]
What exatly conforms to the Gnome HIG and? To block all interaction while it shows help?
