### ISSUE TITLE
<Ctrl>-<Shift>-<N> doesn't work

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [gnunn1/tilix#1340]
```<Ctrl>-<Shift>-<N> doesn't work```

**Comment by gnunn1** [comment]
Works fine for me and creates a new Window, what desktop environment are you using?

**Comment by c-e-p-x-u-o** [comment]
enlightenment E22
<Ctrl>-<Shift>-<N> is not binded in WM settings and does nothing.

**Comment by c-e-p-x-u-o** [comment]
Forgot to say, <Ctrl>-<Shift>-<T> works fine.

**Comment by gnunn1** [comment]
So if it works can I close this. Note I only support Gnome so I generally do not fix bugs that are specific to other desktop environments unless it's obvious what the issue is.

**Comment by c-e-p-x-u-o** [comment]
Forgot to quote. works ```<Ctrl>-<Shift>-<T>```, ```<Ctrl>-<Shift>-<N>``` does not

**Comment by gnunn1** [comment]
That's weird, New Session and New Window both exist at the application level. If you assign the <Ctrl><Shift><T> in Preferences | Shortcuts to New Window instead of New Session does it work?

**Comment by c-e-p-x-u-o** [comment]
I can't assign ```<Ctrl>-<Shift>-<T>``` as tilix doesn't react on it.
And it's not WM problem as I've tried it in pure X11 without WM.

**Comment by c-e-p-x-u-o** [comment]
OK, xev also doesn't receive it. It's not tilix problem, sorry.
