### ISSUE TITLE
Clicking on custom links does nothing

### ISSUE THREAD

**Issue by matclab** [gnunn1/tilix#1342]
I have one custom link definition that highlights when hovered, but does nothing when clicking.
I tried to just call a program like `gvim` to debug, but nothing happens.

Using tilix 1.7.7 on arch linux.

**Comment by phw** [comment]
Opening links is either done by Ctrl + Click or right click and open from context menu.

**Comment by matclab** [comment]
Oh. I was sure I tried it, but trying again it works now.
It looks like I've somehow failed to save the configuration with "gvim" test, and my regexp selection was wrong and gives a bad argument which prevent the initial program (`pass show -c $1@$2`) to execute properly.
Now everyhting's ok and it permit a nice enough integration with [pass](https://www.passwordstore.org/), where opening the link (ssh user@host) copy the password to the clipboard.

I'm really, really sorry for the noise.
