### ISSUE TITLE
Mistyped custom command causes crash

### ISSUE THREAD

**Issue by pbeckley** [gnunn1/tilix#1345]
I went to set a custom command upon opening to modify session config. I mistyped the command and now tilix flashes open and then immediately closes.

**Comment by gnunn1** [comment]
That's expected, tilix has no way of knowing whether the command is valid. You should be able to access Preferences directly by right clicking tilix in gnome-shell and select preferences. Alternatively run tilix from a command line using the --preferences switch.

**Comment by gnunn1** [comment]
It's stored in dconf, all tilix settings are in the com.tilix key.

Getald

**Comment by pbeckley** [comment]
Okay, closing issue. Thanks for the assistance and for the quick response time.
