### ISSUE TITLE
Quake should behave like Yakuake

### ISSUE THREAD

**Issue by zyf0330** [gnunn1/tilix#1346]
I set a shortcut to call clipboard and select a item then I can paste to terminal.
In Yakuake, window won't disappear when I do this. But in Tilix, it will. It is causing by *disappear when lose focus*. Experience in Yakuake is better. What do you think?
And another little thing, Yakuake appears like be pulled down from top, but Tilix Quake appears by scale from center.

**Comment by gnunn1** [comment]
You lost me on "I set a shortcut to call clipboard and select a item then I can paste to terminal.", are you referring to setting a global shortcut in gnome? If so, this is a known issue with global shortcuts in gnome and there is nothing I can do about it unfortunately.

With regards to animating the tilix window, it's not something I'm overly interested in doing at this time.

**Comment by zyf0330** [comment]
I am in kde, don't know this problem of gnome. It is a global shortcut.
As for second, it is just a insignificant little things.

**Comment by gnunn1** [comment]
Unfortunately I do not support tilix on KDE, just gnome. I just don't have enough time to track down and correct bugs in other desktop environments unless they are obvious. I'm closing this bug as a result of that since I will not be investigating further.

**Comment by zyf0330** [comment]
It's all right.
