### ISSUE TITLE
How to let Ctrl+Backspace delete the preceding word?

### ISSUE THREAD

**Issue by kramer65** [gnunn1/tilix#1348]
In all of Ubuntu `Ctrl`+`Backspace` removes the word which is left of the cursor, but only in the terminal this is done using `Alt`+`Backspace` (or `Ctrl`+`w` ). Since I constantly switch between the terminal (Tilix) and other programs it's really annoying that only the terminal demands a different key-combination.

Is it somehow possible to remap `Ctrl`+`Backspace` to deleting one word instead of one letter only? All tips are welcome!

**Comment by gnunn1** [comment]
It is not possible to remap it as it is built into the underlying VTE widget and it does not have support for keyboard re-mapping.

**Comment by egmontkob** [comment]
It _is_ possible to make Ctrl+Backspace delete a word (you just have to do the mapping in the application that receives the keystroke, not in Tilix), see #1498.

**Comment by trevorkirpaul** [comment]
```bash
# .zshrc

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^H" backward-kill-word
bindkey "^[[3;5~" kill-word
```

I copied the above from [this comment](https://github.com/gnunn1/tilix/issues/1498#issuecomment-416044679) and it's working for me on Fedora 33 within Tilix.

**Comment by algj** [comment]
No terminal emulators had a way to select this easily, so...

Also, it is very possible. I tested it out, it sends correct keystrokes.

**Comment by Paynayt** [comment]
For bash you can use this : 

```bash
bind '"\e[5C": forward-word'
bind '"\e[5D": backward-word'
bind '"\C-h": backward-kill-word'
bind '"\e[3~": kill-word'
```

This actually works for me, i was looking for a solution to get the `ctrl + backspace` on tilix and i found it.
