### ISSUE TITLE
"Relaunch" button runs another command

### ISSUE THREAD

**Issue by f2404** [gnunn1/tilix#1350]
If tilix is set to execute a non-existent command (e.g., `tilix -e 123`), it shows a message saying "Failed to execute child process" with a "Relaunch" button. But, clicking the button does not relaunch the given command and runs my bash shell instead.
Gnome-terminal behaves differently and relaunches the non-existent command over and over again which I think makes sense, given that the button is called "relaunch".
```
$ tilix --version
Versions
	Tilix version: 1.7.5
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```

**Comment by phw** [comment]
> Gnome-terminal behaves differently and relaunches the non-existent command over and over again [...]

What is the point of doing this?

**Comment by f2404** [comment]
@phw I guess it's supposing that user has fixed the problem that prevented the command from running in the first place, and wants to relaunch it. Otherwise, what's the point of the "relaunch" button?

At the very least, if the button is really supposed to run the default command (i.e. the shell), it should be named differently, something like "Run the shell instead of the command that you have specified but I'm not willing to run anymore".

**Comment by gnunn1** [comment]
Where is the command being sourced from, using ```--command``` on the command line or as a command in the profile?

**Comment by f2404** [comment]
I was using '-e' command line parameter.

**Comment by gnunn1** [comment]
This is because in tilix the passed in command is transient and not preserved, I'll need to look into it.
