### ISSUE TITLE
When I hide the title bar,I don't know how to re-display it,please help me 

### ISSUE THREAD

**Issue by roadhoghook** [gnunn1/tilix#1352]
![_ _20180326103010](https://user-images.githubusercontent.com/32829983/37884066-c59c4666-30e0-11e8-8476-fdf19ae91506.png)

**Comment by gnunn1** [comment]
Go into the Preferences dialog, under the Appearances section and select an appropriate option for Window Title.

**Comment by roadhoghook** [comment]
sorry。。but nothing，I can't go into the Preferences dialog,there is no button I can click here

**Comment by gnunn1** [comment]
Just type ```tilix --preferences``` at the prompt to bring it up. Tilix is designed for gnome, so in gnome you can right click the running icon and select Preferences from there.

**Comment by mrjk** [comment]
Feature suggestion: Add an entry in the contextual right click menu, à la terminator :)

**Comment by gnunn1** [comment]
I don't have any plans to do that, if you use gnome it appears in the app menu and I only support gnome at this time. Using ```tilix --perferences``` is an acceptable workaround IMHO.
