### ISSUE TITLE
Wrong formatting when pasting URLs with parameters

### ISSUE THREAD

**Issue by terencode** [gnunn1/tilix#1354]
1) Copy the following: https://test?test=1?test2=2
2) Paste it in Tilix
3) URL becomes: https://test\?test\=1\?test2\=2

**Comment by f2404** [comment]
I cannot reproduce this.

**Comment by gnunn1** [comment]
I cannot reproduce either, @terencode what version of tilix are you using? What is the output of ```tilix --version```?

**Comment by terencode** [comment]
Closed because it seems to be an  issue with oh-my-zsh and continuing there: https://github.com/robbyrussell/oh-my-zsh/issues/6706
