### ISSUE TITLE
Tilix VTE patches do not apply

### ISSUE THREAD

**Issue by dsboger** [gnunn1/tilix#1356]
I'm trying to release vte3-tilix 0.52.0 on AUR, and noticed that Tilix VTE patches no longer apply. I tried both applying them directly and on top of the latest Fedora patches (sed'ing padding sizes). The patch command output is below:

Tilix VTE patches alone:

```
-> Applying tilix patches
patching file src/vte/vteterminal.h
patching file src/vtegtk.cc
Hunk #1 succeeded at 739 (offset 52 lines).
Hunk #2 succeeded at 1289 (offset 81 lines).
patching file src/vtegtk.hh
Hunk #1 succeeded at 52 (offset 1 line).
patching file src/vteinternal.hh
Hunk #1 FAILED at 1181.
1 out of 1 hunk FAILED -- saving rejects to file src/vteinternal.hh.rej
patching file src/vteseq.cc
Hunk #1 succeeded at 186 (offset -16 lines).
Hunk #2 FAILED at 386.
Hunk #3 FAILED at 413.
2 out of 3 hunks FAILED -- saving rejects to file src/vteseq.cc.rej
patching file src/vte/vteterminal.h
patching file src/vteseq.cc
Hunk #1 succeeded at 186 (offset -16 lines).
```

Tilix VTE patches on top of modified Fedora patches:

```
-> Making the patch-sets compatible
-> Applying Fedora patches
patching file src/caps-list.hh
patching file src/marshal.list
patching file src/vte.cc
Hunk #1 succeeded at 8664 (offset -40 lines).
Hunk #2 succeeded at 10932 (offset -46 lines).
patching file src/vte/vteterminal.h
patching file src/vtegtk.cc
Hunk #1 succeeded at 709 (offset 7 lines).
Hunk #2 succeeded at 785 (offset 7 lines).
patching file src/vtegtk.hh
patching file src/vteinternal.hh
Hunk #1 succeeded at 630 (offset -5 lines).
patching file src/vteseq-list.hh
Hunk #1 succeeded at 121 (offset 1 line).
patching file src/vteseq.cc
Hunk #1 succeeded at 2200 (offset 88 lines).
patching file src/vte.sh
patching file bindings/vala/app.vala
patching file src/app/app.cc
Hunk #1 succeeded at 1588 (offset 7 lines).
Hunk #2 succeeded at 1823 (offset 7 lines).
patching file doc/reference/vte-sections.txt
patching file src/vte.cc
Hunk #1 succeeded at 10174 (offset -45 lines).
Hunk #2 succeeded at 10228 (offset -45 lines).
Hunk #3 succeeded at 10495 (offset -45 lines).
patching file src/vte/vteterminal.h
patching file src/vtegtk.cc
Hunk #1 succeeded at 491 (offset 1 line).
Hunk #2 succeeded at 595 (offset 1 line).
Hunk #3 succeeded at 1546 (offset 7 lines).
Hunk #4 succeeded at 4088 (offset 7 lines).
patching file src/vtegtk.hh
patching file src/vteinternal.hh
Hunk #2 succeeded at 1265 (offset -5 lines).
patching file bindings/vala/app.vala
patching file src/app/app.cc
Hunk #1 succeeded at 91 (offset 2 lines).
Hunk #2 succeeded at 402 (offset 4 lines).
Hunk #3 succeeded at 1856 (offset 8 lines).
patching file src/vte.sh
-> Applying tilix patches
patching file src/vte/vteterminal.h
Hunk #1 succeeded at 106 with fuzz 2 (offset 2 lines).
patching file src/vtegtk.cc
Hunk #1 succeeded at 746 (offset 59 lines).
Hunk #2 succeeded at 1316 (offset 108 lines).
patching file src/vtegtk.hh
Hunk #1 succeeded at 52 (offset 1 line).
patching file src/vteinternal.hh
Hunk #1 FAILED at 1181.
1 out of 1 hunk FAILED -- saving rejects to file src/vteinternal.hh.rej
patching file src/vteseq.cc
Hunk #1 succeeded at 186 (offset -16 lines).
Hunk #2 FAILED at 386.
Hunk #3 FAILED at 413.
2 out of 3 hunks FAILED -- saving rejects to file src/vteseq.cc.rej
patching file src/vte/vteterminal.h
Hunk #1 succeeded at 109 (offset 2 lines).
patching file src/vteseq.cc
Hunk #1 succeeded at 186 (offset -16 lines).
```

**Comment by gnunn1** [comment]
The disable-bg-draw patch will no longer be needed in 0.52 since VTE added that functionality, however I'll need GtkD to update to a new release to make it available in tilix.

I'll have a look at the alternate-screen one and fix it.

**Comment by gnunn1** [comment]
I've updated the alternate-screen patch in the experimental/vte/0.52 directory. Please try it out and if you have any issues let me know.

Note the background patch will not be ported to 0.52, this will be addressed with a new method in the VTE that will be available in the next version of GtkD (https://github.com/gtkd-developers/GtkD/issues/236) and tilix.

**Comment by gnunn1** [comment]
@dsboger I have updated tilix in git to use the new VTE version as well, so with VTE version 0.52 and this version in git the Badge support will work without the previous background patch.

I need to fix a few bugs, do some more testing plus let the new git version percolate a bit before pushing out an official release of tilix.

**Comment by dsboger** [comment]
@gnunn1 It seems like the new patch applies on top of vte master, but not vte-0-52 stable.

**Comment by gnunn1** [comment]
Me bad, I'll fix it shortly

**Comment by gnunn1** [comment]
OK I've updated it for the vte-0-52 branch, let me know if you are still having problems

**Comment by dsboger** [comment]
@gnunn1 It works! As badges are disabled, I think I'll hold the vte3-tilix update until GtkD 3.8 and next Tilix stable are released.

Thank you for your dedication!

**Comment by phw** [comment]
@dsboger GtkD 3.8 is now in the repositories and Arch's Tilix package has also the patch at https://github.com/gnunn1/tilix/commit/76ac251da7f6e639a1a49d1c4d4ad48e135ab79f added.

So it should be fine to also update the vte3-tilix package now :)

**Comment by gnunn1** [comment]
@phw I think @dsboger concern is that until I push out a new version of tilix the badge functionality will be broken in VTE 0.52 because it uses a supported method of drawing the background now instead of my previous patch.

**Comment by phw** [comment]
@gnunn1 Isn't that what https://github.com/gnunn1/tilix/commit/76ac251da7f6e639a1a49d1c4d4ad48e135ab79f is about? Or is there something else to it?

**Comment by gnunn1** [comment]
Yes but it would only fix it for people using the tilix-git package. The tilix-bin package follows tilix releases and thus the need to push out an official release with that commit. Otherwise people using tilix-bin with tilix-vte would find badges no longer work.

You also cannot just cherry pick that commit, I had to fix a few things to get badges working that had changed in vte between the pre-release and final release.

**Comment by gnunn1** [comment]
It won't break the app but it won't fix the badge functionality either, it's a neutral change without the other commits.

**Comment by Vild** [comment]
Just FYI, I had to add that patch to Tilix, as I didn't want Tilix to block the release of the gtkd package.
But feel free to ping me anytime, if there is anything about the Arch packages :)
