### ISSUE TITLE
Tabs render incorrectly

### ISSUE THREAD

**Issue by thoughton** [gnunn1/tilix#1357]
Hi,

I'm a new user, and I like the application very much, but I've noticed that when switching to Tabs mode the tabs seem to render incorrectly for me:

![image](https://user-images.githubusercontent.com/38389/38135998-51cd62c0-3413-11e8-945b-40ea9a0a9f07.png)

For comparison, here is gedit on the same system:

![image](https://user-images.githubusercontent.com/38389/38136049-b05ee1ec-3413-11e8-9537-be8fe09c3ec8.png)

I am running Ubuntu LTS 16.04, but the one major change I've made is switching from Unity DE to Gnome 3 (version 3.18.2).

If this is something that's likely to be resolved once the next LTS rolls-out in the next few months then I'm more than happy to just wait until then. :)

Thanks!

**Comment by gnunn1** [comment]
Thanks for the bug report, this works fine as far as I can tell on a current release of GTK. Unfortunately the LTS release is a three year old release of GTK, I'm not sure when I'll have time to look at it as it is not a priority for me.

**Comment by thoughton** [comment]
Hi @gnunn1, thanks for the quick response. That's no problem, I figured that the oldness of the LTS would likely be the main issue here, and it's totally understandable that that would make this a low priority. Thankfully the new LTS is not too far away now, so like I mentioned, I'm happy to wait and see if that fixes it. (I'll also try to remember to come back here and update with my findings once I am up-to-date.)

**Comment by gnunn1** [comment]
I'm going to close this since I have no plans to work on this.
