### ISSUE TITLE
Can't set tab/session title using -t / --title

### ISSUE THREAD

**Issue by vista-** [gnunn1/tilix#1358]
Apologies if this has been reported / a fix has been offered for this before, searching for this specific issue is quite the challenge. 
When I try to start a new session in Tilix and set the tab's name from the command-line using the --title (-t) argument, I am unable to do so, the session's title is set to "Terminal" instead.

![](http://static.notx.ml/u/69c510a949.png)

The following are set in my "Appearance" preferences:

![](http://static.notx.ml/u/3fc40b5062.png)

The only other configuration change I've made that differs from default is to open a "New Session" instead of a "New Window" when creating a new instance.

I am using the latest release of Tilix, just downloaded it from the GitHub releases (1.7.7).

**Comment by gnunn1** [comment]
The ```-t``` switch sets the title of the terminal not the session. If you set the terminal title style to something other then ```None``` you will hopefully see it working as intended.

**Comment by vista-** [comment]
I see, is there a way to set the names of the tabs?

**Comment by gnunn1** [comment]
There is no current way to do that but I agree it would be useful.

**Comment by gnunn1** [comment]
Just thinking about it this some more, I think you are hitting a bug where the ${title} for the Default session name should be using the title that is explicitly set and not falling back on the terminal title. I'll have a look at it.

**Comment by gnunn1** [comment]
The variable ```${activeTerminalTitle}``` has been moved from window scope to session scope. So if you set your default session title to this variable it will work fine with ```tilix -t SomeTitle```.

**Comment by Patola** [comment]
In this way, is it possible do dynamically change the title of particular tabs to something you like? I do this via dbus calls to yakuake and guake, I'd love to be able to do that to tilda too.

**Comment by gnunn1** [comment]
You can change the title through the hamburger menu but not from the command line.
