### ISSUE TITLE
The window content is flashing, when using my editor Joe/Jmacs inside tilix in a remote session 

### ISSUE THREAD

**Issue by EmTee70** [gnunn1/tilix#1360]
This is not happening inside a xterm.

Environment: Local Ubuntu 17.10 running tilix
ssh connect to remote Ubuntu 16.10 running Editor Joe/Jmacs inside the Window.

This was my traditional way to use tilix, not sure why this happened.
tilix --version
Versionen
        Tilix-Version:  1.6.4
        VTE-Version: 0.48
        GTK-Version: 3.22.25

Any hint?

**Comment by EmTee70** [comment]
**Ah, thank you!**
It is away when I disable overlay scrollbars. What are overlay scrollbars ? :-)
For your info: I checked it with gnome-terminal and xfce-terminal, too, no problems detected.

When the window is flashing (overlay scrollbars enabled) in the upper left corner the chars "lp" appear  for some miliseconds, than the window content seams to be redrawn.
It does not happen with "less" only the editor (joe/jmacs) suddenly started the trouble.

**Comment by f2404** [comment]
@EmTee70 
> I checked it with gnome-terminal and xfce-terminal, too, no problems detected.

It's because they are not using overlay scrollbars :)

**Comment by gnunn1** [comment]
Overlay scrollbars are a feature in gnome that replaces the traditional scrollbar, they are visual more attractive and hide themselves when not in use. While VTE can be used with overlay scrollbars, there have been some reports of minor issues with them here and there hence why I suggested trying to disable them.

Glad you got the issue sorted out.
