### ISSUE TITLE
Run an arbitrary command at start

### ISSUE THREAD

**Issue by Leprosy** [gnunn1/tilix#1363]
Hi...is there any way to specify a command to be executed at the start by a profile?

For example, I have a session configured with 3 consoles, 2 of them with a profile a and the third one with a profile b. Profile a needs to run a command at the start. Profile b doesn't need to run anything.

**Comment by f2404** [comment]
Preferences -> your profile -> Command -> Run a custom command...
?

**Comment by Leprosy** [comment]
Doesn't work. I need to do a "source" to a python virtualenv, it throws me a:
"Unexpected error occurred: Failed to execute child process "source"(No such file or directory)

Doing something like "ls" as a command shows this:
"The child process was aborted"

**Comment by f2404** [comment]
Running `ls` works for me.

But I guess what you're trying to do is to run a command within a bash session and not instead of it. In that case, the abovementioned option won't work for you.

**Comment by Leprosy** [comment]
Yeah, I think that is the issue. I figured out the custom command option is like a replacement for the default shell used by the terminal. I'm trying to run a command after everything starts. Is there a way to do something like that?

**Comment by f2404** [comment]
I think using a bookmarked command could serve as a kind of a shortcut, in case you don't want to type your long command every time or look for it in the shell history.
However, there's no way to run a bookmark automatically, or at least I don't see one.

**Comment by Leprosy** [comment]
It's good enough, thanks! Perhaps this can be added in a future version...

**Comment by phw** [comment]
You can always just run commands with a shell, e.g. by running with `bash -c`.

**Comment by gnunn1** [comment]
@phw covered the way to do this, gnome-terminal works the exact same way.

**Comment by AlexAndHisScripts** [comment]
I just did this and it closes when the command finishes... I can't access the terminal and I can't find the config files to turn it off.
