### ISSUE TITLE
Multiple quake instances (with different hotkeys, on different monitors)

### ISSUE THREAD

**Issue by Bubu** [gnunn1/tilix#1366]
Ideally I'd like to have a tilix quake instance on each monitor controllable through different hotkeys.

Would such a thing be possible to support with reasonable effort?

(Just discovered tilix, it's awesome!)

**Comment by gnunn1** [comment]
Sorry but I don't have any plans to add this, it would be a fair amount of work for something that isn't likely to be widely used I'M HOPING.

**Comment by Bubu** [comment]
Fair enough. It certainly seems a bit special but would totally make sense for my workflow. :-)

**Comment by benjamin-rood** [comment]
@gnunn1 Can I pay or help crowdfund your time for this? Coming from mac and iTerm2 this is the only way I work. If you're not running a TWM it's extremely useful to do everything in toggleable windows.

**Comment by gnunn1** [comment]
Thanks for the thought but no to the crowd funding or paying. I'm not working on Tilix at the moment, sorry.

**Comment by benjamin-rood** [comment]
@gnunn1 Do you know what it would take to implement? If someone forked tilix and implemented it successfully, would you merge upstream?
