### ISSUE TITLE
Unable to enter '/' (slash) in git log pager view

### ISSUE THREAD

**Issue by Bubu** [gnunn1/tilix#1367]
I just discovered I cannot search in the `git log` pager view with tilix. It briefly shows the `/` character appearing then it disappears again. Quite weird... it works in every other application I've tried. `man`, `less`, `vim` and just `bash`.

```
$ tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.25

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by Bubu** [comment]
The issue disappears when disabling `overlay scrollbars`. (Not sure what these are about anyway?)

**Comment by gnunn1** [comment]
There's a number of issues in VTE related to overlay scrollbars. Overlay scrollbars are a gnome feature where the scrollbar pops out of the side when the mouse hovers over it. It makes for a visually nicer experience but like I said there are some edge cases with it hence why there is the option to turn them off.

This is an upstream issue so I'm closing this, there is another  bug open for this as well and I'll group this under that.
