### ISSUE TITLE
Font name appears across screen

### ISSUE THREAD

**Issue by polaris6933** [gnunn1/tilix#1371]
I don't think I can really explain it well, here's a picture: 
![screenshot from 2018-04-15 19-24-53](https://user-images.githubusercontent.com/13906628/38780678-0bad729e-40e3-11e8-8830-5974f84f1911.png)
This happened after I started using a patched version of the Monaco font. At first it only appeared occasionally and disappeared after switching tabs. Since updating Gnome to 3.28.1 today it stays there permanently. I tried switching fonts / removing the said font and there was no effect whatsoever (to clarify - even with fonts that are not Monaco I still get "mona" printed out).

**Comment by gnunn1** [comment]
It looks like the badge feature, in preferences under whatever profile you are using please confirm you do not have any text in the Badge text field.

**Comment by polaris6933** [comment]
That was it, thank you!
