### ISSUE TITLE
Ubuntu 16.04 profile launch fails

### ISSUE THREAD

**Issue by ChrisHughes** [gnunn1/tilix#1374]
On Ubuntu 16.04 with stock unity desktop interface tilix fails to open when Tilix:Default is launched, one has to go thru the menu to find the global launcher.

Running Tilix with
```
/usr/bin/tilix --gapplication-service
```
results in the process exiting with no status.

any help getting this to launch again after a reboot would be nice. It is currently losing changes to my bookmarks and other settings, which is the big reason I'm using tilix.

**Comment by gnunn1** [comment]
I have never tested it with the ```--gapplication-service``` option, any reason in particular you are using that? Looking at the help for it I'm not seeing what the point of it is?

```Since 2.40, applications that are not explicitly flagged as services or launchers (ie: neither G_APPLICATION_IS_SERVICE or G_APPLICATION_IS_LAUNCHER are given as flags) will check (from the default handler for local_command_line) if "--gapplication-service" was given in the command line. If this flag is present then normal commandline processing is interrupted and the G_APPLICATION_IS_SERVICE flag is set. This provides a "compromise" solution whereby running an application directly from the commandline will invoke it in the normal way (which can be useful for debugging) while still allowing applications to be D-Bus activated in service mode. The D-Bus service file should invoke the executable with "--gapplication-service" as the sole commandline argument. This approach is suitable for use by most graphical applications but should not be used from applications like editors that need precise control over when processes invoked via the commandline will exit and what their exit status will be.```

**Comment by ChrisHughes** [comment]
I'm not adding the --gapplication-service myself. This is the launcher that Unity on 16.04 is creating. When I run the 'Tilix Default' launcher, I should be able to retrieve my last used profile and settings. But it does not launch. When I launch Tilix from the menu, all my settings and changes are lost. This second launcher is the only way it can run on a stock Ubuntu 16.04 system. Please give this a try for yourself, especially after launching it, changing a setting, then reboot or log out, then try and run it again.

**Comment by gnunn1** [comment]
So if you run tilix from the command line in another terminal does it work? If so I'd suggest opening a bug with Ubuntu to fix the launcher.

The settings being lost sounds like something  weird is going on. The settings are stored in dconf under the com.gexperts.tilix key, can you try changing a setting and confirm whether it's persisted in dconf.

**Comment by gnunn1** [comment]
When I launch gedit with this switch it behaves the exact same way so I do not believe this is a tilix bug.

```gedit --gapplication-service```

Please open a bug with Ubuntu.
