### ISSUE TITLE
" breaks clickable Link in Tilix

### ISSUE THREAD

**Issue by gituser823** [gnunn1/tilix#1375]
Hello,

I really like the clickable Links feature in Tilix.

But I always need to click Links, that contain a " and the clickable Link cuts everything after a ".
Is there a Way to make such Links clickable too?
example:
http://github.com/gnunn1/tilix/Issues/new?list=foo&list2=%7B"bar"

cuts off bar"

Thanks.

**Comment by gnunn1** [comment]
Also you can define your own regex patterns which will take precedence over the built-in ones. These can be defined in Preferences | Advanced or per profile in the Advanced tab.
