### ISSUE TITLE
Hyperlinks does not work

### ISSUE THREAD

**Issue by martinanderssondotcom** [gnunn1/tilix#1377]
When the output on my terminal has a URI, it turns into a clickable link. But clicking on the link doesn't do anything. There's no effect what so ever. If I right-click and choose "Open Link", then it is opened in my web browser.

Running on Ubuntu 18.04 x64 (as a VM on top of VirtualBox/Windows 10).

**Comment by phw** [comment]
You have to `Ctrl` + click and it will open.

**Comment by martinanderssondotcom** [comment]
LOL. Thank you, I guess!

But Seriously, this needs to be addressed. There's a link. It's underlined. I hover over it, link changes theme. I click on it, underline disappear for a quick sec, but that's it. I click, nothing happens. I click, nothing happens. This is a big problem.

**Comment by f2404** [comment]
I don't think it should be changed to a simple click as that would cause lots of accidental URI clicks: when trying to select text, focus a terminal, etc.
Ctrl+click seems to be safe enough and is used not only by gnome-terminal but by other terminal apps, too.

**Comment by martinanderssondotcom** [comment]
Accidental clicks? Yeah, for sure. But I think the number of confused users, like myself, far outweighs the number of accidental clicks. Plus, the "cost" of an accidental click is almost negligible compared to the user trying to click something repeatedly for five minutes. At least the no-effect click shouldn't change the styling as if something is about to happen and then the user is just left sitting there waiting to no avail.

However that might be - what's the worst of the two (?) - then I don't think anyone can say clicking links that don't do anything is normal in any shape or form. That's like.. not how the world works lol. Sure, there might be "historical reasons", but the world already suffers from the ailment of backwards compatibility. Let's try to look forward instead, one terminal at a time.

But of course, that's just my five cents. To whomever it might concern, thank you a million for building a fantastic product =)

**Comment by gnunn1** [comment]
So I tried this out locally for a bit and I don't think I will make this change. The problem is that it essentially prevents you from selecting and copying anything within the link since as you click on it the browser gets launched. Given that pretty much all of the terminals I am aware of use ctrl-click I'm not planning on changing it at this time.
