### ISSUE TITLE
Trying to resize with shortcut (maj-alt-arrows) with only one terminal -> crash

### ISSUE THREAD

**Issue by Salamandar** [gnunn1/tilix#1387]
When having only one terminal (so resizing makes no sense), trying to resize this terminal with the shortcuts make the window crash. Tilix should just ignore the shortcut.

**Comment by gnunn1** [comment]
Thanks I can duplicate.

**Comment by gnunn1** [comment]
This is the same issue as a previous bug where GtkD crashes when doing a cast on a null object. GtkD has fixed this in 3.8.2 and I've updated dub.json to use that version.

Thanks for the report

**Comment by Salamandar** [comment]
OK, I've gtkd-3.8.0 installed so… yeah ^^
