### ISSUE TITLE
 right click menu text "open in tilix " disappear, how can i recover???

### ISSUE THREAD

**Issue by V0idk** [gnunn1/tilix#1388]
i have purge and reinstall but not working. 
i am using ubuntu 18.04

**Comment by hongquan** [comment]
Install _gir1.2-nautilus-3.0_ (Ref: [Make Tilix work with Nautilus 3.28](http://quan.hoabinh.vn/blog/2018/5/59-make-tilix-work-with-nautilus-3-28)).
