### ISSUE TITLE
large scrollback seems to segfault?

### ISSUE THREAD

**Issue by lulcat** [gnunn1/tilix#1391]
Heya.. I am using a git version listed as 1.7.1.r45.f678d3c (I built from a commit f678d3c... presumably).

I love tilix but during long compilations, it suddenly crashes often.. only terminal which happens. rendering not really usable imo. I am not sure if it is if sufficient large scrollback (compiling qt5 or some other large package), overflows or so and then exits.. I haven't straced as usually I am not too keen in rerunning a massive comile just to to redo it :)

Although if it's needed, I guess some day when I have time I could try and reproduce and do a strace or so.
Let me know if any other things may help. ( I am trying ot upgrade dlang stuff to get the newest version but it's a bit of a laugh when ldc/phobos complain about not having tghe old libs, when compiling the new :))

**Comment by gnunn1** [comment]
That's an old version, there have been a number if stability improvements in Tilix since then as well as supporting libraries. Please use the latest version and I think you will find it's much better.

**Comment by lulcat** [comment]
heya gnunn1. yes, I managed finally to fix the issues of compiing to newer versions, but again D plays up so much.. I realyl wished ot write some of my OS in it (init sections, service manaager etc.) but ok.. anyway, digression. I will compile tilix and use it for a while and see if it happens again. I hoe so. 

Oh and for the record, I found it amazing : perfect, I intend(ed) before this usse to make it a default terminal for this "distro".

**Comment by lulcat** [comment]
I am on an arch-like derivative, but ye.. I could compile clang and a fair amount of compilatons and no sudden die.. however, when I interrupted a process in a tile, it closed... then I typed exit latyer on in a tile and now I can no longer open more tiles.. (closing more or not), it just flashes and no new tiles will appear.
Iliblphobos doesn't seem 100% sane though so I will test more and see if it can be any D related installation). This can be closed for now, and I can rather open a new ticket later on as you are busy enough withotu more details. Thanks.

**Comment by gnunn1** [comment]
If you are on an arch derivative why not just use the packages from arch?

**Comment by lulcat** [comment]
I believe I did try and still would segfault far into builds. I will try again, as I would love it to be a defualt shell but if it still fails like that it's not possible. It can be the underlying gtkd or D itself, which I suspect of course, as I don't think it's your code. To the question: it would be like asking ubuntu why they don't use debian packages.
