### ISSUE TITLE
Quake mode options

### ISSUE THREAD

**Issue by ddnexus** [gnunn1/tilix#1393]
Quake mode is great but there are a few options that would make it more usable:

1. Is there any possibility to add the usual drop shadow around the window? It may be quite difficult to distinguish the Tilix window from some other background window that has the same background color (and possibly the same text color).

2. What about an option allowing a bottom-aligned window, instead the top-aligned one?

3. Possibility to resize the height while open?

4. You can actually move or resize the window with shortcuts, but its state is not persisted, despite the option "Save and restore window state".

**Comment by phw** [comment]
> Option about size-able height?

You can already configure height and width of the quake window in Tilix' preferences. Or did I misunderstand the question?

**Comment by ddnexus** [comment]
Sorry, I didn't explain it well. I meant _live capabilty_ not actually _option_, i.e. while the quake window is open, changing it live...
I will edit the original post to make it clear. Thanks.

**Comment by gnunn1** [comment]
The quake window is meant to be a special window emulating the quake style console you find in games, it's not meant to be used with a regular terminal window which is what those options you are asking for are geared towards.

1. No there is not, supporting it means it becomes a regular window with all the normal window abilities like dragging the window around the screen, etc. This sin't what quake mode is about
2. I'm OK with this
3. The window mode doesn't support this so no
4. The quake mode size is controlled by the options on the quake page, the save and restore window state is for normal terminal windows.

**Comment by ddnexus** [comment]
Gerald, thanks for the answer. 

I understand what you say, however the most useful feature of the quake mode is the fact that it is always available with a shortcut, certainly not its limitations as a window. To me it would be still more than OK - if not better - even as a normal window... if it would be always available with a shortcut (i.e. behaving as the quake window without the current window limitations).

Anyway, despite the window mode, one is still able to resize the window by using the shortcut (e.g. Alt-F8). In that case if its size would change the settings (when the options "Save and restore window state" is checked) it would be quite useful without detracting anything.

**Comment by gnunn1** [comment]
In Preferences | General set the New Instance option to "Focus window". Then configure a shortcut in Gnome to run```tilix``` instead of ```tilix -quake``` and that will you to focus the window with a shortcut.

**Comment by gnunn1** [comment]
I've added the bottom window option, as mentioned I have no plans for further changes at this time.
