### ISSUE TITLE
First character of first line can not be copied to clipboard

### ISSUE THREAD

**Issue by sowosama** [gnunn1/tilix#1394]
Hi devs,
when tilix is used with a second vertical terminal opened, it is not possible for me to mark the first character from the right terminal because the mouse pointer changes to the "double-pointer" type for resizing terminals.

Do you see any resolution for this problem?

Thanks a lot, Peter

**Comment by gnunn1** [comment]
It's an issue with the way gtk manages splitters. In Preferences | Appearance check the Use wide handles option.
