### ISSUE TITLE
[ Feature request ] Window Blur

### ISSUE THREAD

**Issue by ask6155** [gnunn1/tilix#1396]
Hello!
I've been using Tilix for a while and I love it.
it would be nice to have window blur as a feature.
it would be managed by the theme but you could manually set the amount of 'blurriness'
I use Deepin where all window panels have blur so it would look good with it.
of course, you could set it to not blur the window as a setting.

**Comment by gnunn1** [comment]
Gtk 3 and cairo do not currently support blur, when they do I'm happy to revisit.
