### ISSUE TITLE
Quake mode window hidden behind top bar in stacked dual monitor set-up

### ISSUE THREAD

**Issue by grooveborg** [gnunn1/tilix#1397]
Hello,

I am using a vertically stacked dual monitor set-up with the primary display set to the bottom monitor. When I activate the drop down terminal, it doesn't seem to account for the position of the top bar, and appears behind it. There is no issue when the primary display is set to the top monitor.

Thank you for your time.

![tilixquake](https://user-images.githubusercontent.com/29585369/39667065-04ecafda-507c-11e8-827d-df4d50d21ea9.jpg)

**Comment by gnunn1** [comment]
This is a gtk issue, I have opened an issue here:

https://gitlab.gnome.org/GNOME/gtk/issues/1086
