### ISSUE TITLE
Sporadic VTE Configuration Prompt using fish

### ISSUE THREAD

**Issue by cg505** [gnunn1/tilix#1399]
#481 discusses how fish should be compatible with VTE's expectations (which it usually injects via etc/profile.d/vte.sh). This works perfectly fine, but sometimes I will still receive the "Configuration Issue Detected" dialogue box when starting a new tilix window. Even when this happens, the VTE features still work (splitting maintains current directory).

I don't really have a way to reliably reproduce this except starting a bunch of windows and hoping it will happen to at least one. Is there any info I should try to capture when this happens to help find the bug?

**Comment by gnunn1** [comment]
I don't test with fish but sounds like a timing issue of some sort. If you want to track it down you would need to compile tilix with debug info. Otherwise I think there's a checkbox on that dialog to disable the warning.

**Comment by gnunn1** [comment]
I'm going to go ahead and close this, as mentioned I do not specifically test with fish and unless someone wants to spend the time to track it down there's no need to leave this open.

Workaround is to simple disable the dialog with the checkbox once you confirm it is actually working.
