### ISSUE TITLE
Color theme matcher logic issue

### ISSUE THREAD

**Issue by cg505** [gnunn1/tilix#1400]
Check out [ColorScheme.equalColor()](https://github.com/gnunn1/tilix/blob/master/source/gx/tilix/colorschemes.d#L86). Suppose we are comparing against a theme that is the same as ours, but it also has `useCursorColor`, `useHighlightColor`, `useBadgeColor`, or `useBoldColor` (and `this` does not). Since we only check the instance variables, we don't catch the discrepancies and so the match will appear valid.

I ran into this when tweaking some themes and it was really counter-intuitive and should be pretty straight-forward to fix.

**Comment by gnunn1** [comment]
I have fixed this and re-worked a few things at the same time as I noticed a couple of other bugs. Please do test this out, the color code is a bit ugh and could really use a rewrite but didn't go that far this time, would appreciate some validation that I didn't break anything.

**Comment by cg505** [comment]
Seems to be working pretty nicely. Thanks for the update!
