### ISSUE TITLE
[Question] Divide by 4 in command line

### ISSUE THREAD

**Issue by diogocalgaro** [gnunn1/tilix#1403]
Hi, just a little question that I cannot find in manual.

I want to divide into 4 terminals, just like this screenshot, in a bash script.

![screenshot_20180507_074117](https://user-images.githubusercontent.com/8246699/39698186-30c8d224-51ca-11e8-8c62-13ee40001071.png)

I tried:

`#!/bin/bash`
`tilix --maximize &`
`tilix -a session-add-right`
`tilix -a session-add-down`
`tilix -a session-add-right`

But it divides like this:

![screenshot_20180507_074436](https://user-images.githubusercontent.com/8246699/39698259-8c2da0f4-51ca-11e8-8e42-2fab2bddadf4.png)

**Comment by gnunn1** [comment]
You can't using the command line because each new split focuses that terminal and the next split happens off of that.

A better option would be to create the layout you want and save the session. You can then load it as needed using the --session command line switch.
