### ISSUE TITLE
VTE Configuration the fix don't work

### ISSUE THREAD

**Issue by mic-rigaud** [gnunn1/tilix#1406]
Hello,
I always have the message which explain that i have to go on this website to fix the problem: https://gnunn1.github.io/tilix-web/manual/vteconfig/

However, even if i do the fix explain on this web page nothing change... I don't understand what I can do...

I am on linux Mint 18.3. I use zsh. I have on the end of my zshrc : 
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
And I fix the link in /etc/profile.d/vte.sh

Thank you.

**Comment by gnunn1** [comment]
Are you just getting the warning or is the configuration actually not working? You can determine if the configuration is not working by opening tilix, using the ```cd``` command to switch to a different and then splitting the terminal. If the new terminal has the same directory as the old one the configuration is working, if the new terminal is in your home directory then it is not.

If the configuration is working and it's just a case of receiving the warning you can disable it using the dialog box. If the configuration is not working then I would suggest asking the question in a form for your distro as gnome-terminal would have the same problem and require the same fix.

**Comment by mic-rigaud** [comment]
I did the test, and the configuration is working. I disable the warning message.
Thank you very much and sorry for the interruption. :)
