### ISSUE TITLE
Command  tilix -a terminal-save from console works, but in all cases show file chooser dialog

### ISSUE THREAD

**Issue by glowingsword** [gnunn1/tilix#1407]
Command  

tilix -a terminal-save

from console works, but in all cases show file choosing dialog. 

I want to be able to save terminal output from tilix with cli command with path to output file as a argument of this command. Can you add an additional parameter for this?

**Comment by gnunn1** [comment]
As per the documentation, I only support a limited set of actions:

https://gnunn1.github.io/tilix-web/manual/cliactions/

I don't have any plans to change this since AFAIK the action framework doesn't provide a way to support generic parameters.
