### ISSUE TITLE
"Process completed" notifications with fish

### ISSUE THREAD

**Issue by wehlutyk** [gnunn1/tilix#1410]
I'm trying to get the "process completed" notifications working with fish.

On Arch Linux, after having installed [`vte3-notification`](https://aur.archlinux.org/packages/vte3-notification), in bash I can `source /etc/profile.d/vte.sh` and "process completed" notifications will work. (`sleep 3`, switch to another window, and I get a desktop notification when the process ends.)

Now with fish, there is the possibility of using the [VTE rewrite for fish](https://github.com/fisherman/fish-vte) mentioned in #481 (after rewriting the perl part to rely on perl5, see fisherman/fish-vte#2). But I'm not sure how this should be sourced, as asked in fisherman/fish-vte#1 (and lots of exploration led to nothing).

There is also another possible route, described in fish-shell/fish-shell#1382 and implemented in @TeNNoX's [gist](https://gist.github.com/TeNNoX/e027e5daabe4997093a49873411f5c0e) for Pantheon (to be [fixed](https://github.com/fish-shell/fish-shell/issues/1382#issuecomment-248642708) to use dbus instead of `notify-send`). Would you recommend doing something like that instead? In that case, is there maybe a dbus event that Tilix listens to for this?

EDIT: mention `notify-send` → `dbus` fix for the gist

**Comment by gnunn1** [comment]
It should be done the same way that the Fedora patch for VTE does it, but output a custom OSC code that the patch reacts to and triggers an event. This is the mechanism that tilix supports, I don't think getting this to work in fish should require a specific patch to VTE beyond what the Fedora patch provides, it's just a case of getting fish to emit the same code.

This is something that you should ask the fish folks about, if you open an issue there feel free to link it here and I will keep an eye on it.

I do not have any plans to support dbus notifications, it's too limited as it only works on the local system with no way to make it work over ssh.

**Comment by gnunn1** [comment]
BTW the VTE notification issue describing the Fedora patch can be found here:

https://bugzilla.gnome.org/show_bug.cgi?id=711059

**Comment by wehlutyk** [comment]
Makes sense, thanks for the details. I'll see what I can get working using that route and report here if I have news.

**Comment by philn** [comment]
Any news about this?

**Comment by wehlutyk** [comment]
Sorry nope, haven't gotten around to it and probably won't be able anytime soon... Feel free to pick up where it stopped!

**Comment by BarbzYHOOL** [comment]
:'(
