### ISSUE TITLE
Quake mode: always appear on primary screen

### ISSUE THREAD

**Issue by mlahaye** [gnunn1/tilix#1414]
Hello,

It would be great to have an option "Always on primary screen" for the quake mode - the same way Guake does it 

![screenshot at 2018-05-17 14-44-20](https://user-images.githubusercontent.com/13317330/40200023-cdbc7cd4-59e0-11e8-9fe6-9871555a89c0.png)

The issue is that when I'm moving and plugging/unplugging external monitors (that I use as primary display), the display number changes and sometime tilix will show up on the laptop screen instead of the external monitor

This is a minor quality of life change - thanks for that awesome terminal!

**Comment by computorist** [comment]
:+1:

**Comment by gnunn1** [comment]
Please test this out when you get a chance.

**Comment by mlahaye** [comment]
Sorry for the late answer @gnunn1 - it works great, thanks for implementing this!
