### ISSUE TITLE
Backup and restore configuration from file

### ISSUE THREAD

**Issue by RealOrangeOne** [gnunn1/tilix#1415]
I use Tilix on multiple computers, and syncing config is a PITA! It'd be nice if there was a way to export configuration, and import it. Using `dconf dump` I can do this for some of the config, but it looks like some (primary shortcut config) is missing. Is this stored somewhere else? Many applications read configuration from file, reading from dconf is annoying, but acceptable. I dug around a little and couldn't find any sign.

This is less an issue in the application, more a request for some help.

**Comment by gnunn1** [comment]
See #571 for information on how to do this.

**Comment by RealOrangeOne** [comment]
How strange, those keyboard entries weren't there when I last tried. Maybe it only dumps to `dconf` on exit (doesnt sound right, but could). Either way, this is resolved now!

**Comment by RealOrangeOne** [comment]
Interesting, looks like `dconf dump` shows different things when run from tilix compared to another terminal (Terminator)
