### ISSUE TITLE
Problem with change profile

### ISSUE THREAD

**Issue by Applemann** [gnunn1/tilix#1417]
I am using:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```
manual installed tilix version: 1.7.9
and I am also using i3wm  version:  4.13 (2016-11-08)

In tilix when I am would like change color scheme to `Orchis`.
But it cannot save or change default profile. And when I open new window or tab so there is the color by old scheme..

**Comment by gnunn1** [comment]
You need to set the default profile in Preferences, see screenshot below.

![screenshot from 2018-05-18 12-36-35](https://user-images.githubusercontent.com/9358238/40246815-26561ac8-5a98-11e8-8208-3dc698ebe94f.png)

**Comment by Applemann** [comment]
@gnunn1 it is not working for me.. see video:
[tilix-video.zip](https://github.com/gnunn1/tilix/files/2017772/tilix-video.zip)

**Comment by gnunn1** [comment]
That's likely an i3 problem, for whatever reason the preferences being saved in dconf (via gsettings) are not being persisted. I can see you add the new profile and the next time you open the Preferences window it is gone and all the settings are back to the default.

Note I only support the Gnome desktop environment, I would suggest asking on an i3 forum about this.

**Comment by jbonnier** [comment]
I'll necro this post but had similar issue end up resolving it resetting dconf

dconf reset -f /
