### ISSUE TITLE
Increase GTK minimum version to 3.18

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#1420]
As I start leveraging more and more features of GTK and VTE it's getting time to stop supporting older versions of GTK. The next release of tilix will be the last that supports GTK 3.14. I will also be looking at stopping support for older VTE releases as well.

This will trigger a bit of a code cleanup as well as checks for older versions will be removed and instead checked once at application startup.

**Comment by kalev** [comment]
I think it would be fine to go directly to 3.22, if that's easier. gtk+ 3.22 is in RHEL 7, Debian stable, Ubuntu, Fedora, Arch, pretty much everywhere.
