### ISSUE TITLE
Tilix don't getting the focus when open in Quake mode. 

### ISSUE THREAD

**Issue by guillefar** [gnunn1/tilix#1421]
So it happened me plenty of times that Tilix console doesn't get the focus when I open it in Quake mode. This is particularly bad when I'm using a browser, specially sites like Jira and Gmail, because single keys do actions on them,  what will happen is that I will be in one of those sites, open Tilix and start writting and all kind of things will happen in the sites (deleted emails, moved tasks), even with just a few key pressed. And even when I'm not in those sites, I often use ctrl-r to search previous command in bash, but that in Firefox will cause a reload of a page, which several times caused me to lose text I was writing in it. 

Fixing this will also probably fix or improve this: https://github.com/gnunn1/tilix/issues/1301 

For the record, this happens with "Always on top" option enabled.

**Comment by gnunn1** [comment]
If you disable the overlay scrollbar in Preferences | Appearance does it make any difference?

**Comment by guillefar** [comment]
No, it doesn't. I restarted the laptop to be sure Tilix was closed for good, but no change.

**Comment by gnunn1** [comment]
I'm not able to reproduce, it's working fine here which doesn't help you much I realize. What DE are you using, Gnome?

**Comment by gnunn1** [comment]
Note I do not support KDE or Budgie DEs, just Gnome. Having said that, I have some thoughts with regards to a few things that may help. If you are willing to be a guinea pig and try a few experimental builds let me know.

**Comment by guillefar** [comment]
Absolutely, glad to help. Let me know how to beta test it.

**Comment by bushong1** [comment]
I'm also having this issue after a recent apt update, and would be willing to guinea pig.

**Comment by juanjol** [comment]
I have been able to workaround this by disabling the "focus stealing feature", following this issue comment: https://github.com/gnunn1/tilix/issues/895#issuecomment-385275324

**Comment by guillefar** [comment]
Thanks @juanjol , that helped a lot.

**Comment by gnunn1** [comment]
I've updated the Tilix quake documentation page here to include the focus prevention stealing issue.

https://gnunn1.github.io/tilix-web/manual/quake/
