### ISSUE TITLE
Bookmarks enhacement

### ISSUE THREAD

**Issue by iax7** [gnunn1/tilix#1424]
The bookmarks feature is so useful, but it could be better if it have a bigger and multiline command input text. In this example, I set proxy environment variables which have newlines that render with a strange character.
![image](https://user-images.githubusercontent.com/6983510/40391028-aa039796-5ddc-11e8-9413-84c503058a7e.png)

**Comment by gnunn1** [comment]
I've increased the width of the dialog, however I will not be adding multiline support. The way VTE works is you just feed it a stream of text, there is no way to guarentee that this screen when using line feeds will be processed as separate commands. If you want to do that please create a bash script file and call that.
