### ISSUE TITLE
1.7.9 - Compile or install on Ubuntu 18.04: pcre2 not supported

### ISSUE THREAD

**Issue by nobeh** [gnunn1/tilix#1425]
I've been trying to get Tilix installed or compiled on Ubuntu 18.04 with no luck.

### Trial 1

Use tilix.zip from release page:

```
$ unzip tilix.zip -d /tmp
$ /tmp/usr/bin/tilix --version
glib.GException.GException@../../../.dub/packages/gtk-d-3.8.2/gtk-d/generated/gtkd/glib/GException.d(41): PCRE2 not supported
```

### Trial 2

Build from source:

dmd:

```
$ dmd --version
DMD64 D Compiler v2.080.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

dub:

```
$ dub --version
DUB version 1.9.0, built on May  1 2018
```

libvte:

```
$ sudo apt-cache policy libvte-2.91-common 
libvte-2.91-common:
  Installed: 0.52.1-1ubuntu1
  Candidate: 0.52.1-1ubuntu1
  Version table:
 *** 0.52.1-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status
$ echo $VTE_VERSION 
5201
```

build:

```
$ dub build --force --build=release
Fetching gtk-d 3.8.2 (getting selected version)...
Performing "release" build using /usr/bin/dmd for x86_64.
gtk-d:gtkd 3.8.2: building configuration "library"...
gtk-d:vte 3.8.2: building configuration "library"...
tilix ~master: building configuration "default"...
source/gx/tilix/terminal/regex.d(153,8): Deprecation: module `std.regex.internal.thompson` member ThompsonMatcher is not visible from module regex
Linking...
```

test version:

```
$ ls -lah $(pwd)/tilix
-rwxr-xr-x 2 root root 20M May 23 23:00 /opt/tilix/tilix
$ ./tilix --version
glib.GException.GException@/home/bnobakht/.dub/packages/gtk-d-3.8.2/gtk-d/generated/gtkd/glib/GException.d(41): PCRE2 not supported
```

- which part am I missing to do properly?
- is this a known issue? any workarounds?

**Comment by gnunn1** [comment]
This because Ubuntu decided to remove the pcre2 functionality from the VTE in Ubuntu which causes this issue with tilix or any other VTE based terminal emulator. It's a poor decision IMHO but it is what it is. Ubuntu apparently maintains a tilix patch to work around this, see #916

**Comment by ejabu** [comment]
> This because Ubuntu decided to remove the pcre2 functionality from the VTE in Ubuntu which causes this issue with tilix or any other VTE based terminal emulator. It's a poor decision IMHO but it is what it is. Ubuntu apparently maintains a tilix patch to work around this, see #916 

after hours of reading and testing, still got no chance to locate ubuntu patch you mentioned

**Comment by sitaramshelke** [comment]
Hey @gnunn1, same as @ejabu , Can you please let us know how to apply the patch you mentioned ?

**Comment by gnunn1** [comment]
I have no idea as I am not an Ubuntu user, please open an issue with Ubuntu since this is their patch.

**Comment by nswarup14** [comment]
Hey,
I was able to workaround this issue by updating my `gnome-terminal` to 3.32 from 3.28 and that updated my VTE from 0.52 to 0.56, which I believe fixed the issue. ([See comment](https://github.com/gnunn1/tilix/issues/916#issuecomment-456872478))

Also the way to update has been described [here](https://askubuntu.com/questions/1140843/how-to-install-gnome-terminal-3-32-in-ubuntu-18-04).
