### ISSUE TITLE
Regex warning in system log

### ISSUE THREAD

**Issue by vadi2** [gnunn1/tilix#1428]
```
Versions
	Tilix version: 1.7.7
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

```
May 28 03:44:25 gooseberry tilix[3949]: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
May 28 03:44:25 gooseberry tilix[3949]: message repeated 5 times: [ (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)]
```

Ubuntu 18.04. Let me know if I can provide any other info about it!

**Comment by gnunn1** [comment]
Please open a bug with Ubuntu, since they patch vte to remove pcre2 regular expressions this issue is likely caused by that.

**Comment by vadi2** [comment]
I should file a bug in Ubuntu saying an application is making use of functionality that is not available?

I don't think they would do much, the issue is tilix attempting to do something it can't on the target platform - hence warnings.

**Comment by gnunn1** [comment]
The issue is because Ubuntu patches VTE to remove functionality but doesn't alter the version in any way. Thus tilix has no way to know that the functionality was removed.

Ubuntu maintains an Ubuntu specific patch for tilix to fix this as they do for other VTE based terminal emulators. This is why this is an Ubuntu specific problem.

**Comment by gnunn1** [comment]
See #916

**Comment by vadi2** [comment]
Fair enough, thanks!

**Comment by adrinux** [comment]
The ubuntu patch fixes a crash on start of tilix, but doesn't fix this issue. Still an upstream issue though, so here's the relevant bug report https://bugs.launchpad.net/ubuntu/+source/tilix/+bug/1785885
