### ISSUE TITLE
Transparet strip 

### ISSUE THREAD

**Issue by csharpdevbeginner** [gnunn1/tilix#1433]
Hello i have problem, i just install tilix and i notice transparet strip under toolbar, also there are no icon for app
![selection_002](https://user-images.githubusercontent.com/35164987/40872826-92ad1186-6655-11e8-90d6-813d31a6a63b.png)

**Comment by gnunn1** [comment]
That's probably a problem with the theme you are using, do you have the same issue with Adwaita?

**Comment by csharpdevbeginner** [comment]
i dont have Adwaita can u send me link with this?

**Comment by gnunn1** [comment]
It's included with gtk, what desktop environment are you using?

**Comment by csharpdevbeginner** [comment]
cinnamon

**Comment by koalization** [comment]
Maybe this helps: #910

**Comment by csharpdevbeginner** [comment]
ok this is my second day with linux i have same difficulties. i think i install gdkt and problem is still occur

**Comment by gbl** [comment]
Same problem here. Using XUbuntu 16.04 patched to the newest version, downloaded the newest (1.8.1) tilix.zip from the Github binary releases page, unzipped to root, ran glib-compile-schemas without any error messages. Getting the same transparent terminal title.

I'm using the Kokodi theme, but switching to any other theme doesn't help.

#910 has a problem with pixbuf libraries, but on my system, libgdk-pixbuf2.0-dev (and non-dev and doc and ....) are all installed.

However, when starting tilix from the terminal, I get the error message:

2018-06-06T19:38:20.591:application.d:loadResources:141 Could not load CSS /com/gexperts/Tilix/css/tilix.base.css

Could this be the reason for the problem?

**Comment by gnunn1** [comment]
Yes that would be the problem, the resources file wasn't properly installed for some reason.

What do you see in ```/usr/share/tilix/resources/```, there should be a tilix.gresource file there. I'm looking at the archive and I see the resource in the archive. I extracted the resource file from the archive and copied it over to the directory and ran tilix with no issue on my end.

**Comment by gnunn1** [comment]
I suspect GTK 3.18 doesn't support @bindingset, I only test with 3.24 so I would not have caught that. Thanks @gbl for narrowing it down.

**Comment by gbl** [comment]
Doesn't seem to be the binding-set, at least not directly. I unzipped the 1.8.1 tilix.gresource and used a hex editor to replace parts of it with spaces. Removing the binding-set declaration did not help, but removing the treeview below it that sets -gtk-key-binding (and leaving the binding-set alone) does.
