### ISSUE TITLE
Feature Request: "Allow bold text" checkbox as in Gnome Terminal

### ISSUE THREAD

**Issue by koalization** [gnunn1/tilix#1434]
Hi. To my surprise I've noticed that the `Allow bold text` checkbox is not available in Tilix. It's easily accessible in Gnome Terminal though, via _Edit->Profile Preferences_ . Is it useful? I'd say it is whenever you set a bold font as the font of choice for regular typing. For example (my favourite fixed-width font is _Inconsolatazi4 Bold_):

As you can see, in Gnome Terminal, it is possible to _un_-check the box, which allows me to see the output of the ls command with the same font-weight (but different colors) as the regular one:
![screenshot_2018-06-02_11-46-40](https://user-images.githubusercontent.com/26254032/40873115-ab7d23b8-665a-11e8-8626-e72854574aa1.png)

With Tilix, I can choose the same font with its bold attribute, but the ls command will show a doubly-bold font, which is a bit awkward to look at (sorry but the resolution of the screenshot doesn't show exactly how different the two are, but it's easy to test it and it's specially noticeable when you zoom in the image):
![screenshot_2018-06-02_11-44-00](https://user-images.githubusercontent.com/26254032/40873122-b1196066-665a-11e8-960c-ba5df58d3842.png)

Not the end of days, but this is one of the first config I make in order to be all set and ready with my terminals. I'd be happy to see this option in Tilix as well. Thanks : )

**Comment by gnunn1** [comment]
It's been deprecated in gnome-terminal and I've followed suit. The setting is still available in dconf.

https://bugzilla.gnome.org/show_bug.cgi?id=795857

**Comment by koalization** [comment]
FYI, I've tried to set that option via _dconf-editor_, but it doesn't work on Debian Stable. Too bad they have decided to make it deprecated, the old saying "if it works, don't change it" doesn't seem to apply anymore these days.
