### ISSUE TITLE
Closing tilix instead of a tab

### ISSUE THREAD

**Issue by focmb** [gnunn1/tilix#1436]
Hi,

when I have two tabs open in tilix and I type _exit_  in one tabe I expect, that the currently selected tab willbe closed but the programm is closed.

You can reproduce this:
- open tilix
- open a second tab
- type __exit__
- you will see, that tilix will be closed, not only the selected tab
- Info:

    ```
    ▶tilix -v 
    Versionen
	    Tilix-Version:  1.8.1
	    VTE-Version: 0.52
	    GTK-Version: 3.22.30

    Tilix-Sonderfunktionen
	    Benachrichtigungen aktiviert=0
	    Auslöser aktiviert=0
	    Badges aktiviert=1
```

**Comment by phw** [comment]
That's probably a crash like in #1432, see #1431 for more details. If it is the same issue recompiling Tilix could help.

What distro is this on and what version of gtkd do you have? How did you install Tilix?

**Comment by focmb** [comment]
Distro: Manjarogtkd
gtkd: 3.8.3-1
Installed via paketmanager (pacman)
Gnome: 3.28.2

**Comment by arvindch** [comment]
Yep, I'm facing the same issue on Manjaro (XFCE, up to date as of 06/06/18). Presumably, Manjaro needs to recompile the binary they are distributing then.

**Comment by gnunn1** [comment]
Please open a bug with Manjaro, as @phw pointed out this is likely because they need to recompile Tilix for the new GtkD version. Arch went through the same process.

**Comment by focmb** [comment]
Updated by Manjaro. Now it works again
