### ISSUE TITLE
Where I can disable !1 & !2 & !3... ?

### ISSUE THREAD

**Issue by tomtobac** [gnunn1/tilix#1437]
I am trying to pass a parameter to my program and inside of one parameter I have `xxxx!4xxx`. When I press enter, `tilix` replaces me that part for `tilix --preferences` and put again the command to be executed. 

How can I disable this feature?

**Comment by egmontkob** [comment]
Looks to me you're hitting "history expansion" of bash, use e.g. `set +H` in `~/.bashrc` to disable the special treatment of `!`. It has nothing to do with Tilix.

**Comment by gnunn1** [comment]
Thanks @egmontkob.

**Comment by tomtobac** [comment]
Thanks @egmontkob ! Very helpful !
