### ISSUE TITLE
More than just "open link" for local file hyperlinks

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#1438]
Now VTE has some support for hyperlinks in the terminal (e.g. type  ls --hyperlink) you can right click files output by it and get "Open Link".

It would be good to get some more options for local files the "Open with.." menu that nautilus has would be a great start.

It would be super handy to be able to single click the links to open them as well, but I guess this might need VTE support.

**Comment by gnunn1** [comment]
Tilix already supports the VTE hyperlinks, if there is a specifc issue with them feel free to open an issue. No plans to support single clicking links, too many issues with. See discussion in past issues about control clicking links.

Finally no plans to support more then Open With at this point, I don't get the feeling it would be used much.
