### ISSUE TITLE
Tab numbers?

### ISSUE THREAD

**Issue by verronio** [gnunn1/tilix#1442]
Hi, is it possible to get the number of the tab position to show up in the tab title, like in iterm2?

**Comment by gnunn1** [comment]
Right now it is not, the session number and count is at the application level when defining custom titles. So right now you can set it in Preferences | Appearances in the Application Title field by including the variable ```${sessionNumber}```. This should probably be moved to session scope.

**Comment by gnunn1** [comment]
After looking at this some more I think I'm not going to make this change. Having the session variables at the application level makes sense and follows the same pattern as the terminal variables.
