### ISSUE TITLE
Question: How to generate the /source/secret* and /source/secretc/*

### ISSUE THREAD

**Issue by Supatier** [gnunn1/tilix#1443]
Sorry if this is unrelated. I'm trying to find `Secret.d` in upstream gtkd but I can't find it. I was going to use it for experimenting with logins and keyrings.
Thanks.

**Comment by gnunn1** [comment]
It's not in upstream GtkD AFAIK, I generated it myself using the GtkD binding generator.

https://github.com/gtkd-developers/gir-to-d

**Comment by Supatier** [comment]
Well..., I made the [binding](https://github.com/Supatier/libsecret-d).
