### ISSUE TITLE
Could tilix be used as an intergrated terminal in vscode?

### ISSUE THREAD

**Issue by Lawouach** [gnunn1/tilix#1444]
Hey folks,

First of all, thank you so much for this awesome terminal, it has become my default on Ubuntu!

I am mostly using VSCode these days and would love to use tilix as its default integrated terminal. I have tried this:

```
    "terminal.integrated.shell.linux": "/usr/bin/tilix",
    "terminal.integrated.shellArgs.linux": [
        "--window-style",
        "disable-csd-hide-toolbar"
    ]
```

While the terminal opens as expected, it doesn't do so inside vscode but as its own window which is not what I would like to happen. But I wonder if this is event achievable considering tilix is a GTK app, not a console app, right?

Is there any interest in this by any chance?

Thanks again :)

**Comment by gnunn1** [comment]
No it can not and I have no interest in doing it. Supporting it would likely mean re-writing the terminal into whatever extension mechanism VSCode uses unless it supports parenting windows from other processes which seems unlikely.

**Comment by Lawouach** [comment]
> No it can not and I have no interest in doing it. 

Well, at least that's straight and clear.
