### ISSUE TITLE
Tilix-Nautilus never works in 64 bit Fedora

### ISSUE THREAD

**Issue by xzj8b3** [gnunn1/tilix#1448]
The extension for Nautilus in Fedora 28 X64 (and earlier versions), is not ' ever visible in the right button menu and therefore unusable!!!!

**Comment by gnunn1** [comment]
It definitely does work, I would suggest opening a bug report with your distribution assuming you installed it from a package provided by them. You can also have a look at issue #1278 as well, under Fedora it looks like there is a tilix-nautilus package you may need to install?

**Comment by xzj8b3** [comment]
The package is installed, but it has never worked!!!! The right button menu never appears

**Comment by xzj8b3** [comment]
Yes thanks, actually lacked dependencies
