### ISSUE TITLE
Tilix "Open in Tilix" right click context menu option missing in Antergos 18.6

### ISSUE THREAD

**Issue by jebinphilipose** [gnunn1/tilix#1449]
I'm using Antergos Gnome 18.6 and I installed Tilix from the default repository by running the command:
`sudo pacman -S tilix`
Everything works fine but the 'Open in Tilix' context menu is missing. Please note that I was using Manjaro Gnome and I installed Tilix with the same command and the context menu was being added automatically. But, that's not the same case with Antergos.

**Comment by gnunn1** [comment]
Do you have the ```python-nautilus ``` package installed?

**Comment by jebinphilipose** [comment]
Yes, that fixed it! I thought `python-nautilus` would be installed by default. Anyway, I installed it and got the context menu. Please close this issue. Thanks for your time!

**Comment by eliorc** [comment]
I stumbled upon here with the same problem - for new users (I'm on Ubuntu 20.04) you should install `python3-nautilus`, as the previous one mentioned here is deprecated
