### ISSUE TITLE
Crash: The local file URI may not include a “#”

### ISSUE THREAD

**Issue by debfx** [gnunn1/tilix#1452]
Tilix crashes when trying to open a a file:// URI that has a # Section.

To reproduce;
* echo 'file:///usr/share/doc/git-buildpackage/manual-html/gbp.import.html#GBP.IMPORT.CONVERT'
* Right click on the link, Open Link

Log output of the crash:

> com.gexperts.Tilix[1361]: 2018-07-04T09:37:29.988:app.d:main:150 Unexpected exception occurred
> com.gexperts.Tilix[1361]: 2018-07-04T09:37:29.988:app.d:main:151 Error: The local file URI “file:///usr/share/doc/git-buildpackage/manual-html/gbp.import.html#GBP.IMPORT.CONVERT” may not include a “#”

Tested with tilix 1.7.9

**Comment by gnunn1** [comment]
Confirmed in latest version as well, I will take care of this. Thank you very much for reporting it.
