### ISSUE TITLE
how to custom the badge's font and font size at theme.json?

### ISSUE THREAD

**Issue by roachsinai** [gnunn1/tilix#1454]
I can set badge color follow docmentation, how about font and font size?

Thanks!

**Comment by gnunn1** [comment]
I also think this should not be a part of themes but rather a separate setting similar to the way the terminal font is handled.

**Comment by gnunn1** [comment]
I've added a setting for the font to the Badge configuration page in profiles.

**Comment by roachsinai** [comment]
Can't wait to get the new release!
