### ISSUE TITLE
"Open Remote Tilix Here" fails if path contains space

### ISSUE THREAD

**Issue by m1cm1c** [gnunn1/tilix#1458]
When in an SFTP location in Nautilus, the context menu provides an option called "Open Remote Tilix Here". Usually, it works and does exactly what it says. However, if the path on the remote side contains a space, the shell is opened in the default location on the remote (usually the user's home directory) and this error message is printed to the terminal:

    bash: line 0: cd: /path/to/location/on/remote/containing/a%20space: No such file or directory

Seems like a string that's not been converted back from URL format.

**Comment by gnunn1** [comment]
@bilelmoussaoui Do you have any time to look at this, no worries if you do not.

**Comment by bilelmoussaoui** [comment]
I will take a look by this weekend. Ping me here again if I ever forget

**Comment by bilelmoussaoui** [comment]
@m1cm1c Can you try this PR https://github.com/gnunn1/tilix/pull/1467? 
You can remove the old extension from `sudo rm  /usr/share/nautilus-python/extension/open-tilix.py` and copy the new file either there or in `$HOME/.local/share/nautilus-python/extensions/`. 
Make sure to close Nautilus using `nautilus -q` and try again. 
Thanks!

**Comment by m1cm1c** [comment]
Doesn't fix the problem but only changes the error message from

    bash: line 0: cd: /path/to/location/on/remote/containing/a%20space: No such file or directory

to:

    bash: line 0: cd: /path/to/location/on/remote/containing/a: No such file or directory

To anyone wanting to check for themself: It's not `sudo rm /usr/share/nautilus-python/extension/open-tilix.py` but `sudo rm /usr/share/nautilus-python/extensions/open-tilix.py`.

**Comment by bilelmoussaoui** [comment]
Can you try this? https://pastebin.com/UHg7fB1r This new version only adds a print function that will print the command used to open the terminal on that specific path. Once the file has been modified. Close Nautilus and open it again using terminal. Copy/Paste the content here. If there's any sensitive information you can hide it. 
I'm pretty sure it's an issue with spaces not being replaced correctly with `\ `

**Comment by m1cm1c** [comment]
When I deploy that file, the option to open a (remote) Tilix (both local and remote option and also the one option given in machine-local locations) vanishes from the context menu. I tried deploying the version you gave me previously just to check because I'm now on a different computer and the option to open a (remote) Tilix appeared again.

**Comment by bilelmoussaoui** [comment]
I'm not sure why this won't work.
See `  ssh -t X@Y cd "/test\ aezae\ aqsdsq" ; $SHELL`. It seems to not be the right way to do this. It has to be  `  ssh -t X@Y "cd /test\ aezae\ aqsdsq" ; $SHELL`

**Comment by m1cm1c** [comment]
What you wrote seems right. However, your newest change doesn't solve the problem either. I still get this error message:

    bash: line 0: cd: /path/to/location/on/remote/containing/a: No such file or directory

**Comment by bilelmoussaoui** [comment]
Let me try some changes locally. Will let you know when there are any new changes. Thanks for testing!

**Comment by m1cm1c** [comment]
@bilelmoussaoui So that newest version actually fixed the problem on your machine? I just deployed the version you merged into master on mine, restarted Nautilus, and checked. I still get the shorter error message where everything after and including the space is missing.

**Comment by gnunn1** [comment]
I might have merged that too early, I'll wait for @bilelmoussaoui to comment.
