### ISSUE TITLE
Load session : load several session

### ISSUE THREAD

**Issue by roumano** [gnunn1/tilix#1466]
Not sure if it's possible, but it's will be great if tilix support to open several session at the same time.
Actually, it's limiting to open only one file on the file chooser "Load Session"

At this moment, if i want to open several session, i need to open one session per one session ...

**Comment by gnunn1** [comment]
This is support from the command line with the ```--session``` parameter where you can specify it multiple times. The UI doesn't currently support it as you noted.

**Comment by gnunn1** [comment]
The file open dialog now supports selecting multiple files.
