### ISSUE TITLE
No issues! - Thank you!

### ISSUE THREAD

**Issue by EmTee70** [gnunn1/tilix#1468]
May be thats the wrong place, but after using Tilix for approximately a year, I am so happy with it!
What I just recently realized, was that it is so easy to change the name of an window!
- Just click on it and you are done. I thought it has to be done via the "settngs"-dialog.
By changing some of the keys it now works perfectly with my Xfce environment.

I thought about the option to maximize a tile just to the maximum possible, when still seeing the other
tiles around by one click, so if you have some processes with log activity open you always see them.
What do you think?

**Comment by gnunn1** [comment]
Thanks and I'm glad your enjoying it using. Unfortunately doing that sort of enlargement isn't really feasible as there would be way too many edge cases to manage. Thus no plans to modify or enhance the current maximized feature in this direction.

**Comment by EmTee70** [comment]
Sorry but I have to re open this :-)
Tilix was in the biggest professional German computer magazine in February, just for your info.

![IMG_20190403_104933_514](https://user-images.githubusercontent.com/16942667/55466309-3bcfb400-55ff-11e9-9e86-bdf927823077.jpg)
![IMG_20190316_095312](https://user-images.githubusercontent.com/16942667/55466310-3c684a80-55ff-11e9-9329-04ec310918a0.jpg)
