### ISSUE TITLE
Scroll tabs by mouse wheel

### ISSUE THREAD

**Issue by OlegZharkov** [gnunn1/tilix#1469]
Dear Tilix dev team, thanks a lot for a great tool! 
Just an addition to https://github.com/gnunn1/tilix/issues/448
It would be very useful, if I could scroll over tabs just by mouse wheel like in gnome-terminal or terminator. Wheel scroll works perfectly fine with "sessions", but doesn't with old-style tabs =( .

**Comment by egmontkob** [comment]
> like in gnome-terminal 

[not anymore](https://bugzilla.gnome.org/show_bug.cgi?id=793824)

**Comment by gnunn1** [comment]
I think this is really in GTKs purview, I do not have any plans to add it myself.
