### ISSUE TITLE
Tilix suddenly not setting groups when loading; ubuntu

### ISSUE THREAD

**Issue by bushong1** [gnunn1/tilix#1471]
When tilix starts, the shell it's running in doesn't have my user groups.  This wasn't a problem last week, and I'm not sure if an update started causing this.

```
$ groups
charles
$ sudo su - charles
$ groups
charles adm docker <etc>
```

I've tried running as login/non-login shell, but nothing is helping. Any suggestions as to what could be causing this?

**Comment by gnunn1** [comment]
What changed in the last week, did you get an update of tilix or something else? What linux distro are you using and what desktop environment, Gnome?

And it's working fine for me here on Arch Linux when I test it. You could try disabling DbusActivation in the desktop file to see if that helps.

**Comment by gnunn1** [comment]
Have you had a chance to try disabling the DBusActivation or otherwise fix the problem?

**Comment by bushong1** [comment]
@gnunn1 sorry for the slow response.  i was waiting until I had time to dig into this issue some more.  Long story short, after further testing on my Kubuntu 18.04 system, the issue appear in Konsole as well as Tilix, which suggests whatever it is wouldn't be related to Tilix.  I created a brand new user on my system, launched with Gnome, had no issues; launched with KDE, and the problem occurred.  I guess something with Plasma updated that broke, but that's not your concern.  If you have any suggestions, I'd love to hear, but otherwise I'm closing this issue.
