### ISSUE TITLE
ctrl+shift+S doesnt save directories

### ISSUE THREAD

**Issue by milisarge** [gnunn1/tilix#1473]
when i want to save a session with spesific directories it saves to json file with that  "directory": "",   so i wont load directories latter time

**Comment by milisarge** [comment]
ok, after sourcing /etc/profile.d/vte.sh to .bshrc it solved, thnks

**Comment by 75re** [comment]
> ok, after sourcing /etc/profile.d/vte.sh to .bshrc it solved, thnks

Thank you! I have the same problem and fix it use your method.
