### ISSUE TITLE
Implement imgcat protocol

### ISSUE THREAD

**Issue by torrance** [gnunn1/tilix#1475]
This is a feature request: to implement imgcat in the same way, eg. iTerm2 does.

imgcat outputs the image contents (in base64) directly to stdout, but with an xterm escape sequence preceeding it of `ESC ] 1337 ; key = value ^G`

The page explaining it is at https://www.iterm2.com/documentation-images.html and the linked bash script for imgcat is there too.

Obviously a 'nice to have', but saves scp'ing images across to a personal machine to be able to first inspect them.

**Comment by gnunn1** [comment]
This would need to be added to VTE which does the actual terminal emulation. You can open a request for it at https://gitlab.gnome.org/GNOME/vte
