### ISSUE TITLE
Glob file support in overrideCommand JSON option

### ISSUE THREAD

**Issue by ConorAAG** [gnunn1/tilix#1476]
I want to open a window tail'ing some log files which have date in name. When i try to use an asterisk '*' as a glob operator in the overrideCommand the window fails to open. If I remove the overrideCommand option then the window is open in the specified directory so overrideCommand is the issue.

Option is specified as follows:

...
"overrideCommand": "tail -f laravel-local-*.log",
...

**Comment by gnunn1** [comment]
If you go into preferences, select the profile you are using and in the Command tab change the option ```When command exists``` from  ```Exit the terminal``` to ```Hold the terminal open``` you will see that your command is exiting immediately hence why the terminal closes.
