### ISSUE TITLE
Install 1.8.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by nathan30** [gnunn1/tilix#1480]
Hi, is it possible to install the last release on Ubuntu 18.04 ?

**Comment by gnunn1** [comment]
https://launchpad.net/~webupd8team/+archive/ubuntu/terminix

**Comment by securisec** [comment]
@gnunn1 trying to use tilix on ubuntu 18.04, but no matter what i am trying, i am running into this error `tilix: symbol lookup error: /usr/lib/x86_64-linux-gnu/libvted-3.so.0: undefined symbol: _D3gio10InitableIFQm11__InterfaceZ` 

i tried referencing #916 to do most of the troubleshooting, but no idea how to overcome this. any help?

version installed is:

```
 *** 1.8.5-1~webupd8~bionic0 500
        500 http://ppa.launchpad.net/webupd8team/terminix/ubuntu bionic/main amd64 Packages
```

**Comment by gnunn1** [comment]
I don't manage packaging, please open a bug with the package maintainer for that package.
