### ISSUE TITLE
Problems with notifications in GNOME shell

### ISSUE THREAD

**Issue by xzj8b3** [gnunn1/tilix#1483]
Known for some time an annoying problem also reported to Gnome Shell

But as it seems to happen only with Tilix you point out also to you hoping you can see a resolution

I get that in Fedora 28 x64 on Gnome 3.28.3 (but it does since the release of Fedora 28), every time Tilix terms an operation freezes the desktop until the notification display rather annoying problem that for a few seconds paralyze the desktop to the Vis Ualization of notification  "Tilix has finished the operation "

**Comment by gnunn1** [comment]
Do you have the same issue with gnome-terminal? Note in the worse case you can disable notifications in tilix if you want.

**Comment by xzj8b3** [comment]
I'll try I hadn't thought of trying

**Comment by gnunn1** [comment]
I think this is a problem with Fedora and not Tilix.

https://bugzilla.redhat.com/show_bug.cgi?id=1575281
