### ISSUE TITLE
[Feature] ergonomic scrolling.

### ISSUE THREAD

**Issue by bartoszek** [gnunn1/tilix#1490]
# Feature suggestion: advanced setting for scrolling ergonomics.
Current behaviour is to scroll single line or whole page, but user focuses on a midsection of the screen rather than reading whole content from top to bottom. It would be nice to have a slider that enables to control how much a page get scrolled when pressing [Shift]+[pageg-up/down] also srolling multiple lines at once would be nice to have :smirk:
![tilix-scrolling](https://user-images.githubusercontent.com/1213348/43834473-85d529e2-9b0e-11e8-8f6f-cb834ed88379.jpg)

**Comment by gnunn1** [comment]
Thanks for the suggestion, I don't have any plans to add this feature at this time as I don't think enough people would be interested in it. Also, it would not be possible to get consistent scrolling behavior at both the command line and in various programs like vim, nano, etc which I think would feel weird.
