### ISSUE TITLE
Cannot INSTALL this f**************

### ISSUE THREAD

**Issue by vitpavlenko** [gnunn1/tilix#1491]
It says "../../.dub/packages/gtk-d-3.8.2/generated/gtkd/gtkd/Implement.d:24:8: error: module meta is in file 'std/meta.d' which cannot be read
 import std.meta;
        ^
import path[0] = /usr/lib/gcc/x86_64-linux-gnu/5/include/d
import path[1] = /home/vitpavlenko/.dub/packages/gtk-d-3.8.2/generated/gtkd
gdc failed with exit code 1."

**Comment by gnunn1** [comment]
What distro are you using, packages for tilix are available for the most common ones, see https://gnunn1.github.io/tilix-web/

How are you building it, with autotools (i.e. configure and make) or with dub? With dub it should be pretty easy:

```
dub build --build=release --compiler=ldc2
```

The instructions for autotools are located here:

https://github.com/gnunn1/tilix/wiki/Building-with-Autotools

**Comment by gnunn1** [comment]
No reply from OP, closing.
