### ISSUE TITLE
feature: custom execute command for child in a saved session

### ISSUE THREAD

**Issue by nicmus** [gnunn1/tilix#1493]
Hello, I would like to suggest the following feature which could speed up my typical workflow.
I had a look in a JSON session file created by tilix where I see many info are stored as current working directory, geometry and other per child options. I think it would be nice to have the key-value pair

"execute" : "my_command"

and execute it as first command in the child pane at session loading.
The reason is that at moment I load the session and manually have to select each pane and give the same commands vifm, vim, etc.

**Comment by gnunn1** [comment]
This is already supported under the ```Layout Options```, you can customize the title and command on a per terminal basis there. Then when you save the session you will see those values persisted in the json file.

**Comment by nicmus** [comment]
ooh, I missed it! That's exactly what I was looking for.
