### ISSUE TITLE
Password dialog shows no entries

### ISSUE THREAD

**Issue by yarons** [gnunn1/tilix#1495]
I configured tilix to launch the password dialog when pressing Ctrl+Shift+P and then selecting the password and hitting enter.

I have several problems:
1. The search field is highlighted instead of the entries so I can't quickly select the entry and hit enter, since this is a design decision I totally respect that although it breaks the flow.
2. The list is empty, I need to make a change (create an entry) so the keychain unlock prompt appears and when I'm done editing the entries appear (including the dummy I've created).

That brings me to the question: in order to use a secure password list I may need to unlock my keychain every time I start tilix?

**Comment by yarons** [comment]
I'm using XFCE :smile: (Might explain this behavior).

**Comment by gnunn1** [comment]
Thanks, yes you need to look into how to make the keyring unlock automatically in XFCE. I'm closing this issue since it's not a tilix specific issue.

**Comment by yarons** [comment]
No problem, thanks :smile:
