### ISSUE TITLE
New feature: Open at the bottom of the screen instead of top

### ISSUE THREAD

**Issue by wesselih** [gnunn1/tilix#1497]
Thanks for the great work. With Ubuntu Budgie I switched from Guake to Tilix and never looked back.
Like Guake, I use Tilix in --quake mode. 
However, one small thing I miss in Tilix is that it always opens from the top of the screen while Guake had a setting to choose opening from the bottom of the screen.
It would be nice if there were an option in the settings (Alignment top / botton) that would allow to select the place Tilix pops up.

Thank you very much
Heinrich

**Comment by BelT327l** [comment]
would be nice...

**Comment by cyfrost** [comment]
I second this. I totally love this option, It's often helpful to type something in the terminal looking at the center or top of a webpage content when the terminal opens from bottom. A very convenient feature, indeed. Would love to see this get added. Btw, I've switched from Guake to Tilix and never looked back. Totally loving it! Thanks for the great work!

**Comment by gnunn1** [comment]
This feature is already there, go to Quake options and set the Window position to Bottom.

**Comment by cyfrost** [comment]
@gnunn1 Thanks for the reply. Unfortunately, I'm unable to find the "Window Position" option you've mentioned.

Here's a screencap of what I see:

![image](https://user-images.githubusercontent.com/12471103/54336318-bf763080-4651-11e9-91e6-3fc1e26e736a.png)

Envrionment:
Ubuntu 18.04 LTS
Tilix installed from repos using ` sudo apt install tilix`

Should I perhaps enable some command-line switches?
