### ISSUE TITLE
Support of word delete shortcut (ctrl + delete)

### ISSUE THREAD

**Issue by bagage** [gnunn1/tilix#1498]
Would it be possible to support `ctrl + delete` shortcut to delete the current word ~~and `ctrl + backspace` for previous word?~~ (cf #1348) 

Currently, ~~`ctrl+backspace` is equivalent to `backspace` (removes one characeter)~~, while `ctrl+delete` inserts characters `5~` instead of deleting word on Ubuntu 18.04.1.

```
Versions
	Tilix version: 1.7.7
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

edit: oops, there is #1348 for `ctrl+backspace`. Keeping this open for `ctrl+delete` issue.

**Comment by egmontkob** [comment]
Both Ctrl+Backspace and Ctrl+Delete generate different input than their Ctrl-less counterpart.

Ctrl+Backspace sends the byte 8 (often denoted as `^H` or `\b`) in the typical case when Backspace generates the byte 127 (`^?`), according to "stty erase" or Tilix's compatibility profile settings. Or, in the less typical case when Backspace generates `^H` then Ctrl+Backspace generates `^?`.

Delete typically sends the escape character (byte 27, often denoted by `^[` or `\e`) followed by the characters `[3~`, Ctrl+Delete sends the escape character plus `[3;5~`.

Handling these in a certain way, like deleting an entire word, is up to the application that receives them, it's not Tilix's realm. For example, for the standard shell `bash` (or any utility using the readline library) you can place these in your `.inputrc` file:

    "\b": backward-kill-word
    "\e[3;5~": kill-word

**Comment by bagage** [comment]
Hmmm, indee I always report an issue to tilix but it's never his fault! You are genuinely right, actually I already add (crtl+left arrow and ctrl+right arrow bindings in my `~/.zshrc` file, but I did not thought it could be related to zsh and not to tilix! Anyway, I've now support for all these bindings thanks to:

```
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^H" backward-kill-word
bindkey "^[[3;5~" kill-word
```

Thanks a lot for the explanation @egmontkob :)

**Comment by algj** [comment]
> Would it be possible to support `ctrl + delete` shortcut to delete the current word ~and `ctrl + backspace` for previous word?~ (cf #1348)

I can make a PR, please tell me what CTRL + Delete should output as a keystroke :3
