### ISSUE TITLE
Preferences on small resolution screen

### ISSUE THREAD

**Issue by svireli** [gnunn1/tilix#1499]
Hi,

I'm using ubuntu budgie on my lenovo x260 1366x768,
There are two problems for me:

1. Because screen has low resolution, when i open preferences and want to edit Default profile, 
i can't see some sections below, for example font section. Window is small, has no scroll and is not resizeable.

2. To increase it's size i changed os's toolbar behavior to auto hide and saw some part of font
section, but when i click to close window top bar is appearing over it, so i can't close it.

**Comment by gnunn1** [comment]
What version of Tilix are you using, currently the preferences screen is 687 pixels high so it should fit on gnome with the activities menu. I reduced the size of the preferences a few versions ago so I wanted to check whether you are on a later version like 1.8.1, 1.8.3 or 1.85. 

Also, can you post a screenshot of your desktop with the preferences window open on the Profile | General page please.

**Comment by svireli** [comment]
I think you are right. I had a fresh install of ubuntu budgie latest version. Now I use Kubuntu and here everything works fine.

**Comment by gnunn1** [comment]
Thanks for replying back, I am going to close this issue.
