### ISSUE TITLE
Shortcut require toggle Maximise Minimise active terminal

### ISSUE THREAD

**Issue by ankurloriya** [gnunn1/tilix#1505]
Hey, This is a nice app I love. 

While using the app I miss shortcut for toggle Maximise Minimise active terminal.
I have checked in shortcut list but I could not find it.
If you could add this it will really help to quick switch and will make work faster.

**Comment by gnunn1** [comment]
Yes, there is already a shortcut for this, see the attached screenshot:

![screenshot from 2018-08-29 09-51-46](https://user-images.githubusercontent.com/9358238/44792152-4447a400-ab71-11e8-85d4-a6350139937b.png)

**Comment by ankurloriya** [comment]
@gnunn1 Thank you now, I found the shortcut help menu.

**Comment by techscss** [comment]
There are 5 steps for this:

1. Go to Settings > Devices > Keyboard Shortcuts
2. Create Custom Shortcuts

   ```
    Name: Tilix
    Command: tilix --quake
    Shortcut: Ctrl + Space (Anything you prefer)
    ```

3. sudo nano .zshrc
4. Add following instructions there

        prompt_context() {
          if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    
          fi
        }
        AGNOSTER_PROMPT_SEGMENTS+="prompt_end"
5. Save and restart terminal

**Comment by shakyasaijal** [comment]
I have done this with keyboard shortcuts. There are 5 steps for this:

1. Go to Settings > Devices > Keyboard Shortcuts
2. Create Custom Shortcuts

    ```
    Name: Tilix
    Command: tilix --quake
    Shortcut: Ctrl + Space (Anything you prefer)
    ```
3. sudo nano .zshrc
4. Add following instructions there

    ```
    prompt_context() {
    if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    fi
    }
    AGNOSTER_PROMPT_SEGMENTS+="prompt_end"
    ```
5. Save and restart terminal
