### ISSUE TITLE
Package update removed Tilix

### ISSUE THREAD

**Issue by kukkuk** [gnunn1/tilix#1506]
Hello,

I've been running Tilix on LinuxMint 18.1 happily for more than a year.

This morning, during normal OS updates, Tilix got removed.

When I attempt to manually install it again, I get this error:
```
$ sudo apt install tilix
[sudo] password for barry: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tilix : Depends: libgtkd-3-0 (>= 3.8.3) but 3.8.2-1~webupd8~xenial2 is to be installed
         Depends: libvted-3-0 (>= 3.8.3) but 3.8.2-1~webupd8~xenial2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Any idea how to fix this?

**Comment by isradelatorre** [comment]
Same issue here using Ubuntu 16.04

**Comment by ed-fruty** [comment]
Have the same issue.

**Comment by ed-fruty** [comment]
As I can assume, in PPA details https://launchpad.net/~webupd8team/+archive/ubuntu/terminix
3.8.3 versions can get only `bionic` users. And what's about `xenial` ?)

```

gtk-d | 3.8.3-1~webupd8~bionic0 | Alin Andrei (2018-08-21)
-- | -- | --
gtk-d | 3.8.2-1~webupd8~xenial2 | Alin Andrei (2018-07-06)


```

**Comment by hotice** [comment]
Sorry about that, it's my fault. I forgot to copy the updated gtk-d package from the test PPA to the Tilix PPA. I just copied the package, it should be available as an update in about 10 mintes. After that you'll be able to update Tilix on Ubuntu 16.04.

**Comment by hotice** [comment]
Well, Launchpad is currently down so this may take longer than I expected.

**Comment by kung-foo** [comment]
Installing `libvted-3-0-3.8.3-1~webupd8~xenial0` and `libgtkd-3-0-3.8.3-1~webupd8~xenial0` directly from https://launchpad.net/~nilarimogard/+archive/ubuntu/test4/+build/15284678 seemed to do the trick.

**Comment by ed-fruty** [comment]
It works, thanks.

**Comment by kukkuk** [comment]
I can confirm that it works again. Thanks for fixing it so promptly!
