### ISSUE TITLE
tilix 1.8.5 fails to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by gnuvince** [gnunn1/tilix#1508]
I downloaded `tilix.zip` version 1.8.5, extracted the zip file and ran `glib-compile-schemas` as indicated in the instructions.  Tilix fails to start and gives this messages:

```
$ tilix
glib.GException.GException@../../../.dub/packages/gtk-d-3.8.3/gtk-d/generated/gtkd/glib/GException.d(41): PCRE2 not supported
```

Distro information:
```
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by gnunn1** [comment]
See #916 for a full explanation, but tl';dr is that Ubuntu decided to patch VTE to remove the pcre2 functionality hence why it fails.
