### ISSUE TITLE
^[[O and ^[[I put into shell on focus change

### ISSUE THREAD

**Issue by zdzichu** [gnunn1/tilix#1510]
Hi,

Tilix seem to implement http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-FocusIn_FocusOut . But the control characters seem to be entered into the shell very often. It's quite annoying and make me often enter "wrong" password (because those control characters are interpreted as a part of password).

**Comment by gnunn1** [comment]
Tilix is using the VTE widget for terminal emulation so it is the one that is responsible for handling this. Please open an issue against it here:

https://gitlab.gnome.org/GNOME/vte/issues
