### ISSUE TITLE
Non default behaviour when double clicking on window title bar

### ISSUE THREAD

**Issue by sirex** [gnunn1/tilix#1511]
I have ultrawide monitor and using gnome tweak tool, globally changed behavior of double clicking on window title bar to maximize window vertically. That works for all windows, except Tilix. When I double click Tilix it does full maximization.

It would be great if Tilix would behave the same way as all the other windows.

```
> tilix --version
Versions
	Tilix version: 1.8.5
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

**Comment by phw** [comment]
I tested this, and it actually does not work with any application using CSD for me. This also includes Tweak itself. So this probably should be reported directly to GTK and fixed there.

Btw, I didn't know about this setting, but as I have a ultrawide monitor myself that would be really helpful if it would work :) Thanks for pointing out this setting

**Comment by sirex** [comment]
Yes, you are right it does not work on other windows too. Found  a GTK bug report:

https://gitlab.gnome.org/GNOME/gtk/issues/539

**Comment by gnunn1** [comment]
I'm closing this, as @phw points out this is a GTK issue and not tilix specific.
