### ISSUE TITLE
Keybinds for profile switching

### ISSUE THREAD

**Issue by mistersister** [gnunn1/tilix#1515]
Hello,

recently I started taking advantage of terminal profiles but I realized that the only way to switch profiles is to right-click the terminal title > profiles > select profile which I find uncivilized.

Would it be possible to add keybindings to switch to previous/next profile? Maybe also to select specific profiles like Switch to profile 1, Switch to profile 2, etc.

Thanks!

**Comment by gnunn1** [comment]
I've added a first stab at this one, it looks like it works well with the profile keybindings being integrated into the shortcuts preferences window under the Profile category. Having said that, my implementation could use some improvements:

a. Look at sorting the top level items alphabetically

b. Current implementation stores the keybinding in the profile, this way when you delete the profile the keybinding gets deleted automatically. Downside is walking through all of the profiles and creating/destroying a new GSettings object to get the keybinding is potentially inefficient especially if someone starts creating lot's of profiles. Not sure if I'm going to change this now or roll it out and see how it goes, some thought required.

Here's a screenshot of the feature:

![screenshot from 2018-09-14 21-08-33](https://user-images.githubusercontent.com/9358238/45580718-5f4d3000-b862-11e8-9f8e-e03e4ffb0643.png)

**Comment by mistersister** [comment]
Good to see you have started working in this. Maybe you could release as is, with a warning that the feature is still experimental?

**Comment by gnunn1** [comment]
It will be in the next release, it's just a matter of whether I want to re-work anything before then.

**Comment by gnunn1** [comment]
This seems to be working well for me so I'm not going to change anything at this point, folks can open new issues if there are problems.
