### ISSUE TITLE
Tilix crashes when launching from Nautilus extension

### ISSUE THREAD

**Issue by hongquan** [gnunn1/tilix#1516]
Since the last month, Tilix has crashed every time I launch it from inside Nautilus ("Open Tilix here" menu item). If I reset all its GSettings keys, it will be launched successfully, but after that, the next time it crashes again.

I'm using with GNOME desktop of Ubuntu 18.04.

**Comment by gnunn1** [comment]
What version of tilix are you using and is the folder you are opening a normal local folder, remote or something else?

**Comment by bilelmoussaoui** [comment]
Can you open nautilus from terminal and paste the logs here? 
First you need to kill Nautilus from running in the background using 
`nautilus -q`
then run it again using
`nautilus`

**Comment by hongquan** [comment]
My Tilix:

```
$ tilix -v                                                        
Versions
	Tilix version: 1.8.5
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

When Tilix crashes again, I will collect the log (I has reset GSettings keys, so it doesn't crash now).

**Comment by hongquan** [comment]
Today I get this log, but not sure if it is the one that makes Tilix crash

```
(tilix:17478): GLib-GIO-ERROR **: 14:44:47.524: Settings schema 'com.canonical.Unity' is not installed
```

I'm open in local folder, not remote, not gvfs virtual mount.

**Comment by bilelmoussaoui** [comment]
Well, not a Tilix issue. You're still having an extension that uses something from Unity...

**Comment by gnunn1** [comment]
Tilix does look for that schema based on whether the XDG_CURRENT_DESKTOP environment variable has the word ```Unity``` in it. Can you run ```echo $XDG_CURRENT_DESKTOP``` and post the output here.

Also if you look in dconf, do you have the schema ```com.canonical.Unity```, I assume no because of the error.

Now this should not cause Tilix to crash because I have this wrapped in a try..except but maybe this isn't effective for some reason.

**Comment by hongquan** [comment]
Hi @gnunn1 

```
$ echo $XDG_CURRENT_DESKTOP                                                                                                       
ubuntu:GNOME
```

There is no `com.canonical.Unity` schema, but there is `com.canonical.unity` (lower case) schema.

**Comment by hongquan** [comment]
Oh, how dconf-editor reports is inconsistent:

![image](https://user-images.githubusercontent.com/314607/45835962-b2792400-bd35-11e8-9dc4-3983dd664d83.png)

**Comment by gnunn1** [comment]
The unity code has been removed with #1514 so I don't think this should be an issue anymore. Any chance you can build Tilix from master and test it?

**Comment by gnunn1** [comment]
No response from OP, I believe this is fixed so closing.
