### ISSUE TITLE
Highlight all option in search

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#1518]
This would make the search much more useful when filtering / in out things from really long stack traces.

Would be good if it was like the search in firefox - highlight all uses a different bg colour to the current highlighted item (think it's yellow in FF).

**Comment by FFY00** [comment]
It's probably best for tilix to just reverse the colors.

**Comment by gnunn1** [comment]
Tilix doesn't implement searching, it just uses the search facility in the VTE widget which is providing the terminal emulation. VTE has an open feature request for this already.

**Comment by petedoyle** [comment]
Since this is the first result on Google, here's the link to the feature request in VTE:
https://bugzilla.gnome.org/show_bug.cgi?id=627886

Has been open since 2010.

**Comment by JonasSprenger** [comment]
The feature requests of VTE are now on Gitlab https://gitlab.gnome.org/GNOME/vte/-/issues/1830
