### ISSUE TITLE
Highlight current pane

### ISSUE THREAD

**Issue by sirex** [gnunn1/tilix#1520]
When terminal titlebar is turned off, there is no way to tell which window is currently active.

If a border would be drawn around terminal pane, then it would be much easier to distinguish which pane is currently active.

Here is an example:

![ekrano nuotrauka is 2018-09-12 15-41-30](https://user-images.githubusercontent.com/297583/45425547-60376380-b6a2-11e8-9bc9-cd453f172407.png)

How would you know which pane is currently active and if you would start typing, where your keystrokes would go?

**Comment by gnunn1** [comment]
You can use dimming to do this, it can be set in the profile color page if I recall correctly. No plans to offer something different.

**Comment by sirex** [comment]
Thanks, the property is called **Unfocused dim** and it is under color tab. It helps a bit, but still, not easy to identify active pane, especially when screen is mostly blank. And I can't dim too much, because I still want to clearly see inactive panes. I like how this is solved in [kitty](https://github.com/kovidgoyal/kitty), with a border around active pane.

Thanks, anyway.

Here is how it looks with dimming:

![ekrano nuotrauka is 2018-09-12 16-45-36](https://user-images.githubusercontent.com/297583/45429301-b4931100-b6ab-11e8-947f-16a91c486441.png)

Slightly better.

**Comment by gnunn1** [comment]
Sorry but that's all I've got, I don't have any plans to add support for outlining the current terminal.

**Comment by edmundsj** [comment]
This was the very first thing I noticed when I just installed tilix - clean, nice, but *what terminal window am I currently using??*
