### ISSUE TITLE
The files path copying is no longer working after upgrade to GNOME 3.30 Nautilus file manager.

### ISSUE THREAD

**Issue by Kerrung** [gnunn1/tilix#1522]
Hi! Thank you very much for your greatest work!
But the files path copying is no longer working after upgrade to GNOME 3.30 Nautilus file manager on Arch Linux.
And I did not have such issues when I using GNOME 3.28.
When I right-clicking on the any file "Copy" in context menu using GNOME Nautilus 3.28, then I can to paste to the Tilix the path to this file such as, for example, '/home/user/anyfilename.tar.xz' and it just works fine with Nautilus 3.28, but when I trying to do the same action with Nautilus 3.30 then, sadly, but I see just that:

![screenshot from 2018-09-12 21-59-18](https://user-images.githubusercontent.com/36989404/45440947-29c80b80-b6d7-11e8-9241-f02fd93200a0.png)

But I want to see that:
![screenshot from 2018-09-12 22-29-44](https://user-images.githubusercontent.com/36989404/45442409-60a02080-b6db-11e8-8f00-2277d302b45c.png)

**Comment by gnunn1** [comment]
Note I will not be able to look into this until Arch Linux updates to 3.30 in stable, should happen in a couple of weeks.

**Comment by Kerrung** [comment]
@gnunn1 
>Note I will not be able to look into this until Arch Linux updates to 3.30 in stable, should happen in a couple of weeks.

You can uncomment the [testing] repository in the /etc/paman.conf
# pacman -Syu
then if you want to return to the stable only repositories you can comment [testing] and
# pacman -Syyuu

**Comment by gnunn1** [comment]
Thanks, unfortunately I use my laptop for work and am not interested in using the testing repo.

**Comment by gnunn1** [comment]
And there is already an issue for this in Nautilus open:

https://gitlab.gnome.org/GNOME/nautilus/issues/634

I believe this is a bug in Nautilus so I'm going to close this issue here.
