### ISSUE TITLE
Keep terminal lines/columns when zooming font

### ISSUE THREAD

**Issue by gnuvince** [gnunn1/tilix#1524]
When using `Ctrl+Plus` and `Ctrl+Minus` to zoom the font in and out, the terminal window itself retains its size, but the number of lines/columns displayed changes, i.e., if I have an 80x25 screen, it does not remain at 80x25 when zooming.

Would it be possible to add an option to keep the same number of lines and columns when zooming?  This is the behaviour of most VTE terminals, e.g., mate-terminal, gnome-terminal.

**Comment by gnunn1** [comment]
I do not believe that resizing the terminal in a tiling terminal emulator is desirable since it affects all of the tiles around it. Terminator behaves the exact same way as Tilix.

No plans to change this.
