### ISSUE TITLE
Feature like a quick command list

### ISSUE THREAD

**Issue by ankurloriya** [gnunn1/tilix#1525]
There should a list with pre-configured commands list. Users can quickly execute it.
It should be on right click or top menu with a shortcut key.

This feature will really helpful. Currently, I use **pet** command tool to manage my commands.

**Comment by phw** [comment]
Isn't the "Bookmark" feature covering exactly this? I use it to store commonly used commands, and quickly access them with  Ctrl+Shift+b

**Comment by gnunn1** [comment]
As @phw notes, bookmarks provides this feature. If you feel otherwise please feel free to re-open the issue with some clarification of what is missing or could be improved.

**Comment by ankurloriya** [comment]
> Isn't the "Bookmark" feature covering exactly this? I use it to store commonly used commands, and quickly access them with Ctrl+Shift+b

Yes, thank you.
