### ISSUE TITLE
I Broke my titlebar :(

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#1528]
I made a mistake and used the install script when I already had tilix installed from the Ubuntu PPA.

I uninstalled both, then reinstalled the one from the PPA.

Unfortunately the background in the titlebar and the spliiter icons are missing, any idea how I can get them back ?

![screenshot from 2018-09-18 21-25-39](https://user-images.githubusercontent.com/179677/45714446-8620a480-bb89-11e8-95cb-9f8a7dc853d2.png)

^ the white bit here is actually transparent, you can see other windows behind it ;(

**Comment by gnunn1** [comment]
You are probably missing the resources file:

```/usr/share/tilix/resources/tilix.gresource```

**Comment by stuaxo** [comment]
I am, I guess that is generated at the end of the deb install ?

**Comment by gnunn1** [comment]
That is correct, it's these three lines in install.sh:

```
# Copy and compile icons
cd data/resources

echo "Building and copy resources..."
glib-compile-resources tilix.gresource.xml
install -m 644 tilix.gresource ${TILIX_SHARE}/resources/
```

**Comment by gnunn1** [comment]
You can just download the release zip file and extract the compiled resource from it and copy it to the right location.

**Comment by stuaxo** [comment]
Cheers, I tried one last thing that worked

```
$ apt remove tilix tilix-common
...[snipped]...
Removing tilix-common (1.7.7-1ubuntu2) ...
dpkg: warning: while removing tilix-common, directory '/usr/share/tilix/resources' not empty so not removed
```

Removed the directory above reinstalled 

```
$ rm -fR /usr/share/tilix
```

```
$ sudo apt install tilix
```

Though, to be fair I think I caused the message with the resource directory trying to fix things :)

Thanks for looking at this.
