### ISSUE TITLE
Tilix Preferences Missing After Set to Borderless

### ISSUE THREAD

**Issue by DanitiKain** [gnunn1/tilix#1532]
I am using cinnamon desktop.  How do I still access the preferences once it is set to Border-less.  I like this look but I can't change settings with this method.

Also is there a way to set tilix to open full screen when launched?

**Comment by bilelmoussaoui** [comment]
`tilix --help`
For full screen `tilix --full-screen`
For preferences `tilix --preferences`

**Comment by DanitiKain** [comment]
https://streamable.com/bxcto

Can an option be made for right click menu to still access the preferences?

**Comment by DanitiKain** [comment]
Also I guess I mean maximized not fullscreen.  Fullscreen removes access to taskbar.

**Comment by gnunn1** [comment]
No plans to add Preferences to the right click menu, it's already getting large enough that I can see clipping in your video. Just run ```tilix preferences``` when you need to.

**Comment by gnunn1** [comment]
```tilix --minimize```

**Comment by gnunn1** [comment]
Sorry wrong switch, it's ```tilix --maximize``` to start maximize. Use --help to see all the options.

**Comment by DanitiKain** [comment]
Yeah I got that figured out after I read the above.  Use --help :).  Only issue now is having it be the default when the program as launched.  As you can see I can't get it to launch with default of maximize.
