### ISSUE TITLE
Badges don't scale with DPI Scaling

### ISSUE THREAD

**Issue by gregflynn** [gnunn1/tilix#1534]
Static text in a badge is scaled properly on 96dpi but the font size doesn't scale at 192dpi

At 96dpi, clock/top bar icons for scale:
![image](https://user-images.githubusercontent.com/295898/45981511-48a59680-c023-11e8-91bf-1a7b0c2245bb.png)

At 192dpi:
![image](https://user-images.githubusercontent.com/295898/45981562-712d9080-c023-11e8-94a7-432775d80d32.png)

**Comment by gnunn1** [comment]
Right now it only works with GTK scaling, i.e. ```GDK_SCALE=2 ./tilix```. I'll have a look on the DPI side to see what can be done.

**Comment by gregflynn** [comment]
`GDK_SCALE=2 tilix` worked after closing all instances of tilix but had the unintentional side effect of making my prompt text doubled again (so quadruple scale?)

right now im setting DPI in the following way with `~/.Xresources`
```bash
            case $2 in
                high)
                    echo "Xft.dpi: 192" > ~/.Xresources
                    cat ~/.Xresources
                    echo "Logout for changes to take effect (Super+Shift+Q)"
                ;;
                low)
                    echo "Xft.dpi: 96" > ~/.Xresources
                    cat ~/.Xresources
                    echo "Logout for changes to take effect (Super+Shift+Q)"
                ;;
                *)
                    cat ~/.Xresources
                ;;
            esac
```

https://github.com/gregflynn/dotsanity/blob/master/bashrc_helpers/dotsan.sh#L59-L75

Have I just gotten lucky with other GTK based apps that they read this too? I know DPI scaling on *nix is a choose your own adventure of hacks

**Comment by gnunn1** [comment]
Frankly it doesn't work right now in Tilix because I'm essentially hand-drawing the badge using Cairo and Pango and I didn't think about DPI scaling. I just need to spend some time looking into it to see what's involved.

**Comment by gnunn1** [comment]
This should work now, needed to use the Pango Context from vte instead of relying on the context passed in.
