### ISSUE TITLE
Command notifications

### ISSUE THREAD

**Issue by mistersister** [gnunn1/tilix#1535]
Hello, this is a question/feature request:

I work a lot with databases by querying, dumping, importing and so on. Things that may take from seconds to several hours and also tend to have several tabs and several terminals per tab so I was wondering if there is any way to have Tilix inform when a command finishes execution.

Like having a systray icon that would show a popup or a way to have it send a system notification informing you that command X has finished.

Is this possible at all?

**Comment by gnunn1** [comment]
Tilix already does this but you need to be using a version of VTE that has the Fedora notification patches. It's available on Arch (vte3-tilix) and Fedora (duh), not sure about other distros. 

If you run ```tilix --version``` it tells you what enhancements the VTE you are using has:

```
Versions
	Tilix version: 1.8.6-0.0.1
	VTE version: 0.52
	GTK Version: 3.24.1

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=1
	Badges enabled=1
```

The ```Notifications enabled=1``` indicates I am using a VTE patched for notifications, if it was equal 0 then I would not be.

**Comment by bersace** [comment]
@gnunn1 do you have a link to the VTE patch ?
