### ISSUE TITLE
Is a Snap package planned?

### ISSUE THREAD

**Issue by NatoBoram** [gnunn1/tilix#1543]
Hello!

Is there any plans to package this application as a Snap? I think this would greatly help to make this application discoverable and installable across most Linux distributions. I'm quite a fan of Snaps myself, after using it for a while, and I was trying to move all my programs to snaps where applicable because of all the advantages Snaps have over traditional packages.

There's relevant information on how to build them on the website : https://docs.snapcraft.io/build-snaps/

**Comment by gnunn1** [comment]
I'm not interested in it but always happy to take PRs for it. In fact, some work has already been done here:

https://github.com/gnunn1/tilix/pull/1430
