### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by alvesadrian** [gnunn1/tilix#1546]
~ ❯❯❯ sudo su -
-bash: __git_ps1: command not found
-bash: __vte_osc7: command not found
[root@x230 ~]# 

workaround doc didnt work on latest arch with zsh (prezto)

**Comment by gnunn1** [comment]
I think the problem is the root user is set to use bash while your personal user is set to use zsh. I'm not sure it is a good idea to change the root user to zsh, I would suggest asking about it on a zsh forum. 

This is not a tilix issue as far as I can tell so closing the issue.

**Comment by adrian-gluu** [comment]
root is using bash only my user is on zsh
