### ISSUE TITLE
When 2 external display are connected to laptop, the tilx shows only 1 row.

### ISSUE THREAD

**Issue by Damian-Badura** [gnunn1/tilix#1549]
The problem is, when connect 2 external displays to my laptop, the tilix shows only 1 row instead of 24.
How can I help to reproduce the problem?

**Comment by gnunn1** [comment]
If you disable overlay scrollbars in Preferences | Appearances and restart tilix does that help?

**Comment by Damian-Badura** [comment]
No, but I consider that this bug is connected to ubuntu 18.04, because when I turn on dbeaver and some error come up, the content is set at minimum size ( 1px is visible ).

**Comment by gnunn1** [comment]
Thanks, this doesn't sound like a tilix issue so I'm going to close this issue.
