### ISSUE TITLE
Tabs in Quake mode

### ISSUE THREAD

**Issue by superbobry** [gnunn1/tilix#1550]
Hello, I have configured Tilix to show tabs on the bottom, and it seems to work in normal mode, but not in Quake mode:

Normal:

![image](https://user-images.githubusercontent.com/185856/46805560-a9440b80-cd65-11e8-87aa-233d19c14242.png)

Quake:

![image](https://user-images.githubusercontent.com/185856/46805602-c547ad00-cd65-11e8-851b-5624b30b9a1c.png)

Is there a configuration setting I am missing?

**Comment by alexwhitman** [comment]
There's another "Tab position" setting in the Quake specific settings.
![tilix preferences_002](https://user-images.githubusercontent.com/422013/46812611-fecfe680-cd6c-11e8-909e-c88deb512b28.png)

**Comment by gnunn1** [comment]
@alexwhitman answered this, the reason it is in two spots is that configuring the location differently in quake mode was a common ask.

**Comment by superbobry** [comment]
@alexwhitman @gnunn1 thanks and apologies for missing the setting. At least know it is searchable on GitHub.
