### ISSUE TITLE
Nautilus Plugin - AttributeError: 'str' object has no attribute 'decode' in get_file_items

### ISSUE THREAD

**Issue by midahenshaw** [gnunn1/tilix#1554]
```
file scheme:  file
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 118, in get_file_items
    filename = file_.get_name().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```
Moved videos from local storage to USB flash drive. Folder hopped before the thumbnailer finished creating an image after the file transfer completed according to Nautilus but USB drive LED indicated that storage fulfillment was still occurring. Moving a number of files around on a USB drive also causes this issue.

**Comment by gnunn1** [comment]
This was fixed in PR 1610.
