### ISSUE TITLE
Issues loading saved sessions

### ISSUE THREAD

**Issue by mistersister** [gnunn1/tilix#1565]
Hello

For some time now, I have been experiencing issues when loading saved sessions.

If I have a session with several tiles, sometimes and on a totally random manner, some tiles will load and then automatically autoclose as if I had CTRL+SHIFT-W them. The thing is that if I try to load the session file again, same thing happens time and time again as if the file had been corrupted.

Inspecting the json file though, all the tiles are still defined in there.

Im using this:

Versions
	Tilix version: 1.8.5
	VTE version: 0.54
	GTK Version: 3.24.1
Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1

**Comment by gnunn1** [comment]
Are any of the terminals in the session running custom commands, if the command exits the terminal will close unless the profile the terminal is using is set to hold the terminal open (see the Command Tab in Preferences | Profiles for the option).

**Comment by mistersister** [comment]
> Are any of the terminals in the session running custom commands, if the command exits the terminal will close unless the profile the terminal is using is set to hold the terminal open (see the Command Tab in Preferences | Profiles for the option).

yes, all terminals run ssh commands to different servers. After changing the setting you suggested to hold the terminal, I can see now that command is failing and also the cause of the failure. 

I think it would be a good idea to have the terminal stay open on failure by default. That way, you can easily see the error and start debugging.

Thanks for the tip. Very helpful as always!

**Comment by gnunn1** [comment]
This setting is the default setting in gnome-terminal which is where most people who start using Tilix are coming from. While I agree it's not intuitive in this context it's what people are used to and I do not have any plans to change it at this time.
