### ISSUE TITLE
Change Keyboardshortcut for opening custom RegEx-Links

### ISSUE THREAD

**Issue by gituser823** [gnunn1/tilix#1569]
Hello,

as far as I know, I can only open Link, that I created a custom RegEx for with Ctrl + click.
Is it possible to remove Ctrl and open the Links directly, when I click on them without holding Ctrl?

If not ,can you please add thsi feature?
Thanks

**Comment by gnunn1** [comment]
It's been discussed in the past, see #1377. As per that I'm not planning on changing it.
