### ISSUE TITLE
Feature Request: A shortcut to toggle maximize restore. 

### ISSUE THREAD

**Issue by HenryHaller** [gnunn1/tilix#1577]
Pretty self-explanatory I hope, I started using tilix recently and I like it but I think it would be much better if there was a way to toggle the maximize restore feature. I like using maximize/restore but I think it would be much better if there was a customizable shortcut for it with a reasonable default. I hope that's not too difficult to do considering that the maximize/restore feature works pretty well already. If this exists already and I just haven't found it please let me know.

Thank you.

**Comment by gnunn1** [comment]
The Maximize shortcut  toggles it, you can set the keystroke of your choice in Preferences | Shortcuts.
