### ISSUE TITLE
Maximise/Minimise Tilix Window [Keyboards shortcut] like Yakuake

### ISSUE THREAD

**Issue by nigawtester** [gnunn1/tilix#1581]
Hi,

Are there any options to minimise/maximise Tilix's window with a shortcut? 
With Yakuake you can setup the shortcut which is quite useful when you depend a lot on using the terminal and you want it up immediately. I'm not sure Tilix has anything like this.

I have implemented a quick workaround to have that in my Ubuntu installation.
**Maximise Tilix and if Tilix is not open, open it.**
`id=$(wmctrl -l | grep -i "Tilix:" | cut -d " " -f1); xdotool windowactivate $id || tilix`

**Minimise Tilix and if Tilix is not open, open it.**
`id=$(wmctrl -l | grep -i "Tilix:" | cut -d " " -f1); xdotool windowminimize $id || tilix`

You can save the commands into two different files called maximise_tilix.sh and minimise_tilix.sh then "chmod +x filename_here" on both and use them for your keyboard shortcuts. I'm using both but probably the first one is the useful one.

**Comment by phw** [comment]
Isn't this the job of the window manager? Most should provide some functionality for this already, which will work for all windows (not just Tilix).

**Comment by nigawtester** [comment]
Yakuake has an option where it sets the shortcut for you to make the window disappear or reappear. See image: [https://images.techhive.com/images/article/2015/09/yakuake_03_f12_key-100617178-large.idge.jpg](Yakuake dropdown)

The window manager as far as I know will minimise/maximise any windows with a shortcut. I wanted a shortcut to maximise/minimise a **specific** window (Tilix's). I work a lot with the terminal and I needed a quick way to show Tilix's window without using Alt+tab or others.

**Comment by gnunn1** [comment]
This is what quake mode does in Tilix, please use that feature as this is what it is intended for.

**Comment by phw** [comment]
@nigawtester For Quake mode you have to setup some keyboard shortcut that runs `tilix --quake`. For my usage I have setup a keyboard shortcut in Gnome as shown here:

![grafik](https://user-images.githubusercontent.com/29852/48823646-e4246080-ed61-11e8-8011-1a42785b357f.png)


@gnunn1 Would it be an idea to allow configuring a global keyboard shortcut inside Tilix? For Peek I have had good access using [libkeybinder3](https://github.com/kupferlauncher/keybinder) for this, it taes care of all the quirky details. Works only on X as there is no way to add a global shortcut on Wayland, but this could be made conditional.

**Comment by nigawtester** [comment]
Thank you for your reply. I didn't know about that option. My bad
