### ISSUE TITLE
Cant use Tilix after uninstalling fish

### ISSUE THREAD

**Issue by jsquardo** [gnunn1/tilix#1585]
I installed fish on Ubuntu 18.04 KDEneon. I made it my main shell. I later uninstalled fish and now whenever I open Tilix I get "Failed to execute child process "/usr/bin/fish" no such file or directory. 

I can use Konsole just fine now in bash but Tilix wont work. Even tried changing profiles.

**Comment by gnunn1** [comment]
I don't support KDE and so I'm not sure what the issue is. However obviously something thinks you are still using fish. Did you configure your profile to directly use /usr/bin/fish in the profile command tab per chance?

**Comment by FFY00** [comment]
Did you properly change your shell with chsh?

**Comment by jsquardo** [comment]
> I don't support KDE and so I'm not sure what the issue is. However obviously something thinks you are still using fish. Did you configure your profile to directly use /usr/bin/fish in the profile command tab per chance?

Yea I changed it do use /bin/bash just to see but then I get the pop up error when I open terminal.

**Comment by jsquardo** [comment]
> Did you properly change your shell with chsh?

Yea. It works in Konsole just not Tilix :(

**Comment by gnunn1** [comment]
Sorry I have no clue what the issue is, I'm closing the issue because I don't think it it's a tilix issue. You could try uninstalling tilix and re-installing it to see if that helps just to reset the settings.

**Comment by lucidyan** [comment]
@jsquardo I think you forgot to change your default console to bash after uninstalling fish. Try that next time:
`sudo chsh -s /bin/bash username`
