### ISSUE TITLE
Mouse reporting

### ISSUE THREAD

**Issue by Veske** [gnunn1/tilix#1588]
Are there plans to implement something similar to Mouse reporting in iTerm2? I guess the main takeaway would be ability to scroll `less` output with a mouse wheel for instance.

**Comment by phw** [comment]
> I guess the main takeaway would be ability to scroll `less` output with a mouse wheel for instance.

I don't know nothing about the technical details involved, but this particular use case already works for me, not only with less but also with vim and nano.

**Comment by Veske** [comment]
Yes now that I less'ed a normal log file it seems that you are correct. I was unable to do the same in a `journalctl -b 1` session tough. It looks like you can scroll in there but I think what it does is scroll between boots instead of the actual boot logs?

**Comment by phw** [comment]
Yes, it also doesn't work with journalctl here. I guess you are correct about this is related to how journalctl handles this, but as I said I don't know the technical details. If this is something that could/should be improved in the terminal emulator it probably would be in VTE and not Tilix.

But let's wait for some feedback from @gnunn1 and @egmontkob :)

**Comment by egmontkob** [comment]
On the normal screen, the mouse wheel scrolls VTE's scrollbar. On the alternate screen, it synthesizes Up/Down keypresses (subject to the Alternate Scroll Mode, enabled by default).

`journalctl` invokes `less` in a way that it does _not_ switch to the alternate screen. Check `less`'s command line option `-X` and the `$LESS` variable, as well as `journalctl`'s `$SYSTEMD_LESS` in its manpage that contains `X`.

@Veske I recommend that you come up with your own preferred `$SYSTEMD_LESS` variable.

**Comment by gnunn1** [comment]
Thanks @egmontkob, that seems pretty reasonable. I'm closing this issue.
