### ISSUE TITLE
Feature Request: option to turn off a "cross" on the tab allowing closing the tab

### ISSUE THREAD

**Issue by ser** [gnunn1/tilix#1589]
In some situations people do not want to have a "cross" allowing them to close the tab. The reasoning is that they keep tabs long term and never want to close them, especially accidentally, and the other reason is that cross takes space which is scarce. 

There should be an option "turn off closing cross on the tabs" in configuration.

**Comment by gnunn1** [comment]
Sorry but no plans to add this as I don't think it would be of general interest and I need to be careful about adding new options.
