### ISSUE TITLE
Quake mode doesn't fit second display

### ISSUE THREAD

**Issue by squadgazzz** [gnunn1/tilix#1591]
Manjaro 18 with Gnome 3.30.
Tilix version: 1.8.5
VTE version: 0.54
GTK Version: 3.24.1

First screenshot - first display. Fits perfect.
Second screenshot - second display. Doesn't fit.
![screenshot from 2018-12-05 17-30-18](https://user-images.githubusercontent.com/22964585/49520070-87718b80-f8b3-11e8-87ca-668647546b6b.png)

![screenshot from 2018-12-05 17-30-38](https://user-images.githubusercontent.com/22964585/49520075-893b4f00-f8b3-11e8-87a1-2fb8088cfe15.png)

**Comment by gnunn1** [comment]
Are you using an extension to make the dock always visible, that's likely where the problem. Tilix relies on an API that returns the workarea on a given monitor, if the tilix is always showing the bar in the secondary window counter to what gnome usually does that may be causing the issue.

If you disable that extension, does it work as expected?

Also, if you maximize a window like gedit in the second display, does it go under/over the dock or work as expected?

**Comment by gnunn1** [comment]
No response from OP, closing bug.

**Comment by squadgazzz** [comment]
Sorry, I didn't have time to answer.
Yes, I'm using Dash to Dock, BUT when I maximize the window it looks ok.
When I disable extension it work as expected of course, but that would be awesome to fix that problem in Tilix.
