### ISSUE TITLE
change font in quake mode

### ISSUE THREAD

**Issue by Wolpres** [gnunn1/tilix#1596]
Hi,
I've just installed Tilix and it's awsome, but when exploring the quake feature I bumped into a bug.
When I tried to change a font in profile settings, it instantly loged me out.
It's not a big deal as I don't suppose a lot of people do that very often and it work just fine in normal window mode, but just FIY.

**Comment by bilelmoussaoui** [comment]
It's not Tilix that logged you out. I assume you're using GNOME with Wayland? It's the only way that you were logged out because Shell might have crashed. You should check the logs using journalctl and see what causes the crash. I think something else did that.

**Comment by Wolpres** [comment]
I tried it few more times and the result was always the same.
Here are few tilix related lines from the journalctl output. After this it killed the system.

![image](https://user-images.githubusercontent.com/36886044/49965679-29c9e880-ff1e-11e8-9764-22c9726041f1.png)
![image](https://user-images.githubusercontent.com/36886044/49965726-49611100-ff1e-11e8-8cd5-e000e6047456.png)
![image](https://user-images.githubusercontent.com/36886044/49965752-55e56980-ff1e-11e8-99cb-22bdda6f6bc7.png)

**Comment by gnunn1** [comment]
Unfortunately I do not support quake mode under Wayland even if you are using XWayland, there's just too may issues getting quake mode working under Wayland properly. If you are forcing XWayland with Tilix, do you see the same issue forcing normal Tilix to use XWayland?

**Comment by Wolpres** [comment]
Sorry, I have no idea what wayland or so means. Do you mean if it does the same thing when I do it in normal (not the quake) mode?
If so... no, as I said, in normal mode it works just fine for me.

**Comment by gnunn1** [comment]
In Gnome you have your choice of backends, either X11 or Wayland (default). When you login in you can switch between the two by selecting the appropriate backend. This screenshot shows how to do it in Ubuntu but it works similarly for most Gnome distributions:

https://i2.wp.com/itsfoss.com/wp-content/uploads/2017/10/switch-wayland-xorg.jpeg?w=800&ssl=1

There is an entry in the log file you show saying the connection to xwayland was lost which is what is making me think you are running under wayland. Quake mode is not supported in Tilix under Wayland anymore though you can force it by running Tilix using the XWayland back-end, i.e.

GDK_BACKEND=x11 tilix

If you are doing this then it is at your own risk, I'm not interested in fixing bugs associated with running Tilix under XWayland when using Wayland.

**Comment by gnunn1** [comment]
I'm closing this issue as I don't think this is a tilix issue that I support since as mentioned I don't support using quake mode in XWayland.
