### ISSUE TITLE
RFE: force cursor to stay visible

### ISSUE THREAD

**Issue by larsks** [gnunn1/tilix#1597]
I'm working  with tmux under Tilix (yeah, I know...) and I keep having my cursor disappear.  I'm not sure what's doing it.  The fix suggest in #1326 resolves it (until it happens again).  I wish there was a "keep cursor visible" option to prevent this from happening.

**Comment by gnunn1** [comment]
As noted in #1326 this is likely due to an application that is mis-behaving. There is nothing in tilix I can do to control this behavior.

**Comment by gnunn1** [comment]
Sorry I should have been clearer, tilix is not a terminal emulator, it is a wrapper around the GTK VTE component which does the actual terminal emulation. It is up to that component to handle this (or not) and Tilix would just take advantage of it if it does so.

Feel free to open an issue with VTE here:

https://gitlab.gnome.org/GNOME/vte/issues
