### ISSUE TITLE
Quake mode doesn't fit second display

### ISSUE THREAD

**Issue by squadgazzz** [gnunn1/tilix#1598]
Manjaro 18 with Gnome 3.30.
Tilix version: 1.8.5
VTE version: 0.54
GTK Version: 3.24.1

Origin: https://github.com/gnunn1/tilix/issues/1591

I really want it to be fixed because it's annoying.

I'm using Dash to Dock, BUT when I maximize the window it looks ok.
When I disable extension it works as expected of course, but that would be awesome to fix that problem in Tilix.

**Comment by gnunn1** [comment]
It's not something that can be fixed, the API that returns the workarea includes the space occupied by the dock. There is no easy way to detect the placement of the dock and account for it.

The only workaround I can suggest is to make the width of the quake window less then 100%.

**Comment by squadgazzz** [comment]
> It's not something that can be fixed, the API that returns the workarea includes the space occupied by the dock. There is no easy way to detect the placement of the dock and account for it.
> 
> The only workaround I can suggest is to make the width of the quake window less then 100%.

How to do it with right align?
