### ISSUE TITLE
Unfocused window transparency

### ISSUE THREAD

**Issue by jokx** [gnunn1/tilix#1602]
Hello,

The Ubuntu 18.10 release of Tilix (1.8.1-1build1 amd64) remove background transparency of unfocused Windows. I mean, when a Tilix terminal is focused, the transparency settings is correctly applied to the background. But, if the windows loose the focus, the background became opaque.

Is this a bug ? A feature ?

Humbly, I'll love to get two transparency level settings, one for focused windows, one for unfocused windows.

Thank you for this wonderful application.

**Comment by gnunn1** [comment]
It works fine for me in Gnome 3.24, I suspect this is an issue with Ubuntu or something with your system. Do you get the same behavior using Adwaita as the GTK theme?

**Comment by chrisjbillington** [comment]
Did you report this with Yaru? I don't see any discussion of it over there.

**Comment by jokx** [comment]
I have produce this report :
https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1809564

I just discovered that bug for Yaru is tracked on GitHub (strange for an Ubuntu project ...). So I go to notify again on Github. (The problem is still present on Disco).

**Comment by jokx** [comment]
https://github.com/ubuntu/yaru/issues/1158
