### ISSUE TITLE
Preferences are not getting saved

### ISSUE THREAD

**Issue by arifzeeshan** [gnunn1/tilix#1603]
Any changes in it are not getting saved after restart. It resets to default.

**Comment by gnunn1** [comment]
Tilix uses dconf to save settings, you can try running tilix from another terminal emulator to see if anything is logged. Also you can check the settings in dconf under the com/gexperts/Tilix folder to see if settings are pretty saved at all or are being reset for some reason.

**Comment by arifzeeshan** [comment]
I tried running from terminal and I can't find anything relevant info on which I can work upon- 
(```
tilix:27049): Gtk-WARNING **: 00:18:37.760: Failed to parse /home/arif/.config/gtk-3.0/settings.ini: Key file does not have group “Settings”

(tilix:27049): Gtk-WARNING **: 00:18:37.766: Theme parsing error: gtk.css:7:10: expected ':'
Fontconfig error: "/home/arif/.config/fontconfig/fonts.conf", line 20: junk after document element
```

**Comment by gnunn1** [comment]
What distro are you using and are you using something like flatpak or snap to run tilix?

Otherwise, please have a look with dconf-editor to see if settings are being updated when you change them in the preferences dialog.

**Comment by arifzeeshan** [comment]
Distro- Arch Linux
No, I am using normal pacman package to install it.

**Comment by arifzeeshan** [comment]
And even changing the preferences via dconf-editor doesn't save the changes, it resets back to defaults.

**Comment by gnunn1** [comment]
This sounds like an issue with your system, I haven't seen this issue previously. Are you using Tilix in Arch and have you installed it using pacman and the tilix-bin package?

**Comment by gnunn1** [comment]
Also, are you using the Gnome desktop environment?

**Comment by gnunn1** [comment]
No response from OP, closing issue.

**Comment by arifzeeshan** [comment]
> Also, are you using the Gnome desktop environment?

No, I am using Xfce desktop environment

**Comment by cm1988** [comment]
> > Also, are you using the Gnome desktop environment?
> 
> No, I am using Xfce desktop environment

I'm having the same issue, did you solved it?

**Comment by cedmos** [comment]
I could solve it by closing the last Quake style terminal (logged out) but preserved a regular terminal window. So I guess it's related to the Quake option.
