### ISSUE TITLE
Reset cwd on new terminals

### ISSUE THREAD

**Issue by teresaejunior** [gnunn1/tilix#1604]
Is there an easy way or option to reset cwd on new terminals that I'm unware of? I have found only instructions for doing the opposite... At the moment, I had to create a function to cd to ~ on every shell startup:

```fish
if set -q TILIX_ID; and test "$TERM_PROGRAM" != vscode;
        and test $PWD != $HOME; and status is-interactive;
    cd
end
```

**Comment by gnunn1** [comment]
Tilix automatically inherits the CWD of the currently focused terminal when you split or create a new session (tab). There is not currently an option to disable that behavior, you could disable sourcing vte.sh which would give you this behavior but could impact some other functionality.

**Comment by teresaejunior** [comment]
No problem, thanks!
