### ISSUE TITLE
Debug noise in nautilus extension

### ISSUE THREAD

**Issue by chrisjbillington** [gnunn1/tilix#1609]
[These two printlines](https://github.com/gnunn1/tilix/blob/f1fc5e08229befffdc21012f7452aeca8145f783/data/nautilus/open-tilix.py#L105) in the nautilus extension produce output whenever running nautilus from the terminal, which can be inconvenient noise if one is using printlines to debug some other nautilus extension.

Since these lines look like they are just for debugging, perhaps they should be removed or put within an 'if DEBUG:' block or similar.

**Comment by gnunn1** [comment]
I've merged your PR, thanks!
