### ISSUE TITLE
Tabs on title bar (client side decoration)

### ISSUE THREAD

**Issue by wiktor-k** [gnunn1/tilix#1612]
Hi,

I was wondering if it would be a good idea to support **tabs on titlebar**.

Currently title bar and tabs occupy two rows but some applications (e.g. Firefox) allow using titlebar for tabs thus conserving a little bit of space.

**Comment by gnunn1** [comment]
Gtk does not have a tab strip control, the closest is the stack switcher and it doesn't look good when using it. If GTK adds a tab strip at some point I'm happy to revisit this.

**Comment by wiktor-k** [comment]
Got it, thanks!
