### ISSUE TITLE
Add gap on terminal

### ISSUE THREAD

**Issue by ahloiscreamo** [gnunn1/tilix#1613]
Hi,
Sorry if this unrelated.

i use urxvt a while back with a script to make a slightly gap on terminal,
so there will be a slight gap on right and left window.
(like a blank gap 3px between the border , see this 

![screenshot from 2018-12-29 22-51-55](https://user-images.githubusercontent.com/9318372/50545339-4c147380-0c4b-11e9-8bd8-4ecda4d267e0.png)

So how do i tweak tilix to do this?
if not can you make an option for that,

Happy Holiday,
Thanks,

**Comment by egmontkob** [comment]
There's no Tilix-specific option for this, but you can configure VTE. See e.g. https://askubuntu.com/questions/115762/increase-padding-in-gnome-terminal.

**Comment by ahloiscreamo** [comment]
Thank you @egmontkob work like a charm!

**Comment by Bananaman** [comment]
There is a better solution here:

https://github.com/gnunn1/tilix/issues/2024#issuecomment-1526880096
