### ISSUE TITLE
Reset and clear

### ISSUE THREAD

**Issue by Wokoas** [gnunn1/tilix#1615]
"Reset and clear" shortcut works badly :
prompt disappears
http://imgur.com/5pOQ2Xgl.png

Is it possible to have an equivalent of "CTRL + L" (clear) and "CTRL + U" (clear line) in one shortcut ?
http://imgur.com/L5hIzGxl.png

Thanks

**Comment by egmontkob** [comment]
(Disclaimer: I'm not Tilix's developer.)

"Reset and clear" is an operation performed by _Tilix_. It does what it says, so clears the screen (even when you have something else other than your shell as the foreground process). Your shell is unaware of this having happened, and thus doesn't repaint the prompt.

"Ctrl+L" and "Ctrl+U" are operations performed by your _shell_ (and as such, only work when you're at the shell prompt). They have no special to Tilix. Maybe you can configure your shell (e.g. bash and readline) to perform both actions on a single keystroke, I honestly don't know.

It's technically a truly nontrivial question whether _Tilix_ could implement the behavior you're looking for. Your bugreport made me think about it a bit, and filed [VTE 84](https://gitlab.gnome.org/GNOME/vte/issues/84).

**Comment by egmontkob** [comment]
Nitpicking: Ctrl+U only clears on the left of the cursor in bash, you're looking for Ctrl+L, Ctrl+U and Ctrl+K, I guess.

**Comment by Wokoas** [comment]
Thanks for your answer.

> Nitpicking: Ctrl+U only clears on the left of the cursor in bash, you're looking for Ctrl+L, Ctrl+U and Ctrl+K, I guess.

Yes, or Ctrl-C + Ctrl-L

**Comment by egmontkob** [comment]
I actually realized that my suggestion doesn't really align with your requirement. It would still be impossible to perform something that's done partially by the terminal emulator on its own, and partially by your shell. E.g. if a "smart clear" (as per the linked bug) is implemented, you'd still be at whichever half-typed command that you have at your prompt.

**Comment by gnunn1** [comment]
I'm not planning on adding a combined shortcut for this as I don't think it's worth the overhead of maintaining it considering it's not something that seems to be commonly asked for.

**Comment by hannes-ucsc** [comment]
Just wanted to say that on macOS Terminal does `Ctrl-K` does the equivalent of `Ctrl-L` followed by `Ctrl-U` so there may be a certain class of users that run into this issue.

I work around this by adding 

```
bind '"\C-k": "\C-u\C-l"'
```

 to my `.bashrc`.
