### ISSUE TITLE
Update translations for 1.8.7 release on Weblate

### ISSUE THREAD

**Issue by sogalgeeko** [gnunn1/tilix#1621]
Hi,

It seems that some translations are not synced on Weblate.
For instance I often check French translations page in order to translate them, with the release of 1.8.7 there is still untranslated string but the Weblate page (https://hosted.weblate.org/projects/tilix/translations/fr/) says it is 100% translated.
Am I missing something ?

Thanks

**Comment by gnunn1** [comment]
I've updated the localizations, french is now showing 96% so I think it's been corrected now.

**Comment by sogalgeeko** [comment]
Thanks, French part is done.
