### ISSUE TITLE
Process-monitor option ignored

### ISSUE THREAD

**Issue by Phaenyxx** [gnunn1/tilix#1626]
Hi,
I tried to enable the "process-monitor" option,  but ``${process}`` in tab / title name still shows as "``Not Enabled``".

Out of the box config on fedora 29, got tilix from a random ``sudo dnf install tilix``
output of tilix -v : 
```Versions
	Version de Tilix : 1.8.3
	Version de VTE : 0.54
	Version de GTK : 3.24.1

Fonctionnalités spéciales de Tilix
	Notifications activées=1
	Déclencheurs activés=0
	Badges activés=1
```
 (Déclencheurs stands for triggerers, rest should be self-explanatory.)

**Comment by sogalgeeko** [comment]
Hi,
This is a hidden option, you have to explicitly enable it via Dconf settings.
Note that in some situations segfault may happen after enabling this option.

**Comment by Phaenyxx** [comment]
Oh my bad. thought all instances of tilix were killed. But one was in a hidden workspace, killing it fixed my "problem". Sorry for the disturbance, have a good day.

**Comment by s4n-gt** [comment]
@sogalgeeko can you reproduce any segfault problem?

**Comment by dogweather** [comment]
> This is a hidden option, you have to explicitly enable it via Dconf settings.

Can anyone be a little more specific? What setting requires enabling? Is there a help doc somewhere?

On Fedora, *Terminal* can display the app/process name out of the box.

**Comment by BjoernDaase** [comment]
@dogweather I had the exact same issue and found out that you have to enable `/com/gexperts/Tilix/process-monitor`.

**Comment by dogweather** [comment]
> @dogweather I had the exact same issue and found out that you have to enable `/com/gexperts/Tilix/process-monitor`.

Thanks! Could you describe how to do that? A CLI command ... or config file edit?

**Comment by BjoernDaase** [comment]
`dconf write '/com/gexperts/Tilix/process-monitor' true`
