### ISSUE TITLE
Add support for vt240(or +) for sixel support

### ISSUE THREAD

**Issue by wagoodman** [gnunn1/tilix#1631]
With vt240 (or higher) support for sixels would allow for utilities like https://github.com/hackerb9/lsix (this sounds like it could be a pretty heavy lift given that this is dependent on vte, which I think doesn't support anything above vt220)

**Comment by gnunn1** [comment]
This would need to be done in VTE and they all have an issue open for sixel support in their issue list.

**Comment by algj** [comment]
As far as I can see - it's now possible to build VTE with sixel support.

Related issue: https://github.com/mate-desktop/mate-terminal/issues/410
