### ISSUE TITLE
Running arbitrary command causes some regex error...

### ISSUE THREAD

**Issue by krishraghuram** [gnunn1/tilix#1632]
My requirement : Exactly same as #1363

So I tried using the "Run custom command instead of my shell" option in Preferences->Profile->Command

This works perfectly...

`bash --rcfile '~/.bashrc'`

But this does not...

`bash --rcfile <(echo '. ~/.bashrc; cd YNOS && source venv/bin/activate')`

When I try to launch tilix, it does not open.
Running from CLI gave me this error which looks like something failed somewhere in regex...

```
(tilix:8517): Vte-WARNING **: 10:49:00.889: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
```

Is there something that I'm missing.... or is this a bug/known-imitation....?

**Comment by gnunn1** [comment]
I can't reproduce the regex error, when I try the following equivalent version:

```bash --rcfile <(echo '. ~/.bashrc; cd ~/Development && source test.sh')```

It works fine however tilix does terminate because the process has ended.

What version of tilix are you using, what is the output of ```tilix --version```.

**Comment by gnunn1** [comment]
No response from OP.
