### ISSUE TITLE
Sudden crash when resizing window

### ISSUE THREAD

**Issue by kodo-pp** [gnunn1/tilix#1639]
Tilix suddenly crashed with a coredump when I was resizing its window. I have never experienced any crashes before, and I can't reproduce this crash afterwards. However, I suppose this crash might have been caused by a bug in tilix itself or in some library it is using, and the coredump might help to find this bug. If nothing suspicious is found, you can close this issue.

If necessary, I can provide you with tilix binary which was installed at the moment of the crash

Coredump download link: https://drive.google.com/file/d/109CADYYeRMplxlrsS1buRdr-UMa0C_xQ/view?usp=sharing

Coredumpctl output and version information: https://gist.github.com/kodo-pp/a0049225953a6b7eaede2dbd877195e9

**Comment by kceb** [comment]
I don't even have the option to resize my window. Ideas?

Ideally I'd be able to hover on the edge of the tile/window and be able to resize. For me, that is easier to control than spamming a shortcut repeatedly to get my desired size.

**Comment by fractalf** [comment]
I experienced the same pressing *SHIFT+CTRL+x* and can't reproduce it. Probably related to https://github.com/gnunn1/tilix/issues/1635

**Comment by kodo-pp** [comment]
I've experienced a few more crashes. Not all of them are related to window resizing, for example one crash happened when I pressed `Ctrl+D` to exit the tmux session (and the whole terminal emulator crashed with a coredump), another one happened when I touched my screen (I have a touchscreen on my PC) and it wasn't like I suddenly pressed a close button — I checked, it was a segfault (in libgtk-3.so). Perhaps I should build tilix from source and try to reproduce some crash in something like a debug environment (if only I find some free time)

**Comment by gnunn1** [comment]
Any chance you have the hidden process monitor feature enabled? It's unlikely but just checking since I know that feature has crash issues.

**Comment by kodo-pp** [comment]
I can't find this feature in preferences. How do I check if it is enabled or not?

**Comment by gnunn1** [comment]
It's a hidden preference that can only be changed using dconf editor, it's called ```process-monitor```. You can use dconf-editor to double check that it's disabled.

**Comment by kodo-pp** [comment]
Thanks for the clarification. This feature is disabled

**Comment by kodo-pp** [comment]
I haven't experienced such crashes anymore (using tilix built locally by `dub --build=debug`, commit 04ff6d012d4c903a7d0b7678d09137b5974b2d4e), so I think this issue should be closed for now. If anything like that happens again, I'll reopen it.
