### ISSUE TITLE
Thank you for adding line height support!

### ISSUE THREAD

**Issue by alalfakawma** [gnunn1/tilix#1641]
Thank you for adding Line height support, this is my favorite terminal ever. The line height is making my terminal and Vim even more sexier than before. Thank you for creating this wonderful software. Also, is there a way to Donate to this project? If not available, I'd suggest you to set it up. :100:

**Comment by gnunn1** [comment]
You are welcome, donations are not accepted at this time but thanks for asking.

**Comment by egmontkob** [comment]
Allow me please to chime in (deliberately having waited for Gerald to comment first).

Aseem, you might be aware that Tilix uses the VTE widget for terminal emulation.

Features that are about terminal emulation or its visual representation, including line height, are features of VTE. VTE is developed as part of the GNOME project, myself currently being its second developer behind Christian Persch. The line height feature was implemented by me, using guidance and code reviewing from Christian, as you can see at [GNOME bug 781479](https://bugzilla.gnome.org/show_bug.cgi?id=781479).

Tilix itself is everything that's "outside" of the terminal areas. It allows you to place multiple terminals next to each other, provides the header bar, menus, settings, and so on, including the ability to conveniently configure the spacing. It's all the amazing work of Gerald, but as far as line height goes, only a tiny fraction of the entire work went into Tilix itself, the vast majority went into VTE.

I don't accept donations at this time either, but you might consider [donating to GNOME](https://www.gnome.org/support-gnome/). Up to you, of course. I believe it's money well spent, and I hope Gerald also endorses this idea.

Thanks a lot for your kind words, it's great to hear positive feedback; and also thanks a lot for supporting GNOME if you decide to do so!

**Comment by gnunn1** [comment]
Thanks @egmontkob, I glossed over the feature he was referring to so great you chimed in. As I've said many times Tilix would not exist without VTE.

**Comment by alalfakawma** [comment]
@egmontkob Thanks for the in depth information, thank you for adding line height support, it has been a long wanted feature, we are grateful that people like you guys exist. Long live VTE, Tilix and GNOME :smile:
