### ISSUE TITLE
Tilix should append name to _GTK_APPLICATION_ID

### ISSUE THREAD

**Issue by 3v1n0** [gnunn1/tilix#1643]
gnome-terminal uses the parameters passed to the default gtk option `--name` to update the app-id so that running with `name=weechat` sets the WM_CLASS and `_GTK_APPLICATION_ID(UTF8_STRING) = "com.canonical.Terminal.weechat"`.

This permits to open a single terminal instance that is matched with a different .desktop file (in this case my weechat desktop file)

**Comment by gnunn1** [comment]
I'm not seeing that behavior with gnome-terminal, when I run it as follows:

```gnome-terminal --name=test```

And then do an ```xprop WM_CLASS``` and click on the window I see:

```
WM_CLASS(STRING) = "gnome-terminal-server", "Gnome-terminal"
```

What am I missing? What version of gnome-terminal are you using, I'm on 3.32

**Comment by 3v1n0** [comment]
Ah, I think this got broken recently... As this was supported until 3.28 (at least with ubuntu patches) for sure but when using `--disable-factory` to disable GApplication to reuse the same app daemon.

**Comment by gnunn1** [comment]
Looking at this blog it doesn't look like gnome-terminal supported it so maybe it was Ubuntu patches that added it?

https://chrisirwin.ca/posts/multiple-instances-of-gnome-terminal/

Anyway, after looking at this further I don't think I will be supporting this as set_wmclass is deprecated in GTK.

https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass

**Comment by 3v1n0** [comment]
ndeed it should not use actual WM_CLASS directly, but what `--name`  under X11 does that under the hood.

Anyways, I've checked a bit, and ubuntu supports this through [this wrapper script ](https://paste.ubuntu.com/p/yzYV87WVmF/), so maybe tilix can reproduce something similar?
