### ISSUE TITLE
Path style on Ubuntu

### ISSUE THREAD

**Issue by kaniawave** [gnunn1/tilix#1645]
Hi all... I am really sorry if this question is "stupid" and it's not so important at the end. 

When I have installed Tilix it looks like this (style/background of the current path):
![image](https://user-images.githubusercontent.com/15866068/52173305-303c4a00-2782-11e9-905c-45c28f9ef29b.png)

And not like everywhere else:
![image](https://user-images.githubusercontent.com/15866068/52173319-78f40300-2782-11e9-9a86-be361ad78dda.png)

I checked all the options like 10x and I don;t know how to enable this design. 
Thanks for help.

**Comment by alexwhitman** [comment]
That's Powerline, not a Tilix feature.  Check out https://github.com/b-ryan/powerline-shell

**Comment by kaniawave** [comment]
Thx! That was it. All the best.
