### ISSUE TITLE
change window name without hamburger menu

### ISSUE THREAD

**Issue by darthoctopus** [gnunn1/tilix#1649]
With the toolbar hidden (e.g. borderless window), there is currently no way in which to access some options in the hamburger menu, in particular changing the window name.

**Comment by gnunn1** [comment]
You can assign a shortcut to the command as per the screenshot below.

![screenshot from 2019-02-17 13-11-56](https://user-images.githubusercontent.com/9358238/52917148-ed1bc400-32b5-11e9-9895-d8073d9c2a3e.png)
