### ISSUE TITLE
ncurses box drawing characters not appearing in Tilix (working fine in Terminal app)

### ISSUE THREAD

**Issue by aral** [gnunn1/tilix#1651]
![screenshot from 2019-02-15 13-44-51](https://user-images.githubusercontent.com/41798/52860667-fc6d0700-3127-11e9-90d3-6470e5f48b9c.jpeg)

Tilix version 1.8.1
$VTE_VERSION = 5401
$TERM = xterm-256color
Encoding: UTF-8
App in screenshots: https://github.com/rgburke/grv

**Comment by f2404** [comment]
Looks like an encoding mismatch issue to me. What is your system locale?
Is "Terminal app" the GNOME terminal? What encoding have you set in it?

**Comment by f2404** [comment]
Do other ncurses apps (like mc) have the same issue?

**Comment by aral** [comment]
![screenshot from 2019-02-15 13-59-12](https://user-images.githubusercontent.com/41798/52861290-f415cb80-3129-11e9-9e59-5026b40082ef.jpeg)

Looks like mc works the same way (correctly) in both so I’m assuming this is actually an issue with grv? 

CC @rgburke

**Comment by f2404** [comment]
My bad, it seems `mc` isn't using ncurses. What about `tig` - does it look fine in both apps?

Can you verify what encoding you have set in Tilix and GNOME terminal?

**Comment by egmontkob** [comment]
Could you please compare all your environment variables whose name contains TERM or CURSES, in Tilix vs. GNOME Terminal?

    printenv | grep TERM
    printenv | grep CURSES

Do you have screen/tmux/byoby/etc. in the game?

**Comment by gnunn1** [comment]
No response from op to @egmontkob question so I'm going to close it. OP feel free to re-open if you want to answer the question.
