### ISSUE TITLE
Invalid custom startup command prevent launch and provides no way to change the invalid setting.

### ISSUE THREAD

**Issue by Pdbrantley** [gnunn1/tilix#1652]
I setup tilix to run a custom command on startup 
`tilix --sessions ~./my.json`
Which I've learned is depreciated and should be
`tilix --session ~/.my.json`

This invalid flag prevents Tilix from starting and I can see no way to change the setting.

Launching tilix from another terminal with the proper flag does not work either.

**Comment by Pdbrantley** [comment]
Nevermind, running
`tilix --preferences`
from another terminal allows the issue to be fixed.

**Comment by egmontkob** [comment]
@gnunn1 You might consider adding a desktop file action for opening the prefs, as we [recently did in g-t](https://gitlab.gnome.org/GNOME/gnome-terminal/commit/a44213e3).
