### ISSUE TITLE
"Layout Options" does not work.

### ISSUE THREAD

**Issue by Pdbrantley** [gnunn1/tilix#1653]
I edit the "command" section of "layout Options" to read
`tilix --session ~/.mySession.json`

Expected behavior:
Opening a new window executes 
`tilix --session ~/.mySession.json`
and loads the sessions saves in .mySession.json

What actually happens:
Tilix loads a default session and opening "Layout Options" shows the "command" box is blank.

Launching
`tilix --session ~/.mysession.json`
from another terminal works as expected.

**Comment by gnunn1** [comment]
Layout options isn't intended to be used for loading tilix with a session file, it's intended to be used to initialize a terminal with a specific command. Using layout options in this way could potentially lead to recursive behavior where each new session in Tilix loads another one.

I don't have any plans to correct this. If you want to default tilix to a session the best way to do it is simply alias the tilix command in bash to load it with the session you want.

If I'm misunderstanding something let me know.
