### ISSUE TITLE
Quake mode hides regardless of focus when 'Hide on focus lost' is On

### ISSUE THREAD

**Issue by anton-z-s** [gnunn1/tilix#1658]
Steps to reproduce:
1. Turn on 'Hide window when focus is lost'
2. Toggle quake mode by shortcut or `tilix -q` in another terminal, it doesn't matter
3. Quake mode is open and **get focus**, i can type in it
4. Terminal hides by itself after the time specified in 'Delay hiding' (even if it 5000)

It hides almost every time. 
Other Tilix settings or Gnome Shell extensions doesn't affect the issue. 
When 'Hide window when focus is lost' is off, the terminal doesn't hides by itself.
The issue doesn't reproduce under a new user. The same problem persists with other GTK drop-down terminals, like Tilda.
Clearly, there is a problem in my config, i would appreciate if you point me in the right direction.

I'm on Xorg, Ubuntu 18.10 (tested with both vanilla (without Canonical patches) and Ubuntu Gnome sessions).
```
Versions
	Tilix version: 1.8.1
	VTE version: 0.54
	GTK Version: 3.24.4
Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

PS. If i run Tilix from terminal, the only messages i get are:
```
(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

(tilix:1587): Vte-WARNING **: 23:20:35.118: (../../src/vtegtk.cc:1954):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
```
I wonder if there is more verbose options for debug.

**Comment by gnunn1** [comment]
I have no issue what the issue is but it doesn't sound like a tilix problem. The only way to get a more verbose debug is too compile it your itself with the tracing flag enabled.

When it hides, is the terminal just sitting there with the caret blinking showing the focus is active? Do you have any extensions enabled in gnome shell, I would try disabling all the extensions and run vanilla shell to see if that helps.

**Comment by gnunn1** [comment]
Any chance you are using autokey like in #1647?

**Comment by anton-z-s** [comment]
Thanks for reply!
I don't use autokey, vanilla shell and disabling all extensions doesn't help.
The issue also happens with Tilda, but not with Guake.
I'm going to close the issue as it is pretty hard to reproduce and it's probably only me.

**Comment by ThomasJRyan** [comment]
Six years later, it wasn't just you
