### ISSUE TITLE
"Warn when attempting unsafe paste" not working?

### ISSUE THREAD

**Issue by f2404** [gnunn1/tilix#1659]
Pasting a text containing "sudo" doesn't produce any warning.
```
$ tilix -v
Versions
	Tilix version: 1.8.9
	VTE version: 0.57
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

Related issue: #666

**Comment by alexwhitman** [comment]
Does the text also contain a line break?  The check at https://github.com/gnunn1/tilix/blob/afdbcfe61991d1b40ae0d757b6f2c316bf712cc9/source/gx/tilix/terminal/terminal.d#L1433 requires the text to both contain `sudo` and `\n`.

**Comment by f2404** [comment]
Right, my bad :(
I only read #666 (it's saying "it only looks for the the word sudo in paste text and warns about it.") and didn't pay attention to the code.
