### ISSUE TITLE
quake on kde with shortcut

### ISSUE THREAD

**Issue by ecocode** [gnunn1/tilix#1660]
INFO ABOUT KDE AND QUAKE MODE.

KDE uses .desktop file to create shortcuts.
If you want to create a shortcut to make quake work, you need to add these lines to /usr/share/applications/com.gexperts.Tilix.desktop:

  [Desktop Action quake]
  Name=Quake
  Exec=tilix --quake

Then add quake action by changing next line as follows:

  Actions=new-window;new-session;quake;

Don't forget you need to turn "Focus stealing prevention" to none to make tilix work on kde.

**Comment by gnunn1** [comment]
Thanks, I'm going to close this since it's not an explanation but a how-to.
