### ISSUE TITLE
Feature Request: saved session sidebar

### ISSUE THREAD

**Issue by esantoro** [gnunn1/tilix#1661]
# Feature request: session sidebar

Hi all, it would be nice to have a session sidebar as in SecureCRT (a proprietary SSH client for Windows/Mac/GNU+Linux).

I have been using SecureCRT for work and I must say that such feature is really a game changer.

Example:  http://www.findsoft.net/Screenshots/SecureCRT-for-Linux-75464.gif

**Comment by esantoro** [comment]
The minimum feature would be being able to save an hostname, a port, and an username.

Otherwise, also being able to save an command to run after the shell is initialized would be good (this command could be the appropriate command to start the ssh client command with the appropriate parameters for a given session).

**Comment by gnunn1** [comment]
Don't you already have this with bookmarks, specifically the SSH bookmarks?

**Comment by esantoro** [comment]
Can I have bookmarks in a sidebar ?

**Comment by gnunn1** [comment]
See #1841 which proposes UI changes to do this. Closing this as a duplicate.

**Comment by esantoro** [comment]
Thank you.
