### ISSUE TITLE
Resource tilix/resources/tilix.gresource could not be found

### ISSUE THREAD

**Issue by floweringmind** [gnunn1/tilix#1664]
I am on Mint Linux 19.1 and installed Tilix 1.7.7 through the app center. Tilix worked perfectly until I tried to add a setting in the GUI to have it start in quake mode. Now it launches and crashes. I get the following error:

Resource tilix/resources/tilix.gresource could not be found

(tilix:3406): Vte-WARNING **: 07:45:40.011: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

I have tried uninstalling and purging from system but I still get the same issue over and over. I have no idea how to resolve this.

**Comment by gnunn1** [comment]
All of the CSS, icons and other resources are stored in that file. I'm not sure why it is not being installed on your machine, you would need to debug the package. Note that I do not do the packaging of Tilix so I would suggest opening an issue with whomever packaged it.

Also note that Tilix 1.7.7 is very old, you should probably look at upgrading to the latest releases.
