### ISSUE TITLE
Latest gnome update ugly menu icon on top bar

### ISSUE THREAD

**Issue by tapir** [gnunn1/tilix#1665]
On Arch Linux updated to gnome 3.2.

 Icon on the screenshot appeared. Is there any way to hide it? It doesn't serve a purpose as everything on the menu can be accessed elsewhere.

![Screenshot from 2019-03-16 20-25-08](https://user-images.githubusercontent.com/223984/54479052-ec7d3b80-4829-11e9-9a98-5d2c5a87b97e.png)

**Comment by gnunn1** [comment]
Fixed in latest 1.9.0 which was just pushed out. Thanks @bilelmoussaoui for taking care of the app menu.
