### ISSUE TITLE
Add support for file preview

### ISSUE THREAD

**Issue by FFY00** [gnunn1/tilix#1667]
Several other terminal emulators support file previewing. I understand this is not trivial but perhaps it would be a good addition to tilix.

Here's an example using [ranger](https://github.com/ranger/ranger) and [urxvt](https://github.com/exg/rxvt-unicode).

![image-preview-urxvt](https://user-images.githubusercontent.com/11718923/54483931-03388800-4854-11e9-9f3b-ffeefdace2cd.png)

**Comment by gnunn1** [comment]
This would be up to VTE to implement since it does the actual terminal emulation. If search their issues I believe it's been requested already.

**Comment by FFY00** [comment]
@gnunn1 not necessarily, [termite](https://github.com/thestinger/termite) is VTE based and does support it.

**Comment by gnunn1** [comment]
It works by a hack, i.e. Ranger is using a library that overlays a window on top of VTE to show the file preview. It doesn't work well IMHO and has issues in Wayland. I played with supporting it at one time but there were too many issues and I didn't want to deal with supporting it.

The best way to handle it is if VTE handled it natively IMHO.
