### ISSUE TITLE
Vte-WARNING

### ISSUE THREAD

**Issue by floweringmind** [gnunn1/tilix#1668]
Versions
	Tilix version: 1.8.9
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1

The program never starts and just outputs this:

(tilix:15493): Vte-WARNING **: 11:05:55.615: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

**Comment by gnunn1** [comment]
I don't have any idea what the issue but off-hand any chance you are using Ubuntu with a version of Tilix you downloaded directly from the website? Ubuntu patches VTE to remove PCRE functionality and thus forces you to use a version of Tilix that they patch.

**Comment by gnunn1** [comment]
No response from OP.
