### ISSUE TITLE
Window doesn't have focus after opening

### ISSUE THREAD

**Issue by tapir** [gnunn1/tilix#1670]
This is new behaviour. I'm on arch and update every other day so I don't know exactly which version caused it.

I'm not convinced this is a tilix issue or tilix have any say on window focus but I've tried other Gnome apps and none of them behaves the same way so just in case here it is:

When I open up a new tilix window it doesn't get focused. I can't start typing directly without clicking the window first. Also if there is a window in front of where the new tilix window will come up it just blocks it. You don't see the new tilix window.

Any ideas?

**Comment by phw** [comment]
I actually have this for all applications since the upgrade to GNOME 3.32. My guess is that this is a gnome-shell issue.

**Comment by gnunn1** [comment]
I think this is a GNOME issue and not specific to Tilix:

https://www.reddit.com/r/gnome/comments/b1n5w2/332_new_windows_do_not_receive_focus/

**Comment by phw** [comment]
It is probably a GTK bug, since only GTK applications on X11 are affected. See https://gitlab.gnome.org/GNOME/gtk/issues/1749
