### ISSUE TITLE
Tilix doesn't launch in case of broken package system.

### ISSUE THREAD

**Issue by anshuman73** [gnunn1/tilix#1671]
OS: Ubuntu Budgie 18.04

Tilix doesn't even launch in case of a broken package system. I even restarted the system, but to no avail. As soon as I fixed the package system via a tty, tilix was up and running again (no restarts in between)

**Comment by gnunn1** [comment]
I don't have anything to do with the packaging of Tilix, please open issues against the actual package in whatever issue tracking system your distro is using.
