### ISSUE TITLE
Keyboard shortcuts are broken with bépo layout

### ISSUE THREAD

**Issue by Toniob** [gnunn1/tilix#1672]
Hi,

The keyboard shortcuts are broken when I use a bépo layout. They do work fine when I'm using an Azerty layout (I'm french). It seems that the key sent is still the azerty version, but only when I try to use shortcuts. For example, CTRL+C is working fine in the bépo layout. But if I try to copy some text, CTRL+Shift+C doesn't work. It's the same with the shortcut to open a new tab : CTRL+Shift+T. If I go in the parameters, and I try to change to shortcut, when I press CTRL+Shift+T, it's the J letter which is detected (T in bépo is J in qwerty/azerty).

If you want to test, just add French / Bépo layout in Gnome, switch to it, and try to use keyboard shortcuts.

Thanks

**Comment by gnunn1** [comment]
I don't think I can test this since changing the keyboard layout requires a keyboard of that type. i.e. changing a US keyboard to the AZERTY layout means keys that I press on my US keyboard won't the same. I would need someone with an appropriate keyboard to test this out and submit a PR.

**Comment by Toniob** [comment]
You don't need a specific keyboard to test another layout. You just need to have the layout next to you (gnome allow to see the layout in the interface).

But you probably won't need to test. I've made a few more searches and it seems like a wayland issue : https://bugzilla.redhat.com/show_bug.cgi?id=1438493 . Wayland apps use the default layout when dealing with shortcuts. I just have to put the new layout as first one to make shortcuts work as expected.
