### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by azmeuk** [gnunn1/tilix#1673]
Some terminals like [kitty](https://sw.kovidgoyal.net/kitty/) or [alacritty](https://github.com/jwilm/alacritty) use GPU for the content rendering. After a few days testing those, I think it is a huge user-experience improvement as everything gets *smoothed*.

I know it is a huge amount of work, but may some GPU rendering be planned some day?

**Comment by gnunn1** [comment]
Tilix uses a component called VTE (https://gitlab.gnome.org/GNOME/vte) to perform terminal emulation, this is something VTE would need to support. It's not something tilix can do on it's own.
