### ISSUE TITLE
iterm python API

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/tilix#1676]
The iterm python API is interesting, I wonder how much there is + how hard to implement in tilix ?

The behaviour someone implemented here using it is pretty impressive
https://twitter.com/orta/status/1109797317069209600

![image](https://user-images.githubusercontent.com/179677/54886877-e66c0800-4e84-11e9-9e0a-802fdbd8f68b.png)

**Comment by gnunn1** [comment]
The way to do this IMHO is via a DBus API rather then tying it to a specific language. There is an issue open already for creating a DBus API but it's unlikely to materialize unless someone wants to take that work on as I don't have much interest in doing it.
