### ISSUE TITLE
SSH termination crashes Tilix

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1677]
v1.8.9

I just had two Tilix windows open, with one holdung an SSH connecting to my FreeNAS. I then pressed the power button of my FreeNAS, so I got thrown out of that connection a few seconds later (the prompt changed back to my local prompt). So far, so good. But maybe 10 to 20 seconds later (about at the time where the server finally shut down), all Tilix windows crashed – while I did nothing else, not pressed any button, not even moved the mouse.

I know this is not the best description, but it’s hard to get more output out of a crashing terminal emulator… :/

**Comment by gnunn1** [comment]
I don't think this is reproduceable and there's little point leaving the issue open, if someone can reproduce it feel free to post the steps and I'll have a look.
