### ISSUE TITLE
Opening up multiple sessions, closing random window messes up index 

### ISSUE THREAD

**Issue by perfecto25** [gnunn1/tilix#1680]
Running on centos 7 x64
Tilix 1.8.9

Not sure how to recreate it, but I noticed if I open up 4 or more sessions (clicking + sign on top left), working in various windows, will close 1 session (from same top left drop down), when I go to other windows, it doesnt show the correct window, feels like the window index is incorrect. 

I will try to get solid testing steps to reproduce, hard to tell the sequence of actions to get it to break.

**Comment by KresoDenis** [comment]
same here. at some point by pressing F12 i can see all open terminals and switch with arrows between thumbnails, but when i press enter to actualy switch on it it either doesnt do anything or it switches to wrong terminal.

it looks to appear after closing one window (with exit on terminal) i think.
