### ISSUE TITLE
Quake menu appears behind gnome dock using multiple screens

### ISSUE THREAD

**Issue by JasMich** [gnunn1/tilix#1682]
OS: `Linux 5.0.0-7-generic #8-Ubuntu SMP Mon Mar 4 16:27:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
GNOME: `GNOME Shell 3.32.0`
Tilix:
```
Versions
	Tilix version: 1.8.9
	VTE version: 0.56
	GTK Version: 3.24.7

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```
Tilix quake menu `--quake` appears behind the Gnome dock on the left side of the primary screen. This makes the left part of the terminal window useless.

![Tilix-Gnome-multi-screen](https://user-images.githubusercontent.com/29313398/55319906-3a26b480-5476-11e9-960e-b8a4c894bb38.png)

**Comment by gnunn1** [comment]
I suspect this is a bug in GDK, Gnome or Ubuntu but I'd need to test. Tilix uses the API gdk-monitor-get-workarea API to get the area of the screen not including the dock and I think it may be returning an incorrect area.

https://developer.gnome.org/gdk3/stable/GdkMonitor.html#gdk-monitor-get-workarea

**Comment by adhuham** [comment]
A temporary workaround for this is to decrease the width by going to the Preferences > Quake.

**Comment by JasMich** [comment]
I anyway switched to the Wayland version via gnome extension. But thanks for this information.
