### ISSUE TITLE
Nested pop-up menus are hard to use with the mouse

### ISSUE THREAD

**Issue by mvz** [gnunn1/tilix#1683]
Tilix uses what I guess are 'new-style' pop-up menus. It seems this style was designed for touch devices, because sub-menus appear at the site of the first mouse click, which tends to be far from their menu item that opened the sub-menu, which is where the mouse is. This makes, e.g., switching profiles extremely tedious.

I can see several possible solutions:
* Use 'old-style' pop-up menus, like Nautilus still uses.
* Make the pop-up menu entirely flat, thus avoiding nested menu items.
* Make Gnome re-design these pop-up menus.

(I'm running Tilix 1.8.9 on Debian, but I don't think there have been any changes to this since then).

**Comment by gnunn1** [comment]
There are no plans to change this, you can open a bug report with gnome if you wish for the third option.

Note that I added support for setting a hot key binding for individual profiles in later versions of tilix, see below for where to find it in Preferences.

![Screenshot from 2019-04-05 15-08-36](https://user-images.githubusercontent.com/9358238/55650846-d6252880-57b4-11e9-82e1-efa086cbf242.png)

**Comment by mvz** [comment]
> There are no plans to change this,

Just to be sure, does this mean you don't ever want to change this, or would you accept a pull request that changes this (in particular, for the first option)?
