### ISSUE TITLE
Random characters Ã inserted

### ISSUE THREAD

**Issue by MonkeyKhan** [gnunn1/tilix#1684]
When typing in Tilix, I will sometimes get random characters in my commands. They are not there when I type but get registered as part of the command and appear in the history.

![tilixrandomchar](https://user-images.githubusercontent.com/23155405/55520446-ac68e600-567c-11e9-8512-b0b3f0634d72.png)
The lower command is the result of pressing 'up' on keyboard.

In .bash_history the command appears as `sudo pÃacman -R gnome-alsamixer`.
In another case I got `bash: $'\303sudo': command not found`, but it appears Ã and \303 are the same character.

This is under Arch Linux using bash. Tilix is set to use UTF-8 Unicode and I'm using a German keyboard layout.

I'm only seeing this issue in Tilix, not any other application I'm using.

**Comment by gnunn1** [comment]
Do you experience the issue using gnome terminal?

**Comment by egmontkob** [comment]
Is your locale also properly set up to UTF-8?

Do you have screen/tmux or anything similar?

octal 303 = decimal 195 = hex C3, which is the Laitn-1 / Unicode codepoint for Ã, and is also the first byte of the two-byte UTF-8 sequences denoting any of the German special letters: äÄöÖüÜß.

At this point I'd guess you have a layer (e.g. screen, or maybe bash itself) configured to Latin-1.

**Comment by MonkeyKhan** [comment]
Yes, you were absolutely right with the locale being the cause it seems.
Sorry for opening this issue.
