### ISSUE TITLE
tilix won't launch "The connection is closed Terminated"

### ISSUE THREAD

**Issue by Char-Aznable** [gnunn1/tilix#1685]
I follow the instruction on the wiki to build tilix 1.9.0 with `dub build --build=release`. But it doesn't launch:
```
Library libsecret-1.so.0 cannot be loaded, related functionality will not be available
Gtk-Message: 11:39:35.814: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:39:35.815: Failed to load module "pk-gtk-module"
Gtk-Message: 11:39:35.826: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:39:35.826: Failed to load module "pk-gtk-module"
The connection is closed
Terminated
```
I tried `LD_DEBUG=libs ./tilix` and it shows:
```
...
./tilix: error: symbol lookup error: undefined symbol: gtk_progress_get_type (fatal)
```
For reference, the GtkD version I'm using: https://github.com/gtkd-developers/GtkD/commit/3396c8a5126d0eade5d79c186464ef7e71e3e8b5

**Comment by gnunn1** [comment]
Are you using the gnome desktop or something else, not having ```libsecret-1.so.0``` would seem to indicate you are not on gnome.

What version of GTK do you have installed?

**Comment by Char-Aznable** [comment]
I'm using the gnome desktop. I want to point out that I installed all the dependency from linuxbrew, including GTK. Gtk+3 version: 3.24.7; Gtk+2 version: 2.24.32_2

**Comment by Char-Aznable** [comment]
I found that installing the tilix via the `install.sh /home/linuxbrew/.linuxbrew/Cellar/tilix/1.9.0` and running it again gives 
```
Library libsecret-1.so.0 cannot be loaded, related functionality will not be available
Gtk-Message: 12:26:57.004: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:26:57.004: Failed to load module "pk-gtk-module"
Gtk-Message: 12:26:57.006: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:26:57.007: Failed to load module "pk-gtk-module"
GLib-GIO-Message: 12:26:57.012: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(tilix:1754): GLib-GIO-ERROR **: 12:26:57.058: Settings schema 'org.gnome.desktop.interface' is not installed
Trace/breakpoint trap (core dumped)
```

**Comment by Char-Aznable** [comment]
I then installed libsecret via linuxbrew and do `glib-compile-schemas /home/linuxbrew/.linuxbrew/share/glib-2.0/schemas` and tilix is able to launch. However, the appearance is off: there are icons now shown up and the program segfaults when I try openning "perference"

**Comment by gnunn1** [comment]
Why are you using linuxbrew instead of the normal package mangers, are you using Windows with the Linux subsystem? If so I don't support tilix in that environment. It might be possible to get it running there but I have no clue what's involved to do so.

**Comment by Char-Aznable** [comment]
... because I don't have root access. I used to be able to get tilix 1.7 running. I remember having to tweak something in order to get it to save/load preference but I forget what exactly that was

**Comment by Char-Aznable** [comment]
OK. I get it to work. Here are the things: 
--install adwaita-icon-theme and do `gtk-update-icon-cache` to update the icon cache.
--build and install dconf from source and do `gio-querymodules` to update the module cache

Now I'm able to run tilix and it can save/load my setting
