### ISSUE TITLE
Tilix doesn't show session name in gnome-shell panel >=v3.32

### ISSUE THREAD

**Issue by alexryndin** [gnunn1/tilix#1689]
Starting gnome-shell 3.32, tilix doesn't show session name in application title in gnome-shell:
![Screenshot from 2019-04-09 09-51-11](https://user-images.githubusercontent.com/8342078/55779359-d6237200-5aad-11e9-8497-9375f72da97b.png)
I use session names a lot to distinct them as I use borderless windows style without title.
Session name is actually set (hadoop):
![Screenshot from 2019-04-09 09-51-25](https://user-images.githubusercontent.com/8342078/55779456-2569a280-5aae-11e9-80d4-c28de9be17fc.png)
Here is also Application title config:
![Screenshot from 2019-04-09 09-51-43](https://user-images.githubusercontent.com/8342078/55779487-39150900-5aae-11e9-99f9-f10a08593f5d.png)

Tilix version - tilix 1.9.0-1
gnome-shell version 3.32

**Comment by gnunn1** [comment]
That looks like the default behavior of gnome-shell in 3.32, I see the same behavior with gedit for example where it always shows "Text Editor". It looks like shell is using the name from the desktop file. I don't think there is anything I can do in Tilix to fix it.

**Comment by alexryndin** [comment]
@gnunn1  thank you! maybe you can suggest a solution to display session name? Profile Badge would be soulution, but ${sessionName} variable is not available for badges.

**Comment by gnunn1** [comment]
It gets displayed in the application headerbar, if you have disabled that then the only other option is to use tabs to show the session name.

Badges won't work because they are scoped to the terminal and have no knowledge of sessions.
