### ISSUE TITLE
Open custom links and detach

### ISSUE THREAD

**Issue by Frydac** [gnunn1/tilix#1692]
Hi,

I use the Advanced->Custom links feature successfully to open files with compile errors from gcc's output, in an already running instance of gvim, with the following command:
`gvim --remote-silent "$2" &`
where $2 represents the 2nd regex capture group.
This works, but every time I click on a custom link, a new instance of `sh` process is created and stays alive until I close all instances of tilix (at least thats what I see in my System Monitor application's processes tab).
This isn't a big problem, I just close all instances of tilix from time to time. Maybe I just don't understand processes properly, but is there a way to have the same behavior, but not have many instances of sh process alive, without having to close tilix?
Manually trying to kill these sh processes seems to not work using e.g. `kill -9 <id>` 

fyi: I had the command without the trailing `&`, but then more and more instances of gvim were being kept alive, which gave issues with a vim plugin I use.

fyi2: Maybe if it helps someone, my regex for matching filenames, including optional column and row number ( path/file.ext:row:col ), which definitely doesn't cover 100% of cases, but I works good enough for me atm:
`(^|\s|:)((\/[a-zA-Z0-9_\-\.]+|[a-zA-Z0-9_\-\.]+)(?:\/[a-zA-Z0-9_-]+)*(\.[a-zA-Z0-9_\-\.]+)(:([0-9]+)(:[0-9]+)?)?)`
Then I use the vim plugin https://github.com/bogado/file-line to open the file at the given row:col, really like this functionality.

**Comment by gnunn1** [comment]
That's probably an issue with gvim, if you use gedit instead of gvim do you see the same behavior with respect to the sh command?

**Comment by Frydac** [comment]
Thx for the feedback.
Indeed this does not happen with gedit. But e.g. it does also happen with nvim-qt.
Been using tmux more lately, I suspect I could get similar behavior with it. And also, I've always wanted to compile and parse the compiler output in (g)(n)vim itself, maybe I'll use this as extra motivation to finally get around to making that happen in the way I want :) 
Though, it's really not that big of an issue, was hoping you'd knew some trick I didn't know about, but I don't expect you to put any time into this, thanks.
