### ISSUE TITLE
Can't launch after Ubuntu 19.04 upgrade

### ISSUE THREAD

**Issue by nathan30** [gnunn1/tilix#1694]
Hi,

I was on Ubuntu 18.10 and using Tilix without any issues. Today I upgrade to 19.04 and when I want to launch Tilix I have the following error : 

> tilix: symbol lookup error: tilix: undefined symbol: _D3std9algorithm9searching__T8skipOverZ__TQnTAyaTQeZQxFNaNbNiNfKQtQvZb

Any solutions ? 

Thanks in advance

**Comment by FFY00** [comment]
You updated phobos but not tilix. If you are using a ppa for tilix just wait until they update it, I guess. If you are using tilix from the official repositories then someone f*ed up and forgot to rebuild tilix against the new phobos version.

**Comment by nathan30** [comment]
> You updated phobos but not tilix. If you are using a ppa for tilix just wait until they update it, I guess. If you are using tilix from the official repositories then someone f*ed up and forgot to rebuild tilix against the new phobos version.

Yes I'm using the one from “WebUpd8” team. Thanks ! :)

**Comment by mathewcst** [comment]
Any news on this? Just installed Ubuntu 19.04 on my machine and can't install Tilix.

First I edited the PPA for `bionic` (18.10)  instead of `disco` (19.04). But it requires a dependency that I can't install via apt.

`tilix : Depends: libphobos2-ldc-shared78 but it is not installable`

**Comment by nathan30** [comment]
@mathewcst
I finally succeed the install following "manual installation" of the installation instructions on the tilix website : https://gnunn1.github.io/tilix-web/

**Comment by mathewcst** [comment]
@nathan30 works like a charm. Thanks!

**Comment by teresaejunior** [comment]
One option is to install from the official Ubuntu repositories instead to avoid these Phobo issues on upgrades (Tilix 1.8.9), or wait until the PPA is updated (it was 3 days ago with Tilix 1.9.0). This is not really a bug.

**Comment by gnunn1** [comment]
Closing since this isn't a Tilix bug but rather packaging.
