### ISSUE TITLE
Can't start application on KDE Plasma / Arch

### ISSUE THREAD

**Issue by smarquez1** [gnunn1/tilix#1695]
When I execute the app I get not response at all.
If I run it from command line I don't even get this error message:

```
➜ ~ tilix

(tilix:17095): GLib-GIO-ERROR **: 13:20:00.751: Settings schema 'org.gnome.desktop.interface' is not installed
[1]    17095 trace trap (core dumped)  tilix
```

Any clue of what's going on?

OS: Arch Linux
Desktop Environment: KDE Plasma

UPDATE:
Tried installing gnome-terminal, turns out it doesn't run either, so it looks like its something related to all gnome apps in my system

**Comment by smarquez1** [comment]
Fixed it reinstalling all gnome dependencies on Arch. In the end this issue had nothing to do with tilix. Apologies for creating this ticket

**Comment by phw** [comment]
@smarquez1 You likely forgot to run glib-compile-schemas after installing Tilix. If you installed Tilix via the package management pacman will take care of this, but you probably did a manual install?

The reason that reinstalling gnome-dependencies solved this is that many gnome packages will trigger the pacman hook that runs glib-compile-schemas.
