### ISSUE TITLE
How to set the terminal title to show the current running command?

### ISSUE THREAD

**Issue by Meshikhah** [gnunn1/tilix#1698]
![Screenshot from 2019-05-02 13-36-23](https://user-images.githubusercontent.com/29687018/57065647-528d2780-6cdf-11e9-95b5-9ffcb88ff26d.png)
I want to show cmus in the Application Title but I can find any option in preferences.

**Comment by FFY00** [comment]
I don't think that's in tilix's scope. You should patch your application to set the terminal title. It can be accomplished by simply outputting `\x1b]2;Your Title Here\x07` to `stdout`.

**Comment by gnunn1** [comment]
There's actually a hidden option in dconf for tilix called ```process-monitor``` that does this, but it's actually very buggy and results in crashes when enabled. If someone wants to have a look at the code and fixing it up feel free.

**Comment by waldyrious** [comment]
For future reference, this seems to be closed as a duplicate of #937.
