### ISSUE TITLE
Sidebar switching doesn't always work

### ISSUE THREAD

**Issue by oybed** [gnunn1/tilix#1699]
Running on Fedora 29 and 30, using MATE and Tilix 1.9.1, switching between sessions using the sidebar doesn't always work. I.e.: if it shows 3 / 3 and I click on the drop down to select 1 / 3 or 2 / 3 it doesn't switch. Typically I can then use CTRL+ pg-up/pg-down to switch sessions still, so I know the sessions are active, but the drop down does let me do it (even though the side bar shows up with the preview of the other sessions). 

Some more details:
```
tilix --version
Versions
	Tilix version: 1.9.1
	VTE version: 0.56
	GTK Version: 3.24.8

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=1
```

Also, on F29 I at times experienced that the CTRL + pg-up/pg-down doesn't work, but I have not seen this as much recently.

**Comment by gnunn1** [comment]
The sidebar this is likely related to #1637 which has been fixed in master. I'll push out a new version this weekend.

**Comment by gnunn1** [comment]
Also reported in #1680, will close both of these once I push the new release out.
