### ISSUE TITLE
Computer becomes unusable when trying to take a screenshot; there is reason to suspect tilix

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [gnunn1/tilix#1707]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I was trying to take a screenshot for use in a bug report. I used the Plasma program [Spectacle](https://kde.org/applications/graphics/spectacle/) to do that. Somehow, I could not exit screenshot mode: I was stuck in being asked to draw a rectangle, so as to select the area for the screenshot. Spectacle says I can press `esc` to exit. But that did not work. Other programs did not respond so I could not kill the program. Somehow, and just before I was about to resort to a hard reset, I managed to exit the screenshot mode. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now: at this point I saw a tilix terminal behaving oddly - it was acting as if `return` was depressed, and I think I saw a strange character in the terminal too. (It was a 'Guake' style tilix window and the output in question seems to have disappeared.) And I have this in my recent syslog:

`message repeated 5 times: [ (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)]`

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If this problem does not owe to tilix then let me know and I will file this report elsewhere.

Mint 19.1 Cinnamon
```
$  tilix --version
Versions
	Tilix version: 1.7.7
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
I don't think this hasn't anything to do with Tilix, plus I don't support Tilix on Plasma anyway, only Gnome.

**Comment by LinuxOnTheDesktop** [comment]
I'm not on Plasma but rather (as said) on Cinnamon. Anyhow, problems with Tilix (or Tilix-under-Cinnamon) have led me to abandom Tilix, sadly.
