### ISSUE TITLE
Export and import entire tilix configuration

### ISSUE THREAD

**Issue by leynebe** [gnunn1/tilix#1711]
Maybe I'm missing something but I cannot seem to find a tilix config file that lists your user configuration. Where is the config stored?

The typical location would be "\~/.config/tilix/config" or "~/.tilix/config".

The settings UI also has no possibility to export or import anything.

**Comment by gnunn1** [comment]
Configuration is in dconf, you can use the usual dconf/gsettings tools to import and export the settings.
