### ISSUE TITLE
Deprecating rewrap on resize API

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/tilix#1712]
VTE 0.58 (Sep 2019) will deprecate the rewrap_on_resize API.

0.60 (Mar 2020) is planned to remove the configuration, forcing rewrapping to be enabled. The methods will remain for API compatibility, but will do nothing.

Rationale: https://gitlab.gnome.org/GNOME/vte/issues/135

Please prepare your app for not showing the corresponding UI option if running against (future) 0.59/0.60 or newer.

**Comment by gnunn1** [comment]
That option was removed awhile ago so all is good.

**Comment by egmontkob** [comment]
I see it's commented out in `source/gx/tilix/prefeditor/profileeditor.d`, but not in `source/gx/tilix/terminal/terminal.d`. Anyway, since the API remains, it's probably okay.
