### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by thwaller** [gnunn1/tilix#1714]
When opening Tilix I receive a configuration error dialog directing me to the following page:
https://gnunn1.github.io/tilix-web/manual/vteconfig/

I have tried both option 1 and 2 and neither prevent this dialog from appearing. I am running Ubuntu 18.04.2 with MATE 1.22.1. Tilix is version 1.7.7.

**Comment by phw** [comment]
At least the method using login she'll had always worked for me so far. Did you try creating the symlink /etc/profile.d/vte.sh as described in this page? This seems to be needed on Ubuntu according to the instructions.

If not check which vte related files exist in /etc/profile.d/, maybe the file name is different from the instructions.

**Comment by thwaller** [comment]
Thanks for the reply.
Yes, the symlink is in fact needed and was created. I am still able to use Tilix, I just get that error. I also could check the box not to show it again, but that does not seem to be a solution.

I will keep looking at it, but wanted to report should anyone else have the issue or already found a solution.

**Comment by thwaller** [comment]
Adding an update in hopes that it helps others that may have this issue or even a related issue.

I found that the specific "error" here was:
> runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
Per the references below, I decided to install version 1.9.1 from a third party source. This has corrected the problem. I cannot say fixed as I am actually not sure what is/was affected by this and if it in fact now works or if the message is just hidden or found to be a function that is simply not available.

It appears this is specific to Ubuntu as they have modified some/parts of VTE which is the cause of this, I believe it is PCRE2 according to the sources.

Please see the following references, as I cannot take any credit aside from digging up the information and doing.
RE:
1. This provided the package for Tilix I ended up using: https://launchpad.net/~webupd8team/+archive/ubuntu/terminix
2. These are related issues from Tilix here that assisted in identifying this (916, 1428 and 1480: https://github.com/gnunn1/tilix/issues/916, https://github.com/gnunn1/tilix/issues/1428, https://github.com/gnunn1/tilix/issues/1480
