### ISSUE TITLE
Italics font is not italic but inverted

### ISSUE THREAD

**Issue by 73** [gnunn1/tilix#1715]
## Problem description
I see no italics fonts. I see them inverted (bg and fg color switched):
![tilix-italic](https://user-images.githubusercontent.com/529346/59750292-e2326980-927e-11e9-97d3-28fbc7fb0ebc.png)

## I tried
1. I tried multiple fonts.
2. It works in gnome-terminal.

## Additional info
```
🠶  tilix --version
Versions
        Tilix version: 1.8.9
        VTE version: 0.56
        GTK Version: 3.24.8

Tilix Special Features
        Notifications enabled=0
        Triggers enabled=0
        Badges enabled=1
```

*Maybe there is a setting I missed?*

**Comment by egmontkob** [comment]
It should work.

Do you have `screen` or `tmux` running? They can easily mangle it.

**Comment by 73** [comment]
I feel like an idiot now. 

Yes, it was screen. Thanks man!
