### ISSUE TITLE
Autohide cursor not working

### ISSUE THREAD

**Issue by dylancromer** [gnunn1/tilix#1716]
I am not sure what change in my system (Manjaro, Gnome3 Wayland) triggered this, but recently Tilix has stopped auto hiding my cursor when typing. Instead of hiding, the cursor jumps down and to the right by a small amount but remains visible.

**Comment by dylancromer** [comment]
More information: On a whim I decided to log into Gnome with X11 instead of Wayland, and on X11 this problem doesn't exist.

**Comment by gnunn1** [comment]
Can you reproduce the issue with gnome-terminal?

**Comment by dylancromer** [comment]
I was able to reproduce on gnome-terminal, but after a recent round of updates to my system the problem is gone even in Wayland. Sorry for the noise here.

**Comment by gnunn1** [comment]
Thanks for the follow-up, closing.
