### ISSUE TITLE
Search with Google... option for terminal selection

### ISSUE THREAD

**Issue by grrigore** [gnunn1/tilix#1717]
I think that a shortcut for a Google search would be useful in the right-click menu.

On text selection, you should be able to click `Search with Google...` that will redirect you to a Google search with the selected text.

This would save time when searching for error messages. IntelliJ IDEA has this and I find it really useful.

**Comment by alextakitani** [comment]
I have this working on Terminator via a plugin.

It would be cool to have it on Tilix, that's one of the things that keeps me on Terminator

**Comment by gnunn1** [comment]
No plans for this, there are two many options in Tilix already. If a new maintainer takes over at some point and decides otherwise that's fine but for now I'm closing this as will not do.
