### ISSUE TITLE
Borderless - no way to access preferences or restore borders?

### ISSUE THREAD

**Issue by i-bsd** [gnunn1/tilix#1721]
Tried the borderless option. Looks great.
Now how do I restore the borders or even access the menu? Seems to be no option for it anywhere.
Where is the config file?

**Comment by bilelmoussaoui** [comment]
You can use tilix --preferences to open the settings window.

**Comment by gnunn1** [comment]
What @bilelmoussaoui said is correct.

**Comment by jackdelahunt** [comment]
> What @bilelmoussaoui said is correct.

Thanks for the help

**Comment by HubKing** [comment]
> You can use tilix --preferences to open the settings window.

That worked, but it does not seem like a good UI. How about adding an option "Show preferences" to the drop-down menu that appears when you click the tab header? It could be placed under "Other".
