### ISSUE TITLE
Unicode (indic) characters are not rendered correctly

### ISSUE THREAD

**Issue by srix** [gnunn1/tilix#1725]
Tilix version : 1.7.7 , Kubuntu 18.04

Indic characters ( I tested for Tamil language) are not rendered correctly.

```
srix$ echo தமிழ்
தமிழ்
srix$ printf  "\340\256\244\340\256\256\340\256\277\340\256\264\340\257\215\n"
தமிழ்
```
![image](https://user-images.githubusercontent.com/5801636/60653378-8c0d1b00-9e67-11e9-937a-07cd0ce65056.png)

For reference am sharing the same output on KDE konsole. Where it is rendered correctly.
![image](https://user-images.githubusercontent.com/5801636/60653507-c8d91200-9e67-11e9-8933-e1dc2435a7c2.png)

**Comment by phw** [comment]
It's maybe some trouble with fonts. It does not seem to be a general issue, as it seems to render correctly on my installation (Tilix 1.9.1 with VTE 0.56 and GTK 3.24.9):
![grafik](https://user-images.githubusercontent.com/29852/60667181-2a4db080-9e69-11e9-9b8d-2d21d2f5e238.png)

Could you check whether GNOME Terminal has the same issue and also whether other GTK3 applications (e.g. gedit) can render it correctly?

Also the output of `tilix --version` would be helpful. This could very well be a VTE or GTK bug.

**Comment by srix** [comment]
srix$ tilix --version
Versions
	Tilix version: 1.7.7
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

Same issue with Gnome - Terminal aswell.
![image](https://user-images.githubusercontent.com/5801636/60677050-0fe1fa00-9e9e-11e9-9646-e41f6b1311f8.png)

From your input looks like issue is fixed in later versions. Thanks for Quick reply. can you share your OS version?

**Comment by phw** [comment]
> can you share your OS version?

Arch Linux

> From your input looks like issue is fixed in later versions.

@egmontkob Any idea, could this be an already fixed VTE issue?

**Comment by egmontkob** [comment]
Yes, VTE 0.56 significantly improved Indic (Devanagari etc.) rendering, fixed the dotted circle issue.

Note: Dotted circles still appear if the cursor goes over such characters. A workaround is to use I-beam or underline cursor shape.

**Comment by srix** [comment]
Thanks @egmontkob @phw .  Based on your inputs I  upgraded to Kubuntu 19.04 which has Tilix version: 1.8.9,  VTE version: 0.56, GTK Version: 3.24.8. Rendering is much better but still not as good as what I get from gedit.  Attaching the snapshot.

@egmontkob  thanks for the cursor tip. I changed to I-beam.

Tilix
![image](https://user-images.githubusercontent.com/5801636/60721204-c996a480-9f4a-11e9-8722-c2811b8d19e3.png)

Gedit
![image](https://user-images.githubusercontent.com/5801636/60721260-f21e9e80-9f4a-11e9-9b38-b7a7a071f2fd.png)

If this is confirmed as VTE limitation, will close the ticket here.

**Comment by egmontkob** [comment]
VTE must respect the strict grid layout of cells. If a glyph is wider, it must not push the rest to the right, something that Gedit can do (and Konsole also seems to do, causing much bigger problems). So this is by design and will not change. Not a limitation of VTE, but a limitation of "terminal" or "terminal emulation" as a concept.

You can look for a different font (a real monospace one, sharing the same width across English and Tamil characters), or increase "Cell spacing" in your profile preferences to reduce the amount of overlaps.

**Comment by srix** [comment]
@egmontkob thanks for clear explanation . I adjusted the cell spacing to get readability and set a separate profile in tilix .

I will close the ticket.
