### ISSUE TITLE
Automatic resize on new panel

### ISSUE THREAD

**Issue by lapega** [gnunn1/tilix#1726]
I have a feature request:

When adding new panels, would be nice that tilix window can grow in width.
Or at less have an option to resize the terminal width without use the mouse.

Thank you!

**Comment by alexwhitman** [comment]
If you're using Gnome then keyboard resizing is already a feature of the window manager.  Hit Alt+F8 then use the arrow keys to resize.  Hit Enter to accept.

**Comment by lapega** [comment]
Magic!
