### ISSUE TITLE
Changing Terminal Size Causes Erratic Prompt Behavior 

### ISSUE THREAD

**Issue by webmastak** [gnunn1/tilix#1727]
When reducing the size of the terminal window, such porridge occurs only if the right prompt is enabled.

[![https://i.imgur.com/N1kCcLv.png](https://i.imgur.com/N1kCcLv.png)](https://i.imgur.com/N1kCcLv.png)

If only the left prompt is used, then everything is ok.

**Comment by egmontkob** [comment]
See https://github.com/thestinger/termite/issues/614 and further links from there.

**Comment by webmastak** [comment]
As I understand there is no solution.

**Comment by gnunn1** [comment]
Closing as this isn't a tilix issue.
