### ISSUE TITLE
How about implementing "natural copy & paste"?

### ISSUE THREAD

**Issue by viniciusban** [gnunn1/tilix#1730]
I used elementary OS default terminal in a VM the other day and I was greatly surprised for it uses natural copy & paste with traditional CTRL+C and CTRL+V, without simultaneous SHIFT.

When CTRL+C is pressed, the logic is: 

```
if there's some selected text {
    copies it to clipboard;
} else {
    send the ^C to terminal;
}
```

CTRL+V works as expected.

**Comment by gnunn1** [comment]
Tilix already does this, go into keyboard shortcuts and change copy and paste to ctrl-c and ctrl-v. Tilix is smart enough to know when to copy and when to send the interrupt based on when something is selected.

**Comment by viniciusban** [comment]
Great!

Thank you.

**Comment by ssi-anik** [comment]
I've set those values already in tilix. My OS is Ubuntu 20.04. Even tho it copies the text, it also sends the usual signal (sigint i guess). So, it cancels the running foreground program.
For the preinstalled terminal program, it works fine.

![image](https://user-images.githubusercontent.com/2676602/107883332-9aaf2580-6f18-11eb-9a61-351e2c914e7f.png)

**Comment by KaKi87** [comment]
Hello, although changing shortcuts does the trick, it sometimes won't send interrupt unless pressing twice when nothing is selected. Thanks

**Comment by cwells** [comment]
> Hello, although changing shortcuts does the trick, it sometimes won't send interrupt unless pressing twice when nothing is selected. Thanks

No one ever hits ctrl+c only once.

**Comment by KaKi87** [comment]
I do.
