### ISSUE TITLE
Search through shortcuts should display the shortcut

### ISSUE THREAD

**Issue by dandv** [gnunn1/tilix#1737]
I wanted to find out what the shortcut for Opening a new window was. Only got the command, not the shortcut for it:

![image](https://user-images.githubusercontent.com/33569/61574027-55d9b900-aa6d-11e9-9325-635b64adb15b.png)

**Comment by bilelmoussaoui** [comment]
You should set a shortcut for it on the preferences.

**Comment by dandv** [comment]
> You should set a shortcut for it on the preferences.

That's another confusing UI choice: separating the *viewing* of shortcuts, from setting them. In pretty much all other applications that allow configuring shortcuts, when I double click the accelerator, I can set it.

In other words, the "Shortcut" page should let me set a shortcut when I double click on one, or that page shouldn't exist because it...

![image](https://user-images.githubusercontent.com/33569/61595128-254a6a00-aba8-11e9-90be-0005dea0edc3.png)

... duplicates the Preferences -> Shortcuts

![image](https://user-images.githubusercontent.com/33569/61595147-52971800-aba8-11e9-8894-e26119b2a008.png)

**Comment by gnunn1** [comment]
That's the way GNOME works, the shortcut viewer has no capability to customize shortcuts at this time. The default terminal in GNOME works the exact same way.
