### ISSUE TITLE
No prompt color when open but only after source .bashrc

### ISSUE THREAD

**Issue by sdlins** [gnunn1/tilix#1738]
First of all, thank you for this NICE terminal! 

I begun to have this problem recently: My prompt has no colors when opening Tilix. It only gets colored after `source .bashrc`.

![erro-tilix](https://user-images.githubusercontent.com/412490/61610251-ff1bdd00-ac2e-11e9-87d4-c86850270fc2.png)

Why would Tilix not source my .bashrc when opening? Any ideas?
Thank you!

**Comment by gnunn1** [comment]
Do you see the same thing in gnome-terminal?

What DE are you using?

**Comment by sdlins** [comment]
No, Gnome Terminal works fine. I am using Cinamon (Mint 19.1).

**Comment by egmontkob** [comment]
What does `echo $0` say in these two terminals? I expect gnome-terminal to report `bash` whereas Tilix to say `-bash` with a leading dash, meaning that you've configured Tilix (or is it its default?) to launch a login shell. Login shells source `.profile` and friends _instead of_ `.bashrc` (it's a common practice to source the latter from the former).

**Comment by sdlins** [comment]
Nice @egmontkob! It was exactly what you said, except by I've had to `source ~/.bashrc` in `~/bash_profile` besides `~/.profile`. Thank you!
