### ISSUE TITLE
Drag and Drop Tabs for tiling

### ISSUE THREAD

**Issue by EugenMayer** [gnunn1/tilix#1740]
Is there any chance to see this feature being part of tilix? I really like the whole idea, but sometimes, quiet often, i have several tabs and suddenly i need a side by side view of those.

Usually those are ssh sessions, in a docker container whaterver - creating a new terminal (tiled) and rebuilding the whole connection is just effort and painful.

In any case, thank you!

**Comment by gnunn1** [comment]
I have no plans to add this as a feature, sorry. I think simply dragging the tab into a new window, which is supported in tilix, is sufficient for a side by side view
