### ISSUE TITLE
Wrong line width and strange behavior.

### ISSUE THREAD

**Issue by Sraw** [gnunn1/tilix#1742]
![Screenshot from 2019-07-30 11-27-35](https://user-images.githubusercontent.com/15711730/62098508-23c22580-b2bd-11e9-9669-921bb5416f14.png)

As you can see in the screenshot. It seems that the line width is wrong. And it doesn't correctly go to the new line but repeats from the beginning, and then it works correctly though.

To provide more information, I'm using bash-it and powerline style. So to fix vte problem, I create a custom sh:

```
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    TMP_PROMPT_COMMAND="$PROMPT_COMMAND"
    source /etc/profile.d/vte.sh
    function custom_prompt() {
        VTE_PWD_THING="$(__vte_osc7)"
        PS1="$PS1$VTE_PWD_THING"
    }
    PROMPT_COMMAND="$TMP_PROMPT_COMMAND;custom_prompt"
fi
```
The idea is simple, I first cache the current `PROMPT_COMMAND`, and add what needed after it. Is there anything wrong with my script? Or is it a bug?

**Comment by egmontkob** [comment]
See bash's manual -> PROMPTING -> `\[` and `\]` which you don't use properly in your prompt.

**Comment by Sraw** [comment]
> See bash's manual -> PROMPTING -> `\[` and `\]` which you don't use properly in your prompt.

Thanks for your reply but it isn't the case. I somehow fixed this problem. It looks like I've set `$PS1` twice.

**Comment by egmontkob** [comment]
> but it isn't the case

I've come across this phenomenon dozens of times, and the reason has always been this.

> I somehow fixed this problem.

This "somehow" suggests to me that you probably have no idea what you are doing. (So why exclude the possibility that the problem was actually what I pointed you to?)

> It looks like I've set `$PS1` twice.

This explanation makes no sense. You can't "set twice" an environment variable in a way that both values live. If an environment variable is set again, its old value is overridden, forgotten. It's always the current value that matters.

Anyway, happy that it's fixed for you now (and if it takes a false belief on your side about what the problem was, so it be).

**Comment by Sraw** [comment]
> > but it isn't the case
> 
> I've come across this phenomenon dozens of times, and the reason has always been this.
> 
> > I somehow fixed this problem.
> 
> This "somehow" suggests to me that you probably have no idea what you are doing. (So why exclude the possibility that the problem was actually what I pointed you to?)
> 
> > It looks like I've set `$PS1` twice.
> 
> This explanation makes no sense. You can't "set twice" an environment variable in a way that both values live. If an environment variable is set again, its old value is overridden, forgotten. It's always the current value that matters.
> 
> Anyway, happy that it's fixed for you now (and if it takes a false belief on your side about what the problem was, so it be).

Well, the reason why I use "somehow" because I have to modify the source code of powerline theme which I don't like.

And I do agree and understand that `\[` and `\]` always cause problems especially when it comes to colorful prompt. But it does is not the case as I don't even create my custom command but just concatenate two existing ones.

Finally, yes you cannot set an environment variable twice. Sorry for the confusion and I mean I duplicated some content in the `$PS1` variable which I shouldn't.

**Comment by egmontkob** [comment]
If you happen to come across this issue again, I'd love to see your PS1 purely out of curiosity.

Even if it's not a `\[` `\]` issue, it's much more likely a bug in `bash` than in Tilix. You could test by trying in a non-VTE based emulator such as `xterm`, I expect the bug to occur there too.
