### ISSUE TITLE
trigger - highlight text

### ISSUE THREAD

**Issue by waldauf** [gnunn1/tilix#1748]
Hello,

in iTerm2 possibility to highlight text in output. I would like to ask you if there is the same option in Trigger in Tilix. I read doc page but didn't get if there is this option and if so how to use it.

**Comment by gnunn1** [comment]
There is no option for this in tilix. This feature would be dependent on the VTE widget that tilix uses for the actual terminal emulation to add support for arbitrary text highlighting. So for now I'm closing this, if VTE adds the feature in the future feel free to reopen it.
