### ISSUE TITLE
Change profile (or theme) in all current sessions

### ISSUE THREAD

**Issue by slaters** [gnunn1/tilix#1750]
Right now, I switch between dark and light themes twice or more each day, and it requires doing so with the gui menu in each active session. (It feels like walking through a big house and opening / closing all the binds and curtains.)

So I was wondering if there is any way to script this?

**Comment by gnunn1** [comment]
There is no capability to script this, however you can assign a hotkey to each profile so you can switch them quicker then going through the GUI.

**Comment by slaters** [comment]
Oh, cool suggestion. Thanks 😆
