### ISSUE TITLE
utmp broadcast messages support

### ISSUE THREAD

**Issue by 532910** [gnunn1/tilix#1755]
Please add support for utmp broadcast messages (sended by `wall` command for example). VTE3 has dropped support for it.

**Comment by gnunn1** [comment]
Tilix relies on VTE for terminal emulation so it won't be happening.

**Comment by 532910** [comment]
> won't be happening

It's a pity! While gnome users has it's own vision of the world, not all people shares it.

https://unix.stackexchange.com/questions/150697/broadcast-messages-dont-appear-on-gnome-terminal-but-appear-on-xterm

Moreover, fact that Tilix relies on VTE doesn't prevent to register utmp record.

**Comment by f2404** [comment]
xfce4-terminal can be built with support for utmp record.

**Comment by egmontkob** [comment]
You can also use a helper tool, wrapped around the shell you invoke from your terminal. This works with any terminal. Two such tools are linked from https://bugzilla.gnome.org/show_bug.cgi?id=747046 comments 34-35.
