### ISSUE TITLE
Is it possible to set the font size based on the monitor size? 

### ISSUE THREAD

**Issue by sans-clue** [gnunn1/tilix#1766]
I'm not even sure if this is possible at all, some quick Googling around didn't yield any information at all. 

But I wanted to ask anyway (just in case).

Like a lot of people, I plug my laptop into a nice big monitor. I like having a smaller font size on the big monitor so I can really make use of the space but also would like the bigger font when I'm using the laptop.

Is this possible to do?

**Comment by gnunn1** [comment]
No it is not. What I do is have separate profiles with different font sizes and assign a hot key to each, I can then quickly switch between them as needed.

You can also zoom in and out as another approach.
