### ISSUE TITLE
Multiplex input across multiple tabs

### ISSUE THREAD

**Issue by ikouchiha47** [gnunn1/tilix#1774]
Is there a functionality like cssh or send input across multiple tabs/windows like in iTerm2 availbale?

There is no online support channel, on irc. So had to ask here.

**Comment by encukou** [comment]
For split windows there's Synchronize Input:
![image](https://user-images.githubusercontent.com/302922/82822112-849e9800-9ea5-11ea-8595-da5a563eebfc.png)
When enabled, it can be turned on/off for individual tabs with the "keyboard" button:
![image](https://user-images.githubusercontent.com/302922/82822274-cc252400-9ea5-11ea-980a-84697921e35e.png)
