### ISSUE TITLE
Unable to select font

### ISSUE THREAD

**Issue by alextat120** [gnunn1/tilix#1779]
Hello, I have the "Hack" font installed on my system. When I do `fc-list` the font is showing up, so it should be installed properly. 

I did notice the fonts listed in /usr/share/fonts were able to be selected.

My Hack font tff is in the ~/.fonts folder.

**Comment by alextat120** [comment]
...I just did a fresh install seems to be working now.

**Comment by dejlek** [comment]
Did you update the font cache once you copied the files to ~/.fonts ? `fc-cache -f -v` ?

**Comment by alextat120** [comment]
> Did you update the font cache once you copied the files to ~/.fonts ? `fc-cache -f -v` ?

I did, but as I said, a reinstall did the trick.
