### ISSUE TITLE
please make it possible to configure the cursor color

### ISSUE THREAD

**Issue by g-raud** [gnunn1/tilix#1784]
Hello,

Tilix seems well thought-out but it is missing one important feature: the configuration of the cursor color, which is always of the foreground colour.  Thus the cursor is difficult to find on a screen full of text (like in a visual program).

It is probably possible to configure the cursor since xfce4-terminal has this feature already.

Thanks

**Comment by egmontkob** [comment]
Preferences -> (profile) -> Color -> Advanced ?

**Comment by g-raud** [comment]
That's right!  I missed it although I checked and unchecked many times the "Use theme colors" right next to it.

I'm closing this issue althoutgh I cannot test the option right now because I cannot change my configuration anymore (problem in dconf?).
