### ISSUE TITLE
Clicking on custom links does nothing

### ISSUE THREAD

**Issue by m-kru** [gnunn1/tilix#1800]
I have one custom link definition in my profile. When I hover over the pattern, it gets underlined and hand pointer appears. However after clicking LMB nothing happens.

I have also tried Ctrl + click, but still nothing happens. After clicking RMB and 'Open Link' still nothing.

The `Command` field is set.
![tilix](https://user-images.githubusercontent.com/26227737/68999155-c4fcd800-08bc-11ea-9ee5-51118ac551c8.png)

`Linux arch 5.3.6-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 11 18:28:05 UTC 2019 x86_64 GNU/Linux`

```
Versions
	Tilix version: 1.9.1
	VTE version: 0.58
	GTK Version: 3.24.12

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

**Comment by rubydesign** [comment]
what is the command set to?  
can you paste the regex and the command field

**Comment by m-kru** [comment]
@rubydesign 
`
![links](https://user-images.githubusercontent.com/26227737/74250304-b15de380-4cea-11ea-9740-9f725d858cc3.png)
`

**Comment by rubydesign** [comment]
@m-kru sorry didn't see that up there. I don't read regexp well so i couldn't say much about that. But there is a trick i do for debugging: I use `echo $0 >> out.txt` as the command.
And on a different tab i `tail -f out.txt`

Is there a reason you use $1 and not $0 . All my expressions use $0 .
Also, i think you have a start of line in there at the beginning, is that on purpose?

**Comment by m-kru** [comment]
@rubydesign Ok, I have tried your debug method, both with `$0` and `$1`. The regex is ok I guess, because the correct pattern gets underlined when I mouse over it. The result is that nothing is echoded, like no action is taken when I click on the underlined string.

**Comment by phw** [comment]
You need to Ctrl click for opening the links

**Comment by phw** [comment]
Oh, looking at your screenshot I think the actual issue is that you run vi with the URL. Tilix will just run this command, but just calling vi does not open any window or so. You probably have to change that command to run e.g. Tilix with the --command switch

**Comment by m-kru** [comment]
Thanks @phw, it works now. However it opens new tilix instance and I would like to run vi in the same instance that I click.

**Comment by lacostenycoder** [comment]
I'm not able to get this work at all. What is the secret I'm missing. I was able to get the debug out.txt file to work on the regexp but can't get any commands to work.  I want to open the file in my editor which is Atom binary. But also tried `vi` and got nothing, no file opens anywhere.
