### ISSUE TITLE
Add shortcut for unselect all (select none)

### ISSUE THREAD

**Issue by hannes-ucsc** [gnunn1/tilix#1801]
There is a shortcut for "Select all" so I think there should be a shortcut for the [inverse operation](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-unselect-all).

Tilix has this extremely useful feature that Ctrl-C only copies to clipboard if there is an active selection and otherwise sends the interrupt signal. I often find myself in the situation where I want to send the interrupt signal but have text selected. So I first need to deselect the text by using the mouse. It would be more ergonomic if I could deselect text via the keyboard.

**Comment by alexwhitman** [comment]
Added in #1808

**Comment by hannes-ucsc** [comment]
Confirmed working. Thank you, @alexwhitman & @gnunn1.
