### ISSUE TITLE
Request for a snap version or an EPEL for RHEL 8

### ISSUE THREAD

**Issue by jatin-cbs** [gnunn1/tilix#1813]
I am using RHEL 8 we need tilix on CentOS and RHEL 8 however no snap package is there or an rpm package or a copr repo for RHEL 8 please help.

**Comment by kalev** [comment]
There's a Tilix flatpak in Fedora if it helps, `flatpak remote-add fedora oci+https://registry.fedoraproject.org` and then 'flatpak install com.gexperts.Tilix`

**Comment by jatin-cbs** [comment]
Does the flatpak contains all flathub apps too ?

**Comment by jatin-cbs** [comment]
I mean the fedora oci+https://registry.fedoraproject.org

**Comment by jatin-cbs** [comment]
Yes I installed it for now but the only thing is it takes alot of space cauz we need SDK which is around 500 MB itself, Snaps on the other hand dont take large space as it install app on your system rather than the whole runtime environment.

**Comment by jatin-cbs** [comment]
Also if it can be made available in flathub would be better. :) Still EPEL or Copr repo is preferred.

**Comment by TomC4D** [comment]
This would be great!

**Comment by sogalgeeko** [comment]
Using [OBS](https://build.opensuse.org/), I have made a CentOS 8 Tilix 1.9.3 package.
It is available here: https://build.opensuse.org/package/show/home:sogal:tilix-centos8/tilix

You can get it by [downloading the RPM directly](https://download.opensuse.org/repositories/home:/sogal:/tilix-centos8/CentOS_8/x86_64/tilix-1.9.3-5.1.x86_64.rpm) or adding the repo:

```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:sogal:tilix-centos8/CentOS_8/home:sogal:tilix-centos8.repo
dnf install tilix
```

[GPG fingerprint](https://build.opensuse.org/project/keys_and_certificates/home:sogal:tilix-centos8) is  b6a0 33ca de5c 5041 9cc5 d427 fe5c 2fa0 cd48 b9ee

I am currently using it on CentOS 8 Linux and it works fine. I guess it should work as well on RHEL 8.

**Comment by jatin-cbs** [comment]
Great ! @sogalgeeko

**Comment by zzzuzik** [comment]
@sjpp any chance for 1.9.4? Thank you

**Comment by sjpp** [comment]
@zzzuzik Sure, I just updated the version: https://build.opensuse.org/package/show/home:sogal:centos8/tilix

I did not test installation yet.

```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:sogal:centos8/CentOS_8/home:sogal:centos8.repo
yum install tilix
```

or dl package directly:

`https://download.opensuse.org/repositories/home:/sogal:/centos8/CentOS_8/x86_64/tilix-1.9.4-1.1.x86_64.rpm`

**Comment by brakogh** [comment]
@sjpp can you make a build for EL9 pls?

**Comment by sjpp** [comment]
@brakogh I will work on it at some point but don't have the time currently. And some repos are still missing/incomplete on the OBS.
In the meantime, I suggest you to use this COPR repo : https://copr.fedorainfracloud.org/coprs/arrfab/not-in-epel9/
This guy has tilix 1.9.4 built for EL9 (I have tested it under Rocky Linux 9 and it works flawlessly).
I hope it suits your need !

**Comment by brakogh** [comment]
> @brakogh I will work on it at some point but don't have the time currently. And some repos are still missing/incomplete on the OBS. In the meantime, I suggest you to use this COPR repo : https://copr.fedorainfracloud.org/coprs/arrfab/not-in-epel9/ This guy has tilix 1.9.4 built for EL9 (I have tested it under Rocky Linux 9 and it works flawlessly). I hope it suits your need !

Thank you!
