### ISSUE TITLE
not working on current debian sid

### ISSUE THREAD

**Issue by y0va** [gnunn1/tilix#1816]
The last debian update made tilix not working anymore. This is the error message:

```
tilix:14552): GLib-GIO-ERROR **: 23:27:44.361: Settings schema 'com.gexperts.Tilix.Keybindings' is not installed
Trace/Breakpoint ausgelöst
```

Any ideas?

**Comment by turndn** [comment]
I've faced the same problem.

I fixed `/usr/share/glib-2.0/schemas/com.gexperts.Tilix.gschema.xml` as follows.
Then, I applied this change by executing `glib-compile-schemas /usr/share/glib-2.0/schemas`.

```diff
206c206
<       <default>${title}</default>
---
>       <default>'${title}'</default>
```

**Comment by turndn** [comment]
I think the commit (https://github.com/gnunn1/tilix/commit/df82ea24b10930e095d3fa65f0ab887edd14aa6d) has fixed this problem.

**Comment by y0va** [comment]
Thanx, the workaround fixed it for me.
