### ISSUE TITLE
Tilix adds space to all characters displayed

### ISSUE THREAD

**Issue by smaugfm** [gnunn1/tilix#1819]
I just installed fresh CentOS 8 and have this weird behavior of Tilix when it prints all characters as "double-width" with additional space. I tried different fonts too. Here is how it looks:
![image](https://user-images.githubusercontent.com/16973041/71064920-db76a780-2178-11ea-9162-19659142c671.png)

Tilix is being run in quake mode with `GDK_BACKEND=x11 tilix `
GNOME version: 3.28.2
`Linux upsource 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oktayaa** [comment]
Lubuntu Focal, LXDE, same issue. Very few fonts work properly. Can you reopen?
