### ISSUE TITLE
Ubuntu package is old

### ISSUE THREAD

**Issue by seperman** [gnunn1/tilix#1827]
Hi, thanks for the very cool terminal emulator.
On Tilix's homepage it says:
`Official Tilix packages are available for Ubuntu artful and bionic.`

The artful link is broken and the bionic package of tilix is 1.7.7 from 2017. Here we are 3 years later and the package is not updated there yet? Is that really the last fully stable tilix version for Ubuntu?

**Comment by phw** [comment]
Those are the packages as they are provided by Ubuntu. Newer Ubuntu versions are shipping newer Tilix.

In general Ubuntu does not update package version in their releases except for Bugfixes.

The update strategy of Ubuntu ist outside the control of Tilix.

**Comment by seperman** [comment]
Hi @phw 
Ok so perhaps then the homepage should not recommend installing via `apt` package manager as ` The best way to get Tilix` ?

**Comment by phw** [comment]
Usually the packages provided by your distribution are the easiest way to install the software. The Tilix project itself is not providing binary packages, just the source code. Of course you could also install and build from source.

That distributions are not always shipping the latest version is a different thing. But that's actually just how the distributions work, there is nothing special with Tilix. If you are using the LTS version of Ubuntu you are basically stuck with the releases of all the software from around the time that LTS version was published. If you don't like the way Ubuntu handles software updates it is probably not the right distribution to use. There are other options which provider more up-to-date software.

What would probably be best would be having Tilix available via flathub.org or in the Ubuntu store as a Snap. Unfortunately the Flatpak packaging of Tilix never got finalized as far as I am aware.

**Comment by mhow2** [comment]
Well, what you say @phw cuts both ways : if tilix's users aren't using the latest version of the software, you have less chances to track down recently introduced bugs or features. You can't blame distribution not being rolling release ;)
I agree that a snap package would be a solution.

**Comment by dhollinger** [comment]
@seperman You could always use this PPA if you're still on 16.04 or 18.04: https://launchpad.net/~webupd8team/+archive/ubuntu/terminix

**Comment by seperman** [comment]
Cool, thanks @dhollinger !

**Comment by ximion** [comment]
Closing, since there is nothing for Tilix upstream to do (Ubuntu has meanwhile updated their Tilix package though)
