### ISSUE TITLE
Full Dark mode

### ISSUE THREAD

**Issue by marcinguy** [gnunn1/tilix#1831]
Installed from PPA Tilix 1.9.1, installed GTK3 Dark theme, but somehow bars and terminal bars are still "light"/"white". Any way to make this all dark, black????

Looks like this:

https://gnunn1.github.io/tilix-web/src/images/gallery/tilix-screenshot-3.png

I would like to have GUI UI dark mode.

Thanks,

**Comment by danjac** [comment]
On Fedora 31/Gnome 3.34 I have an issue where the light theme on Tilix is always selected (even if I set the theme to Dark in the settings) when the GTK theme is set to Adwaita Dark, but in normal Adwaita the Tilix dark theme works fine.  Tilix is the only GTK app as far as I know with this bug.
