### ISSUE TITLE
Saving Config is not working

### ISSUE THREAD

**Issue by tgwaste** [gnunn1/tilix#1847]
eve/home/ted$ tilix --version
Versions
	Tilix version: 1.9.1
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1

eve/home/ted$ dconf dump /com/gexperts/Terminix/ > terminix.dconf

eve/home/ted$ ls -la terminix.dconf 
-rw-r--r-- 1 ted ted 0 Feb 27 00:28 terminix.dconf

eve/home/ted$ wc -l terminix.dconf 
0 terminix.dconf

Any ideas?

**Comment by GAmblerDice** [comment]
dconf dump /com/gexperts/Tilix/ > tilix.dconf ? 
u can try to autocomplit dconf dirs by tab

**Comment by tgwaste** [comment]
much better, thank you!
