### ISSUE TITLE
Allow Alt + C/V shortcuts for copy and paste

### ISSUE THREAD

**Issue by BjoernDaase** [gnunn1/tilix#1849]
It would be great, if we could <kbd>Alt</kbd> + <kbd>C</kbd> as an alternative shortcut for copying content and <kbd>Alt</kbd> + <kbd>V</kbd> as alternative content for pasting content.  
This would:
1. Make tilix feel more natural for (Ex-)MacOs users, as they use <kbd>Command</kbd> + <kbd>C</kbd> and  <kbd>Command</kbd> + <kbd>V</kbd> to copy/paste content, while there <kbd>Command</kbd> key has the same physical location on the keyboard as our <kbd>Alt</kbd> key.
2. This would avoid to press <kbd>Ctrl</kbd> +  <kbd>Shift</kbd> + <kbd>C</kbd>, which is by far not easy to reach and not very ergonomic.

**Comment by phw** [comment]
You can customize the shortcuts in the settings.

Also note that Tilix supports setting the copy action to Ctrl+C. In this case Tilix will copy if text is selected and if nothing is selected send the keypress to the terminal.

**Comment by egmontkob** [comment]
You might be interested in https://gitlab.gnome.org/GNOME/gnome-terminal/issues/220. If that gets implemented, it'll be easy to hook up to Tilix as well.

(Or are you perhaps the same guy as over there? :-) I can't tell.)

**Comment by BjoernDaase** [comment]
> You can customize the shortcuts in the settings.

Nice, looked for it on the `Shortcuts` page. Closing.

> Also note that Tilix supports setting the copy action to Ctrl+C. In this case Tilix will copy if text is selected and if nothing is selected send the keypress to the terminal.

Smart, I will definitely try that out.

**Comment by BjoernDaase** [comment]
> You might be interested in https://gitlab.gnome.org/GNOME/gnome-terminal/issues/220. If that gets implemented, it'll be easy to hook up to Tilix as well.
(Or are you perhaps the same guy as over there? :-) I can't tell.)

Actually I am not :laughing: It seems like there are just two persons, having the same first name and asking the same question :grimacing: 

Anyway, thanks for the link. I have just skimmed over it now but will read it in detail later on.

**Comment by egmontkob** [comment]
> having the same first name and asking the same question

with the same background context (coming from Mac), and within two weeks :-)
