### ISSUE TITLE
tilix session with multiple tabs

### ISSUE THREAD

**Issue by 3coma3** [gnunn1/tilix#1851]
Hi I'm trying to get tilix to open a json describing a window with four tabs with a different command each, but it only opens the last one. Is this possible at all?

I've been trying to adapt the JSON I exported from one of the tabs:

```
{
    "child": {
        "title": "project1",
        "directory": "\/home\/repos\/project1",
        "overrideCommand": "vim -S session.vim",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "height": 1032,
        "readOnly": false,
        "synchronizedInput": false,
        "type": "Terminal",
        "width": 1920
    },
    "child": {
        "title": "project2",
        "directory": "\/home\/repos\/project2",
        "overrideCommand": "vim -S session.vim",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "height": 1032,
        "readOnly": false,
        "synchronizedInput": false,
        "type": "Terminal",
        "width": 1920
    },
     "child": {
        "title": "project3",
        "directory": "\/home\/repos\/project3",
        "overrideCommand": "vim -S session.vim",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "height": 1032,
        "readOnly": false,
        "synchronizedInput": false,
        "type": "Terminal",
        "width": 1920
    },
     "child": {
        "title": "project4",
        "directory": "\/home\/repos\/project4",
        "overrideCommand": "vim -S session.vim",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "height": 1032,
        "readOnly": false,
        "synchronizedInput": false,
        "type": "Terminal",
        "width": 1920
    },
    "height": 1032,
    "name": "projects",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 1920
}

```

**Comment by pbulteel** [comment]
Have you figured this out? Has anyone answered you? 

As far as I can tell, you should have sub children. And there are attributes missing.

```
{
  child {
       ### you're missing this below
        "orientation": 0,
        "position": 50,
        "ratio": 0.5,
        "type": "Paned"
       ### you're missing this above
    child1 {
      your stuff
    },
    child2 {
      your other stuff
    },

   "height": 1032,
   etc,
}
```

**Comment by 3coma3** [comment]
Hi! Thanks for replying, no, I didn't get other answers. I'm trying to get references on what is that I'm missing from your config, but I see also that you are specifying "Paned", I'm not trying to set up multiple panes, but multiple **tabs** (aka sessions in tilix terminology). And on each session, run a different command, but every session would have a single pane/window/terminal.

**Comment by toni-lv** [comment]
I am having same issue in Ubuntu 20.04 and I think it is because using a command in more than one word. I don't know how to solve but it would be very interesting if someone can help.

**Comment by 3coma3** [comment]
@toni-lv and everybody sorry for not having updated this issue, in fact I did solve this a long time ago already and managed to have many tilix sessions with multiple tabs each. My solution goes like this:

1. Have a  dedicated directory for tilix sessions (like ~/.tilix or whatever)
2. Under the tilix session directory, have _one subdirectory per each multi-tab session_ you make
3. Have separate JSON configs, one per tab, under the "session subdirectories" in 2.
4. Point tilix to the session subdirectories (I wrapped this part in a script)

The wrapper is this bash code:
```bash
#!/bin/bash

go() {
    session="$1"
    sessions_dir="$HOME/.tilix-sessions"
    tilix_opts=''

    for session in "$sessions_dir/$session/"*; do
        tilix_opts="$tilix_opts -s $session"
    done

    tilix $tilix_opts
}

go $@
```
This way I can just write ```tilix-session``` _session-name_ and have a multitab window opened, with different commands open on each tab.

This is an example session subdirectory:

```
ls -l ~/.tilix-sessions/
total 0
drwxr-x--- 1 me me 134 jun 28  2020 iac
drwxr-x--- 1 me me  42 jun 27  2020 pve
drwxr-x--- 1 me me 100 jul 17  2021 pve-new

ls -l ~/.tilix-sessions//iac/
total 20
-rw-r----- 1 me me 451 jun 28  2020 000general.json
-rw-r----- 1 me me 446 jun 28  2020 001roles.json
-rw-r----- 1 me me 452 jun 28  2020 003bundles.json
-rw-r----- 1 me me 459 jun 28  2020 004image.json
-rw-r----- 1 me me 430 jun 28  2020 005git.json
```
And then you have

**000general.json** 
```json
{
    "child": {
        "type": "Terminal",
        "title": "general",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "directory": "\/home\/me\/work\/repos\/iac",
        "overrideCommand": "vim -S general.vim",
        "readOnly": false,
        "synchronizedInput": false
    },
    "version": "1.0",
    "type": "Session",
    "name": "general",
    "width": 1920,
    "height": 1032,
    "synchronizedInput": false
}
```
**001roles.json** 
```json
{
    "child": {
        "type": "Terminal",
        "title": "general",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "directory": "\/home\/me\/work\/repos\/iac",
        "overrideCommand": "vim -S roles.vim",
        "readOnly": false,
        "synchronizedInput": false
    },
    "version": "1.0",
    "type": "Session",
    "name": "roles",
    "width": 1920,
    "height": 1032,
    "synchronizedInput": false
}
```
**003bundles.json** 
```json
{
    "child": {
        "type": "Terminal",
        "title": "general",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "directory": "\/home\/me\/work\/repos\/iac",
        "overrideCommand": "vim -S bundles.vim",
        "readOnly": false,
        "synchronizedInput": false
    },
    "version": "1.0",
    "type": "Session",
    "name": "bundles",
    "width": 1920,
    "height": 1032,
    "synchronizedInput": false
}
```
**004image.json** 
```json
{
    "child": {
        "type": "Terminal",
        "title": "general",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "directory": "\/home\/me\/work\/repos\/iac",
        "overrideCommand": "vim -S image.vim",
        "readOnly": false,
        "synchronizedInput": false
    },
    "version": "1.0",
    "type": "Session",
    "name": "general",
    "width": 1920,
    "height": 1032,
    "synchronizedInput": false
}
```
**000general.json** 
```json
{
    "child": {
        "type": "Terminal",
        "title": "general",
        "profile": "c8e5ff9a-a2e1-4279-a817-72f9814a619e",
        "directory": "\/home\/me\/work\/repos\/iac",
        "overrideCommand": "bash",
        "readOnly": false,
        "synchronizedInput": false
    },
    "version": "1.0",
    "type": "Session",
    "name": "general",
    "width": 1920,
    "height": 1032,
    "synchronizedInput": false
}
```
When I run `tilix-session iac` I get a window like this:

![tilix-session](https://user-images.githubusercontent.com/1572047/165854712-529397d8-5fb5-4afd-a842-a29510512535.png)
 
Note that for many this way of multiple tabs, each with a vim session WITH multiple tabs, each with multiple windows is an abomination (I actually have been told that :-) ), for me it's great, like a big workspace where I have all the parts I need organized just the way I want and readily available. I can work on inter-related parts  of a big project seamlessly and have direct access, both in editor and mentally, to very different sections that might relate.

One thing I would like though is to retain ctl-z to stop the vims and drop to the shell for a quick command (I tend to do that much more than using !bash, since it's quicker to type). But since the overrideCommand is vim, it doesn't have a shell, it's just a barebones vim instance. I couldn't hit the right combination of escapes to call vim with `bash -c ....`, if someone is able to crack that one, it would be awesome(r). 

Using `bash -c` would also enable something that is even quicker / nicer with tilix: just snap a new split for a temporary command. Since bash isn't CDing to the working directory of the project, a new tilix split starts at $HOME. I guess I could instruct vim to change directory instead, but I feel it would be more elegant to just wrap the thing into a proper shell.
