### ISSUE TITLE
cannot run uninstall.sh on Ubuntu 18.04.4 

### ISSUE THREAD

**Issue by corradom** [gnunn1/tilix#1853]
Hi, 
I installed manually the latest version of tilix, and then I discovered issues running it on Ubuntu :cry: 

Thus I was trying to uninstall it, following the readme: but unfortunately the script doesn't work.
```
sudo sh uninstall.sh 
uninstall.sh: 8: uninstall.sh: Syntax error: newline unexpected
```

how can I remove it manually in order to install it from other sources/packages ?

thanks.

**Comment by denisgolius** [comment]
You can install tilix from ppa
https://launchpad.net/~webupd8team/+archive/ubuntu/terminix
