### ISSUE TITLE
Run hyperlink in current terminal

### ISSUE THREAD

**Issue by wolfwolker** [gnunn1/tilix#1883]
Would be nice to be able to run hyperlink commands in the same terminal you are clicking in:

Usage example:

1. you configure a hyperlink to run vim $0 on .*\.txt
2. you connect using ssh to a remote server and run ls, showing some txt files

**Comment by egmontkob** [comment]
Unfortunately this can only work if the shell is waiting for a command to be typed, with the command line currently being empty. And the terminal has no idea if this is the case or not. Injecting the keypresses whenever the shell is in another context (e.g. simply the command line already contains some text), or some app is running, might easily have uncontrollable undesired side effects.

**Comment by wolfwolker** [comment]
Gotcha. Anyway, the workaround I'm using right now, in case is useful for someone is to copy the desired command in the clipboard automatically on click, so you only need to click your regexp and then ctrl+shift+v to paste in the current terminal or wherever you want.

`echo "vim $0" | xsel -b`
