### ISSUE TITLE
zsh-autosuggestions

### ISSUE THREAD

**Issue by brightmaraba** [gnunn1/tilix#1898]
zsh-autosuggestion works on Gnome Terminal but not on Tilix
Ubuntu LTS 20.04

``plugins=(zsh-autosuggestions zsh-completions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
autoload -Uz compinit && compinit``

It worked perfectly on Ubuntu 18.04 with the same exact .zshrc

**Comment by the-vampiire** [comment]
its working for me on pop_os 20.04 LTS which is just a skin over ubuntu afaik

here is my settings (not sure what autload -Uz and all that is in your command):

```sh
plugins=(
  git
  zsh-nvm
  zsh-autosuggestions
  zsh-syntax-highlighting
  docker
  docker-compose
  zsh-z
)

source $ZSH/oh-my-zsh.sh

...other settings
```

**Comment by phw** [comment]
This is an issue with the shell (zsh), not with tilix, which just is the terminal emulator.

**Comment by poulou0** [comment]
In my case it was the **color scheme** that i set for Tilix, "**Monokai Dark**" works just fine for me.
 _Preferences > (your/default) profile > Color (tab) > Color scheme_

**Comment by brightmaraba** [comment]
@poulou0 Mate! You are awesome. It was the Color! Thanks a lot!

**Comment by alireza-shirzad** [comment]
> In my case it was the **color scheme** that i set for Tilix, "**Monokai Dark**" works just fine for me. _Preferences > (your/default) profile > Color (tab) > Color scheme_

You saved me bro!
Thanks a lot
