### ISSUE TITLE
Tilix Not available in kali-linux w45 build

### ISSUE THREAD

**Issue by skulldealer** [gnunn1/tilix#1958]

**Comment by skulldealer** [comment]
![IMG_20201104_170825.jpg](https://user-images.githubusercontent.com/65908813/98107315-5dbaa800-1ec0-11eb-9352-9a232e39d79e.jpg)

**Comment by skulldealer** [comment]
Meanwhile for any other package

![IMG_20201104_171023.jpg](https://user-images.githubusercontent.com/65908813/98107585-ba1dc780-1ec0-11eb-8374-82167ffe45af.jpg)

**Comment by phw** [comment]
You'd need to report this to your distribution, they are maintaining their package repositories. If they don't have tilix ask them to include it.

**Comment by skulldealer** [comment]
Just followed up with kali-linux developer and administrators 

See this
https://tracker.debian.org/news/1180947/tilix-removed-from-testing/

Tilix removed from debian buster beacuse of a bug. Will be across many distros! Contact debian asap if you are reading this

**Comment by heybam** [comment]
add to your repo

`deb http://http.kali.org/kali kali-last-snapshot main non-free contrib
deb http://http.kali.org/kali kali-experimental main non-free contrib`

**Comment by heybam** [comment]
add to your repo

`deb http://http.kali.org/kali kali-last-snapshot main non-free contrib`
`deb http://http.kali.org/kali kali-experimental main non-free contrib`
