### ISSUE TITLE
It's really difficult for me to know on what "tile" I'm currently working on.

### ISSUE THREAD

**Issue by vinliao** [gnunn1/tilix#1963]
This is more of an UI/UX problem rather than engineering problem.

I came from terminator, and they have a bright red indicator above the currently focused tile. In tilix, I can hardly know where I am when I jump into my terminal.

![Screenshot from 2020-11-23 19-18-36](https://user-images.githubusercontent.com/34117807/99961622-4edd5c00-2dc1-11eb-9ff2-e992c89a9ff5.png)

Is there a way to let the user know where the current tile tilix is currently focusing at?

**Comment by jere-ortega24** [comment]
You can dim the unfocused tiles.
Go to Preferences > Profiles > Your profile > Color > Unfocused dim

**Comment by vinliao** [comment]
@jere-ortega24 wow that's a sick solution. Problem solved, closing issue.

Thanks.
