### ISSUE TITLE
Change Tilix icon

### ISSUE THREAD

**Issue by skulldealer** [gnunn1/tilix#1973]
I have manually changed all icons through .desktop file in /usr/applications but there is no . desktop file for Tilix. How do I change the icon. Where is the file where default .svg path is listed. I want to modify the icon path. I am using debian ubuntu 20.10.

Thanks

**Comment by yochananmarqos** [comment]
It should be `/usr/share/applications/com.gexperts.Tilix.desktop`:
```
Icon=com.gexperts.Tilix
```

**Comment by yochananmarqos** [comment]
FYI, you shouldn't editing system files. Copy the `.desktop` files from `/usr/share/applications/` to `~/.local/share/applications/` then edit them.
