### ISSUE TITLE
Menu and/or shortcut to start a specific profile

### ISSUE THREAD

**Issue by xisberto** [gnunn1/tilix#1983]
If this already exists, help me find the option.

What I'm trying to achieve: have a "home" and a "work" profile.

Home profile will be my default.

Work profile will have ssh on its custom command (Run custom command instead of my shell).

I need a easy way of _starting_ the Work profile, not _changing_ from Home profile to it.

On #1515 there's a shortcut to _change_ the profile, is there any option to _start_ a new session under selected profile?

**Comment by phw** [comment]
There is a `--profile=PROFILE_NAME` command line parameter, see also `tilix --help`

**Comment by xisberto** [comment]
Thanks.

I used "`tilix -p Work`" in the WM shortcuts to get this working.
