### ISSUE TITLE
Bold and semi-bold fonts not correctly rendered using vte 0.62.2

### ISSUE THREAD

**Issue by dottorblaster** [gnunn1/tilix#1984]
Hi,
I'm using a semi-bold font in my terminal right now and using vte 0.62.2 looks like the font weight gets ignored.

Doing a bit of researches I came over [this commit](https://gitlab.gnome.org/GNOME/vte/-/commit/868602fdbe590761418f6be1242b625d494078b1) and I was wondering, given:

> Style and weight need to be default here,
>         * since those are set via SGR attributes

is there any plan to implement this inside tilix, or is this a bug that has to be solved inside VTE?

**Comment by dottorblaster** [comment]
(Anyway I think the comment in this patch has a point, and I hope it gets merged https://gitlab.gnome.org/eworm-de/vte/-/commit/a7d163a0e1fd874fad34b3427749337d851dc2a9)

**Comment by wuxb45** [comment]
I observe the same issue with Roboto Mono and Noto Mono.

**Comment by dottorblaster** [comment]
The issue is being discussed on the GNOME Gitlab, I'm fairly confident that the commit should get reverted but you never know https://gitlab.gnome.org/GNOME/vte/-/issues/323 :D

**Comment by dottorblaster** [comment]
Closing as the behavior seems ok now. Feel free to reopen in a second moment.
