### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by baermathias** [gnunn1/tilix#1987]
@gnunn1 is there a new release planned?

**Comment by ximion** [comment]
We still need a maintainer to step up (see https://github.com/gnunn1/tilix/issues/1700), but I am currently working on blowing some of the dust off `master`, go through the pending PRs and test if the current state is shippable.
If it is, I'd release version 1.9.4, which may - if it happens early enough to permit enough testing - make it into the next Debian release.
That's the state of things, currently.

**Comment by ghuls** [comment]
@ximion Can you add a `tilix.zip` to the 1.9.4 version?

**Comment by ximion** [comment]
I can, but I think you would be much happier just using a distribution-packaged version or the Flatpak variant. Plain binaries-in-a-tarball tend to break quite often or show odd bugs. They are also non-trivial to install.

**Comment by baermathias** [comment]
Does this help for snap packages?
https://github.com/snapcrafters/fork-and-rename-me
