### ISSUE TITLE
"Select all" feature only select visiable area.

### ISSUE THREAD

**Issue by BlackDex** [gnunn1/tilix#1989]
Version: 1.9.1
OS: Arch Linux

`vte-2.91 --version`
`VTE Application 0.62.2 +BIDI +GNUTLS +ICU +SYSTEMD`

Hello there,

I'm using Tilix for a while, and i don't know what happened, but i'm sure i was able to select the `Select all` option which would select the whole history. Now it seems to only select the visible area.

**Comment by evgom** [comment]
Same problem here.

Version: 1.9.3
OS: openSUSE Tumbleweed

**Comment by evgom** [comment]
Looks like this commit is the cause:

https://gitlab.gnome.org/GNOME/vte/-/commit/caf8a6a7a17a3f70fa5fc611c71ffb27a5cfee75

**Comment by BlackDex** [comment]
Hmm, not much this project can do to fix that.
Maybe i need to revert a version.

**Comment by GAmblerDice** [comment]
There is an option in terminal title > other > save output, can it help in your problem, or u using select all option for somethin else besides saving history.

**Comment by BlackDex** [comment]
Well, it is a work-around, but it isn't actually the same.
I often use it to just copy/paste output somewhere on slack, meld etc..
This would create a few extra steps, saving, opening, copy/paste, delete file.

But since it's not something Tilix can fix, i will close this :).

**Comment by trizen** [comment]
I lost so much data due to this issue. :( I assumed it copied the entire text in the terminal, like it used to do before. After I closed the terminal, I realized that it didn't...

**Comment by xird** [comment]
For the next person who ends up here looking for a fix, here's the vte milestone that is meant to fix this, hopefully somewhere in the near future: https://gitlab.gnome.org/GNOME/vte/-/milestones/19#tab-issues
