### ISSUE TITLE
Tilix recently stopped recognizing URLs in the terminal output

### ISSUE THREAD

**Issue by msnspk** [gnunn1/tilix#1996]
I'm building Tilix using the [tilix-git](https://aur.archlinux.org/packages/tilix-git/) package in the Arch AUR, and after rebuilding the package with the [latest commit](https://github.com/gnunn1/tilix/commit/fc66b67b1625cdf9f1af6318a5d08789de351a55), Tilix stopped recognizing URLs in the terminal output, so I can no longer click and open them in my web browser.

Unfortunately, there are no error messages or other output that I can find, and deleting my configuration and rebuilding the package from scratch has not resolved the issue.

The regular [tilix](https://archlinux.org/packages/community/x86_64/tilix/) package in the Arch repository, based on the current 1.9.3 release, still recognizes URLs and works fine.

Additionally, other VTE-based terminal emulators such as [xfce4-terminal](https://archlinux.org/packages/extra/x86_64/xfce4-terminal/) and [gnome-terminal](https://archlinux.org/packages/extra/x86_64/gnome-terminal/) work fine. The issue seems to be specific with a recent Git revision of Tilix.

I am not sure if it is relevant or not, but the [vte3](https://archlinux.org/packages/extra/x86_64/vte3/) package in the Arch repository was updated 2021-01-09, so maybe that has something to do with the issue?

For now I am bypassing this issue by including a custom regex in my Tilix configuration:

`http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+`

Command:

`xdg-open $0`

Sorry I could not be of more help

**Comment by ximion** [comment]
Hmm, the only change relevant to this was https://github.com/gnunn1/tilix/commit/3cf00bd59eaa1ea1bf2365197f238da75723812c, but I don't see how that would have broken URL recognition.
Can you test if reverting this change fixes the behavior for you?
