### ISSUE TITLE
Ubuntu old package

### ISSUE THREAD

**Issue by alexforte** [gnunn1/tilix#2060]
Hi,
we love to use tilix, but on Ubuntu last package version is 1.7.7, that had a lot of bugs (the most important is save session it's not ok).
How it's possible to update to latest version? 
Ubuntu is 18.04 LTS

**Comment by eladyn** [comment]
Don't know if it is still relevant:

Ubuntu is a distribution with regular stable releases (18.04) and thus does usually not provide big updates for packages.

If you want to use newer versions of the software, you are recommended to upgrade to a newer Ubuntu version. If this does not suit you, you can always try to [install Tilix differently](https://gnunn1.github.io/tilix-web/#packages).

For Ubuntu, there is apparently [a PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/terminix), which *should* provide you with more recent versions. If this does not work (haven't tested it), you can always try to install Tilix manually. (see manual installation [here](https://launchpad.net/~webupd8team/+archive/ubuntu/terminix))

Hope this helps!

**Comment by ximion** [comment]
The best option is likely to just update Ubuntu to 20.04 or higher (as 18.04 will run out of support for desktop soon-ish anyway), the easiest may be building from source (unless that PPA works).
