### ISSUE TITLE
Remove background information

### ISSUE THREAD

**Issue by antonio-petricca** [gnunn1/tilix#2065]
Hi, I just updated to the latest release and I see those backgrounds information which I would remove:

![image](https://user-images.githubusercontent.com/6660386/141334160-0d930138-f0ef-465a-b6e8-56fbd6d9f383.png)

How can I accomplish that?

Thank you so much.

**Comment by antonio-petricca** [comment]
Hi, does anybody have the same issue?

**Comment by 237dmitry** [comment]
`tilix --preference` and clear `Badge` field in `profile` settings

**Comment by antonio-petricca** [comment]
Thank you so much, it worked!
