### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gitdrug** [gnunn1/tilix#2075]
.

**Comment by MauricioRobayo** [comment]
Hi @gitdrug . I have spent a lot of time dealing with this same problem, and in the end it seems it is not related to vte but with  `hostname`: https://github.com/gnunn1/tilix/issues/1954#issuecomment-730191381

Try changing your hostname and see if that solves it:

```hostnamectl set-hostname tilix`

**Comment by almson** [comment]
I've never had a problem with Tilix, fish, Xfce, and Arch Linux inheriting the PWD.

It can't be related to /etc/profile.d/vte.sh (or its hostname bug) since that doesn't set fish's command prompt.

**Comment by BarbzYHOOL** [comment]
> `hostnamectl set-hostname tilix`

that's kinda dumb and useless

So any solution?? Notifications don't work at all
