### ISSUE TITLE
The search bar can not be closed?

### ISSUE THREAD

**Issue by OhGhie4iew** [gnunn1/tilix#2131]
Control-F opens the search bar, but there is no close button.
I'm aware that you can press escape, but that is not easily disvoverable.

**Comment by okias** [comment]
Agree. I hit this usability issue multiple times.

**Comment by ericriff** [comment]
+1 on this, very annoying

**Comment by cifvts** [comment]
I wrote a patch that add a close button to the bar, nothing fancy:
![image](https://user-images.githubusercontent.com/34901/233657778-5e4bb02b-f2d2-448e-ad20-86b4f8cfb22e.png)

Could something like this be helpful?
