### ISSUE TITLE
Feature request: open subterminal and go to the directory of the current terminal

### ISSUE THREAD

**Issue by paaguti** [gnunn1/tilix#2133]
In Terminator, when you right-click on a terminal and split to open a second terminal, you are automatically placed in the same directory:

![image](https://user-images.githubusercontent.com/3320432/201906218-eb921d35-efbe-4bac-b407-d6875363bf8a.png)

This may save a lot of typing

**Comment by ricjcs** [comment]
I also want this feature.

**Comment by paaguti** [comment]
Seems to be working on recent Ubuntu debs.
