### ISSUE TITLE
Tilix fails to build with phobos `>= 2.101`

### ISSUE THREAD

**Issue by tranzystorek-io** [gnunn1/tilix#2151]
Phobos 2.101 under ldc 1.31 removes xml from std, which results in Tilix failing to build.

**Comment by tranzystorek-io** [comment]
Seems switching over to https://github.com/dlang/undeaD would help making tilix more forward-compatible

**Comment by yochananmarqos** [comment]
Arch just rebuilt on LDC using upstream undeaD with [1.9.5-5](https://github.com/archlinux/svntogit-community/commit/722423733c05cb5ed8e7a6ae64b79799795e51e6).
