### ISSUE TITLE
"cd .." doesn't work [finally my mistake, not an issue]

### ISSUE THREAD

**Issue by Uhter** [gnunn1/tilix#2189]
Hi everybody,

The `cd ..` command doesn't work as expected. It always change to _~/.local/share/Trash/files_ directory.
I think I'm the only one, but what can I do please?

(Tilix v1.9.5-11, on Manjaro Linux and Xfce)

[EDIT]
This is NOT an issue!

**Comment by 237dmitry** [comment]
Check aliases:

```
$ alias
```

**Comment by Uhter** [comment]
This is the first I did, but I have not alias with "cd".
And if I run `cd ..` in another terminal, the command work well. That the reason why I think this is a Tilix issue. But…
there may be other leads.

**Comment by Uhter** [comment]
I found the answer in this [Askubuntu message](https://askubuntu.com/a/1398831)!
"This happens when you delete a directory using GUI or outside the terminal. But in the terminal, you are still in the directory you have deleted recently."

So, this not a Tillix issue but a human issue: me!
Sorry for that.

**Comment by waldyrious** [comment]
@Uhter if this is not an actual issue, could you close it please?

**Comment by Uhter** [comment]
I would like but how can I do? I'm not admin.

**Comment by waldyrious** [comment]
As the author of the issue you should have the ability to close it. You should have the following buttons under the comment box at the bottom of this issue thread:

![image](https://github.com/gnunn1/tilix/assets/478237/03908e4a-b97a-4ed8-bff8-4ffb5910a517)

Do you see something different?

**Comment by Uhter** [comment]
Wow! I've never seen that button before.
Maybe 'cause I never needed it :)

Tx @waldyrious
