### ISSUE TITLE
Titlebar too large

### ISSUE THREAD

**Issue by thiagomg** [gnunn1/tilix#2199]
Hello,
It would be great to reduce the size of the titlebar - or follow the window manager theme. It's currently super tall for smaller screens.

I added a screenshot of one using the DE theme and tilix.

![terminal](https://github.com/gnunn1/tilix/assets/6472480/0fe36cf1-9dbc-46c7-bc02-a5a35b4307df)

Thanks!

**Comment by 237dmitry** [comment]
![ss](https://github.com/gnunn1/tilix/assets/78153320/fbe167e4-d44e-485c-85ec-b0ac0914b29b)

**Comment by thiagomg** [comment]
Thanks! Somehow I missed that.
