### ISSUE TITLE
Flickering Terminal

### ISSUE THREAD

**Issue by protektwar** [gnunn1/tilix#2213]
Hello, I encounter some flickering in the Tilix Terminal. Everything started a couple of weeks ago, but I was thinking is from the keyboard, changed the keyboard, the problem reapers. Strange that it is not happening always only sometimes, but then it is starting, then you can't use the terminal anymore, especially when you code in vim. It's not the vim, as it's happening also in the shell.. changed the shell it is the same.

Here is a link with what is happening:
<https://www.youtube.com/watch?v=dHSQrx6t4hI>

I'm using Ubuntu 22.04.4 LTS, the system is up to date.
Package: tilix
Version: 1.9.4-2build1
Priority: optional
Section: universe/gnome
Origin: Ubuntu

Maybe this is not related to Tilix, but to GTK?!

**Comment by egmontkob** [comment]
Could be related to

https://gitlab.gnome.org/GNOME/mutter/-/issues/3384
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2059847
https://askubuntu.com/q/1509058

(three different links about the very same issue), although could be something different.

Would be nice to see if the update there fixes your issue. If not then it's probably still something with Mutter / NVidia driver. Most definitely not Tilix or VTE, probably not GTK either.

**Comment by protektwar** [comment]
Good to know it's not Tilix... NVidia I have, so it must be related. 
Thanks!
