### ISSUE TITLE
Delay in registering keys in CLI

### ISSUE THREAD

**Issue by aalbaali** [gnunn1/tilix#2221]
I'm having a strange issue with tilix and quake, where the keyboard keys are registering, but are delayed by one click. For example, to list all files, I click `ls<CR>`. However, this doesn't immediately show the files. Instead, I have to press some arbitrary key (e.g., `<Space>`) in order for the keys to register (i.e., `ls<CR><Space>`).

This behavior is prevalent in different applications such as in (neo)vim. It's inconsistent: sometimes it happens, sometimes it doesn't,. sometimes the results show up after around a second of delay (i.e., no need to press an additional button).

This issue only happens on Tilix and Quake and not other terminals (e.g., Kitty or xterm). Furthermore, it happens in both bash and zsh.

Any help is appreciated.

**Comment by egmontkob** [comment]
https://askubuntu.com/questions/1509058/input-delay-on-terminal-ubuntu-22-04-4 by any chance?
