### ISSUE TITLE
Every new window opens with a percentage sign at the first line and prompt at the second line. 

### ISSUE THREAD

**Issue by bakai-taalaibek** [gnunn1/tilix#2224]
https://github.com/gnunn1/tilix/assets/121804957/64285f32-6f2e-4edf-9308-b7d3e50a2595

I think tilix exhibits this behavior only recently. This problem only exists on zsh, even if I completely clear the zshrc file. On bash there are not excessive percentage signs.

 I am on Fedora, Gnome, Wayland, zsh.

**Comment by egmontkob** [comment]
See #1777.

**Comment by bakai-taalaibek** [comment]
Ok I guess this is not a Tilix issue, and there are no fixes.
