### ISSUE TITLE
tilix session closes automatically after command ends

### ISSUE THREAD

**Issue by Mag1cByt3s** [gnunn1/tilix#2236]
How can i tell tilix to keep my tab / session open once the command finishes?

Example:

I start an nmap scan like so in a new tilix session:
```bash
tilix -a app-new-session -t nmap -x "nmap -p443 website.com"
```

Once the scan is finished (nmap exits) the tab also closes immediately.

Is there any way to keep the tabs open after execution of the command?

**Comment by 237dmitry** [comment]
> Once the scan is finished (nmap exits) the tab also closes immediately.

What should be running in the tab after nmap finishes? Search for "How to invoke bash, run commands inside the new shell, and then give control back to user?"

**Comment by Mag1cByt3s** [comment]
> > Once the scan is finished (nmap exits) the tab also closes immediately.
> 
> What should be running in the tab after nmap finishes? Search for "How to invoke bash, run commands inside the new shell, and then give control back to user?"

The tab should just stay open so you can look at the results. It should just drop you into the shell.

**Comment by 237dmitry** [comment]
> It should just drop you into the shell

The $SHELL should be running in this case, where did you launch it? For example:

```
tilix -a app-new-session -t "some title" -e bash -c "ping example.com; exec bash"
```

**Comment by Mag1cByt3s** [comment]
> > It should just drop you into the shell
> 
> The $SHELL should be running in this case, where did you launch it? For example:
> 
> ```
> tilix -a app-new-session -t "some title" -e bash -c "ping example.com; exec bash"
> ```

that works.

It now drops me into a bash shell once the command exits.

Thanks.
