### ISSUE TITLE
Re-Tile terminals

### ISSUE THREAD

**Issue by Cybso** [gnunn1/tilix#360]
I suggest a feature to retile all windows within a session, like clusterssh does.

For example 4 terminals will be tiled to 2x2 while 6 terminals will be tiled to 3x2 and nine to 3x3.

I think the difficult task would be to find the optimal number of columns and rows, because for example in a window that spans over two displays the optimal solution might be to arrange 4 terminals in one row.

**Comment by gnunn1** [comment]
It shouldn't be super hard to do, it just involves un-parenting the existing terminals and then creating the GTKPaned from scracth and re-parent the terminals appropriately. The feature could even prompt the user for the number of rows/columns.

Having said that, this would be a pretty low priority feature for me to implement but I'm happy to take a pull request for it.

**Comment by Cybso** [comment]
ClusterSSH is using a fixed preconfigured column width:

https://github.com/duncs/clusterssh/blob/55c91fe9915cc5c004643eab86cb61223641c313/lib/App/ClusterSSH.pm#L891

I think by having this feature, and also add a feature to attach multiple "--execute" calls to the same session via command line, this could even replace ClusterSSH. Synchronized Input is already there. I'll try to have a look at the source within the next weeks...

**Comment by arigit** [comment]
Perhaps in addition to tiling in "grid style" it would also be nice to have options to re-tile Vertically or re-tile horizontally - either option giving equal area to each terminal
Somewhat aligned with what the Gnome-Shell extensions for tiling do

**Comment by gnunn1** [comment]
I'm cleaning up issues and closing this as I don't have any plans to implement it.
