### ISSUE TITLE
some ideas for tile management and tile selection

### ISSUE THREAD

**Issue by almson** [gnunn1/tilix#373]
Enabling idea: Forming a selection of multiple tiles using:
- right-click drag
- ctrl- or shift- left click

Resizing:
- resize two tiles without causing other tiles to be proportionally resized by selecting them and dragging the common separator. If more than two tiles are selected, then the other tiles are resized proportionally.

Reshaping
- Align the edges of a group of tiles into a rectangle by selecting them and clicking a button.

Splitting:
- Create a new tile that sits below a group of tiles by selecting the tiles from which to take space, and selecting split down. New tile will have the width of the selected tiles and height half of the selected tiles. Selection remains active so that the height could be adjusted. It helps if the tiles form a rectangle (were reshaped), but if they're not then reshaping could be done automatically prior to splitting.

Renumbering:
- renumber a group of tiles by selecting them and renumbering left-to-right from a specified index

Existing functions:
- setting profiles, encoding, synchronizing input would work on the level of selection

Appropriate UI changes would include moving the per-tile drop-down to the top, and have the controls there, plus the additional controls for the above features, operate on selected tiles. The active tile is automatically selected.

**Comment by gnunn1** [comment]
Thanks for the ideas, there are some interesting concepts there. At the core, the ideas all seem to revolve around the idea of being able to group terminals together, if the intent is for this grouping to be persistent it might involve some architectural changes in Terminix to handle this representation. Transient might be easier, though I'd have to think more about it, but less useful and not likely to support all of your ideas. 

I probably won't get a chance to look at this anytime soon as my plate is full with other features I want to do first, however if someone else wants to take this on feel free to let me know.

**Comment by almson** [comment]
Thank you for the warm reception. I was actually imagining this would be transient (ie, selections). I think persistent "grouping" would be a huge cognitive load because it's like "omg I have to organize."

**Comment by gnunn1** [comment]
I'm doing some clean-up on some of the older issues that frankly will never get implemented. While this one as some interesting ideas, it would require massive re-working of the architecture and I don't have the appetite for that.
