### ISSUE TITLE
Feature Request: Zoom terminal like maximize but with font scaling

### ISSUE THREAD

**Issue by mjeanson** [gnunn1/tilix#501]
I've recently moved from terminator to terminix and this is the only feature I'm missing. In terminator it's called 'Zoom terminal' and is associated to ctrl+shift+z

Same behavior as 'Maximize terminal' ctrl+shift+x but scale up the font size to best match the row/column size of the initial terminal.

**Comment by gnunn1** [comment]
Note you can do this in Terminix but it is more laborious by maximizing the terminal and then zooming in to the desired size. I don't have any plans to work on this myself, but if someone wants to submit a PR I'd consider it. One caveat, it has to be clearly differentiated from the existing zoom in/out functionality in terms of terminology.

**Comment by almson** [comment]
I think it would help if font zooming worked with Ctrl+Mouse Wheel (like in browsers and most apps).

**Comment by phw** [comment]
@almson That's a separate thing from what is requested here, and it was already implemented in
  https://github.com/gnunn1/terminix/issues/580

There is a option you have to activate for this to work.

**Comment by gnunn1** [comment]
I'm cleaning up issues and closing this as I have no plans to implement it.

**Comment by jdorleans** [comment]
Has anyone considered implementing this yet? This is such an useful feature when you need a quick way to present your terminal to others or sometimes when you're tired of looking at smaller font size. I often times have to maximize and zoom a lot during presentations.

**Comment by gnunn1** [comment]
I just have a profile call Presentation with a large font configured and switch to it when I'm doing presentations.

I still don't have any plans to implement it myself.
