### ISSUE TITLE
Line scroll shortcuts

### ISSUE THREAD

**Issue by nasciiboy** [gnunn1/tilix#698]
I like the project, but to be able to replace konsole I would need these shortcuts

1. scroll line to line
2. copy current line

also appear by default to full screen

and to overcome konsole, need to have a select mode to copy from the keyboard

**Comment by gnunn1** [comment]
You can open it in full-screen by default by passing the ```--full-screen``` switch.

Ctrl+shift+up and ctrl+shift+down scroll a single line only if that's what you mean by "scroll line to line", otherwise I'll need more explanation.

**Comment by nasciiboy** [comment]
ups, what is this command (Ctrl+shift+up/down)? I overwritten it

**Comment by nasciiboy** [comment]
I prefer shift+up/down

**Comment by egmontkob** [comment]
Shift+up/down is used by many apps.

**Comment by gnunn1** [comment]
@egmontkob Understood, however there is benefit in allowing users to customize shortcuts if they wish.

**Comment by nasciiboy** [comment]
I have never had conflicts with that configuration

**Comment by egmontkob** [comment]
I meant my comment as a reminder that Shift+Up/Down shouldn't be the default. You're of course free to configure whatever you prefer for yourself.

**Comment by gnunn1** [comment]
I've added definable shortcuts for these, defaults match VTE keystrokes. Note that if alternative shortcuts are defined, the VTE hard coded ones are still active since there is no way in VTE to disable them.

**Comment by nasciiboy** [comment]
Aware, I'll try it

**Comment by nasciiboy** [comment]
Thanks for implementing the scroll configuration by line!
