### ISSUE TITLE
Feature Request: notify on activity/silence

### ISSUE THREAD

**Issue by nafg** [gnunn1/tilix#776]
Konsole and others have this. When triggered, it waits for the specified condition and shows a desktop notification.

This is useful if I'm waiting for some work to finish in the terminal and want to do something else meanwhile in a different window. This way I'll know when it's done (or may be done) without having to keep switching back to Terminix.

On activity: For example, there's some task running silently. When it finishes it will print output. I want to be notified when any output finally appears.
On silence: For example, a task is running noisily. I want to be notified when a certain amount of time goes by without any output. (Not sure what the ideal time is. Of course the optimal time depends on the circumstance.)

Bonus points if the notification includes a thumbnail or text depicting the last output line(s).

**Comment by phw** [comment]
Notifications on command finished is already available, but requires a patched VTE. See the FAQ on notifications at https://github.com/gnunn1/terminix/wiki/FAQ#notifications

Also there is the "triggers" feature, which may be useful for you. Among other actions it can trigger a desktop notification based on certain output.

The notification if there is a process running but no output for a certain amount of time sounds like a nice feature to have.

**Comment by nafg** [comment]
Notify on activity != matching output.
The output appears often and most of the time I don't want to be notified.
However on occasion I want to be notified if there is any output,
regardless of what the output is.

So while notifying on command complete and notifying on set output pattern
are useful (thanks for including them!), they are very different than both
notify on activity and notify on silence.

Again, the way I described them is the way Konsole implements them (I
believe Terminator as well, not sure), and I miss having them.

**Comment by phw** [comment]
How does notify on activity work in Konsole to avoid spamming you with notifications on longer output?

**Comment by nafg** [comment]
What do you mean by longer? The notification doesn't include the output
text. If you mean repeated output, I'm not sure but it could be it's the
inverse of silence, i.e. until the time elapses again with no output, it
won't notify. According to this approach, we define a notion of silence
detection, and notify on silence triggers on the detection, while notify on
activity *resets* (becomes active again) on the same detection. I'm not
sure though. (I guess the alternative would be to only trigger once.)

I should mention that there are times I would actually prefer a "send all
output to notifications" that could easily be switched on and off. For
example while I'm developing a webapp it might be neat sometimes if every
time it logs an exception or an email it would send, the full text would
flash on the screen. I wonder if it makes sense to try to unify that in
with notify on activity. Basically you'd debounce to collect all lines
outputted within a certain amount of time into one notification, and you'd
have a really short silence test time (pretty much the same as the debounce
time?). But that's more far-fetched.

**Comment by gnunn1** [comment]
@nafg Can you show a screenshot of where this feature is configured in Konsole? Do you basically configure a period of silence after which activity results in notification and the silence timer gets reset?

**Comment by nafg** [comment]
![image](https://cloud.githubusercontent.com/assets/98384/23022172/7a8678b4-f41d-11e6-8320-de2a7e9c2c2b.png)

**Comment by egmontkob** [comment]
Among the VTE-based emulators, xfce4-terminal implements activity-based notification (changes the title's text color in the notebook tab).

**Comment by gnunn1** [comment]
This looks pretty simple to implement, I'll have a look.

**Comment by egmontkob** [comment]
Please see the comment https://bugzilla.gnome.org/show_bug.cgi?id=711059#c24 (I guess I wrote it for the explicit notifications, but is just as well valid for the activity-based one). -- Or is it just me overcomplicating things there? :)

**Comment by gnunn1** [comment]
Maybe, or I'm not seeing the complication. Basically from my perspective it's just:

a. Have a variable with the last time there was activity
b. On every VTE commit check if the time has exceeded the threshold. If it has and session is not visible raise a notification (using existing process already in place) otherwise reset time for variable
c. Only permutation I see is if switching to the tab should reset time in variable

**Comment by egmontkob** [comment]
It's not that hard... just harder than not doing this :D

**Comment by gnunn1** [comment]
I've implemented this feature, there is a new setting in profiles for configuring the silence threshold, if it's 0 then it is disabled. I've tested it with the normal command finished notification, I've tweaked it so that if a command completes after the threshold only the command completed notification is fired. If you don't have command notifications then this will still trigger.

The notification will show the last line of text up to 128 characters.

**Comment by simonbcn** [comment]
To me it doesn't work on Arch Linux.
I have set `Notify new activity` to `15`s and I start the compilation/package of a program with `makepkg -srci` and it focus another window. After compiling, it asks me if I want to install it and it expects my answer. I wait more of those 15 seconds with the focus in another window but it doesn't notify anything.

**Comment by phw** [comment]
Works for me on Arch, but it only notifies if there is actual output. E.g. with "Notify on new activity" set to 15 seconds the following script gives me two notifications "Terminal Activity" (with notification body 20 and 40):

    sleep 20 && echo "20"  && sleep 20 && echo 40 && sleep 5

Do you have the patched VTE installed (which is necessary for notifications)? See https://github.com/gnunn1/tilix/wiki/FAQ#notifications

**Comment by simonbcn** [comment]
It works with those commands but it doesn't work on practical cases like I mentioned before. You can test `makepkg -srci` on the PKGBUILD of `mpv-git` and it doesn't alert when the question `Proceed with installation? [Y/n]`

**Comment by phw** [comment]
I think because there is never a period of 15 s without any output. At least for me the build is constantly progressing and outputting stuff, but the function here only notifies if there is inactivity and then output.

What I have actually done for a similar case is set up a trigger, which triggers a notification. You could setup a trigger as follows:

- Regex: `Proceed with installation\? \[Y/n\]`
- Action: Send notification
- Parameters: `title=Proceed with installation?;body=Some notification body if you want to`

**Comment by simonbcn** [comment]
@phw ok, thanks. I didn't know this utility. It's very useful.
On the other hand, should the Tilix window be focused when I press the notification?

**Comment by simonbcn** [comment]
Terminator has a similar feature and it's very useful:
![captura de pantalla de 2017-03-23 19-25-43](https://cloud.githubusercontent.com/assets/428231/24263847/b616fe24-0ffe-11e7-9afa-c768120f6137.png)

**Comment by phw** [comment]
> On the other hand, should the Tilix window be focused when I press the notification?

Yes, it should. If it doesn't you should open another issue for it with some details on your desktop environment

> The only problem is that trigger triggers too when Tilix has the focus.

True, that annoys me sometimes, too. @gnunn1 does an option for triggers to only trigger for unfocused terminals make sense?

**Comment by gnunn1** [comment]
@phw I'm not sure there needs to be an option, I think it should be as simple as only sending a notification following the same rules as the command notification. i.e.

- If window is unfocused, send full desktop notification
- If notification is from a session that isn't visible but window is focused, show the notification bubble for the session but no desktop notification

Does this make sense, if so feel free to open a new bug report for it and I'll have a look at it.

BTW glad to see you are using triggers, I've been wondering if anyone has been leveraging them besides myself.

**Comment by nafg** [comment]
Hi @gnunn1, I really appreciate what you did -- this is the second time I put in a feature request and you implemented it and within a really short time.

However in it's current form it's not so useful -- it's not something I want to be a persistent setting, but something I can flip on momentarily and temporarily.

For example usually building is quick but I may have decided to do a clean build and read something meanwhile on a different virtual desktop, so I want to flip it on, and maybe there are build errors so I go back and fix them and leave it on, but once it finishes and I can go back to incremental builds I want to flip it off as then it would be very annoying.

Do you think you could add it to the context menu or something?

**Comment by gnunn1** [comment]
@nafg I think the way to handle this is too have two profiles, one where this is defined and one where it is not and then switch between the two in the context menu. I'm not very keen on adding this to the context menu as I'm trying hard to keep the menu to a reasonable size.

**Comment by nafg** [comment]
@gnunn1 what about all the other profile settings? Duplicate everything?

Again, it makes no sense to persist the setting anywhere (other than the timeout value), it's something that is only needed for a few minutes at a time. There's a reason why all the other terminals that have this do it this way.

What is your concern about the context menu size exactly?

Again, this is not a setting but an action. Where would you like to put actions? Or do you want to minimize the number of possible actions?

**Comment by phw** [comment]
> Again, this is not a setting but an action. Where would you like to put actions? Or do you want to minimize the number of possible actions?

I think you could make a point about many of the profile settings that they should be quickly changeable, but it is certainly not feasible to put them all in the context menu.

**Comment by nafg** [comment]
@phw I just looked through all the profile settings and I don't see a single one that would make sense to be quickly changeable (other than the leap from "nonzero value for Notify new activity" to "notify new activity is activated"). Can you make a more direct argument?

Maybe it's worth taking a step back and defining the purpose and use case of profiles in the first place. Honestly personally I don't use more than one (if I have ever, it's been a rare occurrence), but I image it would be useful for things like using different shells, and giving them a different background color to more easily identify them. Notably, the defining characteristic is that it's a subset of preferences that are grouped under a set of alternative modes that can be swapped between. What do most people use them for?

**Comment by gnunn1** [comment]
@nafg The issue with the context menu is that it cannot exceed the size of the containing window in X11 otherwise it gets clipped. Additionally, I'm not a fan of having a plethora of items sitting in a menu as I prefer a simpler and cleaner look.

Having said that, I forgot I cleaned up the context menu on the last release and this could be added to the ```Other...``` sub-menu relatively easily. It would be a functional change in behavior though since setting the threshold would not make the feature active in of itself after this change.

**Comment by nafg** [comment]
That functional change would be a huge improvement. I really appreciate
your considering it.

**Comment by gnunn1** [comment]
@nafg I've added this in the Other submenu, please try it out and let me know what you think.

**Comment by nafg** [comment]
Thanks!

I'm using the ubuntu package now, will you update that or do you want feedback first?
