### ISSUE TITLE
Title bar change shortcut suggestion

### ISSUE THREAD

**Issue by leoheck** [gnunn1/tilix#794]
I usually click the title bar and eventually I get trapped in the title renaming text field. 
What do you think to change the behavior from `Click to Edit` to ~`Double-Click`, or~ `Ctrl+Click` to edit or something different?

**Comment by bil-elmoussaoui** [comment]
Double click to edit is just impossible. As double click on the headerbar  usually triggers the maximizing of the window (done by the window manager). The Ctrl+Click might be a good idea :)

**Comment by leoheck** [comment]
@bil-elmoussaoui you are right, I just came back here to say that. Thanks.

**Comment by gnunn1** [comment]
I'm kind of 50/50 on this one as I feel like I just got people trained about this version, plus right now it works the same way as Epiphany so there's some consistency. Would love to hear some more opinions on it.

**Comment by TravellingGuy** [comment]
I just upgraded from 1.4.2 and I'm hitting this and it's very annoying, especially for people that have "Automatically Raise Windows" disabled in the Gnome Tweaks. With that disabled, you need to click the title bar of a window to raise it, which I do all day long.

The different with Epiphany is, in Epiphany there is lots of padding on either side of the URL entry field, so it's easy to click the title bar without activating the URL bar field. In Terminix, the edit title field spans the whole width of the window, so it's nearly impossible to click the title without activating edit mode.

I'm in favour of a Ctrl+Click or make the "click to edit" title much smaller, giving users lots of room to click without activating edit mode.

**Comment by koalization** [comment]
I'm in favour of a Ctrl+Click as well. I like the ability to change the title, but it's something I would do rarely anyway. More often than not my mouse cursor gets accidentally trapped into the title text field.

**Comment by gnunn1** [comment]
I have added an option in Preferences | Global | Behavior to require the Control modifier when clicking the title.

**Comment by leoheck** [comment]
Good, but why not to make this the default behavior instead?

**Comment by gnunn1** [comment]
Because I like it the way it is :)
