### ISSUE TITLE
Terminal height under Wayland

### ISSUE THREAD

**Issue by IamPr377y** [gnunn1/tilix#809]
### Expected behavior

Terminal size is 80x24 or whatever is set in config on both X.org and Wayland backends.

### Actual behavior

Terminal size is 80x27 even though it is set to 80x24 on Wayland backend.

### Versions

- Terminix 1.5.0
- VTE 0.46
- gnome-shell 3.22.3
- libwayland 1.12

**Comment by gnunn1** [comment]
I can reproduce, thanks for reporting this.

**Comment by gnunn1** [comment]
xfce-terminal seems to have the same issue whereas gnome-terminal does not, time to do spelunking through gnome-terminal code.

**Comment by f2404** [comment]
Thanks for the heads up, @gnunn1. I will also look into this.

**Comment by gnunn1** [comment]
One thing I've noticed is that gnome-terminal has a method called ```terminal_window_update_size``` in ```terminal-window.c``` that seems to resize the window based on calculating pixels from the VTE grid size. It's called in a few places after the VTE set_size method is called but I haven't determined if that is what is making the difference.

**Comment by f2404** [comment]
I believe it has something to do with the magic here: https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-window.c#n3627
Another question is why our code is working fine under X but fails under Wayland...

**Comment by gnunn1** [comment]
I've opened an issue in gnome bugzilla for this:

https://bugzilla.gnome.org/show_bug.cgi?id=779572

**Comment by gnunn1** [comment]
I'm closing this as an Upstream issue to fix.
