### ISSUE TITLE
RFE: support global custom links

### ISSUE THREAD

**Issue by larsks** [gnunn1/tilix#812]
I really enjoy the "custom links" feature.  I use it to make the bug references in git commit logs clickable, which turns out to be incredibly convenient.  Unfortunately, if I create a new profile I lose all my custom links.  I wish there was an option to have both global and per-profile custom links.

Sure, I can clone an existing profile to start with a particular static set, but this rapidly becomes a management nightmare because now instead of updating things in one place I'm updating them in multiple places.

**Comment by larsks** [comment]
Here's a super hacky script that will apply the hyperlinks config from one profile to all the others:

```
#!/bin/sh

base=/com/gexperts/Tilix

src=$1

profiles=$(dconf read $base/profiles/list |
	tr -d "'],[")

for profile in $profiles; do
	name=$(dconf read $base/profiles/$profile/visible-name | tr -d "'")
	if [[ $name = $src ]]; then
		links=$(dconf read $base/profiles/$profile/custom-hyperlinks)
		break
	fi
done

if [[ -z $links ]]; then
	echo "ERROR: failed to find hyperlinks configuration in profile named \"$src\"" >&2
	exit 1
fi

for profile in $profiles; do
	name=$(dconf read $base/profiles/$profile/visible-name | tr -d "'")
	if [[ $name = $src ]]; then
		continue
	fi

	echo "applying hyperlinks config to profile $name"
	dconf write $base/profiles/$profile/custom-hyperlinks "$links"
done

```

**Comment by gnunn1** [comment]
There is a new Advanced page now in preferences where custom links and triggers can be set and they will be applied across all profiles. When checking links and triggers it will first check the global ones and then the profile ones.

At the moment I've opted for the simplest implementation where each terminal maintains an individual set of all links and triggers. It's not as efficient as maintaining one global set somewhere but changing this could require a lot of re-factoring and I'm not sure it's worth the effort but something to keep an eye on for the future.
