### ISSUE TITLE
Project name change required due to trademark infringement

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/tilix#815]
Looks like I'm going to have to change the name of the project as I received a letter from the Terminix corporation with regards to trademark infringement. While I could fight it, I don't think it's worth the time or effort.

I think when I ran the naming poll last year the preferred alternative was Mosaic so I'll probably end up going with that.

**Comment by alex285** [comment]
i reckon to get an advisory from Github people before you change the name, and make sure their request is at least legit. But if they cant force it, just stay Terminix and ignore them. Besides pretty sure there are also firms and products called Mosaic too :/

**Comment by alex285** [comment]
@gnunn1 hmm, you removed the letter? why?

**Comment by gnunn1** [comment]
I didn't want anyone harassing the lawyer, he's just doing his job.

**Comment by arcticicestudio** [comment]
I think Alex is right, you should probably ask GitHub for advice on how to handle this or maybe try to contact the corporation to try to clear that this project is in no way connected with / related to their company.

If this doesn't help, maybe you should start another poll to get some more name ideas.
The name "Mosaic" may cause even more problems, just google for it and there will be more than three larger companies were one of them may raise a trademark infringement too :unamused:

I think, if it is necessary to rename the project, should you go with a name related to GNOME since it is based on their design guide and the DE itself.
The GNOME team (non-profit) won't raise any law infringements since they're guys like you and me and they love open source 😄 

➡️ I'd vote for the name *Gnomix*.
There is no project, at least on GitHub, and no distribution based on GNOME which already uses this name. It still contains a part of the old project name `nix` and reflects the idea of a new, clean terminal emulator for the GNOME DE 👣

**Comment by alex285** [comment]
@gnunn1 obviously is up to you, but i would kindly request to attach again the letter. It has nothing to do with who signs it, but with the company. Moreover it is essential to be here for people to understand the issue, and to be aware in future such cases that can came into themselves, and in any case it is a public document since it concerns a public project, and  it is not a private.

My 2 cents!

**Comment by jp7677** [comment]
I like "Mosaic" very much, makes searching in Gnome Shell Overview also easier since "Terminal" always appears before "Terminix" in the search results. But I don't want to turn this thread into a new poll so please stay on topic ;).

**Comment by f2404** [comment]
[Mosaic](https://en.wikipedia.org/wiki/Mosaic_(web_browser)) was a web browser so I'm afraid this isn't a valid choice.

**Comment by gnunn1** [comment]
@f2404 the last release of Mosaic the browser was twenty years ago so I'm not too worried about that. @arcticicestudio makes a good point about the google-ability of the name though, might be better to go with something made up and unique.

**Comment by gnunn1** [comment]
Anyway, I'll run another poll on the name later today.

**Comment by f2404** [comment]
Also, [Mosaic™](http://www.nvidia.com/object/nvidia-mosaic-technology.html) is an NVIDIA trademark.

**Comment by gnunn1** [comment]
@f2404 That would be the show-stopper.

**Comment by gnunn1** [comment]
Here's the text from the lawyer for the Terminix corporation without his contact information:
-----
Our firm represents The Terminix International Company Limited Partnership, an
affiliate of The ServiceMaster Company, LLC (“Terminix”) in its intellectual property
matters. As you may be aware, our client has continuously been using the trademark
TERMINIX for almost 90 years and has built a brand that is recognized internationally as a
provider of pest control services. Terminix has invested significant resources in advertising and elevating the brand to the point that it has become a famous household name.

In recognition of Terminix’s exclusive rights, the United States Patent and Trademark
Office has issued to Terminix U.S. Reg. Nos. 0635715, 1404366, 3586266, 3959928, 4073092, and 4248466, among others, for the TERMINIX marks (“Terminix Mark”).

We recently became aware of your recent terminal emulation software that shares the
same name. Although we recognize that your software is unrelated to pest control, we have to be diligent in protecting the Terminix Mark. If we allow uses like yours, we run the risk that the Terminix Mark will no longer be synonymous with pest control, and our client’s trademark will be weakened.

In order to resolve this matter, we simply request that you change the name of your
software. We look forward to receiving your assurance within seven (7) days that you will
comply with our request. We are happy to discuss non-infringing alternative names that would be acceptable. If you have any questions, please do not hesitate to contact me at the number below.

**Comment by thanostx** [comment]
You kill/fix bugs faster than they do, that's why they fight you! 🥇

**Comment by gnunn1** [comment]
@thanostx I was going to joke that I'm probably improving their reputation which seems pretty horrid based on the reviews I've seen

**Comment by gnunn1** [comment]
So of the names suggested previously in #41, here's the ones I liked:

Tessellate
Splitterm
Ditto

I'm also going to suggest one more name, an invented word which combines Tile and Unix:

Tilix

**Comment by alex285** [comment]
Tessellate is even hard to write
Splitterm is a description, not a name :)
Ditto, I dont know if means something, but I will vote for this
Tilix ..is so typical unIX :p

**Comment by gnunn1** [comment]
Ditto is an English word meaning "a similar thing; a duplicate".

**Comment by gnunn1** [comment]
Termino? It's the Spanish word for Terminus which I also like but would prefer not to use since it's fairly well used already.

**Comment by ivoarch** [comment]
+1 Ditto
+1 Tilix

Tremendous Terminal (tremendous-terminal) , Tremendous Tile (tremendous-tile) , 
Tremendo in Spanish
Tremendus (trĕmendus ) in Latin
Mosaico - el mosaico - mosaĭcum

**Comment by edubxb** [comment]
:+1 for Tilix

**Comment by jp7677** [comment]
What about:
Tico - Tiling Commands, a tiling Terminal Emulator for Linux using GTK+ 3

**Comment by alex285** [comment]
What about TNT Terminal? Tilix Not Terminix :p

**Comment by f2404** [comment]
I also like Tilix, but there seems to be a name clash again: [linux distro](https://distrowatch.com/table.php?distribution=tilix), [company](http://www.tilix.uk/)
Ditto: [clipboard manager](http://ditto-cp.sourceforge.net/), [pokemon](http://www.pokemon.com/us/pokedex/ditto)

**Comment by Vaesper** [comment]
+1 on a name that does not overlap with GNOME Terminal in the overview search. Right now I have to type the name all the way out to `termini` before it will launch Terminix rather than GNOME Terminal. So better to have a unique prefix rather than a unique suffix imho. (Honestly though I think you shouldn't be giving in to this lawyer but this seems like a good opportunity to address that "bug").

**Comment by egmontkob** [comment]
How about adding a bit of ego? gnterm, gnix, gnunnix, ... :)

**Comment by ivoarch** [comment]
Gnuterm

**Comment by gnunn1** [comment]
@egmontkob Thanks for the suggestion, but I'm not much for ego. I have a personal company called GExperts and back in the days when I was doing Delphi development used to name free things I was working on GX..., so my file explorer was GXExplorer, etc. Having said that, things always change and there may come a time where I hand the project over to someone else, I'd prefer it not to be related to me.

@ivoarch Considering I'm using the Mozilla license probably best to avoid Gnu.

@f2404 It looks like that  Linux distro Tilix is discontinued and the home page for it is blank (www.tilix.com). The UK company is a bummer but there's no trademark registered for Tilix in the US or Canada which is the domain I care about legally.

The reality is that it's going to be incredibly difficult to come up with a name that is sensible but it isn't used anywhere else.

**Comment by f2404** [comment]
@gnunn1 OK, I vote for Tilix then if you're fine with this name.

**Comment by Nevel** [comment]
I used to love the GExperts Delphi enhancements, so thanks for making my life easier!
Suggestions I like best so far:
- Tico
- Tilix
- Tremendus

**Comment by dsboger** [comment]
https://en.wikipedia.org/wiki/Tyler

**Comment by gnunn1** [comment]
Just an update, I spoke to the lawyer and agreed to changing the name. In exchange, the lawyer has agreed to vet a new name to make sure there are no conflicts, at least in the US, on a pro-bono basis since it is a lot cheaper for them to do that then litigate it.

**Comment by gnunn1** [comment]
The lawyer said there is no issue with Tilix, at least in the USA, so I'm going to go ahead and change the name to that this weekend. Obviously the repo and web site will be re-named, but various artifacts referencing Terminix in the code and elsewhere will be updated as well.

**Comment by gnunn1** [comment]
Just a heads-up as well, this is going to break everyone's settings since the gsettings will change from com.gexperts.Terminix to com.gexperts.Tilix.

**Comment by egmontkob** [comment]
Could you perhaps add some migration code that copies over all the old settings (if the new ones are absent)?

**Comment by alex285** [comment]
@gnunn1 Tilix (http://www.tilix.uk/) doesn't belongs to TIAA (https://www.tiaa.org/)? thats inside the 50 biggest companies worldwide and US based

in any case and to my view it would be a huge mistake to make a name change for the wrong reasons. first Terminix (the terminal) is totally legit, as it has nothing to do with Terminix (the company) as objective (Terminix isn't even a brand name, is a project name). and while you said that "you could fight it", there is no need to fight it. just politely tell them, you cannot change the name

except if you want to change names every-time that someone is annoyed why his product/compamny does't come Google first

and apart this, it is also wrong to change for reasons like the open source movement/culture etc etc etc
it just feels wrong to me :/

**Comment by gnunn1** [comment]
@alex285 If you want to cover my legal fees to fight it, let me know. Otherwise it's not up for discussion.

Tilix isn't a registered trademark in the US and Canada so it's not a protected term and thus is safe to use.

**Comment by gnunn1** [comment]
@egmontkob Unfortunately I'm not seeing an easy way to do this. Typically the install would involve uninstalling Terminix and then installing Tilix, either manually or by a package manager. Uninstalling Terminix will remove it's gsettings (i.e. removing it's schema) and making the settings inaccessible.

**Comment by egmontkob** [comment]
Can it still ship gsettings schema files under both 'tilix' and 'terminix' for a transational period (about a year or so)? I hope their lawyers wouldn't mind it. Not sure about the technical bits. Thanks!

**Comment by gnunn1** [comment]
@egmontkob There's a number of issues with that as well. First off, there's no way to tell if the person is a new user or an existing one, so that means it will always copy from the old to the new even for new users. This in turn implies a certain amount of backwards compatibility, for example removing from the new schema or changing defaults means I have to maintain the same in the old.

Also for new users it's pollution of dconf with both schemas and potentially leads to confusion.

So no, I don't have any plans for this.

**Comment by alex285** [comment]
@gnunn1 legal fees in what? is there a Terminix (Terminal) company to sue? At the worst what they could do, is to sent a letter to Github and ask them to suspend Terminix (the repo). Thus first thing you should had done was to contact Github legal department and ask for an advice

btw if you look on: https://www.uspto.gov/
you can see there are several Trademarks registered under Terminix on US

Also Terminix not being registered on US and Canada, but being registered on UK for example, how it makes any difference at all. Unless there is an company, it makes absolutely no difference. It goes again to Github policies and rules.

**Comment by gnunn1** [comment]
@alex285 As far as I can tell, all of those Terminix trademarks are registered by the same company, Terminix International. It's quite common to register variants of the name AFAIK.

My expectation is that Github would get a takedown request from them and decide whether or not to takedown the repo. Github's policy on this is pretty clear:

https://help.github.com/articles/github-trademark-policy/

Github could delay the takedown and ask me to work it out with the trademark holder but it just leaves me in the same position as now. I'm just not seeing the point of dragging this out.

Additionally, yes I can be sued as an individual and I have sufficient personal assests that I'm not interested in going down that route. If github were to refuse to takedown the repo, I'd expect that would be the next step.

For me changing the name is far less hassle then the alternatives. At the end of the day I work on this for fun, the minute it stops being fun I'll just move on to something else. Changing the name keeps things in the fun spectrum for me, not changing and dealing with the hassle is not fun.

**Comment by gnunn1** [comment]
@alex285 Also, if you think Tilix is a bad name then feel free to come up with some suggestions and check that they have no issues and I'd be happy to consider them.

**Comment by alex285** [comment]
@gnunn1 

> At the end of the day I work on this for fun, the minute it stops being fun I'll just move on to something else. Changing the name keeps things in the fun spectrum for me, not changing and dealing with the hassle is not fun.

well that is a good point! I'm just pissed with the demands that some people made! anyway!

> if you think Tilix is a bad name then feel free to come up with some suggestions and check that they have no issues and I'd be happy to consider them.

nah, Tilix is okay! Besides when you first placed the naming issue, I wasn't in favor of Terminix anyway! I like Tilix more! If I remember, you wasn't such a huge fan of Terminix name either :)

**Comment by gnunn1** [comment]
I've completed the name change, feel free to open bugs or PRs for things I've missed. I'm sure there will be some issues as we go through a transition period, I appreciate your patience.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 is anything should be reported to Weblate guys ? As far as I can tell the repository name on Weblate is still Terminix

**Comment by gnunn1** [comment]
@bil-elmoussaoui Definitely and I will be sending them an e-mail shortly, just cleaning up a few remainings first.

**Comment by dsboger** [comment]
I'm working with migrating the autotools files. Soon after Ill push a tilix-git to AUR and ask for a merge from terminix-git to tilix.

**Comment by gnunn1** [comment]
Thanks @dsboger, that would be great.

**Comment by dsboger** [comment]
[tilix-git](https://aur.archlinux.org/packages/tilix-git/) is up and running (I'm using it now). The other packages (terminix, vte3-terminix-git) I'll move after Tilix is released.

**Comment by ximion** [comment]
Please note that while Terminix is completely unrelated to software (and therefore I don't know whether their trademark is applicable to Terminix), there is a company called Tilix doing software stuff: http://www.tilix.eu/
However, I couldn't find a registered trademark for Tilix, so going with that name might be fine.

**Comment by Vaesper** [comment]
Under the excuse "better late than never":

Tilter

Short for TILing TERminal.

**Comment by phw** [comment]
For migrating my settings I did:
  
    dconf dump /com/gexperts/Terminix/ > terminix.dconf
    dconf load /com/gexperts/Tilix/ < terminix.dconf

This even works after you have uninstalled the terminix schema, since the user customized settings are available even after the schema got removed, and the default settings do not matter anyway.

You can of course also do this in a single line, but I wanted to have the settings backed up in a file just in case ;) If everything is ok you can probably clear the old Terminix settings with:

    dconf reset -f /com/gexperts/Terinix/

Finally to copy the bookmarks and custom themes just do:

    mv ~/.config/terminix ~/.config/tilix

**Comment by dsboger** [comment]
I've updated most of the Wiki for the new name, but I did not touch the screenshots. It would also be nice to add a question about the name change to the FAQ.

**Comment by dsboger** [comment]
The migration to Tilix in AUR is mostly complete, except some merge requests from old to new packages have not been resolved by trusted users yet. This means that some of the old packages still coexist. Once the merge requests are accepted, the history of the old packages (comments and votes, mostly) will be included in the new packages. The status of AUR packages for Tilix is as follow:

- There is a `tilix-git` that replaces the old `terminix-git` (not merged yet).
- Someone (`carlwgeorge` on AUR, I don't know his name on github) created a `tilix` package (that builds from source) before I did, so now they maintains the "main" package on AUR. They seems cooperative.
- Some users asked me to create a binary distribution package similar to the old `terminix`. I've pushed the `tilix-bin` pacakge and `terminix` got merged into it, so there is no `terminix` anymore.
- There is a `vte3-tilix` that replaces old `vte3-terminix-git` (not merged yet). I dropped the `-git` because the Tilix patches should change rarely and depend more on VTE then Tilix itself.

**Comment by ckrzen** [comment]
Just wanted to give a heads-up that Tilix(Terminix) became the default vte in "Ubuntu Budgie 17.04" and is a great alternative to stjerm(currently unmaintained and my previous choice for a lightweight quak-esque term). Great project. Keep it up!
