### ISSUE TITLE
Terminix in quake mode does not focus

### ISSUE THREAD

**Issue by Kozzi11** [gnunn1/tilix#818]
When running terminix in quake mode it does not focus, so I must click on terminal be able to write anything. It happens mainly with first start of terminix in quake mode

**Comment by gnunn1** [comment]
Is this on X11 or Wayland? Also, what distro and version are you using? Finally what version of terminix are you using.

**Comment by gnunn1** [comment]
@Kozzi11 Any responses to my questions, otherwise I'm going to close this issue.

**Comment by repsac-by** [comment]
@gnunn1 X11 and Wayland with GDK_BACKEND=x11

After first launch has no focus, but after calling an already running instance works correctly.

**Comment by Kozzi11** [comment]
@gnunn1 Sorry, I somehow missed your first response, which is wierd, because even github does not remind me :). It does not matter, which distribution or wayland vs. X11. I am using Arch, Fedora .... It happens on all of them. But on Fedora it seems worse. It happens with almost every open.

**Comment by gnunn1** [comment]
I'm not able to reproduce on Arch as it is working fine for me as far as I can tell. Are you using the version from master or 1.5.2?

**Comment by GreenDou** [comment]
Versions
	Terminix version: 1.5.2
	VTE version: 0.42
	GTK Version: 3.18.9

Also has this issue. Quake mode never focus automatically. But it focus without --quake.

**Comment by gnunn1** [comment]
I just tried it in Fedora 24 as well, works fine for me there as well. Having said that I've checked in a change to try to help with this so feel free to build it and see how it goes.

**Comment by repsac-by** [comment]
@gnunn1 focusing is influenced by the option `Set hint for window manager to disable animation`
if not checked then focused otherwise no focus

**Comment by gnunn1** [comment]
@repsac-by Thanks, that does indeed seem to be the problem. I'll probably remove the option if it's causing this issue.

@Kozzi11 and @GreenDou Can you confirm if you have this option enabled?

**Comment by Kozzi11** [comment]
@gnunn1 Yes, I can confirm that

**Comment by gnunn1** [comment]
I've removed the disable animation option to fix this issue.
