### ISSUE TITLE
Prompt on close expands shell-globs, extending window-width

### ISSUE THREAD

**Issue by Thor77** [gnunn1/tilix#822]
Steps to reproduce
================
1. Run a command including a shell-glob (`*`) - for example `cat /etc/*`
2. Close Terminix while the command is still running

Behaviour
========
Prompt appears asking whether to kill the running process, displaying the command with expanded glob and extending width of the Terminix-window.

Expected behaviour
================
Prompt appears asking whether to kill the running process, displaying the command with expanded glob **not** extending width of the Terminix-window **or** displaying the title of the session (without expanded glob).

Screenshot
=========
![terminix](https://cloud.githubusercontent.com/assets/4989736/23826913/8ae1dd56-06a7-11e7-8f58-c5106cdfccce.png)

**Comment by gnunn1** [comment]
Thanks for the detailed report and screenshot, made it super easy to see what the issue is. I've fixed this by enabling ellipsis if the description is too long.
