### ISSUE TITLE
Terminal size doesn't change

### ISSUE THREAD

**Issue by koalization** [gnunn1/tilix#824]
Today I've compiled the source from the master branch on both Fedora 25 (X11) and Xubuntu 16.04.2. This is something I've done many times because I like the terminal so much that I keep it updated quite often. However, I noticed that the name was changed from Terminix to Tilix. Normally I don't uninstall it before reinstalling it, this time I did it (using the old uninstall.sh script that managed to uninstall Terminix properly), only to avoid conflicts between the two names (which possibly would have meant two different executables). After compiling/installing Tilix, I noticed that although the interface would let me change the values for both the height and the width as usual, the terminal size won't actually change, even after restarting the application. It's stuck to about 120x30 regardless of my settings (I can still change the size manually by dragging the corners with the mouse of course).

**Comment by gnunn1** [comment]
Me bad, I accidentally checked in something I was debugging. Should be fixed now, my apologies for this.

**Comment by koalization** [comment]
Thank you very much for your prompt reply and fix.
