### ISSUE TITLE
Just a very minor correction

### ISSUE THREAD

**Issue by koalization** [gnunn1/tilix#825]
Compiled from master on Fedora25/Xubuntu16.04.2: in Preferences->Shortcuts, section Action->Nautilus, the entry should read "Open in Tilix".

**Comment by gnunn1** [comment]
I think that's just because the localization hasn't been updated yet, I'm holding off until hearing back from the Weblate guys to make nothing gets screwed up. If you look at the code, it's been updated:

https://github.com/gnunn1/tilix/blob/master/data/nautilus/open-tilix.py

**Comment by koalization** [comment]
Thanks.
