### ISSUE TITLE
Titlebar not showing on archlinux

### ISSUE THREAD

**Issue by taurthil** [gnunn1/tilix#830]
I have empty space when using Quake mode on Gnome environment
![titlebar](https://cloud.githubusercontent.com/assets/6709830/24019144/20c2cfd6-0a97-11e7-9dac-4c6cf285d91a.png)
Versions
	Tilix version: 1.5.3-1.0.0
	VTE version: 0.46
	GTK Version: 3.22.9

**Comment by gnunn1** [comment]
Thanks for the report, I don't see the gnome top bar in the screenshot? Are you using an extension like Dash-to-panel to move it?

Also is this Wayland or X11?

**Comment by taurthil** [comment]
X11 but in Ubuntu on my laptop that problem, not exists.
But when I use f12 to show all to show all terminal spaces the Bar returned and hide again

**Comment by gnunn1** [comment]
I'm not able to reproduce and I'm running the same versions as you on Arch. Can you post a screenshot of your Quake options, here is what mine looks like:

![screenshot from 2017-03-17 09-49-27](https://cloud.githubusercontent.com/assets/9358238/24045942/222c0c74-0af7-11e7-862c-f824e784c128.png)

**Comment by taurthil** [comment]
Height percent 90
Width 100

**Comment by gnunn1** [comment]
Thanks, unfortunately I cannot reproduce it using your settings. Do you have window or font scaling enabled at all in the gnome tweak tool?

Also, can you answer the question about the Gnome top bar, how come it's not in the screenshot? Based on your bug report I would expect to see the Gnome top bar, a gap and then the tilix quake mode window.

**Comment by taurthil** [comment]
Sorry. I'm using wrong description about problem because I don't have tilix title bar 
![titlebar](https://cloud.githubusercontent.com/assets/6709830/24046431/cd1c078a-0b22-11e7-939b-6c6a87159464.png) red line

**Comment by gnunn1** [comment]
I wonder if it's transparent because it's not loading resources correctly. If you close all instances of tilix and then it in quake mode from gnome-terminal (or another terminal) are any warnings/errors being printed out. i.e.

```
tilix --quake
```

Also, how did you install it on Arch, from the ```tilix-git``` package?

**Comment by taurthil** [comment]
Yes, I'm using tilix-git. When starting tilix --quake I don't have any information.

**Comment by phw** [comment]
When starting g tilix -- quake make sure no other tilix process is running (so use a different terminal emulator to do this). Otherwise it will just call into the existing process and exit without further output.

**Comment by taurthil** [comment]
oh please. I kill every tilix process and start on gnome terminal

**Comment by gnunn1** [comment]
Ok I'm pretty stumped, a couple more question then I'll spend some thinking on an approach to figure this out.

Are you using the Adwaita theme or something else? If you click where the title bar buttons should be does it actually do anything?

**Comment by taurthil** [comment]
But I'm tired to every startup press F11, I see in conf we can load quake-height-percent=100 and it works. Thanks for your response. Im'm waiting for fix

**Comment by gnunn1** [comment]
Please test this out, should be working now.
