### ISSUE TITLE
Drag a terminal outside of the Terminix window under Wayland: new window not created

### ISSUE THREAD

**Issue by arigit** [gnunn1/tilix#833]
On Fedora 25, terminix installed from COPR / https://copr.fedorainfracloud.org/coprs/heikoada/terminix/

When on a Wayland session, dragging a terminal tile outside of the Terminix window does not create a new window with the tile contents. Dragging the tile within the Terminix window (when having more than one tile open) does re-arrange the tiles within the window. 

When trying the same on an X11 session, dragging a tile outside the window does create a new terminix window with the tile.

Having an entry in the "terminal name popover" to "send to new window" or an optional keyboard shortcut would have been nice as well.

Workarounds I found so far:

- manually launch a new terminix window, and then dragging a tile from one terminix window to another works

- drag the tile/terminal to the existing window's own top-bar (gnome shell decoration bar) - that triggers the creation of a new terminix window (could be a bug rather than a feature, but it helps :)

**Comment by gnunn1** [comment]
This has been fixed, looking at the code for GtkNotebook I can see a new drag target was required for the root window to accept drops under Wayland.
