### ISSUE TITLE
The function you are calling is not pressent in your version of GTK+.

### ISSUE THREAD

**Issue by ivoarch** [gnunn1/tilix#835]
Please is it possible to return the support for GTK 3.14 ?
```
$ tilix
object.Error@(0): The function you are calling is not pressent in your version of GTK+.
```

Thanks!!

**Comment by ivoarch** [comment]
Thanks @gnunn1 !!

**Comment by stugol** [comment]
This problem still occurs with the latest release (which is 1.5.4). I attempted to compile from sources instead, but Debian Jessie doesn't have the `dub` command.
