### ISSUE TITLE
Preferences gone after change to Tilix

### ISSUE THREAD

**Issue by lucascosti** [gnunn1/tilix#836]
I've just upgraded to 1.5.4, but with the name change all my preferences and profiles have been reset back to default.

Before I try to redo them, is there any way of getting them back? I'm no gsettings expert, so I wouldn't know where to start/look...

My system is Fedora 24, and I have been getting updates from the COPR repo at https://copr.fedorainfracloud.org/coprs/heikoada/terminix

**Comment by phw** [comment]
Please see my comment on https://github.com/gnunn1/tilix/issues/815#issuecomment-286097276

@gnunn1 I think some upgrade instructions in the README would be handy :)

**Comment by lucascosti** [comment]
Thanks @phw, worked like a charm.

+1 to the README instructions; I checked there and the wiki before opening the issue (I always forget to check closed issues :neutral_face:)

**Comment by gnunn1** [comment]
I've updated the README.md and I'll update the news post as well on the web site.
