### ISSUE TITLE
Is it possible support rz/sz zmodem file transfer?

### ISSUE THREAD

**Issue by netroby** [gnunn1/tilix#837]
Is it possible support rz/sz zmodem file transfer?

**Comment by gnunn1** [comment]
Isn't this just down with a CLI program, what is there to support?

**Comment by gnunn1** [comment]
@netroby can you answer the question please, otherwise I'm going to close it.

**Comment by netroby** [comment]
Hello. Do you know SecureCRT? or XShell, these windows terminator emu. provided us easy transfer to server / download file from server.

when run rz. then jump out a file choose window. choose file, and transfer file into server

**Comment by gnunn1** [comment]
Unfortunately no I am not familiar with them and I'm not familiar with rz/sx at all. Is the idea when you run one of these you want a file dialog to appear? What is supposed to happen after you select the file, does it get pasted in as a command to rz/sz?

The more you can spell out what you are looking for and how it should work the easier it would be for me.

Searching a bit I saw some mention that iterm2 handled this with triggers, is that an option here?

**Comment by netroby** [comment]
Yes, iterm2 also had this . things works very like.

easy to download server files (the pwd path). and upload local file to server(to path pwd on the server)

**Comment by netroby** [comment]
https://github.com/mmastrac/iterm2-zmodem
seems some github repository talk about it

**Comment by phw** [comment]
I somewhat like the idea to have a file chooser trigger action. It would show a file chooser and paste the chosen file back to the terminal.

This would probably  solve this use case without introducing and functionality specific to rz (which I also don't know).

**Comment by netroby** [comment]
The currently linux world does not have much more easily used terminator EMU tools. 
So much advance feature only available on some Enterprise software like SecureCRT/Xshell(freeware)
Linux user experience need move forward.

Tilix was a huge enhanced term , i have use it for a while, feels good.

**Comment by dsboger** [comment]
I can create a trigger to run `zenity --file-selection`, but the stdout (selected file path) is lost. It would be great if we had a trigger type that took the (first line of the?) command output and pasted it.

**Comment by gnunn1** [comment]
Thanks for the suggestion @dsboger, I have added this feature as I think it opens up a few more possibilities. @netroby can you play around with this and see if it does what you want with respect to the zmodem stuff, you should be able to craft a script similar to that iterms2 script and execute it from a trigger.

**Comment by dsboger** [comment]
It works great. I use the following command to output a file path:

```
echo -n $(zenity --file-selection 2> /dev/null)
```

The `echo -n` removes the line break, so we can review the file path before pressing enter.

**Comment by dsboger** [comment]
Would it be possible (or would it even make sense) to allow triggers to activate on the command being typed (optionally, maybe)? I ask because I realized that in my case the only moment I type file paths is while I'm typing a command. For example, if I add a trigger for `[io]f=`, I could use the file selection command to assemble a `dd` command line.

**Comment by gnunn1** [comment]
@dsboger It's a bit tricky because I get the individual keystrokes rather then a complete string. So there would need to be some additional tracking to handle backspace, enter, etc and a general understanding of what is going on. I've been avoiding it because I'm not sure it's possible to nail it 100%.

If I were to attempt it, I'd probably need to add an additional boolean column to the triggers to allow the user to specify whether it should be used for input.

**Comment by gnunn1** [comment]
Actually after thinking about this more, running triggers against input does not make sense. If I try to evaluate the chunk of text as the user is typing a trigger would be executed multiple times which wouldn't be good.

**Comment by gnunn1** [comment]
@netroby Are you able to test this as requested, otherwise I'm going to close the issue.

**Comment by qingyunha** [comment]
Hello, I made a ssh wrapper to support rz and sz. I hope you find it useful.

https://github.com/qingyunha/zssh

**Comment by perlun** [comment]
For reference, `zssh` is available in both Debian and Ubuntu - but perhaps this is a different tool? :thinking: Seems to have been available for much longer.

- https://packages.debian.org/search?keywords=zssh
- https://packages.ubuntu.com/search?keywords=zssh
