### ISSUE TITLE
Tilix in quake mode?

### ISSUE THREAD

**Issue by PrzemekSkw** [gnunn1/tilix#838]
It's possible to make Tilix work with Terminix quake mode in gnome shell ?

**Comment by gnunn1** [comment]
If you mean the extension (https://extensions.gnome.org/extension/1123/terminix-dropdown/) you would need to contact the author. Tilix works fine in quake mode without it though:

https://gnunn1.github.io/tilix-web/manual/quake/

Just change terminix to tilix in that screenshot, I need to update it.

**Comment by ivoarch** [comment]
@PrzemekSkw 
I have also changed the name of my gnome shell extension from terminix dropdown to tilix dropdown . I've uploaded the new extension a few days ago but still pending to be approved . When this is done will share the new link to install from the gnome extension page . You can also install the extension from the repository on github [1] https://github.com/ivoarch/gnome-shell-TilixDropdown see README.md for details.

**Comment by PrzemekSkw** [comment]
@ivoarch I do like @gnunn1 says and tilix quake mode works same as gnome extension so it's fine for me :D thanks for help
Regards
