### ISSUE TITLE
tilix --action session-add-down --focus-window under wayland: not working

### ISSUE THREAD

**Issue by arigit** [gnunn1/tilix#839]
Fedora 25 / wayland.

I use .desktop files to trigger terminal commands extensively. Since I switched to tilix, the .desktop files have an Exec line that looks like:

tilix --action session-add-down --focus-window -e my_script.py

Usually I have one terminal window in my destop - a .desktop file with the above Exec, when launched with Nautilus, creates a new tile where my_script is executed. Also, I expected it to focus the tilix window, in the new tile (this is important for some scripts that require keyboard input), but this doesn't happen.

If I run "tilix --focus-window" from the shell's "Enter a command" window (Alt-F2), then the existing tilix window is focused, and the last tile is made active. So it looks like --focus-window doesn't work when there are other command line switches - looks like a bug

**Comment by gnunn1** [comment]
Yep this is a bug, the issue is that after it processes the action it exits the command line processing right away since it used to be actions could only be run in Tilix itself. Now that it has been changed some of the other parameters come into play and this needs to be re-jigged a bit.
