### ISSUE TITLE
automake build does not process localized man pages

### ISSUE THREAD

**Issue by phw** [gnunn1/tilix#842]
The automake build does not compile and install the localized manpages. It should do something similar to https://github.com/gnunn1/tilix/blob/master/install.sh#L113

I looked into it, but I don't have much experience with autotools and felt a bit lost. @dsboger could you take a look?

**Comment by gnunn1** [comment]
@dsboger is this something you wouldn't mind handling?

**Comment by dsboger** [comment]
Sure. I'll try to take a look later today.
