### ISSUE TITLE
1px margin on quake mode

### ISSUE THREAD

**Issue by GuillaumeAmat** [gnunn1/tilix#843]
It may be related to #618 but I'm not using a tiling WM...

On Fedora 25, Gnome 3.22, the quake mode has a pixel of margin all around the tilix window.

![capture d ecran de 2017-03-21 19-48-33](https://cloud.githubusercontent.com/assets/1179174/24165057/bd8162ca-0e6f-11e7-8747-56a6984bd228.png)

**Comment by gnunn1** [comment]
Well I feel like a putz, I always thought this was a GTK bug but no it was me using a bad value for alpha in CSS. I should really watch the Pixar movie Bug's Life more often: "First lesson of leadership Princess, it's always your fault" :)

**Comment by GuillaumeAmat** [comment]
Great thanks!
