### ISSUE TITLE
[Custom links] Clicking on custom links does nothing.

### ISSUE THREAD

**Issue by PombaM** [gnunn1/tilix#844]
I have added a `Custom links` using this regex from `Guake`
```
^[a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+\:[0-9]+
```
But when ever i try open those links, Tilix just closes.

My setting:
![screenshot from 2017-03-22 10-15-08](https://cloud.githubusercontent.com/assets/11157420/24182260/b7dfae0c-0ee8-11e7-8f88-ec7d63d210c0.png)

####  Note:
- Changing case or command doesn't affect anything

####  To clarify, i have uploaded a video please check it.

https://drive.google.com/file/d/0B5CiO54Z0AIQa0FZRmNJd2ZjSXM/view?usp=sharing

**Comment by gnunn1** [comment]
Thanks, this is because I'm using D's regex capability to process the result rather then GLib regex. I'll modify the code in the next day or two to use GLib regex everywhere to be consistent.

**Comment by gnunn1** [comment]
OK this should be fixed now. Note that you can also use regex groups to split the filename and line number if they need to be sent as separate parameters. The way it works is that the whole matching group is $0 and each subsequent matching group is $1. So to make your regex work with gedit, I split it into groups as follows:

```
(^[a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+)\:([0-9]+)
```

And then configured the command to be ```gedit $1 +$2```. Here's a screenshot:

![screenshot from 2017-03-23 19-28-56](https://cloud.githubusercontent.com/assets/9358238/24274567/7aaf2a54-0fff-11e7-9ffe-6be48baab967.png)

**Comment by PombaM** [comment]
Thanks, will test after the new release is out.

**Comment by Ghom** [comment]
(^[a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+)\:([0-9]+) this won't work for me. (this doesn't match)
([a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+)\:([0-9]+) I use this instead. 
I don't know if it's a related bug. I tested it with the output of a grep -rnI "word" .
I work under Ubuntu 17.10 and the version of tilix is 1.7.5. and bash

Also is it possible to trigger a command directly from the current terminal eg: vim $1 +$2 and get the vim to open in the terminal I clicked the link.
