### ISSUE TITLE
<enum id='com.gexperts.Window.Style'> already specified

### ISSUE THREAD

**Issue by GeertGeurts** [gnunn1/tilix#845]
Hello,
Trying to upgrade terminix to tilix I got the error
GLib-GIO-ERROR **: Settings schema 'com.gexperts.Tilix.Keybindings' is not installed

Running  glib-compile-schemas /usr/share/glib-2.0/schemas/
Gives following error....
/usr/share/glib-2.0/schemas/com.gexperts.Tilix.gschema.xml:130:1  Error on line 130 char 1: <enum id='com.gexperts.Window.Style'> already specified.  This entire file has been ignored.

No idea how to continue...

Any help/suggestions are highly appreciated!

Regards,
Geert

**Comment by gnunn1** [comment]
You need to uninstall terminix first, then install tilix. If you installed Terminix manually, use the uninstall.sh script to remove it. Note that the uninstall.sh has been updated for tilix, so if you don't have a copy of it you would need to get the version from history before it changed.
