### ISSUE TITLE
Non-terminal windows?

### ISSUE THREAD

**Issue by zbraniecki** [gnunn1/tilix#846]
I imagine that the request may look weird at first, but I'm wondering if there's any hope that one day Tilix will support non-terminal windows like Firefox inside it.

The use case is as follows - I use Gnome and I like the UX. I tried Sway and it's ok, but definitely not polished enough to be used in "stacked" mode for me.

So, half of the time, I'm happy with the stacked mode that Gnome gives me.
Then, the other half, usually when I work, I want a tiling mode, or even, I want one screen to be in tiling mode, and the other in stacked mode.
What I often see myself ending up with is one screen with half of the screen with Firefox (Gnome's ctrl+left), and the other with Tilix (Gnome's ctrl+right) and then terminals inside Tilix.
In fact, since the screen I'm on is large, I could do with Firefox just being 1/3 of the screen vertically, but since there's no easy way to tile it, and put Tilix on 2/3s, I never end up doing it and I end up placing more terminals on the second screen.

I could hope that Gnome will add it, after all they added "half-screen" tiling, but it seems like it'll take them a very long time, if ever, before they'll provide a UX that Tilix has out of the box.

On the other hand, if Tilix could give me ability to launch different windows, I'd have a sort of sway/i3 experience inside a single window that I could just maximize on a screen of choice.

That would give me the best of both worlds - I'd have Gnome session, and I would be able to put a TIlix session on one or both screens and use the Tilix UX for navigating between windows.

**Comment by phw** [comment]
You might want to take a look at https://extensions.gnome.org/extension/294/shellshape/

**Comment by zbraniecki** [comment]
I did. There's a lot of half-baked functionality where drag and drop combines windows that you can then float around and many keyboard shortcuts didn't work for me.

I realize that shellshape is aiming for the UX I'm looking for, but Tilix has the UX I'm looking for already :)

**Comment by gnunn1** [comment]
Sorry, I don't have any plans to do this as it would be a huge amount of work to support and isn't a scope I'm interested in pursuing.

**Comment by zbraniecki** [comment]
sounds fair. Was worth asking  :)
