### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by zbraniecki** [gnunn1/tilix#847]
Quite often, I have a really good layout of windows in Tilix, but in a "main" terminal, I'd like to switch between one of multiple tabs.

So, in the scenario I'd envision, I have, say 1 vertical terminal on the left and 2 terminals on the right, and I can do "ctrl+1" to go to the first one, and then "super+1", "super+2" to switch between tabs in that terminal.

**Comment by phw** [comment]
Tilix has sessions for that. You can press Ctrl+Shift+The to create a new session and Ctrl+Alt+0 to Ctrl+Alt+9 to switch between them.

Or you use the session sidebar for it, which you can open via the icon on the upper left or by pressing F12

**Comment by zbraniecki** [comment]
You're right, but the session changes all terminals. I often have 6-8 terminals open and only need to switch between two tabs in one of them.
If it's nvim - then I can just use tabs in vim, but if it's between, say nvim and build log, then I'm out of luck.

**Comment by gnunn1** [comment]
I think what you are looking for is to have two terminals in the tile but switch between them as desired, i.e. embedded tabs. It's been asked for before but I don't have any plans to do this, the complexity just gets out of hand in terms of supporting drag and drop and all the other terminal navigation features.
