### ISSUE TITLE
Text selection using keyboard

### ISSUE THREAD

**Issue by dbrodie** [gnunn1/tilix#848]
Would be amazing if Tilix got support for selecting text using the keyboard rather than only using the mouse.

Currently the only VTE-based terminal supporting this is [termite](https://github.com/thestinger/termite) with it's [VTE-ng](https://github.com/thestinger/vte-ng) set of patches. Since Tilix requires, anyway, for some of it's features a patched VTE, adding this as well can be relatively simple.

**Comment by gnunn1** [comment]
Do I need to do something in tilix to make this work as tilix should work fine against vte-ng and presumably gain it's features. If this is the case it's more something for people packaging tilix VTE patches then me to consider.

**Comment by dbrodie** [comment]
vte-ng basically exposes an API that allows to set the selection programmatically (and a few other things, such as pause output, etc...). Connecting the API to keybindings and writing the logic would be up to tilix.

I would envision having a keybinding that toggles keyboard selection and then call the API based on the keys that tilix listens to.

**Comment by gnunn1** [comment]
So I had a basic look at this, I don't have any plans to support this as it looks fairly involved to me based on videos of watching it in action. It also appears to me that much of this functionality is actually handled in termite rather then vte-ng which is just exposing a fairly minimal API. See this bug report here where the termite developer explains in more detail (https://bugzilla.gnome.org/show_bug.cgi?id=679658).

If someone wants to look at it in more detail and submit a PR I'd be happy to consider it but it's not something that interests me personally.
