### ISSUE TITLE
"focus-window" doesn't work on Wayland

### ISSUE THREAD

**Issue by simonbcn** [gnunn1/tilix#849]
```
Arch Linux
GNOME Shell 3.22.3 on Wayland
terminix-git 2:1.5.4.r42.46249ab-1 (installed from AUR)
```

I have set `On new instance`:`Focus Window` and I set a shortcut in `gnome-control-center`>`Keyboard` to _open_ a tilix window when I press `F12`. When I press `F12` the first time, it opens a new terminal window and it focuses it. I set the focus to another window and I press `F12` again but it doesn't focus the opened tilix window.
I tested it with `tilix --focus-window` and it doesn't work.

**Comment by simonbcn** [comment]
I think the bug is major. I change `On new instance` to `Split down` and it doesn't work either.
With `New Session` works but it doesn't focus the window.
With `New Window` works well.

**Comment by gnunn1** [comment]
I fixed the add right/down actions, the problem with those is unrelated to the focus issue. I can duplicate the focus issue, I don't why this isn't working in Wayland. I've confirmed that I'm calling ```present``` on the window correctly which should raise it to top. The quake window works because it goes through a hide/show cycle, doing that here makes things works but of course you get annoying flashing.

I'll keep at it and see what I can do to sort it out.

**Comment by gnunn1** [comment]
I suspect this is because of this GTK bug:

https://bugzilla.gnome.org/show_bug.cgi?id=766284

**Comment by simonbcn** [comment]
It's very probably. 😞 Then this isn't a Tilix bug. I close this.

**Comment by simonbcn** [comment]
Confirmed: it's a Wayland bug. I've tested on Gnome Shell on X and it works well.

**Comment by mooop12** [comment]
> With New Session works but it doesn't focus the window.

This part doesn't work on X as well.

**Comment by mooop12** [comment]
Was that commit supposed to fix it? Because `tilix --focus-window --action=app-new-session` still doesn't work. A new tab is opened, the window just isn't focused.

**Comment by gnunn1** [comment]
Should work now, thanks for testing and pointing out that it wasn't.

**Comment by mooop12** [comment]
Thanks, it's working now.

**Comment by fabianonunes** [comment]
Maybe we need to reopen this, because is not working anymore.

**Comment by radugrosu** [comment]
On 22.04 (wayland) I do get a notification that "tilix is ready", while tilix still being in the background. :cry:

**Comment by StephanSchuster** [comment]
Same as @radugrosu: would expect tilix to be refocused on wayland.

**Comment by studokim** [comment]
Definitely needs to be reopened, because the feature still doesn't work
