### ISSUE TITLE
tilix does not import config from previous terminix install

### ISSUE THREAD

**Issue by larsks** [gnunn1/tilix#850]
After upgrading my system, I have the freshly renamed "tilix" package installed, and I was sad to find that it completely ignored all of my previous terminal settings...in particular all the "custom links" patterns I had created.  I wish there was either a one-time "should I import your settings from terminix?" dialog, or better yet an export config/import config feature.

**Comment by gnunn1** [comment]
See the instructions in the README in this repo for how to migrate your settings.

**Comment by larsks** [comment]
Right, but I was thinking that tilix could detect previous terminix config and offer to import this by default? That would seem to be the most painless upgrade experience.

**Comment by gnunn1** [comment]
There's a number of issues with that we discussed in #815, unfortunately I do not see an easy way to do this at this time.
