### ISSUE TITLE
Small issues with screenshots on tilix-web 

### ISSUE THREAD

**Issue by dsboger** [gnunn1/tilix#853]
I was visiting the Website for the first time and I noticed two small issues with the screenshots carousel:
- One of the images have a different height, so when the carousel switches to/from it, the content below shifts up and down.
- The screenshots clip the border and shadows of the windows. I think it would look better if the images portrayed whole windows (plus a small margin showing the wallpaper below and the shadow effect).

**Comment by bil-elmoussaoui** [comment]
Can you please report it on tilix-web? I will fix the first issue next week. For the screenshots feel free or anyone else to update them :+:

**Comment by dsboger** [comment]
I didn't know there was a different repo for that! Reported there. Closing here.
