### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#854]
Would it be of interest to you, implementing a command history – maybe as a side pane on the right – for showing all previous entered commands, like in Matlab/Skilab/Juno etc. A click on a command could lead to a jump to this command for revisiting the corresponding output. And it would be nice if a command could be copied to the current prompt (or to the clipboard) for (altering it a bit and) let it run again.

**Comment by gnunn1** [comment]
This is really a variation of #356, if you are interested in working on this issue just drop a note there and we can discuss what a design would look like.
