### ISSUE TITLE
Bookmarks - Can They Be Imported/Exported to Flatfile? 

### ISSUE THREAD

**Issue by IpsumL** [gnunn1/tilix#856]
I'm trying to figure out how to protect my investment of time if I do attempt to add all the bookmarks I would use to Tilix. Alternatively, how do I get into the backend of Tilix to add bookmarks by means other than the UI? Ideally, I'd be able to figure out a way to migrate bookmarks outside of the UI.

Thanks!

**Comment by arcticicestudio** [comment]
Do you mean a data export?
All bookmarks are stored in the `~/.config/tilix/bookmarks.json` file which can be easily stored in a dotfile repo or edited manually if you'd like to manage your bookmarks without the UI.

**Comment by gnunn1** [comment]
As @arcticicestudio noted, bookmarks are stored in a file already so they are easy to move around. I do recommend backing up your file periodically though if you end up going whole hog on them as I'm not under the impression it's a heavily used feature and thus may not have received a ton of testing.

**Comment by IpsumL** [comment]
Thanks! 

So, ~/.config/tilix/bookmarks.json is only written once Tilix is closed. It is not written if Tilix crashes, which it does if one clicks OK to select a Bookmark when no Bookmarks exist.

	Tilix version: 1.5.4
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
