### ISSUE TITLE
Update the shortcut image in web documentation

### ISSUE THREAD

**Issue by singhay** [gnunn1/tilix#857]
Image used to show how to set Quake shortcut still uses Terminix.
Please update that!!

**Comment by arcticicestudio** [comment]
This is related to the [gnunn1/tilix-web](https://github.com/gnunn1/tilix-web) repository.
I think this should be solved in [#21](https://github.com/gnunn1/tilix-web/issues/21).

**Comment by gnunn1** [comment]
I won't be able to get to this until the weekend, but as @arcticicestudio pointed out it's covered already. Additionally, note that you can simply fork the repo, create a new image and submit a PR to https://github.com/gnunn1/tilix-web
