### ISSUE TITLE
Changing quake mode animation

### ISSUE THREAD

**Issue by psokol** [gnunn1/tilix#859]
Window animation in quake mode looks bad in my opinion. I like the one used in Drop down terminal Gnome extension: terminal slides down from upper edge of screen and it looks very relevant. Is there any chance tilix quake mode window animation could look like that?

**Comment by gnunn1** [comment]
Unfortunately it's not something I'm willing to invest effort in as it is not doable in Wayland as far as I can tell. The extension can do it because it runs within gnome shell and has access to the root window. Tilix is a separate app that doesn't have this benefit.
