### ISSUE TITLE
symbol lookup error: tilix: undefined symbol: _d_allocclass

### ISSUE THREAD

**Issue by SubodhDahal** [gnunn1/tilix#860]
I installed Tilix on my `Ubuntu 16.04.1 LTS` system from the WebUpd8 ppa as follows:

```
sudo add-apt-repository ppa:webupd8team/terminix
sudo apt update
sudo apt install tilix
```
While running tilix I get the following error:
`tilix: symbol lookup error: tilix: undefined symbol: _d_allocclass`

I was previously using Terminix and it was running with no issues. I even imported the settings from terminix by doing:

```
dconf dump /com/gexperts/Terminix/ > terminix.dconf
dconf load /com/gexperts/Tilix/ < terminix.dconf
```

What could be the issue here?

**Comment by gnunn1** [comment]
You should open an issue with the PPA packaged as I don't maintain it. If I had to guess, the package could be dynamically linking libphobos and that library is out of date. However if Terminix worked previously that shouldn't be the issue.

Did you uninstall Terminix?

**Comment by SubodhDahal** [comment]
Yes, Terminix was working flawlessly. I think Terminix was uninstalled when I uninstalled Tilix to try and install it again.

**Comment by SubodhDahal** [comment]
Now the error is no more and tilix is working. Probably a restart fixed the issue.
