### ISSUE TITLE
Compilation issue on centos 7

### ISSUE THREAD

**Issue by Dark-Passenger** [gnunn1/tilix#862]
Hi,

I get the following error on trying to compile tilix on centos 7.3
I am using the latest dmd compiler package from their website and gtkd packages too.
only autoconf is version 1.13

https://gist.github.com/Dark-Passenger/3e443ac4d74c10fd693f9b647126a151

**Comment by gnunn1** [comment]
Do you get the same error if you use dub to build, i.e. 

```
dub build
```

**Comment by Dark-Passenger** [comment]
dub build works.

**Comment by gnunn1** [comment]
The issue might be that autotools is using LDC by default, if you use dub to compile but specify ldc do you get the same error:

```
dub build --compiler=ldc2
```

**Comment by gnunn1** [comment]
When I say the issue might be that it is using LDC by default, the problem is that on centos LDC is likely to be way out of date if installed from packages.

**Comment by Dark-Passenger** [comment]
@gnunn1 centos doesnt really have ldc, Though I do have dmd from their website.
So is dub build the recomended method to build ?
so to install does make install work ? or is there another method.
Sorry am new to the whole D environment.

**Comment by Dark-Passenger** [comment]
also FYI I did have ldc installed but from another copr repository.

**Comment by gnunn1** [comment]
For development I use dub and not autotools, mostly because in my day job I do Java development and have little interest in learning autotools or meson. However, to support packagers @dsboger was kind enough to create an autotools build.

The autotools should work fine, like I said I suspect your version of LDC is out of date. What do you get if you type:

```
ldc2 --version
```
I would recommend at least 1.1 as the minimum version.

**Comment by dsboger** [comment]
I did a test build with latest stable DMD (2.073.2) under Arch for both GtkD and Tilix and it worked fine. Could you post your DMD version number and also the commands you are using to build Tilix and GtkD?

**Comment by Dark-Passenger** [comment]
Hi I made it simply running make as per the build guide in the wiki.

I will post the DMD version. Soon since I am afk.
Though I did download the DMD RPM from dlang's website.

**Comment by Dark-Passenger** [comment]
Last week.

**Comment by dsboger** [comment]
I suspect the issue is that you are building with ldc (I also suspect it is an old-ish version), as it is the default if you have it installed and do not specify otherwise. To use DMD you must use `make DC='dmd'`. Could you confirm that?

**Comment by Dark-Passenger** [comment]
awesome dmd works.
