### ISSUE TITLE
Add info about setting Tilix as default terminal in Gnome?

### ISSUE THREAD

**Issue by xliiv** [gnunn1/tilix#863]
I'd be nice to include such info in readme or other suitable place

After a few minutes of search I've found:

```
sudo update-alternatives --config x-terminal-emulator
# or second way
sudo cp /usr/bin/gnome-terminal /usr/bin/gnome-terminal.bck
sudo ln -s /usr/bin/tilix /usr/bin/gnome-terminal
```

**Comment by gnunn1** [comment]
Feel free to update the General FAQ to include this, you can modify it here:

https://github.com/gnunn1/tilix-web/blob/master/_faqs/general.md

**Comment by baneymelo** [comment]
Doesn't work when I press right-click "Open Terminal", the default terminal is started, some idea?

**Comment by phw** [comment]
The "Open in terminal" you see there is a Nautilus extension provided by Gnome-Terminal itself, it only opens that. Timid provides a similar extension which, if installed, gives an open in tilix menu entry
