### ISSUE TITLE
fc25 upgrade from terminix -> tilix wiped profile configuration

### ISSUE THREAD

**Issue by nvgoldin** [gnunn1/tilix#864]
Hi, I recently upgraded to:
tilix-1.5.4-1.fc25.x86_64

This is the transaction history from dnf: 
```
    Obsoleted  terminix-1.5.0-1.fc25.x86_64                                               @heikoada-terminix
    Obsoleting tilix-1.5.4-1.fc25.x86_64                                                  @heikoada-terminix
    Install    tilix-1.5.4-1.fc25.x86_64                                                  @heikoada-terminix
```

After upgrading - my old profile setting was wiped out. Not a big issue for me(had only different colors configured), but I bet it can be more painful for some users.

**Comment by arcticicestudio** [comment]
This is already documented on the official website and in the README "[Migrating Settings From Terminix](https://github.com/gnunn1/tilix#migrating-settings-from-terminix)" section.

**Comment by nvgoldin** [comment]
Missed that, thanks!

Though I should say when you run 'dnf upgrade' you don't expect this to happen.. maybe it could be added to the spec file, or even just a warning message.

Anyways, confirming the linked solution works for me.

**Comment by gnunn1** [comment]
I don't maintain the packages, you would need to contact the person maintaining the COPR about this.
