### ISSUE TITLE
Can the Select Bookmark window be set to open collapsed?

### ISSUE THREAD

**Issue by IpsumL** [gnunn1/tilix#866]
Presently the "Select Bookmark" window opens with the bookmark structure fully expanded. Can the behavior be set to show the structure fully collapsed as in the Preferences/Bookmarks view?

**Comment by gnunn1** [comment]
Yes it could be, let me think about it. I'd prefer not to have an option for it and just make it one way or the other.

**Comment by dsboger** [comment]
Maybe a context menu action (Collapse/Expand all), instead of an option, would be easier to maintain.

**Comment by IpsumL** [comment]
My two cents, I would prefer to have a default collapsed presentation. That will match with the  Preferences/Bookmarks presentation.

Since a search function is provided and the cursor defaults into that Search field, one may type a unique term, tab and enter to launch that bookmark (no mouse required!). If one must visually search for the bookmark, it's better to expand as one goes, although I'm biased, since I've added 30+ bookmarks with multiple levels of folders and scrolling past the first 12 bookmarks/folders to get to the next folder below the root annoys me.
