### ISSUE TITLE
Losing focus when multiple sessions are open in session sidebar

### ISSUE THREAD

**Issue by SyedElec** [gnunn1/tilix#868]
Hi,

Thanks for this terminal, I just discovered it and found it really useful the way it handles mutliple sessions in the sidebar, however I found that sidebar is not scrolling to the focused session when having mulitple sessions (more than 5). 

here is a screenshot, I am currently in session named "test6" however I don't see it in sidebar when I open it, I need to scroll down to find it.
![screen](https://cloud.githubusercontent.com/assets/9877335/24592706/dc2ec9b0-17cf-11e7-866e-f09a7a313498.png)

Is it possible to make the sidebar scrolling to focused session or is it the correct behaviour ?
Thanks.

**Comment by gnunn1** [comment]
Thanks for the report, I'll have a look.
