### ISSUE TITLE
How to set preferences from command line?

### ISSUE THREAD

**Issue by eightnoteight** [gnunn1/tilix#869]
I want to have 2 windows having different kind of Appearances (one with normal window style and the other with borderless window style). but the only way to change appearance is through preferences dialog and I can't seem to find a way to set window style preference individually. it would be very helpful to me if you could help me in this.

**Comment by gnunn1** [comment]
You can use the gsettings cli to change the setting, for example to set it to disable-csd:

```
gsettings set com.gexperts.Tilix.Settings window-style disable-csd
```

And to set it back to normal:

```
gsettings set com.gexperts.Tilix.Settings window-style normal
```

**Comment by eightnoteight** [comment]
Sorry for not clearly explaining my question. what I want is to be able to parallely run two tilix windows where one is borderless and the other is normal window style.

Your suggestion will only let me have one type of window.

**Comment by gnunn1** [comment]
It works fine for me with these steps:

* Open Tilix window, normal CSD window style is used
* Run gsettings to change window style to disable-csd
* Open a new tilix window, it gets the disable-csd window style
* Run gsettings to change window style back to normal

I now have two tilix windows, one with normal CSD style and one with disable-csd style. You can of course create a bash script to automate the creating of the window with the non-default style.

**Comment by eightnoteight** [comment]
Oh, thanks a lot
