### ISSUE TITLE
SSH Private Keys

### ISSUE THREAD

**Issue by binaryronin** [gnunn1/tilix#870]
I normally use Gnome-Keyring in order to unlock my private keys and keep them unlocked for the session. I've noticed that Tilix does not use this and instead asks everytime for the keyfile password in the terminal window. 

I've also noiced that I have to specify the key that needs to be used, which I also did not have to do before. This is espeically annoying when commiting to different Git repositories that use different keys.

    Linux bebop 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux
    tilix 1.5.4-3
    zsh 5.3.1-2
    gnome-keyring 1:3.20.0+16+gbf8aa97-1

**Comment by gnunn1** [comment]
I'm using the VTE for terminal emulation just like gnome-terminal does, can you confirm you get different behavior in gnome-terminal because you don't specify what the other terminal you are using is. My expectation is that the behavior between the two should be identical and if it is not then it's a bug.

Having said this, I'm not familiar with using gnome-keyring for SSH keys so I may need some help debugging it.

**Comment by binaryronin** [comment]
Sorry, yes in gnome-terminal I get a X based pop-up dialog that asks me to unlock my private key. Also in gnome-terminal I don't have to specify a key. 

As an example `ssh user@hostname` works in gnome-terminal, but fails in tilix. In tilix I have to `ssh -i ~/.ssh/private_key user@hostname`.

These might be two seperate issues, please let me know if you want to treat them as such. Also, I am happy to help in any way I can.

**Comment by phw** [comment]
I have no experience in having the Gnome keyring popup from the shell, but for me this sounds like some files are not sourced. Have you tried setting the session to be a login shell?

**Comment by binaryronin** [comment]
I've tried both setting the session to a login shell and putting the following in my .zshrc:

    if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    	source /etc/profile.d/vte.sh
    fi

**Comment by gnunn1** [comment]
I wonder if this might be related to dbus activation and differences in environment/environment variables. If you open gnome-terminal and run tilix directly from the CLI (i.e. ```tilix``` and press return) and then try your private key in tilix does it make any difference or do you see the same problem?

**Comment by binaryronin** [comment]
Yep, you nailed it! When I run Tilix from gnome-terminal it works as expected.

**Comment by gnunn1** [comment]
Can you try modifying the ```/usr/share/applications/com.gexperts.Tilix.desktop``` file and change the line ```DBusActivatable=true``` to be ```DBusActivatable=false```. You will likely need to log out and in again for the change to take effect.

After this, try running your test again and see if it still works. Thanks for your help in tracking this down.

**Comment by binaryronin** [comment]
Yes, everything works as expected once the change is made.

Thanks for working through it with me, and thanks for making this terminal!

**Comment by gnunn1** [comment]
I'm thinking I might just close this and add a FAQ entry for it, not sure I want to change the DBusActivatable just for this.

**Comment by binaryronin** [comment]
Yeah that's understandble. I think that as long as there is some place that highlights this issue and how to fix it that is good enough.

**Comment by gnunn1** [comment]
I've updated the FAQ on the web site with info about how to disable DBus activation and referenced this issue.

**Comment by nikhilw** [comment]
Just noting here, I needed a restart. For whatever reason log-out and log-in did not work for me.
