### ISSUE TITLE
"ctrl + shift + v" triggers "ctrl + v"

### ISSUE THREAD

**Issue by MichaelThessel** [gnunn1/tilix#871]
Hi,

First of all, thanks for the great work!

I prefer to have ctrl + c and ctrl + v work consistently as copy and paste throughout my environment. I mapped ctrl + v to paste in the Tilix settings which works fine. When I want to enter visual block mode in Vim with ctrl + shift + v paste is triggered. This happens even if I hold down ctrl + shift first and then press v next. I would expect Tilix not to act on a shortcut that is not mapped in the settings.

Thanks!

**Comment by gnunn1** [comment]
I was thinking those were hard-wired in VTE. However testing in gnome-terminal it seems that changing the shortcuts for copy/paste to ctrl-c/ctrl-v does prevent the original ctrl-shift-c/ctrl-shift-v shortcuts from going through.

I'll have a look at the gnome-terminal code and see what they are doing different.

**Comment by gnunn1** [comment]
I've got a feeling fixing this involves using GTK Bindings (https://developer.gnome.org/gtk3/stable/gtk3-Bindings.html). I'll look into this some more tomorrow, would be great if this works as it would provide a way to remove all of the VTE hard-coded shortcuts that tilix implements instead.

**Comment by gnunn1** [comment]
I forgot I was explicitly handling ctrl-shift-v for paste to force it to go through tilix, this doesn't seem to actually be needed.

**Comment by MichaelThessel** [comment]
I mapped interrupt to Ctrl+B. 

```
# cat ~/.profile 

# Map interrupt to ^B
stty intr ^B
```

**Comment by gnunn1** [comment]
Note that if you map Ctrl+C to copy, Tilix is smart enough to copy when something is selected and send the interrupt when it is not.

**Comment by MichaelThessel** [comment]
Nice, I wasn't aware of that. That's definitely something I will check out. Thanks.

**Comment by DanielRios549** [comment]
@gnunn1 Perfect man, I map Ctrl+C to copy and Ctrl+V to paste, it's work perfectly, I think that, them would be the shortcuts by default.

**Comment by evanadelman** [comment]
@gnunn1 "Note that if you map Ctrl+C to copy, Tilix is smart enough to copy when something is selected and send the interrupt when it is not." - at least using 1.7.7 on Ubuntu 18.04, this is not the case - it actually performs both - sends an interrupt and copies.

**Comment by gnunn1** [comment]
Could be because you are using an older version and it's been fixed, try updating to the latest and see if that helps. It definitely works as expected on Arch with the latest as I just tested it.

**Comment by miltongq** [comment]
> Note that if you map Ctrl+C to copy, Tilix is smart enough to copy when something is selected and send the interrupt when it is not.

That just made my day, I was looking for a way to do this because I didn't know it would work out of the box. Now, Tilix is definitely going to be my main terminal emulator from now on.
I can confirm it works on Linux Mint 19.1 with Tilix 1.8.9.
