### ISSUE TITLE
Config file location or .Xresources

### ISSUE THREAD

**Issue by mreinhardt** [gnunn1/tilix#872]
I'd like to save my Tilix config to my dotfiles repo but I can't find where the config is stored. It's not in ~/.config and I'm not sure if anything can be added to my ~/.Xresources file. Is it possible to edit the Tilix settings in a file manually, and if so where?

**Comment by arcticicestudio** [comment]
All configurations are stored in GSettings.
I came up with a JSON config export feature in #440 next to `dconf`, but gnunn1 want to keep the maintainance for possible problems low which is fine.

I've solved this the same way I did for all GSettings based apps I use including my whole system preferences which is a big advantage of GSettings:
Dump the specific scheme into a file and store it in my dotfile repo.

You can save your Tilix settings with
```sh
dconf dump /com/gexperts/Tilix/ > tilix.dconf
```
and load it back with
```sh
dconf load /com/gexperts/Tilix/ < tilix.dconf
```

**Comment by mreinhardt** [comment]
@arcticicestudio That'll do, thanks!
