### ISSUE TITLE
How to set up custom links?

### ISSUE THREAD

**Issue by gmenih341** [gnunn1/tilix#873]
I'm having trouble understanding how to actually set up custom links.

How do I get the `URI` that I clicked? I want to open `google-chrome`, but I can't figure out how to pass the URI to it, so it actually opens the link.

**Comment by gnunn1** [comment]
Matches from the regex are passed as ```$0``` for the whole match and then ```$1``` to $x for matching individual groups in the regex. So in your case if the whole URL matches, it would be ```google-chrome $0```.

Here's a screenshot showing a more complex example for gedit:

![screenshot from 2017-03-23 19-28-56](https://cloud.githubusercontent.com/assets/9358238/24759393/4c0eb7b4-1ab3-11e7-971e-bdf4bfe43060.png)

**Comment by gmenih341** [comment]
Can't get it to work - it opens up Google Chrome, but doesn't pass the URL. Here's my config:

![screenshot from 2017-04-06 16-45-48](https://cloud.githubusercontent.com/assets/1362216/24760334/a5a109a0-1ae8-11e7-852a-7f356681e757.png)

**Comment by phw** [comment]
I also head trouble opening chrome-devtools links in Google Chrome. I think Chrome  does not open those from the command line, at least I could not figure out how. Or does the command work for you when run manually?
