### ISSUE TITLE
Cant set shortcut to view shortcuts

### ISSUE THREAD

**Issue by kascote** [gnunn1/tilix#874]
I'm trying to assign a shortcut to "View configured shortcuts", but no matter what key assign to it, not work. I tried Ctrl+F1, Alt+F1, and variations with Alt and Shift, no one worked. If try the same keybinding with "Open Preferences" for example, work ok. Seems a problem with that slot or I'm doing something wrong ?

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ gnome-shell --version
GNOME Shell 3.18.5
```

**Comment by kascote** [comment]
I tried with and without modifiers, and using others variations like ctrl+shift+s and don't work.. If I use ctrl+shift+s on other shortcut like "Show Preferences" works ok.

**Comment by gnunn1** [comment]
What version of Tilix are you using, I just tried on the latest release and it works fine for me. The only thing I can think of is something peculiar to Ubuntu, I'll try it in my VM later tonite.

**Comment by kascote** [comment]
I'm using version 1.5.4... the version provided by webupd8team ppa

**Comment by phw** [comment]
I think this is Could the Gtk version not yet supporting the shortcut help.

**Comment by gnunn1** [comment]
@phw Hit the nail on the head, the GTK Shortcuts view is only supported since 3.20 hence is disabled in earlier versions.

**Comment by phw** [comment]
Maybe the shortcut config should not be visible in that case, too
