### ISSUE TITLE
Keyboard shortcuts for add terminal right/left/top/down

### ISSUE THREAD

**Issue by SSoulaimane** [gnunn1/tilix#875]
I suggest adding means to set shortcuts to add a new terminal to the **right**/**left**/**top**/**down** of the current one
ex: `Ctrl-Alt-→` / `Ctrl-Alt-←` / `Ctrl-Alt-↑` / `Ctrl-Alt-↓`.
Thank you.

**Comment by gnunn1** [comment]
You can customize the shortcuts for add a new terminal to the right or down in Preferences | Shortcuts. I don't have any plans to add support for the top or left directions.

![screenshot from 2017-04-08 21-10-06](https://cloud.githubusercontent.com/assets/9358238/24833710/c83da690-1c9f-11e7-9438-71e5d218f3dc.png)
