### ISSUE TITLE
Toggling visibility in quake mode doesn't work

### ISSUE THREAD

**Issue by KruyKaze** [gnunn1/tilix#876]
Hello and thanks for making Tilix
I am on arch 64bit and running gnome. I have setup keyboard shortcut to "tilix --quake" and it works fine when you try to show the window but when I hit it again to hide the window , the window seems to close and reopen extremely fast, the animation is not over before it's open and focused again.

Please let me know if you need further info.

P.S: if I double click the hotkey tilix flickers a couple of times and then closes.

**Comment by gnunn1** [comment]
Do you have the quake option ```Hide window when focus is lost``` enabled, if so try disabling it and see if the problem goes away.

**Comment by KruyKaze** [comment]
It does. So does it mean I can't have to chose one or the other?
Thanks

**Comment by gnunn1** [comment]
Right now yes, there is a bug #858 already open for this. I'm working on it, but since I can't reproduce the issue it's tough to fix. I think it's likely a timing issue of some sort, I may need to add a delay somewhere to handle it.

**Comment by gmale** [comment]
For those who find this later and still have this problem, like me, you can leverage the solution to issue 858 and fix this problem by increasing the delay for hiding the Quake window. Per the attached screenshot:

![screenshot-at-23-05-45](https://user-images.githubusercontent.com/1699841/51012699-7d831e00-152c-11e9-8704-8f029b302007.png)
