### ISSUE TITLE
Bookmarks fail if there is a space in the path

### ISSUE THREAD

**Issue by Baemir** [gnunn1/tilix#877]
It seems like Tilix does not automatically 'correct' spaces when you use a bookmark that includes folders with spaces in their names, and cd fails with the 'too many arguments' error message, thinking you're trying to run multiple commands.

**Comment by gnunn1** [comment]
Oops, not sure how I missed that. Thanks very much for reporting it.

**Comment by gnunn1** [comment]
I've escaped any spaces before pasting into the terminal for the Path bookmark. I don't think there is anything to do for other types, for example command, since the user should be escaping/quoting as necessary since it's not feasible to figure out the constituent parts.
