### ISSUE TITLE
Nautilus plugin: option to open in quake mode?

### ISSUE THREAD

**Issue by Gwend4l** [gnunn1/tilix#880]
When using the nautlius plugin to open tilix in a given folder, it opens a new tilix window. However, I only use tilix in quake mode, and I would prefer to have a new tab in the quake window when the nautilus plugin is used. Is there a way to do this?

and thanks for tilix by the way, very neat :)

**Comment by phw** [comment]
If you have tilix already running in quake mode and you configure opening new instances as new session in Tilix global options this will work as you expect.

However if tilix is not already running this will still open a new normal window. Maybe there could be another option to start new instances in a quake mode session (which would open either in the existing quake mode window or open a new quake mode window). Don't know if this is doable, though :)

**Comment by Gwend4l** [comment]
> If you have tilix already running in quake mode and you configure opening new instances as new session in Tilix global options this will work as you expect.

indeed! I was not aware of this option. Thanks, that's perfect.

> However if tilix is not already running this will still open a new normal window. Maybe there could be another option to start new instances in a quake mode session (which would open either in the existing quake mode window or open a new quake mode window). Don't know if this is doable, though :)

I would definitively be interested in such an option :)

**Comment by bil-elmoussaoui** [comment]
I have never used quake mode before, but if this is really needed i would see if it's possible to be implemented ;)

**Comment by gnunn1** [comment]
I don't think this is really needed, the New Session option is sufficient IMHO. I'm trying to avoid having too many options and trying to handle all these cases when activating the application, it's already enough of a mess :)

If more people start asking for it I'll re-consider.
