### ISSUE TITLE
"object.Error@(0): The function you are calling is not pressent in your version of GTK+" on CentOS 7.3

### ISSUE THREAD

**Issue by rogerdalvi** [gnunn1/tilix#882]
Hello!

I've installed Trilix just fine. However, after installation, whenever I try to use an ACTION in the command line, the application crashes and the message "object.Error@(0): The function you are calling is not pressent in your version of GTK+" is presented.

I've installed Trilix using the COPR Epel, and since it did not work I tried the source code install. No joy there either.

I've even tried to use a CentOS fresh install in a VirtualBox machine, but the same error occurs.

Could you guys give me a hand with this?

Thanks.

**Comment by gnunn1** [comment]
What version are you using, I fixed a problem with this in tilix 1.5.6.

**Comment by rogerdalvi** [comment]
I've downloaded the source code from git today, a few hours ago actually. And the repo has the 1.5.6-1 version (which I also tried).

Thanks.

**Comment by gnunn1** [comment]
I just tried CentOS 7.2 and it works fine for me there, did 7.3 update the GTK version from 3.14?

**Comment by rogerdalvi** [comment]
I'm not sure if there was some kind of minor update to GTK, but my installed version is 3.14.13-20.

Thanks.

**Comment by ivoarch** [comment]
Hi, 
I use tilix from [Epel Corp](https://copr.fedorainfracloud.org/coprs/ivoarch/Tilix/) repo on CentOS 7.3, and it works .

```
$ Versions
	Tilix version: 1.5.6
	VTE version: 0.42
	GTK Version: 3.14.13
$ rpm -q gtk3                     
gtk3-3.14.13-20.el7.x86_64
```

**Comment by rogerdalvi** [comment]
@ivoarch, could you please try:
tilix -a session-add-right

Does it work?

**Comment by ivoarch** [comment]
No :( 
Had not tried the option `-a|--action`.

**Comment by rogerdalvi** [comment]
Thanks for the feedback @ivoarch!

**Comment by gnunn1** [comment]
The problem is this API:

https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-action-group

I'm using this to be able to find the requested action and activate it. I don't see an obvious way to work around it so I'm going to disable this feature in 3.14.
