### ISSUE TITLE
Add means for profile switch on directory to stick for all sub-directories under that

### ISSUE THREAD

**Issue by phillipsp2403** [gnunn1/tilix#883]
We work in an environment where we have a top-level set of directories and a bunch of working directories under each (each top-level represents a client development path).  It would be very useful if it was possible for the automatic profile switch on a top-level directory to stay active on any directories under that, i.e., switch to directory for client X selects client X's profile and then any directories under that will continue to use that profile.  Currently as soon as I move down into the sub-directories, the default profile is re-selected.  Since the number of sub-directories and both large and indeterminate, it is not feasible to enter them all into the profile switch list. (I note that the suggested bash script mechanism to switch profiles would be a reasonable work-around for this).

**Comment by gnunn1** [comment]
I agree, I've made a change so that the directory matches from the start rather then requiring an exact match.
