### ISSUE TITLE
allow copy&paste between keepass and tilix

### ISSUE THREAD

**Issue by dasbillgh** [gnunn1/tilix#884]
Hello, 

I'm running the newest tilix (v1.5.4) on my workstation with Fedora 25 and XFCE 4.12
and using keepass (mono) to copy ssh informations like username, password, port to tilix etc 

But since the last update it seems that the copy&paste feature not working anymore
when I copy something from keepass it will insert empty..

It would be really nice when you could look into this and fix with any future release.

**Comment by gnunn1** [comment]
Can you paste into gnome-terminal? How about gedit?

**Comment by arcticicestudio** [comment]
This may be related to your KeePass settings, at least KeePassX provides this setting and I'm sure KeePass too. Open your KeePass *Settings* and check that the option *Clear clipboard after* is disabled or increase the time until it wipes to something like `10s`.
By the way, have you considered to switch to [KeePassX](https://www.keepassx.org) which runs on *every* OS and also supports database files created with the

**Comment by dasbillgh** [comment]
It works with xfce4-terminal, gedit and mousepad.

 @arcticicestudio: Thanks for the tip. I use Keepass Portable because I change between Windows and Linux really often. I can confirm that it works with KeePassX but this is not a solution for me, so there is no Portable version of KeepassX.

**Comment by gnunn1** [comment]
SO I tried it out and confirms that it does work with xfce4-terminal but not gnome-terminal which is weird since the both use VTE like I do. I'm not seeing anything in xfce4-terminal code that is doing anything particularly different for keypass.

**Comment by f2404** [comment]
I'm pretty sure that xfce4-terminal is not doing anything special for keypass.
@gnunn1, can you check if it works with vte's own app - vte-2.91?

**Comment by gnunn1** [comment]
The problem looks to be my usage of the function gtk_clipboard_wait_is_text_available to check if there is text on the clipboard, it returns false with whatever keypass is doing with the clipboard. I tend to think this is a keypass bug personally, although checking gnome-terminal it's not using that function so not sure why it's not working there.

**Comment by gnunn1** [comment]
I've checked in a change that allows the keyboard shortcut for pasting to work by removing the check on gtk_clipboard_wait_is_text_available, within the action it's kind of redundant. However, the popover will show paste as disabled since it still uses this to set the action enabled state. I'm reluctant to remove it since it's a nice visual queue and  as stated previously I tend to consider this a bug with keepass.

BTW, I use keepassx2 and it works fine on Linux and Android in terms of being able to read the same key database.
