### ISSUE TITLE
Extra characters being sent on enter

### ISSUE THREAD

**Issue by rpbaptist** [gnunn1/tilix#886]
I just did a clean install of Ubuntu 17.04 and added Tilix from the webupd8 ppa.

When I press enter a few times it looks like additional characters are being sent to the terminal:

![image](https://cloud.githubusercontent.com/assets/7916262/25073475/fbdcfb88-22e7-11e7-99e7-6be888de3706.png)

**Comment by gnunn1** [comment]
That's weird, the ```>``` character looks like it is going into that mode when you miss closing a quote. Do you get the same behavior in gnome-terminal? Does this happen all the time even if you just press enter once?

**Comment by rpbaptist** [comment]
The `>` character is my prompt, so similar to `$`. I did not have the same problem in Gnome.

I ran into some more issues (Basically PPA's not being ready for zesty) and decided to go back to 16.04.2. No problems anymore with the exact same configuration.

**Comment by gnunn1** [comment]
OK, I'll close the issue but if you go back and have the same issue again feel free to re-open it.
