### ISSUE TITLE
issue with pasting passwords

### ISSUE THREAD

**Issue by deathtrip** [gnunn1/tilix#889]
When pasting passwords, for sudo or cryptsetup for example, i always get a wrong passphrase error.
The passwords are correct, because they work in Konsole, so it must be a Tilix issue.

**Comment by egmontkob** [comment]
works for me

**Comment by gnunn1** [comment]
Where are you copying passwords from, there was an issue with keypads that has been fixed in master. If you copy them from gedit and then paste into tilix do you still have the issue?

**Comment by deathtrip** [comment]
i copy from keepass 2.35 on Arch Linux

**Comment by gnunn1** [comment]
This was fixed in master in #884
