### ISSUE TITLE
Ctrl+Tab to cycle between terminals 

### ISSUE THREAD

**Issue by Skitionek** [gnunn1/tilix#890]
As far I remember it works upon installation, but after changing it you are not able to get the setting back (ctrl+tab jumps to next option).

**Comment by gnunn1** [comment]
Hmm, I don't think GTK allows using the Tab key in shortcuts and thus actively prevents it from being set. I'll probably need a button to reset it to the default value or something similar.

For now, you can use dconf-editor and just manually set it back to the default. It's in com/gexperts/Tilix/Keybindings. The setting is session-switch-to-next-terminal
