### ISSUE TITLE
[ GNOME / Wayland ] Quake mode, start maximised

### ISSUE THREAD

**Issue by luispabon** [gnunn1/tilix#892]
I've been trying to get Tilix to open maximised while in Quake mode to no avail:

```
gnome-shell@luis-LIFEBOOK-A544 ~> tilix -q --maximize
You cannot use the quake mode with maximize, minimize or geometry parameters
```

As it stands, `tilix -q` opens fairly small:

![screenshot from 2017-04-21 17-44-08](https://cloud.githubusercontent.com/assets/6388823/25287796/b7826bae-26ba-11e7-9cca-afed8f3d2279.png)

Tilix doesn't seem to remember its last window size, and I can't see anything on `tilix --help` or preferences that can help.

**Comment by luispabon** [comment]
![screenshot from 2017-04-21 17-44-08](https://cloud.githubusercontent.com/assets/6388823/25287796/b7826bae-26ba-11e7-9cca-afed8f3d2279.png)

**Comment by gnunn1** [comment]
You can change the height of the quake mode window in preferences as per the screen shot below. Note that this screenshot is from when running under X11 and some options, such as adjusting the width, won't appear in Wayland.

![screenshot from 2017-04-21 13-06-47](https://cloud.githubusercontent.com/assets/9358238/25288435/67e31c78-2693-11e7-8fa5-840fd0b643db.png)
