### ISSUE TITLE
Add support for custom window scalling based on env variables

### ISSUE THREAD

**Issue by floringogianu** [gnunn1/tilix#894]
On Gnome 3.24 I use two displays: the hidpi display of the laptop and a regular 24" Dell. The scaling factor is 2, so everything on the Dell is twice as large. Because multi-dpi support is not yet fully baked in Gnome, I am forced to launch apps that I will use on the Dell display with the following flags, to scale it down:

`env GDK_SCALE=0.5 GDK_DPI_SCALE=0.5 CLUTTER_SCALE=0.5 appname`

This works fine with some of the gnome apps (such as Nautilus), but not with Tilix. However I guess it should, because it is a GTK application. Any suggestions?

**Comment by gnunn1** [comment]
I tested it running from gnome terminal and it works as expected:

```
env GDK_SCALE=0.5 GDK_DPI_SCALE=0.5 CLUTTER_SCALE=0.5 tilix
```

I suspect the issue is because Tilix uses DBUS activation. In the tilix desktop file ```/usr/share/applications/com.gexperts.Tilix.desktop``` change ```DBusActivatable=true``` to ```DBusActivatable=false```. 

You may need to restart gnome shell or logout and in for the change to take effect.

**Comment by gnunn1** [comment]
BTW, in Wayland it auto-detects scaling proving the Window scaling factor in dconf is set to 0. I run Linux on a Macbook Retina and use a 27" Asus monitor and it seemed to work for me when I tested it out but honestly I usually disable the laptop screen when connected to my monitor.

**Comment by floringogianu** [comment]
@gnunn1 thank you for the two bits of info, both very valuable. Indeed executing from gnome terminal it scales down as expected (so it partially solves my issue). Not so if a Tilix process is already running. I tried changing `DBusActivable=false` to no effect. (it would be cool to be able to open two different sessions, scaled differently)

I knew Wayland should handle displays with different dpi but I didn't know exactly how to activate it. Even so, the bigger issue is that my install (ubuntu 17.04, **nvidia drivers**) is not showing a _Login with Wayland_ option in GDM. Not sure yet why is that and there's very little info on the net about it. Again, I am hearing that there should be support for the nvidia binaries in Wayland.

**Comment by gnunn1** [comment]
Unfortunately there's nothing I can do about the case where Tilix is already running, by design it's a single process so once you run an instance it's environment is set.
