### ISSUE TITLE
Quake mode focus lost

### ISSUE THREAD

**Issue by Soulsbane** [gnunn1/tilix#895]
I'm not sure if this is a bug or a configuration issue on my end. If I use a hotkey to open tilix use hotkey again to return to what I'm editing the focus of tilix will be lost when I reopen again. I have to use a mousepress in order for tilix to except input.

I created a [video](https://www.youtube.com/watch?v=HDVIOjSUGws) to demonstrate.
Thanks!

**Comment by gnunn1** [comment]
Is this Wayland or X11?

**Comment by Soulsbane** [comment]
x11 on Kubuntu 16.10

**Comment by gnunn1** [comment]
Thanks for the video, is tilix running in full screen or is it just the video is clipped? Otherwise the height is supposed to be limited to 90% of the screen size to avoid issues.

Also note that I don't support KDE, if there's an obvious fix for an issue I'm happy to correct it but I won't spend debugging in KDE.

**Comment by Soulsbane** [comment]
Yeah, the 90% thing was really bugging me and I found a setting in one of the closed issues. I'll try to find it and remove and see if I still get same results. Thanks.

**Comment by Soulsbane** [comment]
Ah, it wasn't a setting I'm launching it with tilix --quake  --full-screen

**Comment by gnunn1** [comment]
That should be fine but try it without full screen to see if it makes a difference.

**Comment by Soulsbane** [comment]
That didn't fix it, unfortunately. I'll try to do some searching to see what I can find on kde and application focus when I have time.

**Comment by gnunn1** [comment]
Thanks. I made some changes in that code in the last few weeks, I'll double check it as well.

**Comment by Soulsbane** [comment]
Ok, I've found a setting that I think will make Tilix work. It's under System Settings->Window Management->Window Behavior->Uncheck "Click raises active window". 

It's working great so far for me *crosses fingers*.

**Comment by gnunn1** [comment]
That's great, I'm glad you were able to resolve it. Is it OK to close this issue, you can always re-open it if needed.

**Comment by Soulsbane** [comment]
You can close it. Thanks a lot!

**Comment by Wirone** [comment]
I am also facing this problem. Today I migrated to new laptop and changed Windows to Kubuntu 16.04, Tilix is my equivalent for ConEmu. I have managed to configure it to behave almost exactly as I want, but this is annoying that focus is lost and I had to click every time I open window (quake mode in full screen). [Solution above](https://github.com/gnunn1/tilix/issues/895#issuecomment-296857149) does not work.

Anyway - great software!

**Comment by Soulsbane** [comment]
I'm running Kubuntu 16.10 for reference and the fix is still working for me.

**Comment by Wirone** [comment]
After restart it started to work in most cases, but ocassionally it does not work, especially when there are several windows in the tab (splitted view). But it's mostly usable :-) Thanks @Soulsbane for the fix!

**Comment by dmitryTsatsarin** [comment]
KDE. Works for me but need 2 steps:
1) as told @Soulsbane  System Settings->Window Management->Window Behavior->Uncheck "Click raises active window".
2) set "Focus stealing prevention" to None

**Comment by utkukaratas** [comment]
All I needed to fix this was setting "Focus stealing prevention" to None. ("Click raises active window" setting is checked - no problems there.)

**Comment by simontong** [comment]
If you want to retain Focus stealing prevention in other windows but add an exception for tilix open up "Window Rules" in KDE, create a new rule for tilix and set 'Focus stealing prevention': Force, None
