### ISSUE TITLE
feature request: open new terminal window from ctrl-shift-n in current directory

### ISSUE THREAD

**Issue by Laeeth** [gnunn1/tilix#896]
rather than home directory.
same behaviour as lxterminal, for example.

Thanks.

**Comment by f2404** [comment]
The best option would be to have this behavior configurable, I think.

**Comment by Laeeth** [comment]
Yes - I agree.

**Comment by gnunn1** [comment]
I'm not sure I agree it needs to be an option, there's too many of them already IMHO. It really should work one way or the other. Besides lxterminal, what do the other major terminals like xfce4-terminal, gnome-terminal and Terminator do?

**Comment by f2404** [comment]
In xfce4-terminal, I added an option MiscDefaultWorkingDir. If it's set (not empty), new tab or window uses its value as working directory; otherwise, current working directory is used.

**Comment by egmontkob** [comment]
gnome-terminal opens in the current directory (both for Ctrl+Shift+T new tab, and Ctrl+Shift+N new window).

(Home directory is used if a new window is requested from the command line, e.g. a "gnome-terminal" command connects to the already running server and opens a new window there. Obviously then you couldn't tell which existing tab to take as referece.)

**Comment by egmontkob** [comment]
I prefer this behavior, hence second @Laeeth 's request, for these two reasons:

If the current directory is kept, but you wanted to be placed in your home, all it takes is to type a simple `cd`. The other way around it's much more complicated.

Most desktop environments allow you to set up hotkeys. E.g. Unity7 opens a new terminal on Ctrl+Alt+T. This one obviously opens in your home, so this way both possibilities are still available for the users.

(Note that hence the default hotkeys, at least for the Unity + gnome-terminal combo are: Ctrl+Shift+N for new window in same dir, Ctrl+Shift+T for new tab in same dir, and Ctrl+Alt+T for new window in home. It's as confusing as it could be, but I'm just lazy to reconfigure :)

**Comment by gnunn1** [comment]
The problem I have here is that Tilix uses GAction everywhere, the New Window action is triggered identically whether you do it from gnome-shell or from internally in the application. I do not get any visibility into what triggered the action.

So either it works this way all the time or for none of it. Maybe I need to re-think about making this an option, I'm kind of leery of adding more but I don't see a better way forward.

Also, should the profile be inherited as well?

**Comment by gnunn1** [comment]
I've added a new option so when active a new window will inherit the profile and directory of the active terminal.

**Comment by Laeeth** [comment]
Great - thanks for this.  Hello from dconf Berlin. 

--
  Laeeth Isharc
  laeeth@laeeth.com



On Sun, 7 May 2017, at 07:11 PM, Gerald Nunn wrote:
> I've added a new option so when active a new window will inherit the
> profile and directory of the active terminal.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/gnunn1/tilix/issues/896#issuecomment-299723807
