### ISSUE TITLE
Can't compile 1.5.6 on centos 7

### ISSUE THREAD

**Issue by Dark-Passenger** [gnunn1/tilix#897]
Hi, 
Fails to compile the latest release on centos 7.  Something in the man compilation are, am compiling with autotools.

And the binary version fails to run on centos 7.

AFK(will post error by tomorrow).

Am still on 1.5.4 which is working fine. On the same device.

**Comment by vmercuri** [comment]
Tilix 1.5.6 is available for RHEL/CentOS 7.x as EPEL package via COPR:

https://copr.fedorainfracloud.org/coprs/ivoarch/Tilix/
https://copr-be.cloud.fedoraproject.org/results/ivoarch/Tilix/epel-7-x86_64/00537310-tilix/

**Comment by zoqaeski** [comment]
I also can't compile Tilix on Arch Linux. [This](https://gist.github.com/zoqaeski/2fe3a73db2268dcf95e0d87f6cf637b3) is the error I get:

```
/usr/lib/libgtkd-3.so: undefined reference to `_D4core6memory2GC10removeRootFNbxPvZv'
/usr/lib/libgtkd-3.so: undefined reference to `_D4core6memory2GC7addRootFNbxPvZv'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
```

I'm not sure whether my issue is the same as @Dark-Passenger reports.

**Comment by AnrichVS** [comment]
Please note that on Arch Linux this problem was fixed by updating and rebuilding GTKD via AUR (GTKD version 3.6.1-1) and then also rebuilding Tilix (version 1.5.6-2).

**Comment by Dark-Passenger** [comment]
Sorry for the delay my error is slightly more lame ... https://gist.github.com/Dark-Passenger/78c5e9079141fa5588bbd674669f9d46

**Comment by postblue** [comment]
Error for me too, very verbose: https://gist.github.com/postblue/8cfc8b454e2058e9cf2c742fa94de468

**Comment by vmercuri** [comment]
@Dark-Passenger, I've just compiled Tilix from master on RHEL 7.3 (please consider CentOS and RHEL perfectly equivalent in this regard). All I did was to install the package `gsettings-desktop-schemas-devel` from the repo `rhel-7-server-rpms` and then I installed DUB 1.2.1 from [here](https://code.dlang.org/download) (put it in `~/.local/bin`) and DMD 2.074.0 from [here](https://dlang.org/download.html#dmd) (with `yum install dmd-2.074.0-0.fedora.x86_64.rpm`). After cloning Tilix from master I launched (from the root of the source tree):

1) `dub build --build=release` (_as normal user_)
2) `./install.sh` (_as root_)
3) `glib-compile-schemas /usr/share/glib-2.0/schemas/` (_as root_)

here's a [screenshot](https://s16.postimg.org/qngu8zuit/Screenshot_from_2017-04-25_18-47-46.png). 
Make sure you have the essential packages for development installed, even though I'm not sure if they are required (`yum groupinstall "Development tools"`) _and_ `dconf`. Everything else is handled by DUB automatically.

**Comment by dsboger** [comment]
@Dark-Passenger Tilix now requires `po4a-translate` to build localized man pages. In Arch it is found in the `po4a` package. Nevertheless, `configure.ac` should stop if it is not found. I'll make a PR to fix that.

**Comment by dsboger** [comment]
@postblue @zoqaeski we had some concomitant ABI-breaking updates last weeks that made things a little chaotic:
- `ldc-1.2.0` and `liblphobos-1.2.0`
- `vte3-0.48.2+2+g837cce9c` and `vte3-tilix-0.48.2+2+g837cce9c+1.5.6`
- `gtkd-3.6.1`
Both `tilix` and `tilix-git` depend on the three and link against `liblphobos` and `gtkd` directly. As AUR is kind of a source distribution, we cannot give atomic updates, so you must rebuild things in the correct order for it to work. Start by rebuilding `vte3-tilix`, then `gtkd` and finally `tilix`.

@postblue taking a closer look at your build log, it does not seem the same issue. Could you try rebuilding from a clean directory (delete everything from the same dir, except for `PKGBUILD` itself)?

**P.S.**: for AUR building issues, please first try asking the packager by commenting on AUR, before coming upstream. You are more likely to get a solution there. I don't know about other distros, but a similar policy should apply.

**Comment by phw** [comment]
@dsboger could po4a-translate be made optional for the autotools build? When I added this I made it optional in the install.sh script, as I think while you should have it if you want to package for distribution it is not really an absolute necessity for a personal build (unless you really want to have localized man pages installed)

**Comment by dsboger** [comment]
@phw I'll look into it. I'll have to learn about it, though, and I'm not with a lot of free time in my hands, so it may take a while, like a few weeks. In the meanwhile, I think it is better to give an informative error message, so I'll PR with the above solution as a temporary measure.

**Comment by gnunn1** [comment]
I'm cleaning up issues, I'm not planning on working on this since RHEL/CentOS are low priorities for me given their primary use for servers rather than workstations.
