### ISSUE TITLE
Can't compile 1.5.6 on Archlinux (GNOME 3.24)

### ISSUE THREAD

**Issue by frnogueira** [gnunn1/tilix#898]
Hi!
After GNOME 3.24 has come to Arch, the Tilix was broken:
```

tilix: symbol lookup error: tilix: undefined symbol: _D3std4json9JSONValue8opEqualsMxFNaNbNiKxS3std4json9JSONValueZb

```
When I try reinstall:

```
dmd -L-lvted-3 -L-L/usr/lib// -L-lgtkd-3 -L-ldl -L-lX11 tilix.o -oftilix
/usr/lib/libgtkd-3.so: undefined reference to `_D4core6memory2GC10removeRootFNbxPvZv'
/usr/lib/libgtkd-3.so: undefined reference to `_D4core6memory2GC7addRootFNbxPvZv'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
make[1]: *** [Makefile:1037: tilix] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-fnogueira/aur-tilix/src/tilix-1.5.6'
make: *** [Makefile:606: all-recursive] Error 1
==> ERRO: Uma falha ocorreu em build().
    Abortando...
==> ERRO: Makepkg não conseguiu compilar tilix.
==> Reiniciar a compilação de tilix ? [s/N]
```

**Comment by repsac-by** [comment]
First rebuild gtkd

**Comment by Koltharius** [comment]
Same error here
tilix: symbol lookup error: tilix: undefined symbol: _D3std4json9JSONValue8opEqualsMxFNaNbNiKxS3std4json9JSONValueZb

**Comment by frnogueira** [comment]
Thanks @repsac-by !
@Koltharius .. Rebuild the gtkd! ;)

**Comment by gittakkie** [comment]
Rebuilding gtkd didn't work for me. I'm getting a bunch of these 'undefined symbol' errors.
First ones begin:
```
make[1]: Entering directory '/home/<user>/.cache/pacaur/tilix/src/tilix-1.5.6'
ldmd -L-lvted-3 -L-L/usr/lib// -L-lgtkd-3 -L-ldl -L-lX11 tilix.o -oftilix
tilix.o: In function `_D7secretc6secret20_sharedStaticCtor232FZv':
source/x11/Xlib.d:(.text._D7secretc6secret20_sharedStaticCtor232FZv[_D7secretc6secret20_sharedStaticCtor232FZv]+0x18): undefined reference to `_D4gtkc6Loader6Linker11loadLibraryFAyaZv'
tilix.o: In function `_D4gtkc6Loader6Linker39__T4linkTPUZE4gtkc12gobjecttypes5GTypeZ4linkFKPUZE4gtkc12gobjecttypes5GTypeAyaAAyaXv':
source/x11/Xlib.d:(.text._D4gtkc6Loader6Linker39__T4linkTPUZE4gtkc12gobjecttypes5GTypeZ4linkFKPUZE4gtkc12gobjecttypes5GTypeAyaAAyaXv[_D4gtkc6Loader6Linker39__T4linkTPUZE4gtkc12gobjecttypes5GTypeZ4linkFKPUZE4gtkc12gobjecttypes5GTypeAyaAAyaXv]+0x7): undefined reference to `_D4gtkc6Loader6Linker9getSymbolFAyaAAyaXPv'

```

**Comment by davibusanello** [comment]
Rebuild gtkd and tilix don't work for me

> /usr/bin/install -c tilix man/man1/tilix.1; \
gzip -f man/man1/tilix.1
/usr/bin/install -c -d "."/man/uk/man1; \
 -k 0 -f man -m "."/tilix -p po/uk.man.po -l "."/man/uk/man1/tilix.1; \
gzip -f "."/man/uk/man1/tilix.1; 
/bin/sh: linha 1: -k: comando não encontrado
gzip: ./man/uk/man1/tilix.1: No such file or directory
make[1]: *** [Makefile:509: man/uk/man1/tilix.1.gz] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-davi/aur-tilix/src/tilix-1.5.6/data/man'
make: *** [Makefile:606: all-recursive] Error 1
==> ERRO: Uma falha ocorreu em build().
    Abortando...
==> ERRO: Makepkg não conseguiu compilar tilix.

**Comment by nelsongustavo** [comment]
Same issu here.

tilix.o:(.data.rel.ro._D2gx3gtk5cairo12RenderWindow6__vtblZ[_D2gx3gtk5cairo12RenderWindow6__vtblZ]+0x15f0): undefined reference to `_D3gtk6Window6Window24internalRemoveOnSetFocusMFC3gtk6Window6Window25OnSetFocusDelegateWrapperZv'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
make[1]: *** [Makefile:1037: tilix] Error 1
make[1]: Leaving directory '/home/nelson/.cache/pacaur/tilix/src/tilix-1.5.6'
make: *** [Makefile:606: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build tilix package(s)

**Comment by gnunn1** [comment]
@davibusanello Do you have po4a installed?

**Comment by Rafaelsalass** [comment]
How do I rebould gtkd?

**Comment by davibusanello** [comment]
@gnunn1 yes, have. i'm installing with yaourt.

@Rafaelsalass i remove full tilix and gtkd, clear caches, and install with AUR package

**Comment by gnunn1** [comment]
@davibusanello You should report this against the Arch package you are using as the problem is likely something on their end.

**Comment by davibusanello** [comment]
@gnunn1 ok, thank you =)

**Comment by Rafaelsalass** [comment]
thank you !!!
