### ISSUE TITLE
Make it possible to reorder sessions by pressing Ctrl+Shift+PageUp like in GNOME Terminal

### ISSUE THREAD

**Issue by TylerRick** [gnunn1/tilix#899]
Coming from `gnome-terminal`, I was pleased that `Ctrl`+`PageUp` [work as I am used to](https://github.com/gnunn1/tilix/issues/187#issuecomment-201970922)... Would be nice if I could reorder the sessions (to me, they're "tabs") as well, with  `Ctrl`+`Shift`+`PageUp`/`PageDown`. This is the same shortcut for reordering tabs used by `gnome-terminal`, `chromium-browser`, and possibly others...

Of course, this would make a bit more sense if sessions *were* actually tabs — then you could actually see the tabs moving when you pressed the shortcut... So, since tabs are appear to be out (#114, #268), what visual feedback would we show the user? Perhaps open the sessions sidebar briefly to show the animation of sessions being moved and then hide it again after a second?

See also #264 (reordering with mouse)

**Comment by TylerRick** [comment]
As it is, if I want two sessions to be "next to" each other (so that I can switch between them quickly with `Ctrl`+`PageUp`/`PageDown` without having to travel through other sessions to get there) ... I have to very intentionally plan things out as I add new tabs... I can't put them in the desired order after the fact (unless I'm missing something)...

Only workaroud I've found so far is painful... drag a session(s) out of the window to detach it, create new sessions where you desire them to be attached, drag the detached sessions back (which I can't seem to do without creating a split), close the temporary placeholder session that the desired session is split with...

**Comment by gnunn1** [comment]
I've added initial re-ordering of sessions via DND, I'll add support for doing the same via these shortcuts over the weekend.

**Comment by TylerRick** [comment]
I still don't see session reordering commands listed under Preferences > Shortcuts in Tilix 1.6.4. 

Did shortcuts actually get added for this? I see it mentioned in https://github.com/gnunn1/tilix/releases/tag/1.5.8 but Ctrl-PageUp or Ctrl-PageDown (for me at least) are bound to `Switch to next/previous session` (as they should be).

![image](https://user-images.githubusercontent.com/14151/36167296-326565cc-10aa-11e8-84ff-ee80d84fe4f3.png)

and `Ctrl`+`Shift`+`PageUp`/`PageDown` (the shortcuts I would suggest for re-ordering) don't appear to be bound to anything.
