### ISSUE TITLE
Unfocused dim should always make terminal darker

### ISSUE THREAD

**Issue by alessandro-guido** [gnunn1/tilix#900]
With the Light Gtk theme variant (the default one), unfocused terminals become lighter (up to white when set to maximum). This is a confusing behavior and looks very strange on dark terminals with light gtk theme.

I suggest that unfocused terminals should always become darker or, maybe better, use the profile color scheme background color.

**Comment by dsboger** [comment]
You can change the dim color in the Advanced button under Color tab of profile settings. I set mine to black to make it darker. Maybe having the default set to black would make sense?

**Comment by gnunn1** [comment]
I think the default should be to set to the opposite of the background, foreground could be an option but I wonder if that just washes out the text? I'll need to play with it a bit.

**Comment by gnunn1** [comment]
I've switched the default Dim color to use the terminal foreground color. It works reasonably well in my testing. Give it a go and if you notice any issues just let me know.

**Comment by alessandro-guido** [comment]
I've just updated to 1.5.6 (from fedora COPR heikoada/terminix) which should include fix #900. The attached screenshot shows two terminals stacked horizontally using "Monokai Dark" color scheme. Unfocused dim is set to the maximum in the terminal profile. The unfocused terminal (left) is completely white, which I don't think is the intended nor (imho) correct behavior.

![screenshot from 2017-05-21 12-38-52](https://cloud.githubusercontent.com/assets/1285126/26283160/7e0d9ad6-3e22-11e7-97f2-2795e0f685b6.png)

**Comment by gnunn1** [comment]
The intent isn't really to set it to 100% though, it tends to work best with lower values. Maybe the maximum should be changed to something like 40%?

Also, feel free to write out how you think the feature should work in more detail.

**Comment by dsboger** [comment]
I vote for ~25% opacity black, with a very GNOMEy enable/disable checkbox. But seriously, I think that using an arbitrary color for dimming is kinda weird. I also don't like using the foreground color with dark background schemes because the unfocused terminal will get brighter, calling more attention.

**Comment by gnunn1** [comment]
@dsboger I think whatever color gets chosen people are not going to like it. I was using the insensitive theme color previously, I could revert the color back to that.

I'm also wondering if I should just rewrite this feature to behave like the terminator does it by updating all of the font colors to reduce their brightness. That approach has some downsides as well though as monkeying with the VTE palette colors can have some side effects on other colors.

**Comment by jkahrs** [comment]
iTerm allows an option to only dim the text.
This way the background color doesn't "flip" around.
