### ISSUE TITLE
Library link order incorrect

### ISSUE THREAD

**Issue by mleise** [gnunn1/tilix#907]
With the current line in the Makefile:
`GTKD_LIBS = -L-ldl -L-lgtkd-3 -L-lvted-3`
I get
`dmd -L-ldl -L-lgtkd-3 -L-lvted-3 -L-lX11  tilix.o -oftilix
/opt/dmd-2.074/lib64/libvted-3.a(Terminal_289_33c.o):function _D3vte8Terminal8Terminal16getGeometryHintsMFJS4gtkc8gdktypes11GdkGeometryiiZv: error: undefined reference to '_D4gtkc8gdktypes11GdkGeometry6__initZ'`
When I swap gtkd-3 and vted-3 it works, which seems legit, as when linking, later libraries plug the holes opened by libraries coming earlier. I.e. since vted-3 has some references into gtkd-3 it needs to come first for compilation to succeed.
`dmd -L-ldl -L-lvted-3 -L-lgtkd-3 -L-lX11  tilix.o -oftilix`
works fine.

Note that this does only happen for me when linking against static phobos and gtkd. Dynamic linking seems to work with both orders.

See also: http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc

**Comment by gnunn1** [comment]
I see the same thing but I'm not sure where to fix as I'm not seeing where the order gets set.

@dsboger Can you give me a hint if you have a moment?

**Comment by dsboger** [comment]
I also don't know how the order is set. Here in my end vted-3 comes before gtkd-3 on the generated Makefile, irrespective of the order I put them in PKG_CHECK_MODULES call in configure.ac. Looks like splitting the checks in two variables is a way to ensure proper linking order. I'll PR with that change.

**Comment by dsboger** [comment]
On a second thought, `pkg-config` seems to order libs correctly by the dependencies stated in the respective `.pc` descriptors. @mleise could you please post the outputs of both
```$ pkg-config --libs gtkd-3 vted-3```
and 
```$ pkg-config --libs vted-3 gtkd-3```

**Comment by mleise** [comment]
Sorry, I was wasting everyone's time. I'm not using the pkg-config files, but set GTK_LIBS manually. This bug report should have been in the Gentoo dlang repository. I fixed it there now. Thanks @dsboger for the hint in the right direction.
