### ISSUE TITLE
Numbers tiles spatially rather than chronologically

### ISSUE THREAD

**Issue by jamienicol** [gnunn1/tilix#908]
I use Alt-1/2/3 etc a lot for switching focus between terminal tiles. Currently the terminals are numbered based on the order in which they were created. For me this is confusing because I forget which order they were created in. I'd find it much easier to remember based on their position. Adding or rearranging splits would often cause existing terminals to change their number which could definitely be confusing for some people, so perhaps this would be better as an option.

**Comment by gnunn1** [comment]
The challenge here is that Tilix has no idea what the actual order of terminals is. It could be determined by brute force by iterating over the screen and sampling coordinates to see what terminal is there but that is less then ideal. I'll need to give this some thought.

**Comment by gnunn1** [comment]
I'm not seeing an easy way to do this other then the sampling method which is a pretty ugh method. Closing this for now, if someone comes up with a great algorithm for doing this feel free to re-open with an explanation.
