### ISSUE TITLE
Transparent terminal titles and missing icons on main title bar (Cinnamon 3.2.8/Fedora 26)

### ISSUE THREAD

**Issue by vmercuri** [gnunn1/tilix#910]
Build from master with:

1. `dub build --build=release`
2. `sudo ./install.sh`
3. `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

after installing `DUB 1.2.1` from [here](https://code.dlang.org/download) and `DMD 2.074.0` from [here](https://dlang.org/download.html#dmd). Also the `Add terminal right` and `Add terminal down` icons don't show up in the main title bar. 
![screenshot_2017-05-05_00-50-05](https://cloud.githubusercontent.com/assets/4584008/25728254/21b22c8a-312e-11e7-93de-d46a0f688a3f.png)

**Comment by gnunn1** [comment]
Likely the resources did not get.built correctly, what's the output of ```sudo ./install.sh```?

**Comment by vmercuri** [comment]
Indeed there was an issue during the installation:

```
Building and copy resources...
tilix.gresource.xml: to-pixbuf preprocessing requested but GDK_PIXBUF_PIXDATA not set and gdk-pixbuf-pixdata not found in path.
install: cannot stat 'tilix.gresource': No such file or directory
```
I managed to solve the problem by installing the package `gdk-pixbuf2-devel` that is actually mentioned [here](https://github.com/gnunn1/tilix#build-dependencies) (but it has a slightly different name on Fedora).  Now everything is working fine:

![screenshot_2017-05-05_01-19-28](https://cloud.githubusercontent.com/assets/4584008/25728807/b287d874-3131-11e7-9055-c93d832d2f0b.png)
Sorry for bothering you about the issue : )

**Comment by gnunn1** [comment]
No worries, glad you were able to resolve it.
