### ISSUE TITLE
Feature request: scroll through session sidebar with mouse wheel

### ISSUE THREAD

**Issue by kostich** [gnunn1/tilix#912]
I would like if it was possible to scroll through available sessions in the sidebar with the mouse wheel. Currently not possible on Fedora 26 Alpha and Tilix 1.5.6.

**Comment by gnunn1** [comment]
The mouse wheel scrolls the viewport so if you have more sessions then can be viewed in the sidebar it scrolls the view up and down. On my machine this works as expected.

I think what you are asking for is to have the mouse wheel behave like the arrow keys where it actually moves the selection up or down. Is this correct? If so, I do not plan to change the behavior as this would not be consistent with other GTK+ applications.

**Comment by kostich** [comment]
Yes. I would like for the mouse wheel to behave like the arrow keys where I can move the selection up and down.

Thank you for your response.
