### ISSUE TITLE
Default Search direction

### ISSUE THREAD

**Issue by towolf** [gnunn1/tilix#915]
Tilix defaults to "search forward". For regular document-based applications this makes sense, for a terminal it doesn't.

Gnome-Terminal, at least the older one where search was not utterly broken, has a toggle for this. 

What I'd like to have is `Enter` for backwards search, finding string from the bottom line upwards. So way to reverse the shortcuts `Enter` and `Shift-Enter`.

A checkbox in the Find Options drop-down (must be persistent) would fix this.

**Comment by gnunn1** [comment]
I agree, I've reversed it so that the <Enter> and <Shift><Enter> shortcuts in the find drop-down now moves backward and forward respectively instead of forward and backward.
