### ISSUE TITLE
Password Favorites

### ISSUE THREAD

**Issue by iax7** [gnunn1/tilix#918]
Currently, enter a password is somewhat slow:
[Key combination] + tab + enter

I propose a set of 3 or 5 favorite passwords to be input as follows:
[Key combination] + [ number ]
![image](https://cloud.githubusercontent.com/assets/6983510/25872778/95600610-34d1-11e7-9204-ad3e4bd7e061.png)
when you hit the number automatically closes the window.

**Comment by gnunn1** [comment]
How do you envision managing these favorites?

**Comment by iax7** [comment]
![image](https://cloud.githubusercontent.com/assets/6983510/25909365/9638c4ae-3572-11e7-8540-437a4d4395c8.png)

**Comment by iax7** [comment]
![image](https://cloud.githubusercontent.com/assets/6983510/25909709/a44be458-3573-11e7-91cd-25cdb279b3ba.png)
or 3 buttons with a number label, and the status of the usage, you can overwrite from this window. Perhaps a tooltip of which password is using the spot.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 A better idea is to set the shortcuts on the json file, and show that on the shortcuts settings which is much better than overcomplicating the Add Password window

**Comment by gnunn1** [comment]
@bil-elmoussaoui What json file are you referring to, the passwords are stored in Gnome key-ring?

**Comment by bil-elmoussaoui** [comment]
Sorry i thought the issue was about Bookmarks, in that case maybe having the id of the password(stored on Gnome Keyring) and assign it to a shortcut that could be saved on a database (sql? or json?)

**Comment by gnunn1** [comment]
If I were to do this, likely I would store the favorites in a gsettings string array with the name of the secrets that are the favorites. The order of the list would correspond to the assigned favorite.

Anyway, it's an interesting idea but not something I'm actively interested in doing personally. If someone wants to take this on I'm happy to accept a PR.

**Comment by gnunn1** [comment]
After thinking about this, why not just prefix the name of the secrets you want quick access to? For example:

1 - SSH Password
2 - Local Password
etc..

You can then just type the number and enter and off you go. No complicated favorites management solution required.

**Comment by gnunn1** [comment]
After thinking about this some more, I think what I've proposed above is fine. I'm not planning on implementing this.

**Comment by iax7** [comment]
The whole purpose of the favorites is to avoid an extra stroke. Just hitting the number assigned to favorites will auto select and close the pop-up window.

With the search functionality that you mention is still more key strokes. 

I just need one password, and I always hit <tab><enter> and I just wanted to hit <number1> and be selected automatically.

I think another good approach for using the search is: if the search finds one result then autoselect and close. That way, if you type 1, it will find only "1 - SSH Password" that can be auto selected.

let me know your thoughts.

**Comment by gnunn1** [comment]
If you preface the password description with a number (1,2,3) it's two keystrokes: the number + enter key. While with what you propose it's only one keystroke, I'm not willing to build a whole favorite management system to save that one keystroke.

**Comment by iax7** [comment]
Actually, the tab keystroke is needed even when only one result is shown in the search. (at least 3 keystrokes)

Can you re-read "another good approach"? is based upon your May 14 comment, not the favorite management.

**Comment by gnunn1** [comment]
@iax7 Thanks for pointing out the issue with tab, I fixed that so it's now two keystrokes as expected (number + enter).
