### ISSUE TITLE
Feature request: an option to create new session in current folder

### ISSUE THREAD

**Issue by PatrickChen83** [gnunn1/tilix#920]
Having searched all preference tabs for this option because I think this option should make sense (and is easy to implement).

**Comment by phw** [comment]
It does that by default. Have you read through https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue ?

**Comment by bil-elmoussaoui** [comment]
https://gnunn1.github.io/tilix-web/manual/vteconfig/

**Comment by PatrickChen83** [comment]
Got it! Thanks for the help!
