### ISSUE TITLE
problem when showing with less

### ISSUE THREAD

**Issue by mozartilize** [gnunn1/tilix#923]
i don't know how to describe it, here is a gif

![peek 2017-05-11 15-36](https://cloud.githubusercontent.com/assets/26346270/25940448/5e071d58-3660-11e7-9e84-3e40943781b0.gif)

it will render forever if i scroll up, it repeated so many times
the problem does not occur on gnome-terminal, but i not sure it's tilix issue

tilix version 1.5.6 on Xubuntu 17.04

**Comment by egmontkob** [comment]
Looks like you pass the `-X` option to `less` (e.g. in the `LESS` environment variable).

**Comment by mozartilize** [comment]
@egmontkob I'm not sure about it, i tried `cat some-long-content-file | less` and it worked fine. The problem I got is when I use `rails c`

**Comment by gnunn1** [comment]
Unfortunately I'm not able to duplicate this on my end using Arch and GTK 3.22. I also tried using the ```-X``` option as suggested by @egmontkob and I don't see the issue.

One major difference between tilix and gnome-terminal is that tilix uses DBusActivation. The problem with DBusActivation is that the environment variables can be slightly different when using it which can sometimes cause odd behaviors.

Can you try running tilix directly? With all instances of tilix closed, open gnome-terminal and type ```tilix``` at the command line. Then try to duplicate this issue in that instance of tilix and see if it occurs.

**Comment by mozartilize** [comment]
yes, it still happens. I'll check again on my ubuntu gnome desktop

**Comment by gnunn1** [comment]
@mozartilize I don't support XFCE in terms of trying to reproduce issues but if it happens on Gnome let me know and I'll try to reproduce in a VM.

**Comment by mozartilize** [comment]
I tried and it's fine on my ubuntu gnome 16.04, gnome-shell 3.20

**Comment by gnunn1** [comment]
That's interesting, not sure what the issue is with XFCE. Unfortunately as mentioned previously I don't support XFCE so I won't be investigating further.
