### ISSUE TITLE
add the tabs feature

### ISSUE THREAD

**Issue by astrotee** [gnunn1/tilix#924]
some programs needs at least 80*24 dimensions, so they won't work using splitting so it would be cool to have tabs

**Comment by astrotee** [comment]
yes but, I thought it would be easier to navigate using tabs at the top
as tabs takes one click but sessions takes two

**Comment by astrotee** [comment]
maybe I can just get used to using sessions :smiley:

**Comment by gnunn1** [comment]
Sorry but no plans to add tabs.
