### ISSUE TITLE
Transparent background not working

### ISSUE THREAD

**Issue by PixelGGamer** [gnunn1/tilix#925]
Hello,
After installing tilix and enabling transparency, it seems that it doesn't work, because i have it black.
My wm is i3. Any help?
![screenshot from 2017-05-12 17-54-15](https://cloud.githubusercontent.com/assets/7670940/26006194/d3ce5930-373b-11e7-8deb-17f45006172c.png)

**Comment by f2404** [comment]
Does your WM support compositing? If not, this is the answer.

**Comment by PixelGGamer** [comment]
Nope,
however i saw lots of people with this working

**Comment by PixelGGamer** [comment]
Found compositing manager and works, thanks
