### ISSUE TITLE
Cannot resize window when exporting display

### ISSUE THREAD

**Issue by phenixrizen** [gnunn1/tilix#926]
When I export the display to another X server I'm unable to resize the window.

**Comment by gnunn1** [comment]
Do other gtk3 apps like gedit work fine when you do this?

**Comment by gnunn1** [comment]
Also, what distro and desktop environment are you using?

**Comment by phenixrizen** [comment]
Yes it looks like all gtk3 apps will not maximize.  I can mange to get the resize arrow on the menu bar if i mouseover just right. I'm running running Ubuntu 16.10 with there default desktop environment and exporting the display to VcXsrv X Server running on Windows 10.

**Comment by gnunn1** [comment]
Unfortunately this doesn't sound like a tilix bug but something more generic if it is affecting all gtk3 applications. I'd suggest opening a bug report with GTK on this.
