### ISSUE TITLE
Optional compact mode when window is maximized

### ISSUE THREAD

**Issue by alxgrtnstrngl** [gnunn1/tilix#927]
Add an optional compact mode when Tilix is maximized or tiled. This could be either removing the titlebar when CSD is disabled or hiding the headerbar. Another way to do compact mode would be to set the window style "borderless" dynamically.

**Comment by gnunn1** [comment]
Isn't this what full-screen mode (F11) already does?

**Comment by alxgrtnstrngl** [comment]
There are GNOME Shell extensions that hide the titlebar when the window is maximized like Maximus NG. But these won't work on Wayland because of CSD. This option would ensure that the window is compact for users who don't want to fullscreen the app but maximize it or snap it side-by-side.

**Comment by gnunn1** [comment]
Thanks for the suggestion, at the moment though I'm trying to avoid adding new options where possible. Additionally, I do think this is something best implemented in the WM rather then at the application level. As a result I will not be implementing this feature, sorry.
