### ISSUE TITLE
Colorscheme not working properly.

### ISSUE THREAD

**Issue by jamespotz** [gnunn1/tilix#931]
Colors work on load but fallsback to default color. This happens to all colors even custom colors.

On load it works. The color I'm using is Solarized-dark
![screenshot_20170519_120744](https://cloud.githubusercontent.com/assets/4239625/26232914/2cc4607a-3c8c-11e7-8c51-851b05def650.png)

but this happens after
![screenshot_20170519_120752](https://cloud.githubusercontent.com/assets/4239625/26232932/43310c96-3c8c-11e7-966e-196bc00141db.png)

**Comment by gnunn1** [comment]
Sorry, can you elaborate what you mean by "fallback"? Does it work the first time you set the colors and then when you re-run it a second time it's back to the default colors?

**Comment by jamespotz** [comment]
No the colors does not work the first time. But if i open a new session the color appears for a brief moment and when zsh loads it just returns back to the default color.

**Comment by gnunn1** [comment]
This isn't sounding like something tilix is doing, I suspect zsh or something related is affecting the colors. If you use bash do you have the same issue?

**Comment by jamespotz** [comment]
yes its not tilix its zsh. I accidentally solve it by removing 
 BASE16_SHELL=$HOME/.config/base16-shell/                                                        │~                              
 [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)

I am closing this.
