### ISSUE TITLE
alt + up arrow in weechat does not work on tilix

### ISSUE THREAD

**Issue by vyasgiridhar** [gnunn1/tilix#933]
I tried using alt + up to switch channels in weechat but it does not work.
It works in gnome-terminal though.

Is there a way for me to get a debug or trace to zero down on the issue?

It does not seem to be a weechat issue.

**Comment by gnunn1** [comment]
By default <alt><arrow-key> is used to move between terminals in a session. You can re-map the shortcuts to something else in Preferences | Shortcuts.
