### ISSUE TITLE
Restore last session window on launch (minimized/maximized)

### ISSUE THREAD

**Issue by rancidfrog** [gnunn1/tilix#935]
Currently tilix always starts with a minimized window, even when last session was exited with maximized.
Could a setting be added to restore last sessions appeance?
Or, whether maximized/minimized on start?

Thank you

**Comment by gnunn1** [comment]
You can use the command line switches to start Tilix maximized or minimized if that's what you want, i.e:

```
tilix --maximize
tilix --minimize
```

otherwise it is the window manager's responsibility to manage this and I don't have any plans to make it a preference.

**Comment by rancidfrog** [comment]
Thank you for quick response.

My issue is that whenever I launch tilix from application menu it starts minimized.
Most apps standard scenario is launch the way you exited; so, if you exit maximized, the next launch will also be maximized.
Files/Nautilus, web browsers, and most other apps follow this manner.
(Not sure how they do it, config file remembers last state?)
However tilix always starts minimized, unless you launch command tilix --maximize

Anyway thank you for response

**Comment by gnunn1** [comment]
That's weird, what desktop environment are you using, Gnome? There's nothing in my code that I'm aware of that would cause this.

**Comment by rancidfrog** [comment]
Yes, Version 3.24.2 Gnome on Archlinux.

**Comment by gnunn1** [comment]
That's what I'm using as well. I'll think about what could be causing this, but right now I don't have any obvious ideas. Are you using any extensions in gnome?

**Comment by rancidfrog** [comment]
No extensions.
But, it may be an issue with gnome, as terminal and terminator both always start minimized too from application menu.
So not sure what to tell you, but strange.

**Comment by gnunn1** [comment]
Weird too how it's the terminal applications. If you run tilix in gnome-terminal from the command line is there any error or warning shown? Also is this in X11 or Wayland, if Wayland do you get the same behavior in X11?

I'll check the minimize/maximize state saving of Nautilus and gedit, if they are indeed doing that then yes tilix should do the same.

**Comment by rancidfrog** [comment]
Yes,
```
** (tilix:2871): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-YFrm2ZpDHT: Connection refused
```
I believe X11

**Comment by gnunn1** [comment]
I've added some code to save and restore window state similar to gedit and nautilus.

As to the minimize issue, I have no clue what the issue there is but I don't think it's a tilix issue. Looking at the accessibility error you posted, it doesn't seem to be the cause of this issue.

**Comment by rancidfrog** [comment]
Thank you,
Working as expected, but with one exception.
Tilix quake mode is treated as minimized, and closing tilix while in quake mode results in state returning to minimized. I believe it should be treated separately, (I have tilix --quake bounded to custom keyboard shortcut).
Usually I use tilix maximized unless I want to do a quick cmd for which I use quake mode.

**Comment by gnunn1** [comment]
Thanks, I've fixed it.
