### ISSUE TITLE
Feature Request:  support for viewing current/running process in title

### ISSUE THREAD

**Issue by s4n-gt** [gnunn1/tilix#937]
ConEmu on Windows and iterm2 on MacOS have a feature to show running process.
(ref: https://www.reddit.com/r/linux4noobs/comments/6cu425/show_current_process_in_terminal/)

it would be nice to have this functionality in tilix.

**Comment by gnunn1** [comment]
What do they do for processes with excessively long names?

**Comment by s4n-gt** [comment]
[sorry for late replay]

for long names, conEmu only shows first 63 characters.

![conemu](https://cloud.githubusercontent.com/assets/28922018/26506159/57047456-426d-11e7-83c1-c72a487952ee.png)

**Comment by gnunn1** [comment]
I played around with this, the primary obstacle is being notified when a child process is created. Unless the window title changes or some other activity happens where VTE triggers an event tilix doesn't know that a process kicked off. For example, when running nano no events are triggered in tilix.

I'd prefer not to resort to polling the shell process periodically as that just chews up cycles. If someone more familiar with kernel capabilities knows of a way to get notified of new processes that doesn't require root access feel free to let me know. I didn't see any obvious candidates in a brief search.

**Comment by s4n-gt** [comment]
I am not familiar with kernel.

please keep this alive for someone who is knowledgeable in this stuff.

**Comment by gnunn1** [comment]
I think I'm going to have to resort to polling for this, I believe that's what iterm2 is doing.

**Comment by gnunn1** [comment]
I have added an initial implementation of this feature, however since it is using threads to do the polling I have disabled it by default for now until I get a chance to test it before. I have only briefly tested it but it seems to work quite well in this limited testing. Note that the polling period is set to 250ms at the moment and I don't think it's feasible to set it lower.

I still have some things to optimize as well. At the moment all terminals receive notifications even if it is for a process that is not there. Need to figure a way to bind signals selectively in D that is clean.

If someone wants to try it, you need to enable the ```USE_PROCESS_MONITOR``` flag in constants.d and then re-compile tilix.

**Comment by gnunn1** [comment]
Also, when enabled you will notice a new variable called ```Process``` in the list to be used for titles.

**Comment by gnunn1** [comment]
Sorry for the spam, just reminding myself of a few things. I wonder if I could use this feature to drive notifications on systems that don't have the fedora VTE notification patch?

Also, might be an idea to add trigger support for it as well.

**Comment by gnunn1** [comment]
I've enabled this feature by default, let me know if there are any issues.

**Comment by s4n-gt** [comment]
>period is set to 250ms 

I think it is more than enough.


I have built and tested https://github.com/gnunn1/tilix/commit/dd70121137533daf8d00eba5a24a6dde0c9e77c3 on ubuntu 16.04 (I had to install `libx11-dev` manually)

I have ran this code

```python
from subprocess import call
call(['wget', 'http://downloads.dlang.org/releases/2.x/2.075.0/dmd_2.075.0-0_amd64.deb'])
```

and title is looking like this.

![tilix](https://user-images.githubusercontent.com/28922018/29158193-ed575466-7dcb-11e7-8e85-2536a0335fc0.png)

It is not changing. It just takes  currently running command and keeps it persisted.

Is it ubuntu specific problem?

**Comment by gnunn1** [comment]
It doesn't keep track of children of children, you are running a python script with wget embedded in it hence why python is showing. If you run wget directly that should as well.

How does iterm2 handle it?

**Comment by s4n-gt** [comment]
Not sure about iterm2 (I haven't used it),
I found it here https://bbs.archlinux.org/viewtopic.php?id=222054

I have used this feature on ComEmu (on windows).
Here is the implementation

github.com/Maximus5/ConEmu/blob/bdb3552bc95693413edfdb5f1728cc2e68376b0f/src/ConEmu/RealConsole.cpp#L8171

and usage

https://github.com/Maximus5/ConEmu/blob/bdb3552bc95693413edfdb5f1728cc2e68376b0f/src/ConEmu/Status.cpp#L85


sorry that I didn't explain what I wanted :(

**Comment by gnunn1** [comment]
Sorry I don't code in C++ and I'm not interested in trying to decipher what they are doing, can you just write out a couple of paragraphs with regards how you think the feature should behave please.

**Comment by s4n-gt** [comment]
I have sent a mail to the author of ConEmu. so, we can wait for it.

**Comment by gnunn1** [comment]
I might be misunderstanding here but all I'm looking for is a brief explanation of how you want this feature to work from a user perspective, I don't need to understand ConEmu's implementation of it. From my perspective the feature works as intended showing the name of the current process. However it sounds like you had a different expectation, if you briefly talk about the use case you are looking to fulfill then I can look at revising the implementation accordingly.

**Comment by s4n-gt** [comment]
[from arch forum](https://bbs.archlinux.org/viewtopic.php?id=222054)

>if a long running shell script is being executed in the terminal, tab title will automatically change to reflect the currently running process (binary file being executed under /bin to be exact) as different lines of the script are processed. Title also changes correctly to indicate which command in the pipeline is currently being executed

current implementation fulfil this requirement. but title bar doesn't change on my build. may be unity specific issue or building error. process variable behave like a constant. It only shows the name of the command (`not process ` that we see in task manager) which it finds at the time of setting.

even after fixing this problem, it won't works for this

> if you run 'git log' and the computer is slow enough or not warmed up, title even shows the commands internally executed by git like 'xcodebuild', 'basename' and the like.

something like if I run `gcc`, it will show cc1, ld etc. are running.

-----
ConEmu logic:
1. If some process is inside readline routine, the process is active.
2. Otherwise, the active process is the most lately  started process in the console.

**Comment by s4n-gt** [comment]
```patch
--- old_terminal.d	2017-09-23 22:13:27.690502411 +0600
+++ gnunn1-tilix-db06268/source/gx/tilix/terminal/terminal.d	2017-09-24 07:45:48.162993733 +0600
@@ -1236,11 +1236,11 @@
     void updateTitle() {
         string title = _overrideTitle.length == 0 ? gsProfile.getString(SETTINGS_PROFILE_TITLE_KEY) : _overrideTitle;
         title = getDisplayText(title);
-        if (title != lastTitle) {
+        //if (title != lastTitle) {
             lblTitle.setMarkup(title);
             lastTitle = title;
             onTitleChange.emit(this);
-        }
+        //}
     }
 
     void updateTitleBar() {
@@ -3477,7 +3477,9 @@
 
         import std.file: read, FileException;
         try {
-            name = to!string(cast(char[])read(format("/proc/%d/cmdline", childPid)));
+            string data = to!string(cast(char[])read(format("/proc/%d/stat", childPid)));
+            long rpar = data.lastIndexOf(")");
+            name = data[data.indexOf("(") + 1..rpar];
         } catch (FileException fe) {
             name = _("Unknown");
             warning(fe);
@@ -3606,10 +3608,11 @@
         static if (USE_PROCESS_MONITOR) {
             if (text.indexOf(VARIABLE_TERMINAL_PROCESS) >= 0) {
                 string name;
-                if (isProcessRunning(name))
+                //if (isProcessRunning(name))
+                    isProcessRunning(name);
                     text = text.replace(VARIABLE_TERMINAL_PROCESS, name);
-                else
-                    text = text.replace(VARIABLE_TERMINAL_PROCESS, "");
+                //else
+                    //text = text.replace(VARIABLE_TERMINAL_PROCESS, "");
             }
         }
         string path;
```


With this patch, I was able to get my expected result except for viewing child of child process.

The first change helps to change title;
The second change helps to get proper process name (from psutil);
The third change helps to get shell process;

----------
P.S: I had to  remove
https://github.com/gnunn1/tilix/blob/db062684a65b2ab61430a535a6d558664b9c2c42/source/gx/tilix/customtitle.d#L168
line due to a segmentation fault while clicking on title.

**Comment by gnunn1** [comment]
@s4n-gt If you want to submit this as a PR I'm happy to look at incorporating it.

**Comment by s4n-gt** [comment]
@gnunn1 

I have made a prototype in python.
I think it works fine except maximum recursion limit error.
https://gist.github.com/s4n-gt/12be86c8957d6b7551f796f267c1fd98

what do you think about this approach?

**Comment by s4n-gt** [comment]
Improved version: https://gist.github.com/s4n-gt/9524ae4b9ee8d0aa7dc675fccc83099c

I have made a stripped version of `psutil`'s `Process` to minimize CPU usage (maybe 10x less) and to make it easy to port this into D as D doesn't have psutil alternative. Also, this version has no recursion limit problem.

I hope D version will consume much less CPU than python. But it will take some time to port it.
