### ISSUE TITLE
Automatically hide scrollbar in vim/neovim

### ISSUE THREAD

**Issue by syedelec** [gnunn1/tilix#940]
Hi,

I am using scrollbar in the terminal and if I enter nvim/vim, I still have it even if it has no use since you can't use it to scroll into the buffer. I wanted to know if is it currently possible to hide the scrollbar when vim is started. If not, it would be a nice feature to implement.

Thanks !

**Comment by gnunn1** [comment]
No plans for this feature, if you use GTK 3.22 or later Tilix will use overlay scrollbars instead of dedicated ones and it becomes a non-issue IMHO.
