### ISSUE TITLE
Profile switch does not work when switching directly between two profiled directories

### ISSUE THREAD

**Issue by phillipsp2403** [gnunn1/tilix#942]
I have two profiles (say A and B).  Profile A which sets a blue background is triggered when I change to directory /opt/A and profile B which sets a red background when I change to /opt/B.  This works first time, however if I am already in /opt/A with a blue background and cd directly to /opt/B, the background color does not switch to red.  I have to cd to a "neutral" directory to return to the default profile and then to /opt/B to get the switch to occur in this case.

**Comment by gnunn1** [comment]
Thanks, I'll have a look at it.

**Comment by gnunn1** [comment]
This should be fixed now in master, thanks for reporting this.
