### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by rafaelmardojai** [gnunn1/tilix#944]
It is possible to save the size of the window in dconf like Lollypop does?

I like to have the terminal window not maximized in a specific size, and is a little bit annoying resize the window every time i open tilix.

Regards, and thanks for the great job!

**Comment by gnunn1** [comment]
You can set the preferred size of the terminal in the preferences dialog under profiles, just set the number of columns and rows you want it to be.

**Comment by felipemouzerlemos** [comment]
The preferred size does not work when the last used window was maximized.
In that situation the new window will be maximized too, and I can't force with --geometry because it is ignored.

**Comment by gnunn1** [comment]
The ```-geometry``` has been fixed in master so it will be in the next release, hoping to do a bug fix release this weekend.

**Comment by simonwiles** [comment]
this was fixed in a previous version, but after an update it seems to have resurfaced?

```
$ tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
@simonwiles It was made optional since it seemed to be disliked by many. You can turn it on in the General options under Behavior, ```Save and restore window state```.

**Comment by simonwiles** [comment]
So I can -- thanks :)
