### ISSUE TITLE
Title in the headerbar is not properly centered

### ISSUE THREAD

**Issue by dsboger** [gnunn1/tilix#945]
It is a very minor issue!

![image](https://cloud.githubusercontent.com/assets/2356842/26533121/fcc0f112-43e9-11e7-8629-a9eb60c1edf2.png)

**Comment by gnunn1** [comment]
I wonder if it's because of the hidden Entry used for editing the title. I'll have a look.

**Comment by dsboger** [comment]
I'm afraid the issue is still present. Is anyone else able to reproduce it? Maybe it is related to something on my end.

**Comment by dsboger** [comment]
I've made some experiments and found two problems:

- the `CustomTitle` end up hexpanding even when the children don't (I'm not sure why)
- when the title editor entry loses focus by clicking away, the `ViewMode.LABEL` is not applied

I'll make a PR with a fix that *Works For Me*.
