### ISSUE TITLE
Tilix missing in Kali Linux

### ISSUE THREAD

**Issue by honze-net** [gnunn1/tilix#946]
I installed a new Kali Linux (Kali Linux 2017 W22) and neither "terminix" nor "tilix" is available. In my previous installation (2016 W50) it was available.

German output of 2016 W50, but you will get the point:
```
root@kali:~# apt search terminix
Sortierung... Fertig
Volltextsuche... Fertig
terminix/kali-rolling,now 1.3.0-5 amd64  [installiert]
  Tiling terminal emulator for GNOME

terminix-common/kali-rolling,now 1.3.0-5 all  [Installiert,automatisch]
  Tiling terminal emulator - data files

root@kali:~# uname -a
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux
```
2017 W22:
```
root@kali:~# apt search terminix
Sortierung... Fertig
Volltextsuche... Fertig
root@kali:~# apt search tilix
Sortierung... Fertig
Volltextsuche... Fertig
root@kali:~# uname -a
Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux
```

In Debian (base for Kali) it is also available. Is this something you can fix or do I have to head over to the Kali Linux team?

**Comment by gnunn1** [comment]
You are correct, you need to open a bug with Kali as I don't handle packaging Tilix just the development.

**Comment by phw** [comment]
@honze-net Have a look at https://pkg.kali.org/pkg/terminix , the terminix package was removed a couple of days ago. You might want to contact the packager directly for the reason.

**Comment by honze-net** [comment]
I opened a ticket on the Kali bugtracker and got the following response:
"tilix will be available after the release of Debian 9 (June 17), it will migrate from unstable to testing and from there to kali. " (https://bugs.kali.org/view.php?id=4064)

So just wait a bit. This is fine for me.
