### ISSUE TITLE
Preferences window opens too wide

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/tilix#948]
Screenshot to illustrate.  Also, when moving the mouse cursor to the edge of the window the cursor changes to the resize image but the window itself isn't resizeable.

![screenshot from 2017-05-31 09-00-22](https://cloud.githubusercontent.com/assets/422013/26621741/ac1b6916-45df-11e7-8236-5aac61aaa30d.png)

**Comment by phw** [comment]
Things like that are usually caused by some UI element, probably a string, running too wide. Can you look through the preferences if there is anything that could cause this?

**Comment by phw** [comment]
Just after I wrote the above I found one thing that can cause this: When entering a very long bookmark title this will blow up the preferences dialog. I think the labels should not grow the size of the dialog but rather get cut off if they don't fit.

There could be more things causing the dialog to grow, but that's one possible issue I found in quick testing.

**Comment by gnunn1** [comment]
I've updated the bookmark editor to change the horizontal scrollbar policy from NEVER to AUTOMATIC which corrects that specific behavior for me.

@alexwhitman Could you check all of the pages of your preferences and look for any widgets which are displaying abnormally large strings.

**Comment by alexwhitman** [comment]
I can't see any long strings.  I don't have any bookmarks set and most of my settings are the default except for some of the dropdowns and checkboxes.  I can provide screenshots of each page if that helps?

**Comment by gnunn1** [comment]
If you can take screenshots of just the pages that have controls that go all the way from the left edge to the right edge that would be helpful. Also, did this issue just start with 1.5.8?

**Comment by Aidoboy** [comment]
I just installed Tilix 1.5.8 on CentOS 7.3, and I'm having the same issue.

**Comment by kascote** [comment]
Same issue here. I don't saw at first glance any long string or some strange wide widget. 
The issue started with 1.5.8. I'm using ppa from webupd8team

```
$ tilix --version
Versions
	Tilix version: 1.5.8
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

~
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

**Comment by alexwhitman** [comment]
Screenshots below.  Not sure what version it started with as I haven't looked at the preferences recently and I'm often compiling the latest master version to test.

![tilix preferences_001](https://cloud.githubusercontent.com/assets/422013/26639692/77acb638-461d-11e7-90c4-7883fb31ef6c.png)
![tilix preferences_002](https://cloud.githubusercontent.com/assets/422013/26639696/77b808f8-461d-11e7-829c-07c051bb44ce.png)
![tilix preferences_003](https://cloud.githubusercontent.com/assets/422013/26639694/77b07cf0-461d-11e7-8f52-ebfc86fdd8f5.png)
![tilix preferences_004](https://cloud.githubusercontent.com/assets/422013/26639693/77ad476a-461d-11e7-964c-7c86519a7a2d.png)
![tilix preferences_005](https://cloud.githubusercontent.com/assets/422013/26639695/77b5bb70-461d-11e7-8065-b74c0ecf7ae1.png)
![tilix preferences_006](https://cloud.githubusercontent.com/assets/422013/26639691/77abfedc-461d-11e7-8738-decad3367931.png)
![tilix preferences_007](https://cloud.githubusercontent.com/assets/422013/26639697/77bf0d56-461d-11e7-84c6-d456001c431c.png)
![tilix preferences_008](https://cloud.githubusercontent.com/assets/422013/26639698/77c69ada-461d-11e7-9fd2-b6b889550877.png)
![tilix preferences_009](https://cloud.githubusercontent.com/assets/422013/26639699/77e32bf0-461d-11e7-9516-6ee770269390.png)

**Comment by NoXPhasma** [comment]
I have the same issue since the update to 1.5.8. There are several drop down menus which use the full with of the window, but none of them has any text which would explain that.

It's also impossible to make the window smaller when opened, I can only raise the size.

```
$ tilix -v    
Versionen
	Tilix-Version:  1.5.8
	VTE-Version: 0.42
	GTK-Version: 3.18.9

Tilix-Sonderfunktionen
	Benachrichtigungen aktiviert=0
	Auslöser aktiviert=0
	Badges aktiviert=0

$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
```

**Comment by gnunn1** [comment]
I'm not seeing the issue in Ubuntu 17.04, I'll try CentOS next.

**Comment by NoXPhasma** [comment]
I and others in this issue have multi monitor setups. Maybe this is the cause?

**Comment by Aidoboy** [comment]
I only have one monitor, but I'm using a VM over VNC.

**Comment by kascote** [comment]
At this moment I have one monitor, but had 2 a couple months ago

**Comment by nean-and-i** [comment]
confirm same issue on Ubuntu Gnome 16.04

```
$ tilix --version
Versions
	Tilix version: 1.5.8
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```



```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

**Comment by bil-elmoussaoui** [comment]
I have a dual monitor and i can't reproduce it on Archlinux with Gnome 3.25 (alpha)

**Comment by gnunn1** [comment]
Is everyone who has this issue on GTK 3.18 or earlier?

**Comment by alexwhitman** [comment]
I am, on Ubuntu 16.04 LTS.

```
Versions
	Tilix version: 1.5.9-0.0.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by Aidoboy** [comment]
On Centos 7.3

```
Installed Packages
Name        : gtk3
Arch        : x86_64
Version     : 3.14.13
Release     : 20.el7_3.1
Size        : 15 M
Repo        : installed
From repo   : updates
Summary     : The GIMP ToolKit (GTK+), a library for creating GUIs for X
URL         : http://www.gtk.org
License     : LGPLv2+
Description : GTK+ is a multi-platform toolkit for creating graphical user
            : interfaces. Offering a complete set of widgets, GTK+ is suitable for
            : projects ranging from small one-off tools to complete application
            : suites.
            : 
            : This package contains version 3 of GTK+.
```
```
Installed Packages
Name        : tilix
Arch        : x86_64
Version     : 1.5.8
Release     : 1.el7.centos
Size        : 12 M
Repo        : installed
From repo   : ivoarch-Tilix
Summary     : A tiling terminal emulator based on GTK+ 3
URL         : http://github.com/gnunn1/tilix
License     : MPLv2.0
Description : A tiling terminal emulator
```

**Comment by dflock** [comment]
I get this too, on a freshly installed tilix, from the very first time I opened the preferences.

```console
$ neofetch 
            .-/+oossssoo+/-.               duncan@duncan-desktop 
        `:+ssssssssssssssssss+:`           --------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 16.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Model: All Series 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.4.0-62-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 114 days, 23 hours, 49 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3317 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.3.48 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Xfce 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Xfwm4 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Greybird 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Greybird [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Elementary-xfce-darker [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: tilix 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-4770K (8) @ 4.300GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 770 
      -+sssssssssssssssssyyyssss+-         Memory: 17695MiB / 32113MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.                                       

$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                         Version             Architecture        Description
+++-============================-===================-===================-==============================================================
ii  libgtk-3-0:amd64             3.18.9-1ubuntu3.3   amd64               GTK+ graphical user interface library
ii  libgtk2.0-0:amd64            2.24.30-1ubuntu1    amd64               GTK+ graphical user interface library

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
