### ISSUE TITLE
Custom Links stopped working: Error Opening Match

### ISSUE THREAD

**Issue by rpbaptist** [gnunn1/tilix#952]
The pop up shows: `Could not open match "`

![image](https://cloud.githubusercontent.com/assets/7916262/26670767/3c0e77d8-46b3-11e7-83ee-c629c2a66e9b.png)

```
> tilix --version
Versions
	Tilix version: 1.5.8
	VTE version: 0.44
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

I used it with my editor Sublime Text and it was working fine until yesterday. I used the following:

Regex: `\.?\S+\.(rb|ru|json|js|html|haml|yml|md|scss|css|sass):?\d*:?\d*`
Command: `subl $0`

This stopped working. Now I know it may be a bit complex, so I tested a more simple version:

Regex: `test\.txt`
Command: `subl $0`

Same message pops up.

Oddly enough, this one still works for images:

Regex: `\.?\S+\.(svg|png|jpg|jpeg|gif)$`
Command: `viewnior $0`

I thought maybe the `$` was what saved it, but `test\.txt$` displays the same error.

I exchanged the `subl` command for a different program to see if that was the problem: `leafpad $0` shows the same error.

**Comment by rpbaptist** [comment]
I suspect yesterdays update:

```
> apt show tilix
Package: tilix
Version: 1.5.8-1~webupd8~zesty0
Priority: optional
Section: gnome
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Installed-Size: 3094 kB
Provides: terminix
Depends: tilix-common (= 1.5.8-1~webupd8~zesty0), libgtkd-3-0 (>= 3.5.1), libvted-3-0 (>= 3.5.1), dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.14), libphobos2-ldc71, libx11-6
Recommends: libsecret-1-0, gir1.2-secret-1, python-nautilus
Breaks: terminix (<= 1.5.3)
Replaces: terminix (<= 1.5.3)
Download-Size: 454 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/webupd8team/terminix/ubuntu zesty/main amd64 Packages
Description: Tiling terminal emulator for GNOME
 Tilix (previoulsy Terminix) is a feature-rich tiling terminal emulator following the
 GNOME human interface design guidelines.
 Its many features include:
 .
 * Layout terminals in any fashion by splitting them horizontally or
 vertically.
 * Terminals can be re-arranged using drag and drop both within and
 between windows.
 * Terminals can be detached into a new window via drag and drop.
 * Input can be synchronized between terminals so commands typed in
 one terminal are replicated to the others.
 * Supports notifications when processes are completed out of view.
```

**Comment by rpbaptist** [comment]
I can confirm a downgrade to 1.5.6 made my custom links work agian.

**Comment by larsks** [comment]
Oh look, somebody has already opened a bug for the issue I was going to report.  I'll just...you know, me too.

**Comment by diskotechjam** [comment]
I'm having a similar issue, but I cannot open any URL. I didn't think that you needed to setup a custom link to handle URLS, but perhaps I am wrong.

**Comment by bil-elmoussaoui** [comment]
@diskotechjam In order to open a URL you will have to CTRL + Left click on it. The issue is about https://gnunn1.github.io/tilix-web/manual/customlinks/

**Comment by diskotechjam** [comment]
@bil-elmoussaoui Hmm, seems to only work once per session, then I continue to get the Error Opening Match message. The right click menu "Open Link" and "Copy Address" don't work either. Seems to be independent of custom links problem.

**Comment by f2404** [comment]
I guess this could be related to that issue with pcre2 as URLs handling is also based on regexes.
