### ISSUE TITLE
GSettings errors on Archlinux

### ISSUE THREAD

**Issue by Urgau** [gnunn1/tilix#958]
Hello,

when I install Tilix (tilix-bin) on Archlinux I received this error when "Compiling GSettings XML schema files..." :

> Aucune clé nommée « sort-directories-first » dans le schéma « org.gnome.nautilus.preferences » comme défini dans le fichier « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » de redéfinition ; la redéfinition de cette clé a été ignorée.
Aucune clé nommée « sort-directories-first » dans le schéma « org.gnome.nautilus.preferences » comme défini dans le fichier « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » de redéfinition ; la redéfinition de cette clé a été ignorée.
Aucune clé nommée « sort-directories-first » dans le schéma « org.gnome.nautilus.preferences » comme défini dans le fichier « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » de redéfinition ; la redéfinition de cette clé a été ignorée.

English :

> No named key « sort-directories-first » into the schema « org.gnome.nautilus.preferences » as define in the file « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » redifinition; the redifinition was ignored
No named key « sort-directories-first » into the schema « org.gnome.nautilus.preferences » as define in the file « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » redifinition; the redifinition was ignored
No named key « sort-directories-first » into the schema « org.gnome.nautilus.preferences » as define in the file « /usr/share/glib-2.0/schemas/99_deepin-default-gsettings.gschema.override » redifinition; the redifinition was ignored

**Comment by bil-elmoussaoui** [comment]
Nothing to do with tilix. You've recently installed deepin which patch some default functionality on Nautilus except this feature is key on gsettings has changed i guess
