### ISSUE TITLE
Can't launch tilix after update to 1.6.0 in Fedora 25

### ISSUE THREAD

**Issue by aditiapratama** [gnunn1/tilix#960]
Hi,
I'm using copr build `heikoada-terminix` and today I realize Tilix has been updated to version 1.6.0. But after restart, i tried to launch and get this 

```shell
object.Exception@../../../.dub/packages/gtk-d-3.6.5/gtk-d/generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdkglext-3.0.so.0): libgdkglext-3.0.so.0: cannot open shared object file: No such file or directory
```

Should we install extra library in this case. `libgdkglext-3.0.so.0`?

Thanks

**Comment by gnunn1** [comment]
No, there is an issue with newer versions of GtkD making this library required instead of optional like it was previously. I'm in the process of pushing out a fix that builds against the older GtkD library and fixes the issue. Give me a few minutes.
