### ISSUE TITLE
version 1.6 failed load libgdkglext-3.0.so.0

### ISSUE THREAD

**Issue by arcadian09** [gnunn1/tilix#962]
Just updated to Version tilix-1.6.0-1.fc25.x86_64

Tilix does not start and outputs the following exception.
object.Exception@../../../.dub/packages/gtk-d-3.6.5/gtk-d/generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdkglext-3.0.so.0): libgdkglext-3.0.so.0: cannot open shared object file: No such file or directory

Downgraded to version tilix-1.5.8-1.fc25.x86_64 and issue none existent.

Fedora version 25
GNOME Shell version 3.22.3
GTK3 version 3.22.15-2.fc25

**Comment by gnunn1** [comment]
It's been fixed with 1.6.1, my apologies for the issue.
