### ISSUE TITLE
Weird symbols after "ls -la" command (not easily reproducible)

### ISSUE THREAD

**Issue by vmercuri** [gnunn1/tilix#963]
Built from master (via dub) on Fedora 25 (Cinnamon 3.4.0). The terminal emitted a long sequence of symbols after pressing Enter on the ``ls -la`` command. This has only happened twice in a few hours, after multiple attempts to reproduce the issue. As you can see, I have zsh installed and configured it with oh-my-zsh, but since the problem never happened with past builds of Tilix, I can't infer that my shell configuration can be the cause. 
![screenshot from 2017-06-05 18-13-17](https://cloud.githubusercontent.com/assets/4584008/26793120/1afa41b8-4a1d-11e7-80eb-62f50664f8fb.png)
![screenshot from 2017-06-05 18-10-33](https://cloud.githubusercontent.com/assets/4584008/26793121/1b0076d2-4a1d-11e7-9b2d-c8bbd6de8ba3.png)

**Comment by gnunn1** [comment]
This is probably an issue with VTE rather then tilix itself since VTE provides the terminal emulation. How are you generating that prompt with the arrow, is it using any fancy character sequences? Also, can you reproduce this in gnome-terminal?

**Comment by vmercuri** [comment]
The problem is that I didn't see the issue until yesterday, after I rebuilt Tilix. The gnome-terminal doesn't have the same problem (I use both terminals quite often). This morning, something similar happened also when I changed the font color in the Preferences (but I can't remember exactly which event caused a long sequence of '8' to be printed out, it probably happened when I released the mouse left-button). My terminal prompt is just a theme from [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh), a plugin for customizing the zsh shell. As I said, this should not be the issue, because I used the same configuration until yesterday and everything has always worked as expected. However, I'm going to remove this plugin and switch back to Bash just to test Tilix on a clean environment. I'll try to make the issue reproducible, if possible.

**Comment by gnunn1** [comment]
Thanks, if you can reproduce it in bash that would be very helpful.

**Comment by vmercuri** [comment]
After one day, I have not been able to reproduce the issue in bash. I should conclude that the zsh configuration I used caused it, but at the same time I can't explain why everything worked until the latest build and why this doesn't happen with gnome-terminal. I'm going to try further with zsh enabled, with and without the oh-my-zsh plugins installed, just to make sure whether this might be a bug in oh-my-zsh or not, rather than Tilix. I'll let you know if I get to anything new that may help you understand better what is going on. Thanks for your time.

**Comment by gnunn1** [comment]
Thanks for the update.

**Comment by gnunn1** [comment]
Anymore luck with this?

**Comment by vmercuri** [comment]
Hi, sorry for my late answer. I've been trying to replicate the issue while keeping my settings as minimal as possible, so I used an empty .zshrc and the default .bashrc for the distribution I use. That long sequence of weird characters I posted in the two images above only appears when the oh-my-zsh plugin is installed. So I uninstalled it. However, with both bash and zsh I do see a strange behavior. To reproduce the issue I "blasted" the terminal by repeatedly typing ``ls -la`` and pressing ``Enter`` (of course I used the Up-Arrow key to re-use the last command). I want to point out that this only happened in Tilix, it never happened with gnome-terminal. 

This is what I get on bash:
![screenshot from 2017-06-12 14-53-29](https://user-images.githubusercontent.com/4584008/27035005-1338858a-4f80-11e7-955a-67b829f1edd6.png)

This is with zsh:
![screenshot from 2017-06-12 14-36-57](https://user-images.githubusercontent.com/4584008/27034994-03790caa-4f80-11e7-853f-1f40ee75b910.png)

As you can see the prompt is preceded by spurious characters (the sequence ``^[[A`` in bash and ``%`` in zsh). This is with uncustomized rc files and prompts. I want to stress that this can be only seen very infrequently (in my case, it only happened with a rate of about twice in a 1-minute try or so) and I had to try many many times in order to be able to take the screenshots. So this does not really affect any activity in any way, at least for now, at least for me.

**Comment by gnunn1** [comment]
I can't reproduce this at all, are you using the same font in both gnome-terminal and tilix?

**Comment by ddddavidee** [comment]
I've a similar problem. With ZSH (and oh-my-zsh) when I press TAB to autocomplete the command, the line is refreshed and the cursor is moved away, making, sometimes difficult to edit the line. 
![screenshot from 2017-06-20 15-49-28](https://user-images.githubusercontent.com/1660705/27336597-5888f77c-55d0-11e7-83e3-7c2a826c920d.png)
In the image you can see the green "ls" that I wrote and the lscpu that is moved after I pressed tab to autocomplete. With longer lines the effect is very annoying.

**Comment by ddddavidee** [comment]
seems to be linked to the prompt theme, if I switch to a theme without any fancy character it works with no problem. 
To the original poster, could you try with the "ys" theme to see if we have the same issue?

**Comment by nean-and-i** [comment]
can you guys try the test version provides in #888 as for me it seems to be some similarities in terms of special esc sequence patterns,...

**Comment by gnunn1** [comment]
@nean-and-i The test version I sent you won't make any difference for this, it only affects things when using synchronization.

**Comment by nean-and-i** [comment]
@gnunn1 , hmmm, I had randomly freezes in vim and on regular terminal operation like jump ctrl+a/ctrl+e, search ctrl+r etc. even when sync was off, now this seems to be gone.

**Comment by gnunn1** [comment]
@vmercuri Is this still an issue or something that was related to zsh?

**Comment by ddddavidee** [comment]
I think it was related to the unicode char in the prompt.

**Comment by gnunn1** [comment]
No response from OP, closing issue.
