### ISSUE TITLE
Update broke Tilix install on Fedora 25 from COPR repo

### ISSUE THREAD

**Issue by humanamerican** [gnunn1/tilix#964]
I installed from https://copr.fedorainfracloud.org/coprs/heikoada/terminix/. It worked until this morning (after an update), when I tried to run and got: 

$ tilix
object.Exception@../../../.dub/packages/gtk-d-3.6.5/gtk-d/generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdkglext-3.0.so.0): libgdkglext-3.0.so.0: cannot open shared object file: No such file or directory

**Uninstalling and reinstalling tilix** seems to have fixed the problem.

**Comment by f2404** [comment]
Please see #960 #961 #962
