### ISSUE TITLE
Not working nautilus integration with unicode-named directories

### ISSUE THREAD

**Issue by zgwerby** [gnunn1/tilix#965]
Not working nautilus integration (Open with... feature) with unicode-named (if have in name at least one unicode or non-english symbol) directories. Arch Linux, Gnome 3.24.2, Nautilus 3.24.1, Tilix 1.6.1 - fresh compiled from AUR.
![2017-06-06 19-11-02](https://user-images.githubusercontent.com/21217444/26839599-97417a48-4af4-11e7-90c4-f3875dff8d53.png)
![2017-06-06 19-11-16](https://user-images.githubusercontent.com/21217444/26839601-974260e8-4af4-11e7-8ed3-9a8bbf94968f.png)
![2017-06-06 19-11-32](https://user-images.githubusercontent.com/21217444/26839600-974243f6-4af4-11e7-87b7-80d8bd79aa4a.png)
![2017-06-06 19-11-47](https://user-images.githubusercontent.com/21217444/26839602-974666d4-4af4-11e7-8338-48b6dd980104.png)

**Comment by gnunn1** [comment]
The nautilus extension uses Python2 so it's probably related to the poor unicode handling that it has versus Python3.

**Comment by bil-elmoussaoui** [comment]
I will see what i can do next week :)
