### ISSUE TITLE
Regression In Custom Links: Error Opening Match

### ISSUE THREAD

**Issue by pkkid** [gnunn1/tilix#968]
I believe this is a regression in the latest version of Tilix (1.5.8).  I have a custom link that matches filenames and allows opening them in a text editor. It was working fine for several months on previous versions of Tilix, but now seems broken on the latest version. It is defined as the following:

Regex: `([\w\/\.\-]+\.[\w]{1,4})(:(\d+)|\n|\s)`
Command: `/usr/bin/subl $1:$3`
Case Insensitive: Yes

The *first* time I click a matched link it opens correctly.  Any subsequent times I open the same or other links, I get the following popup.

```
Error Opening Match
Could not open match ''
```

FWIW, URL links also seem to be broken in the same manner.

OS: Ubuntu Gnome 17.04
Tilix: Version 1.5.8

**Comment by gnunn1** [comment]
Are you using 1.6.0, this was fixed in 1.6.1. If you are using 1.6.1 I'll look into it.

**Comment by pkkid** [comment]
I am on 1.5.8, let me upgrade and I'll close if that's the case, thanks.

**Comment by pkkid** [comment]
The PPA is still back on 1.5.8 and building from source is not something I want to commit to at this point. Thanks for the heads up on the version this was fixed. I'll wait for webup8 to get the latest version.
