### ISSUE TITLE
Window is too small after restoring from maximized state

### ISSUE THREAD

**Issue by dessaya** [gnunn1/tilix#969]
Steps to reproduce:

* I use Gnome3
* Start tilix, maximize the window, close tilix.
* Start tilix again, window is maximized.
* Restore the window to "normal" state (using eiter a keyboard shortcut, or the Unmaximize option from the window context menu).

Expected result: Window goes back to initial size (80x25).

Restult: Window is 1 line tall:

![window too small](http://i.imgur.com/jXyvtfB.png)

I'm not a fan of the new behavior of remembering the maximized state. Is it possible to disable it?

Thanks!

**Comment by gnunn1** [comment]
I can't reproduce, it goes back to normal size for me as expected. What DE and version of Gnome are you using?

**Comment by gnunn1** [comment]
Sorry what I say DE, I meant to type distro. You already said you were using gnome. :)

Can you post the output of ```tilix --version``` as well please.

**Comment by dessaya** [comment]
Distro: Arch, everything up to date.

```$ tilix --version
Versions
	Tilix version: 1.6.1
	VTE version: 0.48
	GTK Version: 3.22.15

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
Thanks I'm also running Arch with the same versions except for VTE as I'm using vte3-tilix to get support for notifications, triggers and badges. However it would be very, very surprising if this difference was causing the issue.

Do you have any extensions installed that manage or watches for window state changes?

Anyone else having this issue?

**Comment by dessaya** [comment]
> Do you have any extensions installed that manage or watches for window state changes?

The only Gnome extensions I have enabled are Alternatetab and gnome-system-monitor. I doubt any of them are responsible.

I just reproduced the bug while running tilix inside a terminal, and got this message:

```
(tilix:3382): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
```

Does it help?

**Comment by gnunn1** [comment]
Are you using Wayland?

**Comment by gnunn1** [comment]
Yep this looks like a Wayland issue as I can reproduce it there, will have a look.

**Comment by gnunn1** [comment]
This looks to be a bug in GTK, I can reproduce the exact same problem in gedit. I have opened a bug in GTK:

https://bugzilla.gnome.org/show_bug.cgi?id=783901
