### ISSUE TITLE
Home/end keys not working

### ISSUE THREAD

**Issue by hgaiser** [gnunn1/tilix#970]
Hey,

It seems my Home/End keys are not working. At first I thought they may be bound by some other application but URXVT does seem to work correctly.

For the record, I expect HOME key to move the cursor to the beginning and END to the end of the line. Curiously enough it does work in vim (running inside tilix). It appears to only be on the command line where it is not working, any thoughts on what causes this issue?

Best regards.

**Comment by egmontkob** [comment]
xterm generates `\e[H` and `\e[F` (in application mode `\eOH` and `\eOF`). Many other emulators, including VTE-based ones (such as Tilix), but also konsole, terminology etc. also do the same.

Another quite popular approach is `\e[1~` and `\e[4~` emitted e.g. by the Linux konsole, or Putty by default.

st (from suckless) is a weird mixture of these two: `\e[H` and `\e[4~` (like, seriously?).

urxvt is a weird one out there generating `\e[7~` and `\e[8~`, something I haven't seen anywhere else. I keep having this feeling that usually urxvt is the odd one.

For some reason your shell seems to be prepared for urxvt's sequences, but not for xterm's/vte's.

**Comment by egmontkob** [comment]
Check your `$TERM` env variable, it should contain `xterm-256color` or perhaps `xterm`.

**Comment by hgaiser** [comment]
I see, thank you for your explanation, this helped me look further for what could cause this issue. I was indeed using urxvt before trying tilix and `$TERM` was set to `xterm-256color`. I should also note that I am currently using zsh and the config that I am using had this (among other bindings too, but I omitted those) :

```
typeset -A key

bindkey -e

key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}

[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
```
However disabling that didn't give me correct HOME/END functionality. I tried bash and found out that HOME/END was working correctly there. I tried removing my zshrc so that I get 'vanilla' zsh, but HOME/END was not working still.

I will experiment some more, but perhaps this already means something to you :)

**Comment by egmontkob** [comment]
Home/End send different escape sequences depending whether in "normal" (as in zsh) or in "application" cursor keys mode. Terminfo describes the latter one.

If you ask me, just hardcode the escape sequences in your zsh config and forget the trouble. Ugly but works.

**Comment by hgaiser** [comment]
I agree, not worth the time :) I ended up doing:

```
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
```

Which fixes the problem for now. Perhaps in the future I'll look for a better solution. Thanks for the help!
