### ISSUE TITLE
Supporting OS/X

### ISSUE THREAD

**Issue by MisterTea** [gnunn1/tilix#971]
Hey!

Are there plans to support OS/X?  I'm the lead dev on Eternal Terminal and got this issue: https://github.com/MisterTea/EternalTCP/issues/33

Basically "tmux -cc" only works on iTerm, so linux people are out of luck.  I want to help them but I only run os/x and don't know of a good cross-platform emulator.  I'd be willing to write a replacement for tmux control mode that outputs JSON instructions and also writing a spec so more terminal emulators can support it.

What would be involved in making Tilix work on OS/X?

**Comment by gnunn1** [comment]
I do not have any plans to support OSX myself as I'm not a regular user of that platform. In theory it should be fairly straightforward to get it going since both D and GTK are supported on OSX. I do see people posting bugs about in the GtkD (D's GTK wrapper) page so presumably it is doable.

In terms of changes, I can think of a few things as follows:

a. Add a new constant when building for the OSX platform
b. Use the constant in ```static if``` blocks to remove code that won't work on OSX. For example, the few places where I call X11 functions directly.
c. Maybe look at adjusting some of the UI defaults for a better experience when running on OSX.

And that should be it. I'm sure there would be a few issues involved. Are you familiar with the D language as this is what Tilix is written in. If you are comfortable with C or Java you won't have any issue picking up D.

**Comment by gnunn1** [comment]
Also, GtkD has a guide for OSX here:

https://github.com/gtkd-developers/GtkD/wiki/Mac-OS-X-Notes

You can ignore the comments about X11 as I don't use gtkDgl, at least not directly.

**Comment by MisterTea** [comment]
I am getting this error, not sure if you are familiar with it:

```
➜  tilix git:(master) dub build --build=release
Performing "release" build using dmd for x86_64.
gtk-d:gtkd 3.6.5: target for configuration "library" is up to date.
gtk-d:vte 3.6.5: target for configuration "library" is up to date.
tilix ~master: building configuration "default"...
Linking...
Undefined symbols for architecture x86_64:
  "_XSendEvent", referenced from:
      _D2gx3gtk3x1117activateX11WindowFC3gtk6Window6WindowZv in tilix.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
dmd failed with exit code 1.
```

**Comment by gnunn1** [comment]
You are getting that error because you don't have X11 on OSX. You need to add a flag to constants.d and then tell the compiler to ignore compiling that code by using ```static if```. If you grep for ```static if``` you can see how I'm using it.

I can add this flag for you tomorrow night as well.

**Comment by MisterTea** [comment]
Actually it's that the build file needs to look for libraries in /usr/X11/lib and add the X11 library if mac

This did the trick:

```
diff --git a/dub.json b/dub.json
index 6939dcd..b2f1e4d 100644
--- a/dub.json
+++ b/dub.json
@@ -4,6 +4,7 @@
     "copyright": "Copyright © 2016, Gerald Nunn",
     "authors": ["Gerald Nunn"],
     "mainSourceFile": "source/app.d",
+    "lflags": ["-L/usr/X11/lib"],
     "dflags-ldc": ["-disable-linker-strip-dead","-defaultlib=:libphobos2-ldc.a,:libdruntime-ldc.a"],
 
     "dependencies": {
@@ -30,12 +31,14 @@
             "name": "default",
             "targetType": "executable",
             "libs-linux": ["X11"],
+            "libs-osx": ["X11"],
             "versions": ["StdLoggerDisableTrace"]
         },
         {
             "name": "trace",
             "targetType": "executable",
             "libs-linux": ["X11"],
+            "libs-osx": ["X11"],
             "debugVersions": ["Destructors"]
         },
         {
@@ -43,6 +46,7 @@
             "targetType": "executable",
             "libs": ["gtkd-3"],
             "libs-linux": ["X11"],
+            "libs-osx": ["X11"],
             "lflags": ["-defaultlib=gtkd-3.so"],
             "versions": ["StdLoggerDisableTrace"]
         }

```

**Comment by gnunn1** [comment]
While that works, it means there is a dependency on X11 which I don't think is needed for OSX. Like I said, if you need me to add a platform constant to remove the X11/Wayland stuff, let me know.

**Comment by MisterTea** [comment]
Yeah actually I got another missing symbol error when I tried that. I think
I'm going to pass on getting this to work on OSX since I have no context.

**Comment by gnunn1** [comment]
Ok, if you decide to change your mind let me know as I'm happy to collaborate.

**Comment by barthelemypousset** [comment]
Hi, can you still add that flag to make the build happen on Macos ?
I would love to have that tool on Mac. Thanks
