### ISSUE TITLE
Import color palettes

### ISSUE THREAD

**Issue by varemenos** [gnunn1/tilix#974]
There seems to be a functionality to export custom color palettes but not import. Would you be willing to add such a functionality to tilix?

I'm more than happy to write a script to import some color palettes from other popular terminal emulators ([like I did in the past for guake](https://github.com/varemenos/iterm2guake)).

**Comment by gnunn1** [comment]
I'm not of the mind that this is needed, it's easy enough to create a new scheme and copy it to ```.config/tilix/schemes```. There's already a large number of schemes available here:

https://github.com/storm119/Tilix-Themes

Having said that, if you want to write a utility like you did for guake to import schemes I don't have any issue with that but I don't think I would include it in tilix.
