### ISSUE TITLE
Tilix : blur effect

### ISSUE THREAD

**Issue by boubouhkarim** [gnunn1/tilix#975]
Hi,

The blur effect is kinda the fashion today in Windows 10 as well as Linux.

Is there any chance to see the blur effect on Tilix as an option beside background images and transparency ?

**Comment by gnunn1** [comment]
I'm not averse to supporting it, however I don't believe the underlying drawing library Cairo supports blur. Someone who knows graphics better then I do would need to write an algorithm for it in D.

**Comment by gnunn1** [comment]
Actually I don't think this is technically possible since to a blur you need to have the data of the image. Thus blurring instead of transparency isn't doable since there's no way to capture what's under the window.
