### ISSUE TITLE
Paste Anyway

### ISSUE THREAD

**Issue by Skitionek** [gnunn1/tilix#976]
When trying to copy to the terminal by the middle click the window is asking if I want to copy administrative code. **The problem is that pressing "Paste Anyway" button does not paste anything to console.** Moreover, it clears the buffer so I need to mark the code again if I want to copy it. 
This issue occurs for pasting by middle click (a buffer which works in parallel to clipboard) but it does not finish here.
**When I would use the key combination instead (Shift + Insert) the code is copied without warning.**
If you do something the do it right this functionality should be either neglected or corrected.

Tilix installed on Ubuntu 16.04

**Comment by gnunn1** [comment]
What version of tilix are you using, on master pasting with the middle-click works fine for me. When I highlight something like ```sudo echo hello``` and then middle click paste it I get the warning dialog and when I paste anyway it pastes it successfully.

As for the shift-insert, I can reproduce that issue though it should be working as I'm capturing that shortcut. I will investigate.

**Comment by gnunn1** [comment]
I've fixed the issue with shift-insert.

**Comment by gnunn1** [comment]
I think the problem with the selection disappearing looks to be an issue with GTK 3.18, I've tested in GTK 3.22 and it works as expected as there. No plans to try to workaround this in Tilix to specifically address this.
