### ISSUE TITLE
Crash when opening in non-existent directory

### ISSUE THREAD

**Issue by jotaf98** [gnunn1/tilix#977]
Hi, first of all, great work on Tilix! It's easily the best user experience of all terminals I've tried before.

I'm using this command for a "Open terminal here" shortcut in my file manager (so in principle the directory should always exist). However, if the directory doesn't exist, Tilix crashes. It should be a rare event but still, it would be best to be robust against this kind of input. Steps to reproduce:

tilix
tilix -a session-add-right -w "/non-existent-directory"

**Comment by gnunn1** [comment]
Thanks for reporting this, should be fixed now
