### ISSUE TITLE
Reset and clear all terminals

### ISSUE THREAD

**Issue by cazacugmihai** [gnunn1/tilix#978]
Hi,

Is there a way to reset and clear the all opened terminals? I am searching for this behavior:
1. Use the shortcut key associated to "Synchronize the input" (e.g.: Ctrl-Shift-I)
2. Use the shortcut key associated to "Reset and clear the terminal" (e.g. Ctrl-Shift-G) to reset and clear the all terminals.

Thanks and KUTGW!
Mihai

**Comment by gnunn1** [comment]
Currently there is not, I'm not sure it makes sense to have terminal actions work on all terminals when synchronization is enabled though for this one I could see how it could be the exception.

**Comment by gnunn1** [comment]
Quick poll, shoud reset and reset and clear affect all terminals with input synchronization enabled?

**Comment by cazacugmihai** [comment]
Yes, it would be so helpful!

**Comment by cazacugmihai** [comment]
@gnunn1: Thank you for this fix!
