### ISSUE TITLE
KDE Plasma window rules cause segfault with autostart (ksmserver)

### ISSUE THREAD

**Issue by nanohard** [gnunn1/tilix#980]
I can't get tilix to autostart on my system using the `--session` option. Not saying that it's an issue with tilix, but I don't know. I've tried every way I can think of to get it to start automatically with my system and it always fails in some fashion. I am finally reaching out after a month of failure in the hope that someone knows what is happening.

This is the output of my latest attempt, with an attached core dump.
#### Use `lrunzip` to extract this 1.7MB file to its original 342MB. The `.zip` extension was only used to be able to upload to Github.
[core.1179.zip](https://github.com/gnunn1/tilix/files/1093644/core.1179.zip)

Linux Arch 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux
Tilix version: 1.6.1
VTE version: 0.48
GTK Version: 3.22.16
Desktop Environment: KDE Plasma 5.10.2

```
$ journalctl
Jun 21 22:49:56 Arch ksmserver[956]: ksmserver: Starting autostart service  "/home/user/.config/autostart/tilix.desktop"
Jun 21 22:51:02 Arch kernel: tilix[1179]: segfault at 7f40580eaa10 ip 00007f40568b0f2b sp 00007fff280a4650 error 4 in libc-2.25.so[7f4056838000+19c000]
Jun 21 22:51:07 Arch ksmserver[956]: ksmserver: autostart service ("/usr/bin/tilix", "--session=/home/user/tilix.json") finished with exit code  11

$ cat /home/user/.config/autostart/tilix.desktop
[Desktop Entry]
Comment[en_US]=
Comment=
Exec=tilix --session=/home/user/tilix.json
GenericName[en_US]=
GenericName=
Icon=system-run
MimeType=
Name[en_US]=Tilix
Name=Tilix
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=none
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by gregbs7** [comment]
Hello,

you have to write the exec command liket this :
Exec=tilix -s "~/default.json"
in your case :
Exec=tilix -s "/home/user/tilix.json"

**Comment by nanohard** [comment]
Still get the segfault error, although now with`libglib` rather than `libc`.
I have no idea getting tilix to start on boot with a session is such a problem for me.

```
MESSAGE=ksmserver: Starting autostart service  "/home/user/.config/autostart/tilix.desktop"
MESSAGE=tilix[1154]: segfault at 841f0f ip 00007f2640098b20 sp 00007ffdb58777c0 error 4 in libglib-2.0.so.0.5200.2[7f2640030000+111000]
MESSAGE=ksmserver: autostart service ("/usr/bin/tilix", "-s", "/home/user/tilix.json") finished with exit code  11

$ cat /home/user/.config/autostart/tilix.desktop
[Desktop Entry]
Comment[en_US]=
Comment=
Exec=tilix -s "/home/user/tilix.json"
GenericName[en_US]=
GenericName=
Icon=system-run
MimeType=
Name[en_US]=Tilix
Name=Tilix
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=none
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by gnunn1** [comment]
Can you post your json file?

Also, if you run it directly from gnome-terminal does it work, i.e.

```tilix -s /home/user/tilix.json```

**Comment by gnunn1** [comment]
I just tested it myself with a simple json file and it auto-started fine for me using your desktop file. If you post with your json file I can try with that.

**Comment by nanohard** [comment]
I appreciate your help.

~/tilix.json
```
{
    "child": {
        "child1": {
            "directory": "\/home\/user",
            "height": 540,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 1920
        },
        "child2": {
            "child1": {
                "directory": "\/home\/user",
                "height": 539,
                "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
                "readOnly": false,
                "synchronizedInput": true,
                "type": "Terminal",
                "width": 960
            },
            "child2": {
                "directory": "\/home\/user",
                "height": 539,
                "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
                "readOnly": false,
                "synchronizedInput": true,
                "type": "Terminal",
                "width": 959
            },
            "orientation": 0,
            "position": 50,
            "ratio": 0.5,
            "type": "Paned"
        },
        "orientation": 1,
        "position": 50,
        "ratio": 0.5,
        "type": "Paned"
    },
    "height": 1080,
    "name": "Default",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 1920
}
```

**Comment by nanohard** [comment]
Whoops. Turns out it's an issue with KDE window rules. My bad. Forgot to delete the virtual desktop window rules. You're right, tilix does autostart fine, but when window rules are applied to it by Plasma it freaks out with a segfault.

**Comment by gnunn1** [comment]
Thanks for the update and glad you found the issue. Closing the issue since it's not a tilix issue.
