### ISSUE TITLE
VTE configuration warning pops up sometimes

### ISSUE THREAD

**Issue by phw** [gnunn1/tilix#982]
I have this issue very long, but never reported it, as I have found no reliable way to reproduce it and it pops up very infrequently.

From time to time (very seldom) when I start Tilix the VTE configuration warning pops up. It happens mainly when I start Tilix completely new, but also when I just open another session or window. In general on my Arch system I have this configuration issue. I fixed it not by sourcing `vte.sh` but instead by using a login shell.

As this happens infrequently I suspect this is probably some kind of race condition somewhere.

**Comment by gnunn1** [comment]
The warning itself is driven off of events raised by the VTE and as such it is going to be affected by timing. For example, I know it can happen if you start typing before the prompt appears so when I was using powerline I'd sometimes get it.

I'll see if there is some improvement to squeeze out of it but as I recall getting this working was suprisingly tricky and it may not be possible to improve it further.

**Comment by klingtnet** [comment]
I can confirm this issue on Arch Linux but I also wasn't able to pinpoint what causes the problem.

**Comment by gnunn1** [comment]
For me it happens if I start typing before the prompt appears. This can be fixed by commenting out the line ```gst.updateState();``` at 942 in terminal.d however I can't help but feel I put that there for a reason, I'll try running tilix for a few days without this line and see if there is any ill effect.

**Comment by klingtnet** [comment]
@gnunn1 Any instructions on how to reproduce this (typing before the prompt appears)? Adding a `sleep 1` on top of my `.zshrc` does not help.

**Comment by gnunn1** [comment]
I just started typing before tilix appears, that ensures a character gets accepted before the powerline prompt appears.

**Comment by gnunn1** [comment]
I think I've taken this as far as I'm willing to go with it, I've checked in one change that hopefully improves it.
