### ISSUE TITLE
opening links works once, but the second time gives 'Could not match"'

### ISSUE THREAD

**Issue by sramkrishna** [gnunn1/tilix#983]
I don't know if this is a unique issue with me or what.  I would think this would be something someone would ran into by now.  I'm running Arch Linux, and working on opening links inside tilix doesn't seem to work after the first time I use it.  I did try to update to the latest -  here is what tiliix --versions says:
Versions
	Tilix version: 1.6.1
	VTE version: 0.48
	GTK Version: 3.22.16

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
I hope this helps.  I'll try to see if I can duplicate it by getting it from github.

**Comment by sramkrishna** [comment]
Well tried to build from source and I had the same problem.

**Comment by gnunn1** [comment]
This has been fixed in #952 so if you are building from source it should work. Is there a specific link you are testng with?

**Comment by sramkrishna** [comment]
I was just using a youtube link, so nothing specific.  I did try building from source, but I had the same issue and this was two days ago.  I'll try again.  Thank you for all your work on tilix.  I am really enjoying using it.

**Comment by gnunn1** [comment]
Any update on this? Can you run ```tilix --version``` and post the output here please.

**Comment by gnunn1** [comment]
@sramkrishna Are you still having this issue?

**Comment by sramkrishna** [comment]
Thank you for following up!  I do not see this issue anymore.  I will close.  Thanks again.
