### ISSUE TITLE
Terminal window in quake mode appears briefly on the other screen

### ISSUE THREAD

**Issue by Mike-Now** [gnunn1/tilix#985]
During startup in the quake mode Tilix appears briefly on the other window and then moves to the one with focus.

System : Fedora 25
Computer: Laptop
Display: Wayland

```

Versions
	Tilix version: 1.6.1
	VTE version: 0.46
	GTK Version: 3.22.15

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0

```

**Comment by Mike-Now** [comment]
Workaround: disable Wayland and enable XOrg

https://ask.fedoraproject.org/en/question/96134/how-can-i-set-xorg-as-a-default-on-fedora-25/

Works great!

**Comment by gnunn1** [comment]
There's not much I can do about this in Wayland since it doesn't allow you to position the window. This is why the options for choosing the monitor and active window are hidden on Wayland.
