### ISSUE TITLE
Tilix in fullscreen and guake mode opens on the wrong screen

### ISSUE THREAD

**Issue by Mike-Now** [gnunn1/tilix#986]
1. Tilix in quake mode
2. Press F11 to enter fullscreen mode
3. Close tilix by entering `tilix--quake`
4. Move mounse pointer to the other screen (not builtin)
5. Open tilix in quake mode
6. Tilix window appears on the builtin screen

System : Fedora 25
Computer: Laptop
Display: Wayland

```
Versions
	Tilix version: 1.6.1
	VTE version: 0.46
	GTK Version: 3.22.15

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```

**Comment by Mike-Now** [comment]
Workaround: disable Wayland and enable XOrg

https://ask.fedoraproject.org/en/question/96134/how-can-i-set-xorg-as-a-default-on-fedora-25/

Works great!

**Comment by gnunn1** [comment]
Same as my previous comment, unfortunately things are inherently limited under Wayland with respect to quake mode.
