### ISSUE TITLE
Guake: hiding with shortcut does not work when hide on focus loss is active

### ISSUE THREAD

**Issue by lightonflux** [gnunn1/tilix#987]
1. Enable hide on focus loss. 
1. Reveal window with F10. 
1. Press F10 again to hide. 
1. The window opens again and is not hidden. 

Disable hide on focus loss and you can use the shortcut for reveal **and** hide.

Video: https://vid.me/7Ii8

**Comment by gnunn1** [comment]
This was fixed in #858 with the addition of a new option to tune the delay when hiding the window.
