### ISSUE TITLE
Does tilix have plan to add suport of ligatures?

### ISSUE THREAD

**Issue by lung-zijim** [gnunn1/tilix#989]
I found that Tilix cannot handled ligatures correctly, but gedit works really well.

**Comment by gnunn1** [comment]
Tilix uses the VTE for terminal emulation which AFAIK does not plan on supporting ligatures.

**Comment by meshy** [comment]
For reference, here's the upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=584160

**Comment by sassanh** [comment]
This is how VTE maintainer think about it: https://bugzilla.gnome.org/show_bug.cgi?id=781597
He really thinks supporting font ligature breaks terminal's grid, like he doesn't understand a font that's monospaced is a monospaced no matter if it has ligature or not. He talks about a problem in Konsole I have never faced past 2 years (I used to use Konsole 15 years ago and I can't remember it then too)

I suggest to get rid of VTE, I tried tilix few months ago, but after I noticed some problems and traced them to VTE and saw how poor VTE is maintained I decided to go back to Konsole.
