### ISSUE TITLE
Pressing "Preferences" closes the terminal in Ubuntu

### ISSUE THREAD

**Issue by VladimirDev93** [gnunn1/tilix#990]
Yeah... so... weird, but, pressing the "Preferences" menu on ``Ubuntu 16.04`` closes the window. It does not crash, it reproduces the animation for closing.

This is what the terminal shows if launch ``Tilix`` via Ubuntu's GNOME Terminal. This is what it shows when pressing "Preferences" menu tab.
```bash
2017-06-30T20:45:44.387:app.d:main:150 Unexpected exception occurred
2017-06-30T20:45:44.387:app.d:main:151 Error: Unrecognized image file format
```

**Comment by gnunn1** [comment]
Are you using a background image, looks like you have an invalid image set. This shouldn't an exit and I'll look into it, but for now use dconf-editor and clear it in com/gexperts/tilix

**Comment by gnunn1** [comment]
I tried duplicating it with a non-existent background image plus using a text file and no issues. I wonder though if the issue is that you have a bad installation and one of the resource files was corrupted. Are you installing tilix from a package or compiling it yourself?

**Comment by VladimirDev93** [comment]
I had a corrupt system. Reinstalled the system again, now everything works. Sorry for useless issue.
