### ISSUE TITLE
Split Terminal always opens in $HOME even after adding VTE Configuration

### ISSUE THREAD

**Issue by MunifTanjim** [gnunn1/tilix#991]
I've followed the steps in [VTE Configuration Issue](https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue). And the warning doesn't show anymore.

But still, when splitting terminals in Tilix instead of inheriting the directory from the current terminal the split terminal always opens in home.

Also, it's mentioned in the wiki that:
> Gnome Terminal has the same issue when creating new tabs.

But `gnome-terminal` & `mate-terminal` actually don't have this issue at all.

**Comment by gnunn1** [comment]
What do you see if you echo PROMPT_COMMAND in tilix, i.e.

```
[gnunn@gnunn-xps15 ~]$ echo $PROMPT_COMMAND
__vte_prompt_command
```

Also, try enabling a login shell within your profile and restart tilix to see if it makes any difference.

**Comment by MunifTanjim** [comment]
Sorry, I use [liquidprompt](https://github.com/nojhan/liquidprompt) and the issue was with it. Solved it.

Anyway, looks like Gnome Terminal fixed this problem way back. So user's don't have to source `vte.sh` anymore. Reference:

- [Launchpad Ubuntu Gnome Terminal Bug](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1132700)
- [Bugzilla Gnome Terminal Bug](https://bugzilla.gnome.org/show_bug.cgi?id=697475#c43)

**Comment by gnunn1** [comment]
No, it's up to Ubuntu to fix it.
