### ISSUE TITLE
Open in File Browser option

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#992]
i found this on elementary's Pantheon Terminal and it is kinda handy! it is the opposite of "Open Tilix" in Nautilus, and it saves you the "nautilus ."

![show-in-file-browser](https://user-images.githubusercontent.com/11244308/27757996-4e26d812-5e13-11e7-908d-355ca1c6bef5.png)

not sure if it is a good idea to overpopulate the menu, but personally is something i often do. open FilesApp in the current terminal location

**Comment by MunifTanjim** [comment]
Adding that to menu is kind of unnecessary and also it needs you to touch the mouse/trackpad.

Why don't you just type `nautilus . &`?
Or you can set an alias, `alias ofm='nautilus . &'`.

This is faster even.

**Comment by alex285** [comment]
@MunifTanjim some reasons:
1. i dont like doing s/c on terminal, because i always forget them
2. because 'nautilus . &' will still close if you close the terminal ¹
3. sometimes mouse comes handy

¹ that is not true in case of Nautilus in GNOME, because it runs as a background process, but it may be the case for other file managers, or other desktops than Shell

also im not sure either this is a good idea, but i share it. it seems handy to me in Pantheon Terminal

**Comment by gnunn1** [comment]
I added the feature as it was pretty straightforward and I can see how it could be useful. Note that this won't work for remote directories.

**Comment by alex285** [comment]
@gnunn1  thank you!

**Comment by alex285** [comment]
@gnunn1 is there an objection to move that in the context menu? because it is not very convenient to use on the titlebar menu

**Comment by alex285** [comment]
@gnunn1 actually either-case is fine with me!

**Comment by lung-zijim** [comment]
@alex285 Is this Tilix? Looks totally different from mine.

**Comment by alex285** [comment]
@lung-zijim no, on screenshot is elementary-terminal, for the feature reference
