### ISSUE TITLE
[Feature Request] option to set "Window style" from Command-line

### ISSUE THREAD

**Issue by MunifTanjim** [gnunn1/tilix#993]
Some type of command-line option for setting "Window style" when invoking `tilix` from command-line or shell script. E.g.:

`tilix --hide-csd`, `tilix --hide-border`

or

`tilix --window-style=<style>`

## Use Case

I've got some Global-shortcut set to open terminal application with text-based user-interface.

**For example**:

With `mate-terminal` and [cmus](https://github.com/cmus/cmus) the shortcut is something like this:

`mate-terminal --hide-menubar -e cmus`

And the result is:

![cmus-mate-terminal](https://user-images.githubusercontent.com/8050659/27758786-9cd77026-5e3f-11e7-9017-9066c9ec3039.jpg)

But with Tilix:

![cmus-tilix](https://user-images.githubusercontent.com/8050659/27758827-640e1082-5e40-11e7-8512-10f0a30ec32f.jpg)

In this scenario, the CSD has no usage.

**Comment by gnunn1** [comment]
That seems like a pretty reasonable option to me.

**Comment by gnunn1** [comment]
I've added a new --window-style parameter to override this at runtime.
