### ISSUE TITLE
new terminal window does not respect the profile size preference

### ISSUE THREAD

**Issue by urandom** [gnunn1/tilix#994]
Hi,

When I open a new window, it inherits the 'maximized' property of the active one. Meaning, that if the active one has been maximized, any new ones will be maximized as well. I feel that this is incredibly counter productive.

I hope this is just a bug, but in case it isn't, please provide some sort of preference for disabling this behavior.

Thanks

**Comment by gnunn1** [comment]
There is already an option to disable this in master, thanks for the feedback.
