### ISSUE TITLE
Outputting binary data causes audio to stop working

### ISSUE THREAD

**Issue by mannol** [gnunn1/tilix#995]
**Serious vulnerability?**

How to reproduce:
  - use netcat to listen for binary data using: `nc -l`
  - use curl to send multipart/form-data to the netcat
  - can no longer hear audio from any source (notably: youtube)

This happens on ubuntu 16.x and above (haven't tried earlier versions)

**Comment by gnunn1** [comment]
Outputting binary data in a terminal is likely to lead to unexpected behaviors as the terminal attempts to render what it perceives as control codes and UTF-8 sequences in textual data. You might be experiencing an issue where the binary data is outputting a control code that interacts with the audio system (i.e. BEL) and maybe doesn't close it as expected. I'm totally guessing here though.

Some questions as follows though:

a. If you close tilix does the audio resume?
b. Is the issue repeatable?
c. Can you reproduce the issue in gnome-terminal?
d. What is the output of ```tilix --version```

Note that tilix is using the same terminal emulation component as gnome-terminal, namely the VTE. If you can reproduce the issue in gnome-terminal I would suggest filing a bug at https://bugzilla.gnome.org.

**Comment by mannol** [comment]
Yup, seems to be the problem with gnome component.

**Comment by gnunn1** [comment]
Thanks for reproducing it in gnome-terminal, please open an issue upstream and feel free to paste it a link to it for reference. I'm closing this as an upstream issue.
