### ISSUE TITLE
Ctrl+Shift+d closes tilix

### ISSUE THREAD

**Issue by martinruenz** [gnunn1/tilix#997]
Sometimes I hit <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>d</kbd> instead of the default <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>d</kbd> combination to split the window, which results in tilix closing. Is this behaviour on purpose? There is no shortcut in the preferences for the aforementioned combination.

System: Ubuntu 16.04.2 LTS, using GNOME Shell 3.18.5

**Comment by gnunn1** [comment]
I think this is because Ctrl-D sends an EOT (End Of Transmission) code which terminates Bash and Ctrl-Shift-D gets interpreted the same way. The easiest thing to do would be to add some code to ignore the latter and force it to be Ctrl-D only for EOT.

**Comment by gnunn1** [comment]
I see xterm behaves the exact same way, as a result I'm not going to swallow this keystroke as I'm concerned it may cause issues with cli applications looking for it. If it really bothers you, I'd suggest an alternate shortcut to the split window down action.

**Comment by martinruenz** [comment]
Oh I see, thanks for the info!
