### ISSUE TITLE
Mouse scroll not working

### ISSUE THREAD

**Issue by ahmed-shariff** [gnunn1/tilix#999]
I just started using tilix. When I try to use the mouse scroll on the terminal or even on any of the preferences menus, there is no response. I have to click and drag on the scroll-bar or use shortcut keys.

**Comment by gnunn1** [comment]
I'm not sure this is a tilix issue, sounds like you have a system or GTK issue of some sort. Does the mouse wheel work fine in other applications? What desktop environment are you using, Gnome?

**Comment by ahmed-shariff** [comment]
Sorry about the late reply. And this is embarrassing, I should have checked that before. I am using stumpwm. The problem doesnt exist when I login into xfce. And the problem seems to be there on other GTK+ applications. It does seem that it is not an issue with Tilix.

**Comment by gnunn1** [comment]
No worries, glad you figured it out.
